### PR TITLE
try to notifiy users_id_tech on planning recall; see #695

### PR DESCRIPTION
**Pull request by orthagh**
relative to #695

### CODE REVIEW

**Comment by yllen** [comment]
Why create a function getAdditionalTargets($event='') {?
You can directly add new recipient in function getNotificationTargets($entity) {

**Comment by yllen** [comment]
function getTaskAssignUser() is the same as function getItemAuthorAddress();

**Comment by orthagh** [comment]
ok for getAdditionalTargets.
Could you explain me when we need to use getAdditionalTargets and getNotificationTargets ?

anyway, for getTaskAssignUser, the difference is in these fields : 
* users_id_tech for getTaskAssignUser
* users_id for getItemAuthorAddress

So, no it's not the same.

**Comment by yllen** [comment]
getNotificationTargets is for an entity and getAdditionalTargets is for and event
PlanningRecall is an alert so based on the entity

Ok for your function, you want to notify user assign to the task and not the author

**Pull request merged**
