### PR TITLE
Fix 2958

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2958

### CODE REVIEW

**Comment by yllen** [comment]
OK for Historical tab.
But you delete link to go to saved search, you must stay it.
My problem was for List link not saved search name

**Comment by trasher** [comment]
There is no alerts lists; this link was provided as a link to te saved search when you came from the saved search list. The "List..." link was a default I did not know we can remove initially; and the link to the saved search is already present in the form.

**Comment by yllen** [comment]
I have the problem with this link List only after create a new alert.
Question: why in saved search i only have public search? The notification alert can be for private one.
And how can i modify an existing one? when i click on the name the bookmark is loaded

**Comment by yllen** [comment]
Another point to alert.
If i have only 1 item i can't create 2 alerts (i have button but nothing done when i add, even message).
I you can create disable alert you can create several.

**Comment by trasher** [comment]
> why in saved search i only have public search? 

In saved search management interface you mean? I've just tested with two saved searches created from computers, on private and one public;  can see both (with default glpi account).
Modification of private search is the same than public ones; from the management interface. The slide panel does not provide that.

> i have button but nothing done

You mean you even do not have the alert form? I've tested on previously created searches, I was able to create several alerts on each one...

Don't know what the problem is exactly right now; but I wonder if both problems does not have only one cause. Did you try relogin? Which profiles did you use?

**Comment by yllen** [comment]
In Tools > saved search i only see public search
In star to load bookmarks i see public and private searches.
So i can't modify private because there are not in list

**Comment by yllen** [comment]
>You mean you even do not have the alert form? I've tested on previously created searches, I was able to create several alerts on each one...

Example: i have only 1 phone in item Phone
I create a bookmark for this phone.
I create an alert for this bookmark.
I want to create a second one. I have the button Add a new alert. I click on it, have the form and complete it. On click on Save button, form is reload empty

**Comment by yllen** [comment]
Test done this day and issue is the same. I used Super-Admin profil

**Comment by trasher** [comment]
I still cannot reproduce :/ Tested on a phone asset as well; and I can see private searches in the list; and also create as many alerts as I want.

For the list problem, could you please send the query that is played in the management interface?

**Comment by trasher** [comment]
OK, got it for private searches...
All private searches are in the root entity; and not recursive. In the panel, we take care of that, looking for entities restrictions only for public ones.

So the problem only appears when you use any entity but the root.

**Comment by yllen** [comment]
I think i have understand the issue.
In search engine you only have searches for this entity or recursive one.
With bookmarks of my settings you have public bookmarks for this entity and private bookmark for all entities.
So if you have define a bookmark from root entity no recursive and private, you can load it from a sub-entity.

**Comment by trasher** [comment]
I do not know why is_recursive is set to 0; it always been. On private searches; this does not really makes sense. I propose to change is_recusrive to 1 for all private searches.
Could you try if that fixes your issues?

**Comment by yllen** [comment]
I can need to do a specific search for a sub-entity.
For me in bookmarks list of my settings i must have only private search for this entity

**Comment by trasher** [comment]
So, this is related to https://github.com/glpi-project/glpi/issues/2882

**Pull request merged**
