### PR TITLE
Fix #3475: [9.2.1] Impossible to search problems or changes by id

### LINKED ISSUE #3475: [9.2.1] Impossible to search problems or changes by id
Hi,

A client on 9.1.1 can't search for problems or changes by id when inside a change or problem. The same issue appears on 9.2.1.

I'm working on a fix, please advise on the procedure to publish it.

* Steps to reproduce:
  * Have a lot of problems and a lot of changes
  * For problems->changes:
    * Go to a problem (/front/problem.form.php?id=1), then switch to the changes tab
    * Search for a change by id => the problem is not found
  * For changes->problems:
    * Go to a change (/front/change.form.php?id=1), then switch to the problems tab
    * Search for a problem by id => the problem is not found
* This happens even with "Show GLPI ID" set to "Yes" in the Configuration default values

### PR DESCRIPTION
**Pull request by pVesian**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3475

### CODE REVIEW

**Comment by pVesian** [comment]
@cedric-anne I don't think this solves the problem, isn't `$_SESSION['glpiis_ids_visible']` set only when ids have to be displayed?

**Comment by cedric-anne** [comment]
Indeed, the solution I propose will enable search by ID only if ID is displayed in the select box. I think that doing a match on a text/value that is not display could be really confusing for users.

**Comment by pVesian** [comment]
Ping @trasher or @orthagh for a choice: general fix but need to activate ID display or specific fix?

**Comment by orthagh** [comment]
Fix suggested by @pVesian doesn't seems strange compared to another place (See Ticket list in a Change: https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/change_ticket.class.php#L273)

By the way, i agree with you @cedric-anne, if we enable the `glpiis_ids_visible` option, in these cases, we have double id displayed.

A more generic way could be to remove checking existence of `displaywith` param to search on id.
See: https://github.com/glpi-project/glpi/blob/9.2/bugfixes/ajax/getDropdownValue.php#L165
No need to display it, we could always search on this field

**Comment by pVesian** [comment]
@orthagh Ok, if I understand correctly it would be better to always search on id?

> A more generic way could be to remove checking existence of displaywith param to search on id.
See: https://github.com/glpi-project/glpi/blob/9.2/bugfixes/ajax/getDropdownValue.php#L165
No need to display it, we could always search on this field

That would work for me, do you want me to code it?

**Comment by orthagh** [comment]
yes, please

**Comment by pVesian** [comment]
Will be done in another PR

**Pull request closed without merging**
