### PR TITLE
fix(ticket): cloning, unexpected automatic task

### PR DESCRIPTION
**Pull request by Rom1-B**
When cloning a ticket with tasks with durations, the created ticket had an automatic completed task, like this:

image

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !25928

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Please add a test

**Comment by Rom1-B** [comment]
I do not see the cases where this auto task should appear?

**Comment by trasher** [comment]
Test should ensure there is nothing more added than expected

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Same problem will present on `Problem` and `Change` classes.

Also, I did not tested it, but maybe the following code would be more relevant:
```php
    public function prepareInputForClone($input)
    {
        unset($input['actiontime']);
        return $input;
    }
```

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
