### PR TITLE
[9.2] fixe item relation - see #4850

### PR DESCRIPTION
**Pull request by yllen**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4850

### CODE REVIEW

**Comment by yllen** [comment]
null in lower cas => you have the issue
NULL in higher case => issue disappear in 9.2, 9.3 and 9.4

**Comment by cedric-anne** [comment]
Hi,

Here is a possible explaination: https://stackoverflow.com/a/51073969

Regards

**Comment by trasher** [comment]
Also, we're not going to accept any PR for 9.2 branch. 9.4 will be released soon, so you should target 9.3 minimum.

**Comment by yllen** [comment]
null was sent to canConnexityItem in last parameter.
But in this function this parameter is defined to null, so it's not useful to sent it.
If you delete the last parameter sent ($item1 or $item2) you have the error of rights.

**Comment by yllen** [comment]
I think i find the problem
if ($connexityItem == null) {
this should be
 if ($connexityItem === null) {
or better if (is_null($connexityItem)) {

**Comment by yllen** [comment]
https://github.com/glpi-project/glpi/pull/5349

**Comment by trasher** [comment]
Thank you @yllen, I close this one

**Pull request closed without merging**
