### PR TITLE
Fix OpenAPI schema validation issues

### LINKED ISSUE #18158: OpenAPI 3.0 json file problems
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-dev

### Bug description

The provided OpenAPI 3.0 json (at **/api.php/doc.json**) file is not fully compliant with OpenAPI v3.

If you put the json file into the online editor of swagger (https://editor.swagger.io) you can have a detailed list of errors.

{C6877C29-FD8C-4DED-91CC-7C8DF039FA22}

### Relevant log output

_No response_

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

The OpenAPI schema has some validation issues according to the online Swagger editor. None of the validation issues actually seem to affect the Swagger UI display, but I guess some tools could have trouble parsing it. For example, the online Swagger editor doesn't seem able to generate clients based on the schema.

Fixes #18158

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

**Review by trasher — CHANGES_REQUESTED** [review]
Tests and CS are failing

**Comment by orthagh** [comment]
I don't remember when or why I noticed that issue again.
But it's still present, and apart tests fixing, PR could be merged without issues.

**Comment by cconard96** [comment]
Last time I checked, there were still issues. I originally thought I caught them all, but the Swagger site is very slow with parsing our JSON and identifying issues and it doesn't make it clear if/when it has finished validating it but it still shows the endpoints as if it is finished.

**Comment by orthagh** [comment]
> but the Swagger site is very slow with parsing our JSON

The [new one](https://editor-next.swagger.io/)  is worse.

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Comment by cconard96** [comment]
> The [new one](https://editor-next.swagger.io/) is worse.

The UI looks horrible... nevermind the performance. I'll try to find an offline way to validate the schema and see if we can add a CI check.

**Comment by orthagh** [comment]
>  if we can add a CI check.

good point

**Pull request merged**
