### PR TITLE
increase width of a ticket form classic view

### PR DESCRIPTION
**Pull request by lexx015**
In case that you have a nested categories with a few leves or with long names, you will get a overlapped ticket form.

### CODE REVIEW

**Comment by orthagh** [comment]
Hello.

Could you provide a screenshot of issue (before your changes) ?

**Comment by lexx015** [comment]
Yep, sure.
css
newcss

**Comment by orthagh** [comment]
I just changed some css rules for dropdown (in 07eb6b57 commit).

* Max-with is set to 270px and elipsis on the left for folded dropdowns
* The  witdh of unfolded is now auto

Can you check current master ?

For information, i don't want to increase complet panel width because in split layout), it will be broken

**Comment by lexx015** [comment]
Yep, i just checked. Now it looks perfect. Thanks!

**Pull request closed without merging**
