### PR TITLE
Generic Dropdowns

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Intended to be integrated with custom fields for generic assets in a future PR.
PR also generalizes the generic asset code to de-duplicate the work between generic assets and generic dropdowns.

Generic dropdowns may optionally be "tree" dropdowns instead of flat ones. This can be changed at any time. When not in tree mode, the items are added at level 0 with the complete name set properly as if they were root items. The base class switches between `CommonDropdown` and `CommonTreeDropdown` depending on the value of `is_tree` in the definition.

Being based on the standard dropdown classes, these custom ones are obviously translatable in the same way.

### CODE REVIEW

**Review by orthagh — COMMENTED** [review]
I wanted to test this one as well but as we (once again) are late on review, I thikg it's not up to date with the last evolution of generic routes for dropdown (#17454), no?

**Comment by cconard96** [comment]
> I wanted to test this one as well but as we (once again) are late on review, I thikg it's not up to date with the last evolution of generic routes for dropdown (#17454), no?

I think it needs a new route. Custom Asset types and models aren't handled by the new controller either.

**Comment by cedric-anne** [comment]
> > I wanted to test this one as well but as we (once again) are late on review, I thikg it's not up to date with the last evolution of generic routes for dropdown (#17454), no?
> 
> I think it needs a new route. Custom Asset types and models aren't handled by the new controller either.

They are mapped with the generic dropdown controllers here: https://github.com/glpi-project/glpi/blob/22df3fd58a764a63d406c5f71fc6b5cee5a9e84a/src/Glpi/Http/LegacyDropdownRouteListener.php#L87-L93

**Review by cedric-anne — APPROVED** [review]
I made some changes. Most important is that all custom dropdown are tree dropdowns, as it permits to simplify the code. I validated this change with @orthagh.

I did not had time to pass the whole test suite. If tests fails, I will fix them.

**Comment by cconard96** [comment]
> Most important is that all custom dropdown are tree dropdowns

Disagree with that change but not willing to argue. Will wait and see if any users provide feedback about that forced behavior.

**Comment by orthagh** [comment]
> Most important is that all custom dropdown are tree dropdowns

I agreed on this one for various reasons:
- it eases the code
- fields plugins was already like that and it may facilitate migrations

**Comment by orthagh** [comment]
Can we move the global menu entry into a breadcrumb entry of dropdowns

image

I don't think this will be such a common action, it's better to display it in a secondary context.

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
@cedric-anne 
2 small issues with massive actions:
- Put in trashbin does nothing
- Update on name display a dropdown instead of a text field.

**Comment by cedric-anne** [comment]
> Can we move the global menu entry into a breadcrumb entry of dropdowns Like "Home > Setup > Dropdowns > Dropdown definitions".
> 
> image
> 
> I don't think this will be such a common action, it's better to display it in a secondary context.

Done



> 2 small issues with massive actions:
> 
> * Put in trashbin does nothing

I removed the `is_deleted` field. None of the GLPI dropdowns have a trashbin management. The deletion system is specific and relies on a "replacement" feature on purge that would not work, at the moment, with a soft deleted state.

> * Update on name display a dropdown instead of a text field.

I remove this massive action. Changing a name massively makes no sense as dropdown names are expected to be uniques.

**Review by AdrienClairembault — APPROVED** [review]

**Comment by orthagh** [comment]
As said IRL, we need to do better regarding system name (the remark is valid for custom asset also) UX.
We should ask for a default label (we use it in absence of translations) and we deduce the system name from it (slugifying).
We should manage issues from reserved keyworks (like a label finishing by Model should be replaced by CustomModel or something like that).

Not blocking for this pr, but it should be done before release.

**Review by orthagh — APPROVED** [review]

**Pull request merged**
