### PR TITLE
send a fetch query instead xhr for unlocking object

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #5799

Fetch api seems to work on my side like explained in #5799, tested with chrome 78 and firefox 70
Added fallback for IE<=14 (Edge supports fetch api)
I need confirmation for this fallback (@tomolimo if you have internet explorer in production)

### CODE REVIEW

**Comment by orthagh** [comment]
For information, i needed to use `unload` to have fetch api working on firefox, `beforeunload` event with this browser failed without detail, just a cryptic message (TypeError: NetworkError when attempting to fetch resource.)

**Comment by tomolimo** [comment]
Hello @orthagh 
I made tests in our environment using this:
```
         $(function() {
               $(window).on('beforeunload', function() {
                  // will do an asynchroneous POST to the unlockobject script
                  var url = '".$CFG_GLPI['root_doc']."/ajax/unlockobject.php?unlock=1&id=$id';
                  if (navigator.sendBeacon) {
                     navigator.sendBeacon(url, '');
                  } else {
                     $.ajax({
                        method: 'POST',
                        url: url,
                        cache: false,
                        data: ''
                     });
                  }
               });
```
And I changed the reception for using $_REQUEST instead of $_GET

What do you think about this?

Thank you,
Regards,

Tomolimo

**Comment by orthagh** [comment]
No. As we said before in the issue conversation, sendBeacon doesn't work well (fetch yes) as it can send the beacon after a page is fully refreshed (too late so).

For POST/GET/REQUEST, yes it's ok for me.

**Comment by tomolimo** [comment]
Ok, then I'll do some tests with your proposal.
Just one thing: are you sure about the test: `window.fetch !== 'undefined'`? Shouldn't it be `typeof window.fetch !== 'undefined'`

**Comment by orthagh** [comment]
good catch

**Comment by tomolimo** [comment]
And then in ajax/unlockobject.php you should change $GET into $_REQUEST?
The fetch will do a POST, and the $.ajax a GET

**Comment by orthagh** [comment]
in my current change, both parts send parameters in GET.
By the way, i still can clean the method: POST as it's not used anymore

**Comment by tomolimo** [comment]
Hello,

I made a test with FF 70.0.1 and Chrome 78.0.3904.97, and in the network traces, one can see that the fetch is done after the get of the main ticket page:

image

and such the ticket is locked when doing a refresh of the page (F5)

....

the tests are ok with IE11 (fetch is not used in this case)

**Comment by cedric-anne** [comment]
On Chromium Version 78.0.3904.97, when adding an item in timeline, ticket is marked as locked on page reload.

**Pull request merged**
