### PR TITLE
Fixed next month for ticket recurrent for last day

### PR DESCRIPTION
**Pull request by edgardmessias**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | no

Old: `2018-01-31`, +1 MONTH, `2018-03-03`,  `2018-04-03`,  `2018-05-03`

New: `2018-01-31`, +1 MONTH, `2018-02-28`, `2018-03-31`, `2018-04-30`

### CODE REVIEW

**Comment by allanlopesprado** [comment]
I suggest the option is added (31 days)

image

**Comment by cedric-anne** [comment]
This fix does not work if start date is `30th day of january` and interval is `1 month`. In this case computed date will be `1st day of march` or `2nd day of march` depending on day count in february.

It will also not work if start date is `29th day of february` and interval is `1 year`. In this case computed date will be `1st day of march`.

**Comment by allanlopesprado** [comment]
I suggest again adding the 31st day in the calendar

**Comment by edgardmessias** [comment]
@cedric-anne, the solution is only for last day of month

**Comment by edgardmessias** [comment]
@allanlopesprado, open a issue with your request

**Comment by trasher** [comment]
This fix is only for one particular case, while there are several other known issues. I've created a ticket (https://github.com/glpi-project/glpi/issues/4134), to get all fixed (and anyways, there is no guarantee this will not break something else).
I close this one.

**Pull request closed without merging**
