### PR TITLE
Re-organize Search Code

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

### Issues:
The current Search class is a "god" object with nearly 9000 lines. It covers too many responsibilities and has a ton of references to other classes (mostly for quirks for various item types).
The class currently covers:
- The search input (query builder UI)
- The SQL building
- The display for all types including exports (Table, Map, CSV, PDF, Names List, etc). Multiple conditional checks are used to control the logic flow based on the output type. Map, browse, and standard table views are all just considered HTML output and only differentiated by a property in the data array.

#### Additional issues:
- Search options arrays have no strict schema (No array shape PHPDoc or class representation)
- Many exceptions for specific item types
- The shared data array is passed between functions as an argument instead of as a class property
- The search data array has no defined schema (Array shape PHPDoc or class representation)

There are a few new features that I looked into adding that I found would be very difficult and require a lot of changes (Searching on unstructured grouped data like toner percentages from the Native Inventory SNMP data, improving search on grouped data like ticket actors, etc). With the search engine broken up into separate systems, it should be easier to add new features.

### Goal:
1. Split the code of the current Search class into various classes in a new `Glpi\Search` namespace.
Breaking out the code will help developers focus on specific aspects of the Search engine at once.
2. Provide a schema for all or at least most of the array structures either in PHPDoc or through a class object.
3. Reduce usage of static and public methods.
4. Reduce the amount of data being passed between functions as parameters instead of class properties.
5. Reduce/remove the usage of globals like `$PDF_TABLE`.
6. Remove all unique logic for specific item types from the Search code

### The work done by this PR:
Most of the methods of the current Search class are now stubs that call methods in other classes in a new `Glpi\Search` namespace to maintain BC.
Everything in the new namespace is broken out into classes based on responsibility.
Every thing in the new namespace has no promise of BC and each class has been marked with an `internal` PHPDoc tag.
I expect that very little will remain as it currently is between now and the "completed" version.
The goal is to initially have the logic in easily mapped methods from the original class to avoid introducing too many bugs and make it easier for core developers to adapt.
Over the next few minor 10.X versions, the goal is to clean up the code and refactor it more and find ways to remove all the specific item type cases.
When the next major version comes and breaking changes can be added, the current Search class can be dropped in favor of a new entrypoint `Glpi\Search\SearchEngine`.
Ideally the new SearchEngine class will become mostly stable before the next major version and the current Search class can be deprecated to ease the transition more.

Layout of new Glpi\Search namespace:
- SearchEngine: Mostly a placeholder class that would become the new entrypoint for the search functionality.
- SearchOption: Represents a search option and has some static functions related to search options.
- Input\*: Classes that represent the input method for the search engine. Currently this is just the Query Builder input but in the future this could include any other input like a simple/tagged search bar (Like what is used in the Kanban?)
- Provider\*: Classes that contain the logic that takes the criteria from the Input classes and retrieves data from a data source. Currently, this is just a SQL Provider.
- Output\*: Classes that display or export the search results. There are classes for each of the current formats.

The planned/expected workflow for a standard search:
1. Call SearchEngine method to show a search page
2. Determine the Search Input to use
3. Call method in Search Input class to display the UI
4. Pass current/default criteria to the Search Provider
5. Search Provider parses the data and queries its data source (Database, etc)
7. Standardized results sent to the Search Output class for the requested output format.

Exports would work in a similar manner but would have a different entrypoint method in the SearchEngine class as it could bypass the Search Input part.

### CODE REVIEW

**Comment by orthagh** [comment]
To be continued asap, this is will be required for #12600 
And in roadmap project (see organization level), we will follow by also replacing echoing html by twig templates

**Comment by cconard96** [comment]
How much refactoring should be done in this PR alone? Right now, the methods are mostly moved as-is to new classes.
I'm working on fixing conflicts now.

**Comment by cedric-anne** [comment]
> How much refactoring should be done in this PR alone? Right now, the methods are mostly moved as-is to new classes.

IMHO, we should not do more on this PR, for 2 reasons.

1) The Search engine is likely to be impacted by global technical topics, and we will probably want to work on many of them quickly. The longer the time spent in a separate branch, the more time will be wasted managing conflicts.

2) As most of the changes are are only code moving, reviewing this PR will not be too hard. Once this PR would be merged, it would be possible to create additionnal small PRs to deal with this topic in small steps. Small steps will be easier to review than a global PR that would rewrite thousand lines of code. Also, if tests fails on a small step, it is easier to identify the source of this failure.

We talked about this IRL with @orthagh yesterday and he agreed with that.

@trasher Are you OK with this way of working for this topic?

**Comment by cedric-anne** [comment]
@cconard96 I wait for tests to be fixed before reviewing this PR.

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Pull request merged**
