### PR TITLE
API : GET /search/Itemtype : no content-range if no result 

### PR DESCRIPTION
**Pull request by btry**
see #1259

### CODE REVIEW

**Comment by btry** [comment]
this should be rather easy to test, I'll add it

**Comment by btry** [comment]
I added a method to check deeper consistency between Content-Range, count and total count of items returned by the Search endpoint

**Comment by orthagh** [comment]
Could you replicate the code into APIXmlrpc also ?

**Comment by orthagh** [comment]
did it myself

**Comment by orthagh** [comment]
@trasher could you check again with my last commit ?

**Comment by orthagh** [comment]
travis tests pass but with some output.
I'll check that monday

**Comment by trasher** [comment]
Closed for now, replaced by #1645 
Refactoring must be done on master, not on 9.1/bf.

**Pull request closed without merging**
