### PR TITLE
Add 'url' and 'specific_tags' like for dropdown::show()

### PR DESCRIPTION
**Pull request by tomolimo**
Added:
1) 'url' in the options of User::dropdown() to permit to re-use the User::dropdown for special processes.
2) 'specific_tags' in the options to permit pass of special tags for special processes.

### CODE REVIEW

**Comment by orthagh** [comment]
This can be merged after addition of short documention in docblockr

https://github.com/glpi-project/glpi/blob/0.90/inc/user.class.php#L3125-L3157

**Comment by tomolimo** [comment]
Would like me to it?

**Comment by orthagh** [comment]
Yup, please.

**Comment by tomolimo** [comment]
done :)

**Comment by orthagh** [comment]
great , i merge

**Pull request merged**
