### PR TITLE
Do not load commands of disabled plugins

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Prevent disabled plugin's command to be loaded.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Tests are failing

**Review by cedric-anne — APPROVED** [review]

**Comment by trasher** [comment]
please rebase to solve conflict

**Comment by trasher** [comment]
Tests are still failing

**Comment by AdrienClairembault** [comment]
I'm not sure why, only the `CSS compilation test` block fail.
`bin/console build:compile_scss` works fine on my end.

Also the error is a null `$DB` on this line: https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/commondbtm.class.php#L343.
Could this be a problem with the containers or CI ?

**Comment by trasher** [comment]
Well, I do not know why this is failing here exactly, but I'm almost sure scss compilation should have nothing to deal with glpi database, nor call the `isApi` function

**Comment by cedric-anne** [comment]
I am trying to understand why there is this failure.

> Well, I do not know why this is failing here exactly, but I'm almost sure scss compilation should have nothing to deal with glpi database, nor call the `isApi` function

These errors are not directly related to the CSS compilationc ommand. They are related to the console application initialization.

**Comment by trasher** [comment]
> These errors are not directly related to the CSS compilationc ommand. They are related to the console application initialization.

Yes, and I do not think we should use GLPI methods at this level.

**Comment by AdrienClairembault** [comment]
It works when removing typehint from the __construct command (see last commit).
Issue with the autoloader ? Looking into it.

**Comment by cedric-anne** [comment]
> It works when removing typehint from the __construct command (see last commit).
> Issue with the autoloader ? Looking into it.

It was passing with my previous commit.

I do not know why, but it seems that instanciation of `new Plugin()` in `CommandLoader` constructor was causing some weird issue with globals. I did not reproduced on local, but calling logic that find commands only when needed fixes the issue.

**Comment by cedric-anne** [comment]
> > These errors are not directly related to the CSS compilationc ommand. They are related to the console application initialization.
> 
> Yes, and I do not think we should use GLPI methods at this level.

DB is used as cache config is in DB (we could remove DB usage here by moving cache config outside DB, and, not sure about that, but the `isApi()` was used here in error handling process.

**Comment by AdrienClairembault** [comment]
Good to merge now I think, thanks @cedric-anne

**Review by trasher — APPROVED** [review]

**Pull request merged**
