### PR TITLE
Fix scss cacheability

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Backport of #5972, #5985, #5988, #6479, #6483 from 9.5/bugixes branch to make SCSS compiled on release process and highly cacheable.

### CODE REVIEW

**Comment by trasher** [comment]
@remicollet @yllen could you please test this one? You've talked me about some issues regarding to SCSS cache that should be solved. Thanks!

**Comment by yllen** [comment]
How to test it?
- I patch with changes of cedric-anne but not css_compile directory
- i do "php bin/console build:compile_scss", directory was created but empty

I don't know how to test it (view with @remicollet)

**Comment by cedric-anne** [comment]
Hi,

It should work by just calling `php bin/console build:compile_scss` on this branch.

image
image

Be sure to call the command with a user that has rights to create files.

Regards

**Comment by yllen** [comment]
I done this command but directory was created empty

**Comment by cedric-anne** [comment]
Hi,

Can you run the command with maximum verbosity (`php bin/console build:compile_scss -vvv`) and give us its output ?

Regards

**Comment by trasher** [comment]
Just tested on my side, that works (php 7.3/fedora). 
I had a fatal error on Zend/Laminas change; I had to drop the vendor directory and run composer install again (maybe due to a switch from a development branch).

**Comment by yllen** [comment]
`[yllen@nelly git94 (9.4/bugfixes)]$ php bin/console build:compile_scss -vvv
PHP Warning:  Cannot write "/home/yllen/git94/files/_cache/glpi_cache_db_9.4.55ee321469189133a2b583f704b59cd47.json" cache footprint file. Cache performance can be lowered. in /home/yllen/git94/inc/cache/simplecache.class.php on line 224
PHP Stack trace:
PHP   1. {main}() /home/yllen/git94/bin/console:0
PHP   2. Glpi\Console\Application->__construct() /home/yllen/git94/bin/console:71
PHP   3. Glpi\Console\Application->initCache() /home/yllen/git94/inc/console/application.class.php:79
PHP   4. Config::getCache() /home/yllen/git94/inc/console/application.class.php:307
PHP   5. Glpi\Cache\SimpleCache->__construct() /home/yllen/git94/inc/config.class.php:3135
PHP   6. Glpi\Cache\SimpleCache->checkFootprintFileIntegrity() /home/yllen/git94/inc/cache/simplecache.class.php:71
PHP   7. trigger_error() /home/yllen/git94/inc/cache/simplecache.class.php:224

Warning: Cannot write "/home/yllen/git94/files/_cache/glpi_cache_db_9.4.55ee321469189133a2b583f704b59cd47.json" cache footprint file. Cache performance can be lowered. in /home/yllen/git94/inc/cache/simplecache.class.php on line 224

Call Stack:
    0.0012     235656   1. {main}() /home/yllen/git94/bin/console:0
    0.8680    2734832   2. Glpi\Console\Application->__construct() /home/yllen/git94/bin/console:71
    1.0407    6626456   3. Glpi\Console\Application->initCache() /home/yllen/git94/inc/console/application.class.php:79
    1.0408    6627200   4. Config::getCache() /home/yllen/git94/inc/console/application.class.php:307
    1.4109    8834496   5. Glpi\Cache\SimpleCache->__construct() /home/yllen/git94/inc/config.class.php:3135
    1.4286    8939904   6. Glpi\Cache\SimpleCache->checkFootprintFileIntegrity() /home/yllen/git94/inc/cache/simplecache.class.php:71
    1.4286    8940304   7. trigger_error() /home/yllen/git94/inc/cache/simplecache.class.php:224

PHP Warning:  error_log(/home/yllen/git94/files/_log/php-errors.log): failed to open stream: Permission denied in /home/yllen/git94/inc/toolbox.class.php on line 587
PHP Stack trace:
PHP   1. {main}() /home/yllen/git94/bin/console:0
PHP   2. Glpi\Console\Application->__construct() /home/yllen/git94/bin/console:71
PHP   3. Glpi\Console\Application->loadActivePlugins() /home/yllen/git94/inc/console/application.class.php:91
PHP   4. Plugin::load() /home/yllen/git94/inc/console/application.class.php:393
PHP   5. plugin_init_reports() /home/yllen/git94/inc/plugin.class.php:168
PHP   6. searchReport() /home/yllen/git94/plugins/reports/setup.php:63
PHP   7. includeLocales() /home/yllen/git94/plugins/reports/inc/function.php:50
PHP   8. Toolbox::logInFile() /home/yllen/git94/plugins/reports/inc/function.php:85
PHP   9. error_log() /home/yllen/git94/inc/toolbox.class.php:587

Warning: error_log(/home/yllen/git94/files/_log/php-errors.log): failed to open stream: Permission denied in /home/yllen/git94/inc/toolbox.class.php on line 587

Call Stack:
    0.0012     235656   1. {main}() /home/yllen/git94/bin/console:0
    0.8680    2734832   2. Glpi\Console\Application->__construct() /home/yllen/git94/bin/console:71
    1.9120   13275032   3. Glpi\Console\Application->loadActivePlugins() /home/yllen/git94/inc/console/application.class.php:91
    2.1549   14026808   4. Plugin::load() /home/yllen/git94/inc/console/application.class.php:393
    2.1550   14027728   5. plugin_init_reports() /home/yllen/git94/inc/plugin.class.php:168
    2.1550   14029528   6. searchReport() /home/yllen/git94/plugins/reports/setup.php:63
    2.2245   14069752   7. includeLocales() /home/yllen/git94/plugins/reports/inc/function.php:50
    2.2368   14070520   8. Toolbox::logInFile() /home/yllen/git94/plugins/reports/inc/function.php:85
    2.2369   14071096   9. error_log() /home/yllen/git94/inc/toolbox.class.php:587

Processing "css/styles".

In StreamHandler.php line 107:
                                                                               
  [UnexpectedValueException]                                                   
  The stream or file "/home/yllen/git94/files/_log/php-errors.log" could not   
  be opened: failed to open stream: Permission denied                          
                                                                               

Exception trace:
  at /home/yllen/git94/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
 Monolog\Handler\StreamHandler->write() at /home/yllen/git94/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:39
 Monolog\Handler\AbstractProcessingHandler->handle() at /home/yllen/git94/vendor/monolog/monolog/src/Monolog/Logger.php:344
 Monolog\Logger->addRecord() at /home/yllen/git94/inc/toolbox.class.php:434
 Toolbox::log() at /home/yllen/git94/inc/toolbox.class.php:447
 Toolbox::logDebug() at /home/yllen/git94/inc/html.class.php:6819
 Html::compileScss() at /home/yllen/git94/tools/compilescsscommand.class.php:115
 CompileScssCommand->execute() at /home/yllen/git94/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/yllen/git94/vendor/symfony/console/Application.php:982
 Symfony\Component\Console\Application->doRunCommand() at /home/yllen/git94/inc/console/application.class.php:196
 Glpi\Console\Application->doRunCommand() at /home/yllen/git94/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /home/yllen/git94/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/yllen/git94/bin/console:72

glpi:build:compile_scss [-f|--file [FILE]]`

For the file, i's an old one
image

**Comment by trasher** [comment]
> `[yllen@nelly git94 (9.4/bugfixes)]$ php bin/console build:compile_scss -vvv
> PHP Warning: Cannot write "/home/yllen/git94/files/_cache/glpi_cache_db_9.4.55ee321469189133a2b583f704b59cd47.json" cache footprint file. Cache performance can be lowered. in /home/yllen/git94/inc/cache/simplecache.class.php on line 224

You have an issue in your environment. At least `files/_cache` and `files/_log` must be writeable for both your apache and local users.

Somethng like:
```
$ sudo chown -R apache:yllen files/
$ sudo chmod -R g+w files/
```

**Comment by trasher** [comment]
This fix has been reported as working by another user, at least to fix the issues he reported.

**Pull request merged**
