### PR TITLE
No history on MailCollector functional updates

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #17770

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
Looks good but I think we should use the `history_blacklist` property instead.
This avoid having to send the `false` value each time someone try to update a mailcollector (and also cover plugins).

Also, what do you think about clearing the relevant logs on the next database update ?
I checked our own GLPI instance and we have more than 500k unwanted logs on a single collector for this, it would make the history way more readable to delete them.

**Comment by trasher** [comment]
I do not understand your point. Adding an entry in logs table does not seems relevant in any of those cases.

**Comment by trasher** [comment]
> Also, what do you think about clearing the relevant logs on the next database update ?

Working on logs table takes an huge amount of resources and time, so no; I do not think we should handle that core side.

**Comment by AdrienClairembault** [comment]
> I do not understand your point. Adding an entry in logs table does not seems relevant in any of those cases.

Setting `public $history_blacklist = ['last_collect_date']` mean that any logs on this property will be refused.
You then don't have to worry about any update from core or plugins code, it is handled automatically.

> Working on logs table takes an huge amount of resources and time, so no; I do not think we should handle that core side.
I agree that working on the logs can be difficult, however the specific issue reported here is that the history of the collector is very slow and can't be used (because of the useless rows).
If we don't fix this history, the original issue is not really fixed :/

Not sure how we can deal with that, I guess some kind of non-mandatory update ?
I think we did it in the past with an index on the log table that isn't added if you have too many rows, instead GLPI tells you to manually run the query (but I guess most people in this case forget about it and never run the query...).

**Comment by trasher** [comment]
Honestly, I do not think any update is mandatory, and I have no time to work on that. 
As of the blacklist thing, I have no idea if it's really relevant.

**Comment by cedric-anne** [comment]
- Adding the property in the `$history_blacklist` property is indeed the best way to fix this.
- The `glpi_logs` table is supposed to have ndexes now, so deleting row that matches the corresponding itemtype and id_search_option should be fast, even on huge databases.

**Pull request closed without merging**
