### PR TITLE
Search / Future dates

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Allow future date on the following search criteria:

* Certificate:
   * Expiration date
* Tasks:
   * Begin date
   * End date
* Contract:
   * Start date
   * End date
* Infocom:
   * Decommission date

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !21923

### CODE REVIEW

**Comment by trasher** [comment]
If possible, I guess this would need unit tests

**Review by orthagh — APPROVED** [review]

**Comment by trasher** [comment]
> If possible, I guess this would need unit tests

ping?

**Comment by AdrienClairembault** [comment]
> 
> 
> > If possible, I guess this would need unit tests
> 
> ping?

Do you mean that you want me create a test for the 'maybefuture' param (it appears to not be tested yet) ?
I'll add it to my todo list, maybe this can be merged without it since it's not really adding any new feature (just enabling an existing option on some fields) ?

**Comment by trasher** [comment]
> Do you mean that you want me create a test for the 'maybefuture' param (it appears to not be tested yet) ?
> I'll add it to my todo list, maybe this can be merged without it since it's not really adding any new feature (just enabling an existing option on some fields) ?

Okay to add that in a future version, you're indeed right: this is not really a new feature.

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
