### PR TITLE
Add ticket status in navigation header

### PR DESCRIPTION
**Pull request by Drimmwald**
| Q             | A
| ------------- | ---
| Bug fix?    |  no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

Issues #2964

### CODE REVIEW

**Comment by trasher** [comment]
Hello,

Thanks for the PR, I got some remarks. First, CS checks are failing (not very important, but this needs to be fixed).

Second, copying the entire `showNavigationHeader` is probably not the way to go; we need to find something more generic I guess.

**Comment by trasher** [comment]
Maybe adding an option to existing method should does the trick (I've just took a very quick look)

**Comment by trasher** [comment]
Great; that sounds better :)

Just one more remark: maybe this new code should be run only  if we're from a Ticket (or maybe from a CommonITILObject; I guess this should appply as well on Changes and Problems).

**Comment by Drimmwald** [comment]
I think you are right. Now code working with Changes and Problems, but some styles of these statuses are absent. I will try fix in the near time.

**Comment by orthagh** [comment]
Sorry to answer late on this submission, but this is not ok imo.
We have an existing iconography for ITIL status representation and the submitted colors didn't match at all.
image

This set may be outdated and subject to review but we need to do a spec on this (on spec wiki: https://github.com/glpi-project/spec/wiki).
And this change should aim next major version.

In parallel, we can try to transform theses images in full css.

**Comment by trasher** [comment]
Reworked; see https://github.com/glpi-project/glpi/pull/3820

**Pull request closed without merging**
