### PR TITLE
Upgrade Font Awesome to version 5.2.0

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3270

### CODE REVIEW

**Comment by orthagh** [comment]
first and rapid review:

most important part is not changed at the the moment:
image

**Comment by cconard96** [comment]
Should be... test environment had it working as the code for those icons didn't need changed. I'll check I didn't have something cached on my browser when I get off work (+10 hours).

Its possible chrome handles them differently than Firefox as well and requires a higher font weight.

**Comment by cconard96** [comment]
I haven't been able to re-create that issue on a fresh copy of the master branch and my commit. Tested in Linux with Chrome and Firefox, and Chrome from my phone.

**Comment by cconard96** [comment]
This should be the final commit. I believe the missing icon issue has been corrected by setting font weights in 9c4717d.

**Comment by orthagh** [comment]
Ok, it was my fault for missing icon, my working folder for master was broken.

With your last and a clean on my side, here is some additional notes:
- size for some icons changed: 

image

- Calendar pic is very ugly: 
image

Maybe we could use `calendar-alt`

- fa-global became also ugly, 
image

I suggest replace by `globe-americas`

**Comment by orthagh** [comment]
One last thing also, instead adding font-weight, it could be better to add the corresponding classes provided by the lib (if not used in a before|after pseudo classes)

**Pull request merged**
