### PR TITLE
Fix display of actiontime in problems

### PR DESCRIPTION
**Pull request by jnsc**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #8828

### CODE REVIEW

**Comment by jnsc** [comment]
Sorry, I somehow unwillingly closed previous pull request.

**Comment by trasher** [comment]
No problem ;)

**Review by trasher — APPROVED** [review]

**Comment by cedric-anne** [comment]
I have some remarks.

1. I saw you are copying `actiontime` of source ticket when creating a problem from a ticket. I do not know if it make sence on the ITIL point of view, but I saw that this `actiontime` property is not updatable in a ticket (field is only displayed on creation form). @orthagh @trasher Do you know any reason for this ?

2. This issue is also affecting change form. It should be fixed too.

**Comment by orthagh** [comment]
Filling `actiontime` on ticket creation will only create a task with the same duration and a label like "Auto-created task"
So it's just a shortcut

On the global subject, i don't know, but it make sense to **not** copy actiontime as when you create a problem from a ticket, you are probably in another time than the original ticket (and so you spend different hours).

**Comment by cedric-anne** [comment]
I wonder if the fix is correct.

What should be done when user defines an actiontime on change/problem creation ? Should a task be created like for tickets ? In this case, as for tickets, field should not be visible/updatable on edit form.

**Comment by jnsc** [comment]
> I wonder if the fix is correct.
> 
> What should be done when user defines an actiontime on change/problem creation ? Should a task be created like for tickets ? In this case, as for tickets, field should not be visible/updatable on edit form.

Not sure if I can help on this, for me I just was willing to fix the issue that the value was not displayed, and thus reset to 0 on each ticket updated. 
But creating a "linked" task might also be a good idea, but I do not see how to create them in the interface as there is no kind of "followup" like tickets. But I also wondered if this existed, as they are referenced in the planning (you can show problem tasks).

**Comment by cedric-anne** [comment]
> I do not see how to create them in the interface as there is no kind of "followup" like tickets.

There is a `processing xxx` tab in changes/problems which propose almost same features as for tickets.

Finally, the fix should be to apply to the changes and problems what is currently done on the tickets:
 - the `actiontime` field should be visible only on creation form,
 - when the value of `actiontime` field is > 0 on item creation, a task should be created automatically (see `Ticket::post_addItem()`).

As I can see in the code, `actiontime` of corresponding ITIL item is updated each time a task `actiontime` is updated.

If you don't think you will be able to produce such a fix, you can close this PR.

**Comment by jnsc** [comment]
Ok, I'll try to implement it that way.

**Comment by cedric-anne** [comment]
Hi,

I close this PR because it seems that it will not be finished. Feel free to reopen it later, if you want to work on it.

Regards

**Pull request closed without merging**
