### PR TITLE
Add administrator as a default notification recipient

### PR DESCRIPTION
**Pull request by MyvTsv**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

This PR ensures that the administrator is automatically added as the default recipient in notifications to the GLPI installation if there are no recipients.

### CODE REVIEW

**Review by stonebuzz — APPROVED** [review]

**Comment by trasher** [comment]
I'm not sure this should be changed in a stable release; also test are failing.

Is this required for a customer?

**Comment by Rom1-B** [comment]
At the moment, these notifications are created without a recipient, so they don't work by default. This was probably an oversight?

The aim is to add it only for new installations, not for upgrades.

**Comment by cedric-anne** [comment]
> At the moment, these notifications are created without a recipient, so they don't work by default. This was probably an oversight?

What are these notifications ?

**Comment by MyvTsv** [comment]
> > At the moment, these notifications are created without a recipient, so they don't work by default. This was probably an oversight?
> 
> What are these notifications ?

- Alert Reservation
- Alert Ticket not closed
- Cartridges
- Consumables
- Contract End
- Contract End Periodicity
- Contract Notice
- Contract Notice Periodicity
- Item not unique
- Software Licenses
- Ticket Recall
- Infocoms

**Comment by cedric-anne** [comment]
> > > At the moment, these notifications are created without a recipient, so they don't work by default. This was probably an oversight?
> > 
> > 
> > What are these notifications ?
> 
> * Alert Reservation
> * Alert Ticket not closed
> * Cartridges
> * Consumables
> * Contract End
> * Contract End Periodicity
> * Contract Notice
> * Contract Notice Periodicity
> * Item not unique
> * Software Licenses
> * Ticket Recall
> * Infocoms

I am not sure that every GLPI administrator want to receive them. IMHO, the GLPI administrator should only receive notifications related to system issues.

**Comment by trasher** [comment]
> The aim is to add it only for new installations, not for upgrades.

Yes, but this will introduce a quite important change on default installations, beginning in an arbitrary minor release.

Anyway, I'm still not sure of the change. It's something that must be configured per instance right now, and maybe it's the better option.

**Comment by Rom1-B** [comment]
OK, we thought it was an oversight, but if it was intentional, it's definitely a change in behavior, **so it must target MAIN**

**Review by trasher — CHANGES_REQUESTED** [review]
See comments

**Pull request closed without merging**
