### PR TITLE
Allow specifying authorized OAuth redirect URIs

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Allow specifying the authorized redirect URIs for OAuth clients.

### CODE REVIEW

**Comment by flegastelois** [comment]
LGTM, is it possible to move the inputs?
Client ID, then Client Secret (on the left).
Grants, then Comments (right).

image

**Comment by cconard96** [comment]
Fields have been moved. The blank space on the right side between Grants and Comments is the Scopes field whenever we decide to define any. Since no scopes are defined, the field is hidden and replaced with a placeholder "null" field.

**Comment by trasher** [comment]
Tests are failing

**Review by orthagh — APPROVED** [review]

**Comment by flegastelois** [comment]
It seems that we cannot delete a redirect URL.

Click on the “trash” button:
image

Then save:
image

Redirect URL is still present.

**Comment by cconard96** [comment]
I think this PR is OK now. The globally allowed redirect URIs are shown now to hopefully avoid any users thinking that no URIs listed means it would accept every redirect by default.
There were some other issues I noticed while testing again, but it looks like they were only on my end. Apparently, Swagger caches the authorization code, so if you log out and back in, it tries to get a new token with the now expired authorization code. There was also an error once about the state being invalid (non-blocking warning), but I've not been able to recreate the issue since then.

**Review by cedric-anne — COMMENTED** [review]
Seems OK.

**Review by orthagh — APPROVED** [review]

**Pull request merged**
