### PR TITLE
Show product_number in dropdown

### PR DESCRIPTION
**Pull request by xacobofg**
Show both Model name and Product Number for every Model in GLPI.
Allow model dropdowns lookup by Product number additional to Model name.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
This may be an interresting feature. I guess it could be activated for everyone, without requiring a new option.

Could you add a test on this case ? There is already a test called `Dropdown::testGetDropdownValue()`. Adding a new case in `Dropdown::getDropdownValueProvider()` should be enough.

**Review by orthagh — APPROVED** [review]

**Comment by xacobofg** [comment]
Hi @cedric-anne.
I have no experience adding tests.
How should I add a new case?

**Comment by cedric-anne** [comment]
> Hi @cedric-anne.
> I have no experience adding tests.
> How should I add a new case?

It depends on test case, so most of the time, looking on an existing test case is a good way to find the way to do.

I added a test case by myself and rebased your pull request.

**Review by cedric-anne — APPROVED** [review]

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Provided patch must be applied.

**Comment by trasher** [comment]
> > Hi @cedric-anne.
> > I have no experience adding tests.
> > How should I add a new case?
> 
> It depends on test case, so most of the time, looking on an existing test case is a good way to find the way to do.
> 
> I added a test case by myself and rebased your pull request, but was not able to push it on your repository. Here is the patch.
> 
> [test.patch.txt](https://github.com/glpi-project/glpi/files/5867267/test.patch.txt)

Not sure adding bootstrap data is required here; should not this be added locally only? (not a blocker).

**Comment by cedric-anne** [comment]
> Not sure adding bootstrap data is required here; should not this be added locally only? (not a blocker).

All tested data from this provider comes from Bootstrap, so I wanted to keep the same logic.

**Comment by trasher** [comment]
> All tested data from this provider comes from Bootstrap, so I wanted to keep the same logic.

Ok sounds legit then :)

**Review by trasher — APPROVED** [review]

**Pull request merged**
