### PR TITLE
Rest API

### PR DESCRIPTION
**Pull request by orthagh**
## Todo

- [x] Enhance Logs
- [x] Dedicated page for config
   - [x] with logs
   - [x] link to inline documentation
   - [x] enable/disable auth methods (credentials/token)
- [x] Unit tests
- [x] URI with 2 itemtypes (ex /api/Ticket/1/TicketFollowup/), with GET/POST
- [x] IP Restriction
- [x] app_token declaration
- [x] protocols
   - [x] REST
   - [x] XMLRPC

### CODE REVIEW

**Comment by orthagh** [comment]
## Todo

- [ ] Enhance Logs
- [ ] Dedicated page for config
   - [ ] with logs
   - [ ] link to inline documentation
   - [ ] enable/disable auth method (credentials/token)
- [ ] XML with REST
- [ ] URI multiple itemtypes
- [ ] IP Restriction
- [ ] app_token declaration
- [ ] Others protocols (XMLRPC, SOAP) ?

**Comment by remicollet** [comment]
I saw 2 new lib:
* guzzlehttp
* parsedown

Can you please give version used / required ?

**Comment by remicollet** [comment]
In tools/composer.json, I see

+        "guzzlehttp/guzzle": "~1.6.0"

Adding external lib, when registered on packagist, is a good idea (IMHO) and can simply maintaince.

Bug 1.6.0... this sounds very strange....

**Comment by orthagh** [comment]
I need to add parsedown to composer.json.
For guzzle, i didn't find their autoloader.php included in .tar.gz version of release and so, i couldn't complete the update_lib.sh script


You're right for 1.6.0 version, i can't explain why i write this version (it must be 6.2.0)

**Comment by orthagh** [comment]
1.6.0 is the version of parsedown :)

**Comment by remicollet** [comment]
I think we shoudl really move to use the composer.json and its autoloader.... 

With, in inc/autoload.function.php

     require_once dirname(__DIR__) . '/vendor/autoload.php';


This will make everything more simpler.
People using the git snapshot will just have to run a "composer install"

**Comment by ddurieux** [comment]
I started see this features and the only I have seen, this is my comments:

* Token is the session id instead a token in the account database, so it expire
* Token MUST be passed in basic auth instead variable in GET
* Auth (initSession) params must be in POST instead GET because backend (GLPI framework) can generate the token
* Get data of an itemtype not use HATEOAS, so it's not very usable
* When add item, use the key 'input' is  useless, so send directly a list of data [{...}, {...}]
* When get items, the the fields where is _integer_ is offered as string

I haven't see all, but perhaps code this big feature, make specifications can be a very good idea...

**Comment by orthagh** [comment]
Thank you for your suggestions. Here some answers : 

> Token is the session id instead a token in the account database, so it expire

yes, this one is a session_token and represent a valide session in glpi.
It's now a http header parameter.

> Token MUST be passed in basic auth instead variable in GET

Done, now initSession support Basic Auth instead of query parameters

> Auth (initSession) params must be in POST instead GET because backend (GLPI framework) can generate the token

See above

> Get data of an itemtype not use HATEOAS, so it's not very usable

It was a wip, now getItem and getItems endpoints support a more complete HATEOAS (not exhaustive but we can complete furtherly)

> When add item, use the key 'input' is useless, so send directly a list of data [{...}, {...}]

It's a good point and it was because of the session_token was passed by json payload.
Now, this last pass by http header, i can work on removing this input key.

> When get items, the the fields where is integer is offered as string

Fixed by a JSON_NUMERIC_CHECK in  d212b0d

> I haven't see all, but perhaps code this big feature, make specifications can be a very good idea...

As you can see, this feature is not yet in official glpi core.
It's a draft implementation a.
In fact, minimal specs exists for internal teclib project and for a mutual work with prelude project (CS company).

**Comment by axlroden** [comment]
When accessing the add API agent page I have no save button.
/glpi/front/apiclient.form.php

screen shot 2016-07-06 at 14 01 56

**Comment by orthagh** [comment]
Is your tests are done a new glpi installation ?

**Comment by edgardmessias** [comment]
And SOAP protocol?

**Comment by ddurieux** [comment]
Really? Back in the Middle Ages :D

**Pull request merged**
