### PR TITLE
fix(notification): force `quoted-printable` encoding

### PR DESCRIPTION
**Pull request by stonebuzz**
I've been trying for a while to understand why some notifications have a poor HTML rendering in Outlook.

- GLPI Notification template translation

image

```sql
+----+--------------------------+----------+---------+--------------+--------------------------+
| id | notificationtemplates_id | language | subject | content_text | content_html             |
+----+--------------------------+----------+---------+--------------+--------------------------+
| 35 |                       36 | fr_FR    | toto    | a            | &#60;p&#62;a&#60;/p&#62; |
+----+--------------------------+----------+---------+--------------+--------------------------+
```

- Generated notification

image

```sql
MariaDB [preprod]> select * from glpi_queuednotifications where id = 44659 \G
*************************** 1. row ***************************
                      id: 44659
                itemtype: Ticket
                items_id: 362876
notificationtemplates_id: 36
             entities_id: 0
              is_deleted: 1
                sent_try: 0
             create_time: 2023-06-20 09:38:30
               send_time: 2023-06-20 09:38:30
               sent_time: 2023-06-20 09:38:37
                    name: [***** Ticketing System #0362876] test
                  sender: *******@*****.com
              sendername: 
               recipient: teclib@****.com
           recipientname: teclib
                 replyto: NULL
             replytoname: NULL
                 headers: {"Auto-Submitted":"auto-generated","X-Auto-Response-Suppress":"OOF, DR, NDR, RN, NRN"}
               body_html: &#60;!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                        'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'&#62;&#60;html&#62;
                        &#60;head&#62;
                         &#60;META http-equiv='Content-Type' content='text/html; charset=utf-8'&#62;
                         &#60;title&#62;[***** Ticketing System #0362876] teest&#60;/title&#62;
                         &#60;style type='text/css'&#62;
                           
                         &#60;/style&#62;
                        &#60;/head&#62;
                        &#60;body&#62;
&#60;p&#62;a&#60;/p&#62;&#60;br&#62;&#60;br&#62;-- 
&#60;br&#62;&#60;br&#62;Généré automatiquement par GLPI&#60;br&#62;&#60;br&#62;

&#60;/body&#62;&#60;/html&#62;
               body_text: a

-- 

Généré automatiquement par GLPI


               messageid: GLPI_fjdKeHbgf6PeW4iOhjztWKNiRBIfPDgYcKZsxWKN-Ticket-362876.1687246710.2147018271@5326-glpi
               documents: 
                    mode: mailing
```

- Decoded raw

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                        'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html>
                        <head>
                         <META http-equiv='Content-Type' content='text/html; charset=utf-8'>
                         <title>[**** Ticketing System #0362876] toto</title>
                         <style type='text/css'>

                         </style>
                        </head>
                        <body>
<p>a</p><br><br>-- 
<br><br>Généré automatiquement par GLPI<br><br>

</body></html>
```

- Outlook rendering

image

Switching to the 'base64' encoding seems to fix the problem.

I therefore think that the problem lies with PHPMailer

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !27844

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]

**Comment by cedric-anne** [comment]
To be more precise, we figured out that some notifications were wrongly rendered on Outlook (they were using the `8-bits` encoding), and some were correctly rendered (they were using the `quoted-printable` encoding).

Usage of 2 distinct encodings is due to https://github.com/PHPMailer/PHPMailer/blob/312ed95ab03e7f3f0316191e5bfb9f920b705825/src/PHPMailer.php#L2829-L2833

Forcing usage of `quoted-printable` fixes the issue in Outlook, and permit to ensure that all notifications are built the same way.

**Review by orthagh — APPROVED** [review]

**Comment by yanisvolteo** [comment]
Hello, the solution you proposed only works for PHPMailer and not for an office SMTP notification service?

**Comment by stonebuzz** [comment]
Hi @yanisvolteo 

```PHPMailer``` is used by GLPI to send mail via SNMP if configured.

See ```GLPIMailer``` class that extends ```PHPMailer```

Best regards

**Comment by yanisvolteo** [comment]
hi @stonebuzz thank you so much, it's good !!

Best regards

**Comment by wessrafamessi** [comment]
Hello,

I have encountered an issue regarding the email notifications for tickets. The automatic action "queuednotification" is not functioning as expected, which means that I have to execute it manually to clear the notification queue.

I would appreciate your assistance in resolving this issue, if possible.

Best regards

**Comment by stonebuzz** [comment]
@wessrafamessi 

I don't think this is a problem about this request.

Please open a new issue

**Pull request merged**
