### PR TITLE
Adding an address field and inheritance in the location drop down

### PR DESCRIPTION
**Pull request by amma35**
PR for location see #532

### CODE REVIEW

**Comment by orthagh** [comment]
Sorry for delay of answer & management of this PR.

I'm testing the feature and can't find how this works.
You're adding an adress field, but it doesn't to be editable anywhere (i can't find where i guess, in the location form).

Also, can you explain the mecanism for inheritance field ?

**Comment by amma35** [comment]
You can add a location when the location have no parent or if the inheritance is not checked

Exmple : I can add an adress on this location (because he doesn't have parent)

image

In this case, the child location has inheritance checked so you cannot change his address

image

**Comment by yllen** [comment]
I don't understand the need.
If inheritance of the parent location you can change the address that means you can't change longitude, Latitude and Altitude. But you can't have two different locations this these same information.

**Comment by trasher** [comment]
Sounds like the changes are not OK; and PR is stalled from a while. I'm closing, thanks.

**Pull request closed without merging**
