### PR TITLE
fix(Inventory): prevent SQL warning on load lockedfields

### PR DESCRIPTION
**Pull request by stonebuzz**
Prevent SQL warning when GLPI try to load ```LockedField``` from item

```shell
  *** MySQL query warnings:
  SQL: SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Item_DeviceFirmware' AND ((`items_id` = '' OR `is_global` = '1'))
  Warnings: 
1292: Truncated incorrect DECIMAL value: ''
  Backtrace :
  src/DBmysqlIterator.php:112                        
  src/DBmysql.php:1078                               DBmysqlIterator->execute()
  src/Lockedfield.php:218                            DBmysql->request()
  src/Lockedfield.php:158                            Lockedfield->getLocks()
  src/Inventory/Asset/InventoryAsset.php:433         Lockedfield->getLockedNames()
  src/Inventory/Asset/Device.php:175                 Glpi\Inventory\Asset\InventoryAsset->handleInput()
  src/Inventory/Asset/MainAsset.php:937              Glpi\Inventory\Asset\Device->handle()
  src/Inventory/Asset/MainAsset.php:852              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/Inventory/Asset/NetworkEquipment.php:228       Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/RuleImportAsset.php:988                        Glpi\Inventory\Asset\NetworkEquipment->rulepassed()
  src/Rule.php:1541                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1640                        Rule->process()
  src/Inventory/Asset/MainAsset.php:574              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:722                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:353                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:283                      Glpi\Inventory\Request->inventory()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:242                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:187                         Glpi\Inventory\Conf->importContentFile()
  src/Inventory/Conf.php:291                         Glpi\Inventory\Conf->importFiles()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->displayImportFiles()
  {"user":"2@stanislas-asus-desktop"} 
```

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15724

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — COMMENTED** [review]
As far as I understand, this issue is trigerred when a new device is created. Do we have a test case for this in our test suite ?

**Comment by trasher** [comment]
I don't think we have tests about that, and I have no idea how to reproduce

**Comment by stonebuzz** [comment]
after several tests, I can't trigger the warning

the behavior seems different 

even with 

```patch
diff --git a/tests/units/DB.php b/tests/units/DB.php
index 6082026eda..625e3d3b00 100644
--- a/tests/units/DB.php
+++ b/tests/units/DB.php
@@ -773,6 +773,17 @@ SQL,
             '1292: Truncated incorrect INTEGER value: \'1a\'' . "\n" . '1292: Truncated incorrect INTEGER value: \'123b\'',
             LogLevel::WARNING
         );
+
+
+        $db->query('SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = \'Item_DeviceFirmware\' AND ((`items_id` = \'\' OR `is_global` = \'1\'))');
+        $this->array($db->getLastQueryWarnings())->isEqualTo(
+            [
+                'Level'   => 'Warning',
+                'Code'    => 1292,
+                'Message' => 'Truncated incorrect DECIMAL value: \'\'',
+            ]
+        );
+        $this->hasSqlLogRecordThatContains('1292: Truncated incorrect INTEGER value: \'\'', LogLevel::WARNING);
     }
 
     protected function dataDrop()

```

**Comment by trasher** [comment]
Well... We have an initial issue with lack of information; and requester did not provide any further details.

I'm not fan of making changes we cannot reproduce, because we may miss the real issue.

I'll take a look to add a test to reproduce.

**Comment by cedric-anne** [comment]
By the way, this issue will only happen on MariaDB.
For example, there is this kind of workaround in search engine testing:
https://github.com/glpi-project/glpi/blob/82da80aac54634904c2c6b3f7b89dc233cf23f30/tests/functional/Search.php#L3649-L3664

Also, I think I found why we had no failure on this. Look at the following code. The first SELECT does not trigger any warning, probably because the `` `itemtype` = 'Item_DeviceBlabla' `` condition is false, and following conditions are not even evaluated. The second SELECT produces a warning, because there is matching rows for the `` `itemtype` = 'Item_DeviceFirmware' `` condition, so the following ones are evaluated.
```php
global $DB;
$DB->insert("glpi_lockedfields", ["field" => mt_rand(), "itemtype" => "Item_DeviceFirmware", "is_global" => 0]);
$DB->query("SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Item_DeviceBlabla' AND ((`items_id` = '' OR `is_global` = '1'))");
$DB->query("SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Item_DeviceFirmware' AND ((`items_id` = '' OR `is_global` = '1'))");

**Comment by stonebuzz** [comment]
I can reproduce on my side with new TU and byusing old way

```$locks = $lockeds->getLockedNames($item->getType(), $item->fields['id'] ?? 0);```

```shell
tests\units\Glpi\Inventory\Asset\Firmware::testLockedFieldandFirmware():
In file DEV/GLPI/10.0-bugfixes/tests/functional/Glpi/Inventory/Assets/Firmware.php on line 0, array() failed: Unexpected entries in log in tests\units\Glpi\Inventory\Asset\Firmware::testLockedFieldandFirmware:
Array
(
    [0] => Array
        (
            [channel] => glpisqllog
            [level] => WARNING
            [message] => DBmysql::query() in DEV/GLPI/10.0-bugfixes/src/DBmysql.php line 419
  *** MySQL query warnings:
  SQL: SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Item_DeviceFirmware' AND ((`items_id` = '' OR `is_global` = '1'))
  Warnings: 
1292: Truncated incorrect DECIMAL value: ''
  Backtrace :
  .../GLPI/10.0-bugfixes/src/DBmysqlIterator.php:112 
  ...LIB/DEV/GLPI/10.0-bugfixes/src/DBmysql.php:1078 DBmysqlIterator->execute()
  .../DEV/GLPI/10.0-bugfixes/src/Lockedfield.php:218 DBmysql->request()
  .../DEV/GLPI/10.0-bugfixes/src/Lockedfield.php:158 Lockedfield->getLocks()
  ...ixes/src/Inventory/Asset/InventoryAsset.php:433 Lockedfield->getLockedNames()
  ...0.0-bugfixes/src/Inventory/Asset/Device.php:175 Glpi\Inventory\Asset\InventoryAsset->handleInput()
  ...I/10.0-bugfixes/src/Inventory/Asset/Bios.php:77 Glpi\Inventory\Asset\Device->handle()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:937 Glpi\Inventory\Asset\Bios->handle()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:852 Glpi\Inventory\Asset\MainAsset->handleAssets()
  .../GLPI/10.0-bugfixes/src/RuleImportAsset.php:988 Glpi\Inventory\Asset\MainAsset->rulepassed()
  ...TECLIB/DEV/GLPI/10.0-bugfixes/src/Rule.php:1541 RuleImportAsset->executeActions()
  .../GLPI/10.0-bugfixes/src/RuleCollection.php:1640 Rule->process()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:574 RuleCollection->processAllRules()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:722 Glpi\Inventory\Asset\MainAsset->handle()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:353 Glpi\Inventory\Inventory->handleItem()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:101 Glpi\Inventory\Inventory->doInventory()
  ...I/10.0-bugfixes/tests/InventoryTestCase.php:132 Glpi\Inventory\Inventory->__construct()
  ...nctional/Glpi/Inventory/Assets/Firmware.php:173 InventoryTestCase->doInventory()
  ...gfixes/vendor/atoum/atoum/classes/test.php:1352 tests\units\Glpi\Inventory\Asset\Firmware->testLockedFieldandFirmware()
  Standard input code:1                              atoum\atoum\test->runTestMethod()
 
        )

    [1] => Array
        (
            [channel] => glpisqllog
            [level] => WARNING
            [message] => DBmysql::query() in DEV/GLPI/10.0-bugfixes/src/DBmysql.php line 419
  *** MySQL query warnings:
  SQL: SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Item_DeviceFirmware' AND ((`items_id` = '' OR `is_global` = '1'))
  Warnings: 
1292: Truncated incorrect DECIMAL value: ''
  Backtrace :
  .../GLPI/10.0-bugfixes/src/DBmysqlIterator.php:112 
  ...LIB/DEV/GLPI/10.0-bugfixes/src/DBmysql.php:1078 DBmysqlIterator->execute()
  .../DEV/GLPI/10.0-bugfixes/src/Lockedfield.php:218 DBmysql->request()
  .../DEV/GLPI/10.0-bugfixes/src/Lockedfield.php:158 Lockedfield->getLocks()
  ...ixes/src/Inventory/Asset/InventoryAsset.php:433 Lockedfield->getLockedNames()
  ...0.0-bugfixes/src/Inventory/Asset/Device.php:175 Glpi\Inventory\Asset\InventoryAsset->handleInput()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:937 Glpi\Inventory\Asset\Device->handle()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:852 Glpi\Inventory\Asset\MainAsset->handleAssets()
  .../GLPI/10.0-bugfixes/src/RuleImportAsset.php:988 Glpi\Inventory\Asset\MainAsset->rulepassed()
  ...TECLIB/DEV/GLPI/10.0-bugfixes/src/Rule.php:1541 RuleImportAsset->executeActions()
  .../GLPI/10.0-bugfixes/src/RuleCollection.php:1640 Rule->process()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:574 RuleCollection->processAllRules()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:722 Glpi\Inventory\Asset\MainAsset->handle()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:353 Glpi\Inventory\Inventory->handleItem()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:101 Glpi\Inventory\Inventory->doInventory()
  ...I/10.0-bugfixes/tests/InventoryTestCase.php:132 Glpi\Inventory\Inventory->__construct()
  ...nctional/Glpi/Inventory/Assets/Firmware.php:173 InventoryTestCase->doInventory()
  ...gfixes/vendor/atoum/atoum/classes/test.php:1352 tests\units\Glpi\Inventory\Asset\Firmware->testLockedFieldandFirmware()
  Standard input code:1                              atoum\atoum\test->runTestMethod()
 
        )

    [2] => Array
        (
            [channel] => glpisqllog
            [level] => WARNING
            [message] => DBmysql::query() in DEV/GLPI/10.0-bugfixes/src/DBmysql.php line 419
  *** MySQL query warnings:
  SQL: SELECT * FROM `glpi_lockedfields` WHERE `itemtype` = 'Item_DeviceFirmware' AND ((`items_id` = '' OR `is_global` = '1'))
  Warnings: 
1292: Truncated incorrect DECIMAL value: ''
  Backtrace :
  .../GLPI/10.0-bugfixes/src/DBmysqlIterator.php:112 
  ...LIB/DEV/GLPI/10.0-bugfixes/src/DBmysql.php:1078 DBmysqlIterator->execute()
  .../DEV/GLPI/10.0-bugfixes/src/Lockedfield.php:218 DBmysql->request()
  .../DEV/GLPI/10.0-bugfixes/src/Lockedfield.php:158 Lockedfield->getLocks()
  ...ixes/src/Inventory/Asset/InventoryAsset.php:433 Lockedfield->getLockedNames()
  ...0.0-bugfixes/src/Inventory/Asset/Device.php:175 Glpi\Inventory\Asset\InventoryAsset->handleInput()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:937 Glpi\Inventory\Asset\Device->handle()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:852 Glpi\Inventory\Asset\MainAsset->handleAssets()
  .../GLPI/10.0-bugfixes/src/RuleImportAsset.php:988 Glpi\Inventory\Asset\MainAsset->rulepassed()
  ...TECLIB/DEV/GLPI/10.0-bugfixes/src/Rule.php:1541 RuleImportAsset->executeActions()
  .../GLPI/10.0-bugfixes/src/RuleCollection.php:1640 Rule->process()
  ...-bugfixes/src/Inventory/Asset/MainAsset.php:574 RuleCollection->processAllRules()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:722 Glpi\Inventory\Asset\MainAsset->handle()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:353 Glpi\Inventory\Inventory->handleItem()
  ...I/10.0-bugfixes/src/Inventory/Inventory.php:101 Glpi\Inventory\Inventory->doInventory()
  ...I/10.0-bugfixes/tests/InventoryTestCase.php:132 Glpi\Inventory\Inventory->__construct()
  ...nctional/Glpi/Inventory/Assets/Firmware.php:173 InventoryTestCase->doInventory()
  ...gfixes/vendor/atoum/atoum/classes/test.php:1352 tests\units\Glpi\Inventory\Asset\Firmware->testLockedFieldandFirmware()
  Standard input code:1                              atoum\atoum\test->runTestMethod()
 
        )

)
```

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Pull request merged**
