### PR TITLE
glpi_networkequipments.ram is a string, not an integer

### PR DESCRIPTION
**Pull request by kabassanov**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
Can you explain, for instance with screenshots or with a small description of the issue?

**Comment by kabassanov** [comment]
> Can you explain, for instance with screenshots or with a small description of the issue?

Sorry, I'm just facing users assault due to my GLPI migration :).

So, it is rather simple... I tried to find through the global search field a pattern (let's say 12345) and got a lot of sql warnings:
```Warnings: 1292: Truncated incorrect DOUBLE value: ''
```
So I copied the sql request into mysql and got the same warning until I found that there was a comparison in the where clause in the form  glpi_networkequipments.ram = 12345. As the table field is defined as string, the unquoted pattern is not correct.

**Comment by cedric-anne** [comment]
The `number` type permits to do searches with advanced operators, for instance `>= 64` to search for network equipements that have more than 64 Mio of RAM.

I guess problem may appear for all fields that have SO with `number` type but are stored as string in database.

**Comment by kabassanov** [comment]
> The `number` type permits to do searches with advanced operators, for instance `>= 64` to search for network equipements that have more than 64 Mio of RAM.
> 
Is there in GLPI a special treatment for patterns that could be interpreted as numbers?  In this case, there is probably a way to try translating sql values to numbers?

> I guess problem may appear for all fields that have SO with `number` type but are stored as string in database.
I guess too... But just detected the one in the global search of my setup...

**Comment by trasher** [comment]
I cnanot reproduce any error on my side. Please provide a way to reproduce.

**Comment by kabassanov** [comment]
> I cnanot reproduce any error on my side. Please provide a way to reproduce.

Is your user allowed to check in glpi_networkequipments and does your search configured to look for? Also the real pattern I used was  4500298820 . don't think this changes anything. BTW, I use glpi code with bugfixes applied until last Saturday.

**Comment by trasher** [comment]
Tested on up to date 10.0/bugfixes, with super admin user. Someone else has tested too, and cannot reproduce either (same conditions as me I guess).

**Comment by kabassanov** [comment]
> Tested on up to date 10.0/bugfixes, with super admin user. Someone else has tested too, and cannot reproduce either (same conditions as me I guess).

I have still a copy of the request, even if right now does not show this warning... Could you contact me in private somehow?

**Comment by cconard96** [comment]
I confirmed the reported bug while the `ram` column is added to my display preferences. Oddly, this warning wasn't logged initially after I added the display preference but is now consistently showing.

A more complete fix, seems to be the following which will ensure the values are quoted even though they may be numeric. On the database side, it then wouldn't matter what the data type is as it is valid to have `'12345'` in a comparison for a numeric field. On the GLPI side, we can maintain the `number` datatype for the search option to allow the more advanced operators feature.

Most likely, this would be fixed and handled in a similar way with the values being quoted anyways once the Search code is updated (WIP) to use the array format.

```diff
diff --git a/src/Search.php b/src/Search.php
index 3d742db96d..a80a2d9ae3 100644
--- a/src/Search.php
+++ b/src/Search.php
@@ -3559,21 +3559,23 @@ JAVASCRIPT;
                     }
 
                     if (is_numeric($val)) {
+                        $numeric_val = (int) $val;
+                        $quoted_numeric_val = $DB::quoteValue($numeric_val);
                         if (isset($searchopt[$ID]["width"])) {
                             if (!$NOT) {
-                                return " $LINK (`$NAME` < " . (intval($val) + $searchopt[$ID]["width"]) . "
+                                return " $LINK (`$NAME` < " . $DB::quoteValue($numeric_val + $searchopt[$ID]["width"]) . "
                                         AND `$NAME` > " .
-                                           (intval($val) - $searchopt[$ID]["width"]) . ") ";
+                                        $DB::quoteValue($numeric_val - $searchopt[$ID]["width"]) . ") ";
                             }
-                            return " $LINK (`$NAME` > " . (intval($val) + $searchopt[$ID]["width"]) . "
+                            return " $LINK (`$NAME` > " . $DB::quoteValue($numeric_val + $searchopt[$ID]["width"]) . "
                                      OR `$NAME` < " .
-                                        (intval($val) - $searchopt[$ID]["width"]) . " ) ";
+                                    $DB::quoteValue($numeric_val - $searchopt[$ID]["width"]) . " ) ";
                         }
-                       // Exact search
+                        // Exact search
                         if (!$NOT) {
-                            return " $LINK (`$NAME` = " . (intval($val)) . ") ";
+                            return " $LINK (`$NAME` = " . $quoted_numeric_val . ") ";
                         }
-                        return " $LINK (`$NAME` <> " . (intval($val)) . ") ";
+                        return " $LINK (`$NAME` <> " . $quoted_numeric_val . ") ";
                     }
                     break;
             }
@@ -5273,7 +5275,8 @@ JAVASCRIPT;
                     }
 
                     if (is_numeric($val) && !$decimal_contains) {
-                        $numeric_val = floatval($val);
+                        $numeric_val = (float) $val;
+                        $quoted_numeric_val = $DB::quoteValue($numeric_val);
 
                         if (in_array($searchtype, ["notequals", "notcontains"])) {
                             $nott = !$nott;
@@ -5288,18 +5291,18 @@ JAVASCRIPT;
                                 $ADD = " OR $tocompute IS NULL";
                             }
                             if ($nott) {
-                                return $link . " ($tocompute < " . ($numeric_val - $searchopt[$ID]["width"]) . "
-                                        OR $tocompute > " . ($numeric_val + $searchopt[$ID]["width"]) . "
+                                return $link . " ($tocompute < " . $DB::quoteValue($numeric_val - $searchopt[$ID]["width"]) . "
+                                        OR $tocompute > " . $DB::quoteValue($numeric_val + $searchopt[$ID]["width"]) . "
                                         $ADD) ";
                             }
-                            return $link . " (($tocompute >= " . ($numeric_val - $searchopt[$ID]["width"]) . "
-                                      AND $tocompute <= " . ($numeric_val + $searchopt[$ID]["width"]) . ")
+                            return $link . " (($tocompute >= " . $DB::quoteValue($numeric_val - $searchopt[$ID]["width"]) . "
+                                      AND $tocompute <= " . $DB::quoteValue($numeric_val + $searchopt[$ID]["width"]) . ")
                                      $ADD) ";
                         }
                         if (!$nott) {
-                            return " $link ($tocompute = $numeric_val) ";
+                            return " $link ($tocompute = $quoted_numeric_val) ";
                         }
-                        return " $link ($tocompute <> $numeric_val) ";
+                        return " $link ($tocompute <> $quoted_numeric_val) ";
                     }
                     break;
             }
```

These changes seem to pass the functional tests without issue with the exception of one test that was expecting an unquoted numeric value in the generated SQL (so not an issue).
```diff
diff --git a/tests/functional/Search.php b/tests/functional/Search.php
index 16bbbeb941..3752cfcf95 100644
--- a/tests/functional/Search.php
+++ b/tests/functional/Search.php
@@ -435,7 +435,7 @@ class Search extends DbTestCase
          ->contains("(`glpi_users`.`id` = '2')")
          ->contains("OR (`glpi_users`.`id` = '3')")
          // match having
-         ->matches("/HAVING\s*\(`ITEM_Budget_2`\s+<>\s+5\)\s+AND\s+\(\(`ITEM_Printer_1`\s+NOT LIKE\s+'%HP%'\s+OR\s+`ITEM_Printer_1`\s+IS NULL\)\s*\)/");
+         ->matches("/HAVING\s*\(`ITEM_Budget_2`\s+<>\s+'5'\)\s+AND\s+\(\(`ITEM_Printer_1`\s+NOT LIKE\s+'%HP%'\s+OR\s+`ITEM_Printer_1`\s+IS NULL\)\s*\)/");
     }
 
     public function testViewCriterion()
```

**Comment by trasher** [comment]
I'm still not able to reproduce adding column in display preferences. I guess the real issue is somewhere else, either a bad data, or a column combination?

Proposed fix does not seems correct to me, jbut I can't really say since I still not reproduce

**Comment by cedric-anne** [comment]
IMHO, the correct fix is to change the datatype in database. If value is expected to be an integer, we should use a `int` type in database.

**Comment by kabassanov** [comment]
> The bug can be reproduced only if the database has some particular datas in it. Will tell you more in few minutes.

OK, In my glpi_networkequipments table all "ram" entries contain an empty string instead of being NULL. Do you have the same?

**Comment by trasher** [comment]
This column defaults to null, and that's what I have when there si no value. Maybe your issue is coming from fusioninventory migration (I've not checked). All networks equipments in my tests database has been inventoried this morngin with native inventory.
I'm also waiting for @cconard96 feedback, I'm not sure he had migrated data on his side.

**Comment by cconard96** [comment]
An older network equipment I have that I manually added does have an empty string value for ram. The rest are numeric or null.
This was a text field in older GLPI versions rather than a number field.

**Comment by kabassanov** [comment]
> This column defaults to null, and that's what I have when there si no value. Maybe your issue is coming from fusioninventory migration (I've not checked). All networks equipments in my tests database has been inventoried this morngin with native inventory. I'm also waiting for @cconard96 feedback, I'm not sure he had migrated data on his side.

My network equipments are not inventoried (by glpi & plugins). And if you want to create one manually, the corresponding dropdown seems to be (now) an integer list defaulting to 0 ...

**Comment by trasher** [comment]
OK, then I reproduce, setting manually an empty string as `ram` column value, haveing this column displayed and issuing a search with a mathematical comparison (like `>1`).
I still think the Search modification proposed is to huge (without any tests run, hard to say - I'm always a bit affraid of changing Search class). 
I think a correct fix would be to set the column in database to the correct type. 

Thoughts?

**Comment by trasher** [comment]
See #14965 as an alternative

**Comment by trasher** [comment]
Replaced with #14951

**Pull request closed without merging**
