### PR TITLE
Fixes #5303

### LINKED ISSUE #5303: [GLPI 9.3] Can update a ticket even if UPDATE rights are not given
Hello,

A user can update a ticket if he/she is a requester (or writer) of this ticket and if there is no followups and no tasks and ticket.status is not closed, nor solved.

This is a problem, when the UPDATE right is not given to this user.

And this is of course a problem with the object lock mechanism.

See screenshot:

image

I'm going to provide a fix for that.

Thank you,
regards,
Tomolimo

### PR DESCRIPTION
**Pull request by tomolimo**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #5303

### CODE REVIEW

**Comment by trasher** [comment]
Tests are failing

**Comment by cedric-anne** [comment]
Hi,

Base logic seems to be that the requester can update its ticket if no work has been done on it yet. So I agree with the addition of a check on the number of tasks, but not really on the check on the global update right.

By the way, we should also check if there are no solution.

Regards

**Comment by ConteZero** [comment]
> Base logic seems to be that the requester can update its ticket if no work has been done on it yet. So I agree with the addition of a check on the number of tasks, but not really on the check on the global update right.


I have to disagree here, I think that if the UPDATE permission is not set for a profile than the user with that profile should not be able to update the ticket, no matter if he's the requester and no work has been done on the ticket yet.

Giving the user the ability to make changes to his tickets could potentially break the workflow on some installations, for example when you use a service catalog and you don't want any changes from the user after ticket creation.

**Comment by yllen** [comment]
> > Base logic seems to be that the requester can update its ticket if no work has been done on it yet. So I agree with the addition of a check on the number of tasks, but not really on the check on the global update right.
> 
> I have to disagree here, I think that if the UPDATE permission is not set for a profile than the user with that profile should not be able to update the ticket, no matter if he's the requester and no work has been done on the ticket yet.
>
With comportment is for simplified interface that not have the right to update a ticket.

**Comment by trasher** [comment]
No feedback from a while, closing.

**Pull request closed without merging**
