### PR TITLE
Fixed missing empty choice string for timezone settings

### PR DESCRIPTION
**Pull request by nenes82**
On main tab for personal settings

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Review by tomolimo — APPROVED** [review]

**Review by cedric-anne — COMMENTED** [review]
You should also change it in the showForm method.

**Comment by nenes82** [comment]
> You should also change it in the showForm method.

Hello,
In which file ?  I changed it in the showForm method of user.class.php

**Comment by cedric-anne** [comment]
> > You should also change it in the showForm method.
> 
> Hello,
> In which file ? I changed it in the showForm method of user.class.php

In the same file. You changed it in the `showMyForm` method, and it should also be changed in the `showForm` method.

Regards

**Comment by nenes82** [comment]
> > > You should also change it in the showForm method.
> > 
> > 
> > Hello,
> > In which file ? I changed it in the showForm method of user.class.php
> 
> In the same file. You changed it in the `showMyForm` method, and it should also be changed in the `showForm` method.
> 
> Regards

Ok! It's done
Regards

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
