### PR TITLE
Add missing 'getIcon()' function to the AllAssets class

### PR DESCRIPTION
**Pull request by RomainLvr**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33468

The Advenced dashboard plugin uses a `getIcon()` function on certain classes for saved searches, for example. However, for a saved search that concerns all assets, we need the `getIcon()` function of the AllAssets class, but it doesn't exist.

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]
@orthagh is that icon OK for you?

**Review by AdrienClairembault — APPROVED** [review]
Note: this is a fa icon.

I know we try to prioritize tabler icons but this specific icon doesn't exist on their side, so I guess it is OK (unless someone suggest an alternative, but it isn't easy to find a good icon for this case).

**Comment by orthagh** [comment]
Agree, please use a tabler icon

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
We have a different icon here:

image

I don't know which icon we want to keep but it must be the same for both places (the menu should call the getIcon method and not use a hardcoded value).

**Comment by cconard96** [comment]
> Note: this is a fa icon.
> 
> I know we try to prioritize tabler icons but this specific icon doesn't exist on their side, so I guess it is OK (unless someone suggest an alternative, but it isn't easy to find a good icon for this case).

The direct replacement I think is `ti ti-packages`.

**Comment by RomainLvr** [comment]
> We have a different icon here (`Global` is a link to `front/allasset.php`):
> 
> image
> 
> I don't know which icon we want to keep but it must be the same for both places (the menu should call the getIcon method and not use a hardcoded value).

I've found the place in the code where the icon is defined and it's hardcoded :
`Html.php` lines 1522 to 1526

image

I think the icon suggested by Curtis would be suitable.
image

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Comment by AdrienClairembault** [comment]
👍

**Pull request merged**
