### PR TITLE
Fix In-Reply-To token for thread of notifications

### PR DESCRIPTION
**Pull request by OlivierLM**
See http://cr.yp.to/immhf/thread.html and http://cr.yp.to/immhf/token.html

### CODE REVIEW

**Comment by OlivierLM** [comment]
Sorry, pushed my master to fast, refer to commit 485b5f3e74eb685c8f8e1a1dce42ab3320e20a75 on my master branch for this pull request

**Comment by yllen** [comment]
In many of your commits you want to delete all information about GLPI and i'm not agree with that.

**Comment by remicollet** [comment]
Please close this, and open a correct one, with the change you think are acceptable.
* 1 PR per goal with  explanation.

**Comment by orthagh** [comment]
+1 to macro PR and explanation.
And so, please use english commits.

Thanks for your contributions

**Pull request closed without merging**
