### PR TITLE
Dashboard/TicketSummary: don't filter waiting_validation on current user

### PR DESCRIPTION
**Pull request by AdrienClairembault**
image

On the "Ticket summary" card that you can see above, the "To validate" column is filtered on the current logged in user.
This doesn't make sense as the other four columns only filter on status.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !22124

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
If you remove this filter, you also have to change this label: `__("Tickets waiting your validation")`.

**Review by orthagh — CHANGES_REQUESTED** [review]
I disagree with this change as it impact some cards and it shouldn't

Ex:
- "Number of Ticket waiting for your approval"
- "List of Ticket waiting for your approval"

these two (at least) are impacted by your change and i think they should be kept as current.

The cause is `Glpi\Dashboard\Provider::genericTicket` is genericaly used by many cards and one change can be destructive

**Comment by AdrienClairembault** [comment]
After last commit:
image

**Comment by AdrienClairembault** [comment]
There is an issue with the list display that seems to be caused by this changes, looking into it.

**Comment by AdrienClairembault** [comment]
Rebased and fixed, should be all good now:
image

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
