### PR TITLE
Allow to add pending reasons when item is already pending

### PR DESCRIPTION
**Pull request by AdrienClairembault**
It is currently impossible to add a pending reason to a pending ticket:

image

After changes:

image

Note that if the ticket is pending AND already have a pending reason, the input will still not be shown to avoid overriding the active pending reason.

image

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !26069

### CODE REVIEW

**Comment by Rom1-B** [comment]
For the 3rd screenshot, after adding a manual pending follow up, do auto follow ups work?

**Comment by AdrienClairembault** [comment]
> For the 3rd screenshot, after adding a manual pending follow up, do auto follow ups work?

Do you suspect any issue with it ? It does not impact auto follow as far as I know.

**Comment by Rom1-B** [comment]
Yes, currently, when a ticket has an active pending reason and a follow-up is added (pending or not), the pending reason stops, there are no more auto generated follow-ups.
If the new follow-up is pending, either the waiting reason continues to work or it is stopped, but in this case, the dropdown of the reasons should be displayed to be able to activate a new one.

**Comment by AdrienClairembault** [comment]
Understood, I'll do some testing and report back ;)

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Comment by AdrienClairembault** [comment]
> Yes, currently, when a ticket has an active pending reason and a follow-up is added (pending or not), the pending reason stops, there are no more auto generated follow-ups. If the new follow-up is pending, either the waiting reason continues to work or it is stopped, but in this case, the dropdown of the reasons should be displayed to be able to activate a new one.

Fixed in `1d4e8cd66d`.

We should probably add tests for this part, will look into it.

**Review by cedric-anne — APPROVED** [review]

**Review by Rom1-B — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
