### PR TITLE
make itil buttons visible above debug bar

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

### CODE REVIEW

**Review by cedric-anne — DISMISSED** [review]

**Comment by cedric-anne** [comment]
When debug bar is completely closed, there is a display issue.

image

**Comment by orthagh** [comment]
With the following diff, it seems everything ok:
```diff
diff --git a/css/includes/components/_debug-toolbar.scss b/css/includes/components/_debug-toolbar.scss
index 5570f9ad63..e12e4d6e90 100644
--- a/css/includes/components/_debug-toolbar.scss
+++ b/css/includes/components/_debug-toolbar.scss
@@ -78,3 +78,37 @@
         }
     }
 }
+
+body.debug-active:not(.debug-folded) {
+    .search_page {
+        .search-container {
+            @include media-breakpoint-up(lg) {
+                height: calc(100vh - #{$contextbar-height} - #{$content-margin} - 50px);
+            }
+        }
+    }
+
+    .tab-pane:not([id^="tab-Ticket_main"]) {
+        margin-bottom: 50px;
+    }
+
+    .itil-object {
+        @include media-breakpoint-up(lg) {
+            height: calc(100vh - 187px - 46px);
+        }
+    }
+
+
+    &.horizontal-layout {
+        .itil-object {
+            @include media-breakpoint-up(lg) {
+                height: calc(100vh - 257px - 46px);
+            }
+        }
+    }
+
+    .search-footer,
+    .itil-footer {
+        bottom: 46px;
+    }
+}
diff --git a/css/includes/components/itilobject/_footer.scss b/css/includes/components/itilobject/_footer.scss
index 24113a89f6..00beb28a4a 100644
--- a/css/includes/components/itilobject/_footer.scss
+++ b/css/includes/components/itilobject/_footer.scss
@@ -31,11 +31,6 @@
  * ---------------------------------------------------------------------
  */
 
-body.debug-active {
-    .itil-footer {
-        bottom: 50px;
-    }
-}
 
 .itil-footer {
     position: sticky;
diff --git a/js/modules/Debug/Debug.js b/js/modules/Debug/Debug.js
index 8a1f56311d..bf95978325 100644
--- a/js/modules/Debug/Debug.js
+++ b/js/modules/Debug/Debug.js
@@ -350,12 +350,14 @@ window.GLPI.Debug = new class Debug {
     showDebugToolbar() {
         $('.debug-toolbar-content').removeClass('d-none');
         $('#debug-toolbar').addClass('w-100').css('width', null);
+        $('body').removeClass('debug-folded');
     }
 
     hideDebugToolbar() {
         $('.debug-toolbar-content').addClass('d-none');
         $('#debug-toolbar-expanded-content').addClass('d-none');
         $('#debug-toolbar').removeClass('w-100').css('width', 'fit-content');
+        $('body').addClass('debug-folded');
     }
 
     toggleExtraContentArea(force_show = false) {
diff --git a/templates/components/debug/debug_toolbar.html.twig b/templates/components/debug/debug_toolbar.html.twig
index b89c0ef7b8..772df473d1 100644
--- a/templates/components/debug/debug_toolbar.html.twig
+++ b/templates/components/debug/debug_toolbar.html.twig
@@ -44,7 +44,7 @@
    </li>
 {% endmacro %}
 
-<div id="debug-toolbar" class="position-sticky bottom-0 w-100 card" tabindex="0">
+<div id="debug-toolbar" class="position-fixed bottom-0 w-100 card" tabindex="0">
    <div class="resize-handle my-n2" style="cursor: row-resize; height: 10px; z-index: 1030"></div>
    <div class="d-flex flex-row">
       <div class="debug-toolbar-badge d-flex py-2">
```

Main changes are:
- changing the debug-bar to fixed position rather than sticky (no space reserved at the bottom so)
- adding a class on body for tracking toggle of debugbar
- adjusting position of some elements already set with 100% viewport height

**Comment by cedric-anne** [comment]
@cconard96 Could you rebase and check the fix proposed by @orthagh ?

**Comment by cconard96** [comment]
Seems OK to me

**Review by orthagh — APPROVED** [review]

**Comment by cedric-anne** [comment]
There is a scrollbar on the ticket creation form, and probably some useless spacing between the form and the bottom of the page.
image

**Review by cedric-anne — APPROVED** [review]

**Comment by AdrienClairembault** [comment]
I don't know if you consider this an issue or not but with the bar extended some content at the bottom of the page is unreachable 

image

It is less problematic as you can reduce the bar as needed, not a blocking issue.

**Pull request merged**
