### PR TITLE
Add ability to link ITIL items to a project

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Add ability to link ITIL items to a project. Previously, it was only possible for changes.

### CODE REVIEW

**Comment by trasher** [comment]
Tests are failing

**Comment by cedric-anne** [comment]
There was a typo in the `glpi-empty.sql` file.

**Comment by trasher** [comment]
Maybe good to add unit tests?

**Comment by cedric-anne** [comment]
I added basic tests on:
 - link creation,
 - link copy on project clone (from template),
 - link deletion on project deletion,
 - link deletion on ITIL item deletion.

**Comment by trasher** [comment]
Could you please rebase and squash?

**Comment by cedric-anne** [comment]
Done.

**Pull request merged**
