### PR TITLE
Added a global configuration named "include_inactive_users" to includ…

### LINKED ISSUE #1590: Cannot search for inactive users in search forms
Hello,
When in a search list form (ex: ticket.php, user.php, ...), and you need to search for inactive users (or users with `glpi_users.end_date < NOW()`), you cannot find them in the `is + dropdown` list and such can only find them in the `contains + textbox` using their name.
This is not OK, as for exemple when a technician left the company and of course his/her account has been de-activated, then you can't do any request to find his/her still open tickets, or whatever you need to find about him/her.
Regards,
Tomolimo

### PR DESCRIPTION
**Pull request by tomolimo**
to include inactive users in user dropdowns
fixes #1590

### CODE REVIEW

**Comment by tomolimo** [comment]
> At least, you'll have to open a separate PR against master, to add parameter correctly; and handle the update

Ok I'll do it

> BTW, maybe should we think about a way not to alter schema when adding new config parameters.

I totally agree with that, otherwise it's not useful to have change the configuration setting (cancelling of one field per config setting).

**Comment by orthagh** [comment]
(for information, dont set milestone on your PR when you have a ticket, same for tags)

**Comment by tomolimo** [comment]
Ok, thank you

**Comment by orthagh** [comment]
Any news on this ?

Do you plan to rework it to target master and add update/install process ?
Or should we close it ?

**Comment by tomolimo** [comment]
I plan to push it on master like we discussed, but currently I've no time :(

**Comment by orthagh** [comment]
Ok, no worry. 
I just ping to have an eta.

**Comment by tomolimo** [comment]
Hello,
As I detected a side effect on this PR, I close it without merge.
I'll propose something else,
Regards,
Tomolimo

**Pull request closed without merging**
