### PR TITLE
Forms: collaspe sections

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Allow sections to be collapsed.

image

Collapsed:
image

Non-collapsed:
image

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]

**Comment by AdrienClairembault** [comment]
Seen with @orthagh, we will fully hide the questions while in collapsed mode.

**Comment by AdrienClairembault** [comment]
Now a collapsed section's questions are fully hidden:

image

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Comment by cedric-anne** [comment]
Please rebase to solve conflicts.

**Comment by AdrienClairembault** [comment]
Wait before merging, I've found a small issue

**Comment by AdrienClairembault** [comment]
All good now

**Pull request merged**
