### PR TITLE
Instanciate cache during container compilation

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

I added checks on `Toolbox::useCache()` at every place we use the global `$GLPI_CACHE` object.
The idea it to make everything working without cache, in order to instanciate cache during DI container initialization (and not prior to).
Next step will be to fetch cache parameters from container itself.

### CODE REVIEW

**Comment by cedric-anne** [comment]
We can also make the opposite, considering that cache is always enabled and drop this kind of tests.
To do this, we have to ensure that nothing uses the cache prior to container compilation, but this should be done anyway.

**Comment by trasher** [comment]
Doing like this is what I had in mind; I found complicated to always have to check and not be sure cache is available.
Another point is activating cache really does makes a difference, currently on a few parts, but this is growing. Having a cache system - even if it is a "basic" one - make sense to me.

Also, I've replaced some `$_SESSION` entries by using cache. If there is no cache, I guess this would cause issues.

**Comment by trasher** [comment]
Oh, I forget to mention that cache should certainly not be used before the DI setup; even if I guess this is not as simple right now ;)

**Comment by cedric-anne** [comment]
Ok, I would try to do this.

**Comment by cedric-anne** [comment]
I had to use `glpi_configs` instead of `Config::getTable()` and encounter the same problem for `glpi_plugins` in another work. Cache on this method is maybe a bad idea as it is hard to not use it in application bootstrap.  As it is only a string computation, could we use static property to cache values instead of cache storage?

**Comment by trasher** [comment]
Data are already stored in the `$CFG_GLPI` variable. Since most of the `DbUtils::getTableForItemtype()` method do quite light operations, I guess we should just not rely on any cache/global/whatever in `CommonDBTM::getTable()`

**Pull request merged**
