### PR TITLE
Collasped sidebar tweaks

### PR DESCRIPTION
**Pull request by AdrienClairembault**
A few minor improvements to the collasped sidebar.

Before:
image

After: 
image

Side by side:
image    --- image

The issues that were bugging me with the sidebar were:

1\) Not enough top padding for the logo.

image

Now the padding match the padding used for the "non-collapsed" logo:
image

2\) The "go to menu" icon didn't match the size of the others icons.

image

It was even more noticeable if you swaped the icon for the same as the one below:

image

3\)  Not enough spacing between each menu:

It felt like the icons were accumulated at the top of the page.
They are now spaced a bit more evenly, matching the spacing of the "non-collapsed" menu.

4\) Can't read the active menu:

I don't think this one was intentional but it definitely needed to be fixed:

image

After fix:

image

I realize that some of these changes might be subjective, so let me know what you think :) 

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Review by orthagh — COMMENTED** [review]
> The "go to menu" icon didn't match the size of the others icons.

It affects also the non collapsed layout. if you can push a fix for it.

> I realize that some of these changes might be subjective, so let me know what you think :)

seems good for me

**Comment by AdrienClairembault** [comment]
> It affects also the non collapsed layout. if you can push a fix for it.

Done 6c95915.

Note that this icon difference is because its a button instead of an `<li>` element.
Maybe another PR could be done to convert it to an `<li>` element for the vertical layout.

**Comment by orthagh** [comment]
as seen together and to be picky, fix of GLPI logo position could be done also on expanded state

**Review by orthagh — APPROVED** [review]
Go for merge, logo part will be fixed in another PR

**Pull request merged**
