### PR TITLE
add new field : glpi_computers.os_kernel_version; and add a dialog to…

### PR DESCRIPTION
**Pull request by orthagh**
add new field : glpi_computers.os_kernel_version; and add a dialog to see advanced os information in primary form

### CODE REVIEW

**Comment by orthagh** [comment]
Example : 

OS adavanced information

**Comment by yllen** [comment]
Be careful  $tab[48] is use in monitor that can be requester from computer list

**Comment by orthagh** [comment]
@yllen, in **meta**-criteria, no ? So we don't have any collisions (no 48 searchoptions in computer directly)

**Comment by orthagh** [comment]
manually merge in d90de29040f03d48edfb51173b070fa712d61d03 to avoid conflict (and a lot of pain)

**Comment by ddurieux** [comment]
I think we have a regression on display OS information.
Before this patch, we see directly in computer form _service pack_, _os productID_ ... and now user need click on link to display it.

Why not keep it display be default? I think many users will complain about this usefull information.

**Comment by wawax** [comment]
It's not a regression, this is what we wanted.
We want to hide these kind of information, that you don't need to see everyday.

**Comment by remicollet** [comment]
I think the new popup is inconsistent with over display in GLPI.

If you have there is too much information on the main tab, please consider adding a new tab.

**Pull request closed without merging**
