### PR TITLE
Fix OLA progress bar

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #8179 (maybe)

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Comment by carlosbayerl** [comment]
Could you tell me which file and in which folder it is recorded? So that I can fix it.

**Comment by cconard96** [comment]
> Could you tell me which file and in which folder it is recorded? So that I can fix it.

The files changed tab shows each file that and changes (only src/Search.php here), the and the lines that were changed. For 9.5.X, the file would be inc/Search.class.php but the lines would be different depending on the version.

**Comment by carlosbayerl** [comment]
@cconard96 Hello.
The version I use is 9.5.6. and the toto file is different. I replaced the entire file, it still didn't work.  Can you help me?

**Comment by carlosbayerl** [comment]
I inserted the new lines in the file. And it still didn't work. Then I copied the code presented on the forum and it didn't work either.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
