### PR TITLE
Fix multiple MAC handling for network equipment connection

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #17459

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
Seems OK, but is it possible to add a test?

**Comment by cconard96** [comment]
> Seems OK, but is it possible to add a test?

If I understood what it was doing, or supposed to be doing, maybe. Without spending a ton of time on it, it just looked like the suggestion made in the bug report was correct. The `connections` property has numeric keys while `connection_ports` is keyed by itemtype.

**Comment by cedric-anne** [comment]
> > Seems OK, but is it possible to add a test?
> 
> If I understood what it was doing, or supposed to be doing, maybe. Without spending a ton of time on it, it just looked like the suggestion made in the bug report was correct. The `connections` property has numeric keys while `connection_ports` is keyed by itemtype.

The idea is not to validate the fix, but to validate that this case will continue to work in the future.

@trasher or @stonebuzz  may probaby help to add a test case.

**Comment by trasher** [comment]
I'll try to add a test

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
