### PR TITLE
Improve kb

### PR DESCRIPTION
**Pull request by trasher**
Various improvement to the knowledge base. See [the changelog!](https://github.com/TECLIB/glpi/blob/d8453e514abf37b9716f3944e6da3b761141bd1e/CHANGELOG.md)! :D

### CODE REVIEW

**Comment by trasher** [comment]
I've rebased and re-tested; all sounds to work... Ready for review :)

**Comment by orthagh** [comment]
Already saw this work but splitted in different branches.
So one comment, for new ajax files, maybe we could merge into one who take all action, no ?

**Comment by trasher** [comment]
Honestly... I do not know. What is the problem with multiple files?

Note for myself: drop all `$AJAX_INCLUDE`; this is certainly useless :)

**Comment by trasher** [comment]
OK, ajax_includes have been dropped.

As for the ajax files, it would provide a very complicated file for almost no factorization; so I'll let as is.

**Pull request merged**
