### PR TITLE
VirtualMachines genericity

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Review by orthagh — APPROVED** [review]
tested quickly seems good

**Comment by trasher** [comment]
I tried to add missed deprecated classes; but since I add `src/ComputerVirtualMachine.php`; database update is failing; I really have no idea why and how to fix :/

**Comment by cedric-anne** [comment]
> I tried to add missed deprecated classes; but since I add `src/ComputerVirtualMachine.php`; database update is failing; I really have no idea why and how to fix :/

My last commit should fix it. There was a `getTableForItemType('ComputerVirtualMachine')` usage in an old migration.

**Comment by trasher** [comment]
> My last commit should fix it. There was a `getTableForItemType('ComputerVirtualMachine')` usage in an old migration.

Well catched, thanks :)

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
