### PR TITLE
Semi-column was missing in &quote HTML entity

### PR DESCRIPTION
**Pull request by tomolimo**
Semi-column was missing in &quote HTML entity, and such when double-quotes were present in the text, they were converted into '; instead of '

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Comment by cedric-anne** [comment]
`&quote;` is for double quotes, shoud be changed by `&apos;` (see https://www.toptal.com/designers/htmlarrows/punctuation/apostrophe/)

**Comment by tomolimo** [comment]
> `&quote;` is for double quotes, shoud be changed by `&apos;` (see https://www.toptal.com/designers/htmlarrows/punctuation/apostrophe/)

That's why I changed ' to this ", do you propose to add `&apos;` to the conversion array?

**Comment by tomolimo** [comment]
Or should we use a standard PHP function like `htmlspecialchars_decode()`?

**Comment by tomolimo** [comment]
Here is a complete (?) list of HTML entities: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

**Comment by cedric-anne** [comment]
This `addslashes_deep` function has been designed to handle `'` chars escaping for DB operations. I do not know why there is such replacements on entities, but I think it should only handle transformation of `'` chars.
So I propose to remove this `&quote;` and replace it by an `&apos;`.

**Pull request merged**
