### PR TITLE
Added missing 'group in charge of the task'

### PR DESCRIPTION
**Pull request by tomolimo**
In Planning recall notifications is missing the 'group in charge of the task'

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Review by orthagh — CHANGES_REQUESTED** [review]
I agree with the proposed changes, but currently `9.5/bugfixes` branch is in maintenance only mode.
You must target master for this pr.

No more remarks, the code is good.

**Comment by tomolimo** [comment]
Hello @orthagh 
I understand, but we really need this in 9.5.5 and next releases, otherwise it means that we are going to be blocked in 9.5.5 and that we will not use 9.5.6 ....
Thank you,
Regards,
Tomolimo

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]
As discussed with @orthagh ; ok ot merge

**Comment by tomolimo** [comment]
Thank you to you all.
Regards,
Tomolimo

**Pull request merged**
