### PR TITLE
0.91 sla gti

### PR DESCRIPTION
**Pull request by korial29**
New SLA structure

see #382

### CODE REVIEW

**Comment by orthagh** [comment]
1st impressions :
- Seems very good.
- Why would you want a slt menu ? A slt is always a son of a sla, no ?
- Some trailings space in update. What ide/text editor do you use ? Common ones have an option/plugin to highlight theses.
See a capture of my sublime text (pink rectangles shouldn't be here) : 
image

**Comment by korial29** [comment]
Ok i'll remove the SLT menu, it's available from the SLA object.
I use Netbeans, i think there is an option to check the trailing spaces, i'll see that

**Comment by orthagh** [comment]
The good way is to highlight only (and not auto strip), to avoid commits with large changes and avoid new features with spaces

**Comment by orthagh** [comment]
image

Why due date is on the left and other date on the right ?
Imo, they should be reversed.

**Comment by korial29** [comment]
I put SLT on SLA menu, and invert due_date / limit_takeintoaccount_date display

**Comment by orthagh** [comment]
An additionnal suggestion : 
```patch
diff --git a/inc/slt.class.php b/inc/slt.class.php
index fbc9712..9e5ffab 100644
--- a/inc/slt.class.php
+++ b/inc/slt.class.php
@@ -42,11 +42,15 @@ if (!defined('GLPI_ROOT')) {
 /**
  * SLT Class
 **/
-class SLT extends CommonDBTM {
+class SLT extends CommonDBChild {
 
    // From CommonDBTM
    var $dohistory                      = true;
 
+   // From CommonDBChild
+   static public $itemtype             = 'SLA';
+   static public $items_id             = 'slas_id';
+
    static $rightname                   = 'sla';
 
    static protected $forward_entity_to = array('SLALevel');
@@ -268,6 +272,11 @@ class SLT extends CommonDBTM {
 
       // SLT list
       $sltList = $slt->find("`slas_id` = '".$instID."'");
+      Session::initNavigateListItems('SLT',
+            //TRANS : %1$s is the itemtype name,
+            //       %2$s is the name of the item (used for headings of a list)
+                                     sprintf(__('%1$s = %2$s'), $sla::getTypeName(1),
+                                             $sla->getName()));
       echo "<div class='spaced'>";
       if (count($sltList)) {
          if ($canedit) {
```


To have that behaviour : 
image

**Comment by orthagh** [comment]
You percent in your tr (in ticket) overlap 100% : 
image

**Comment by orthagh** [comment]
I can do it later but some minor points : 
- if not sla/slt exist in db, we could hide the relative buttons in tickets
- "Assign a slt" is a long string and it's difficult to keep to clean interface with. here is some ideas
  * break line after date
  * Use an icon instead (with an alt text), it's my preference.
  * reduce sdtring to "SLT"

**Comment by korial29** [comment]
Ok i'm fixing it ! 
For the SLT icon, have you a preference ? i found this one : 
clock

**Comment by orthagh** [comment]
Ok for me, if you could resize it or 

you could use font-awesome icons (scalable), see this one : 
http://fortawesome.github.io/Font-Awesome/icon/clock-o/

For png export use fa2png.io

**Comment by orthagh** [comment]
After a discussion with @wawax about a news being written, we agreed on the EN terms : 
- Time to own (TTO)
- Time to resolve (TTR)

It's more concise and effective than : 
- limit take into account date
- Due date (ok, not this one)

If you agree, do you think you can change the gettext sentences ?

**Comment by korial29** [comment]
Ok for gettext, but i'll also have to change variables in order to have have a good understanding of the code

**Comment by orthagh** [comment]
icon is missing in your last commits :)

**Comment by korial29** [comment]
Ok i updated the locales and variables for 'Time to own' and 'Time to resolve'

**Comment by orthagh** [comment]
Merged manually in one commit (7bda94b) after : 
- master remerging
- and change on used keys (slt_tto -> slts_tto_id, slt_ttr -> slts_ttr_id)

**Comment by yllen** [comment]
Many errors to fix:
https://github.com/glpi-project/glpi/commit/d352e4a3678f13cd932fd431032404a7a49cdfb0
https://github.com/glpi-project/glpi/commit/586a8af3d46001eeed0b892b4d90e3fe043053c5
https://github.com/glpi-project/glpi/commit/e7b77f169aaf43a1be38a0337b5b45cdf87b9e2d
https://github.com/glpi-project/glpi/commit/298ee19323fa590a14a3a1cdba5f95684ac693da
https://github.com/glpi-project/glpi/commit/283691a6f0ead31cc7bb2a6776a05076289066a3

**Comment by orthagh** [comment]
Thank you @yllen for your review.

I think i need to rework some parts (if @tsmr or @korial29 don't show on this topic and fix by themself).
sla can now have multiple calendars_id so delay computation in itilobjects is insane.
I plan to redo 'time' fields in glpi_slas table

**Comment by orthagh** [comment]
Done.

Calendars_id now in glpi_slas table
Computation of time in tickets/itilobject reviewed.

**Comment by yllen** [comment]
@tsmr https://github.com/glpi-project/glpi/commit/77eff2647bcfc329a21cef65d648c6d5fe0fcd5e
you can't do that because commonitilobject is also used with change and problem

**Comment by yllen** [comment]
You still have the problem of slalevels_id still present in glpi_tickets after migration

**Comment by tsmr** [comment]
For slalevels_id present in glpi_tickets after migration

- tto & ttr share at this time this field but if we think about the process : 

If we add levels for tto slt, the actions of the rule engine for levels, modify the ticket so the takeintoaccount_delay_stat is calculated. So this is not logical.

I think we must hide levels for tto & let the slalevels_id only for ttr. And rename it for sltlevels_id in a second time ?

**Comment by yllen** [comment]
@Tsmr you don't understand my post.

If i look at 9.1 empty => you don't have slalevels_id
If i look at update 0.90.3to9.1 => you don't have the line to delete/rename this field.

You agree with me that slalevels_id is present in 0.90 empty
and if it's not present in 9.1 empty, you must delete it in update0903to9.1?

**Comment by orthagh** [comment]
@tsmr, @korial29 

I agree with @yllen, we have a problem  with missing (?) glpi_tickets.slalevels_id in 9.1-empty.sql

We still have a Ticket method who insert this field (https://github.com/glpi-project/glpi/blob/master/inc/ticket.class.php#L359).
I don't see any usage of this data anyway, if someone can check also.

So we have two options: 
- remove this field in update_0905_91.php and clean the field in Ticket::getDatasToAddSLT
- or if used, reinsert the field in 9.1-empty.sql

**Comment by orthagh** [comment]
I'm currently thinking the first option is the good one (one line removed in https://github.com/glpi-project/glpi/commit/7bda94b#diff-007edb12589cf3c8df3121cd7b19028aL350 but not in the else part)

**Comment by tsmr** [comment]
The field was deleted : https://github.com/glpi-project/glpi/commit/c225e945ba564637caaabac4bda6565b1a5008c9#diff-50fc0878bdbe5923aa299463f457a812L7052

so we can delete field : 
But i search & i found slalevels_id into other three files : 
entity.class.php
relation.constant.php
slt.class.php

So we must clean this files too

**Comment by orthagh** [comment]
You confirm the slalevels_id shouldn't be anymore in glpi_tickets ?

I can take care about clean but what about migration of this fields.
We already have previously level in a separate table, what's the point of this field ?

**Comment by amma35** [comment]
Yes, the slalevels_id shouldn't be anymore in glpi_tickets, It was the old operation.

**Comment by orthagh** [comment]
As previously said, we all agree on the fact that slalevels_id is not needed anymore in glpi_tickets.
The remaining question is "what about migration of the data stored in this field ?". We don't have any line who transfer the data to another table.

**Pull request closed without merging**
