### PR TITLE
Fix detection of renamed plugin

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

If a plugin is active and someone removed it to install a new version that uses another directory, check should not define its state as "To be cleaned", unless new directory is already present in DB.

### CODE REVIEW

**Comment by trasher** [comment]
There is a conflict, @cedric-anne could you please rebase this PR to solve it? Thanks :)

**Comment by cedric-anne** [comment]
> There is a conflict, @cedric-anne could you please rebase this PR to solve it? Thanks :)

Done.

**Comment by trasher** [comment]
thanks

**Comment by trasher** [comment]
ping @orthagh; I'd like you to look at this one

**Pull request merged**
