### PR TITLE
0.90/wip eventlog

### PR DESCRIPTION
**Pull request by orthagh**
see #27

### CODE REVIEW

**Comment by remicollet** [comment]
* date can be dropped (already added by logInFil)
* missing EOL (don't know why logInFile add one "before" text" and not "after"...)

**Comment by orthagh** [comment]
For event*s*.log, I think we must keep singular. Others files in this folder are singular.

i'll merge this pr afternoun.

**Comment by remicollet** [comment]
> Others files in this folder are singular.

Like php-errrors and sql-errors ?

**Comment by orthagh** [comment]
Yes, like these :)
Ok, i change the filename

**Pull request merged**
