### PR TITLE
Bug in search engine for Having - fixed #6225

### LINKED ISSUE #6225: Bug in search engine for HAVING
You can't have WHERE and HAVING in a same request.
So if you need to use HAVING you must change WHERE to only use HAVING.

### PR DESCRIPTION
**Pull request by yllen**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #6225 

Tested for many items in computer with OR as criteria (memory size or name).
Not tested for all items

### CODE REVIEW

**Comment by flegastelois** [comment]
Seems to be a duplication of this PR: https://github.com/glpi-project/glpi/pull/6204 which is already validated.

**Comment by yllen** [comment]
Before purpose a PR i always done a git pull from git branch 9.4/bugfixes and this issue was still present.

**Comment by trasher** [comment]
This duplicates https://github.com/glpi-project/glpi/pull/6204. Since test are KO and the other add a specific new test, we do not keep this one.

Please test and give feedback on https://github.com/glpi-project/glpi/pull/6204; thanks :)

**Comment by trasher** [comment]
Also, please avoid creating branches on main project, prefer using your fork.

**Pull request closed without merging**
