### PR TITLE
permits to disable display of initials in timeline

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

Again, following a meeting about glpi 10 with Nicolas, he says me one of its colleagues initials is a bad idea to display (in France context)  in the timeline.

So here is a config to disable display of initials in timeline.
When set to no, user avatar will display a generic picture (the same used for anonymous heldesk):

image

### CODE REVIEW

**Comment by cconard96** [comment]
Does the Kanban need changed too? For users the default badge shows initials.

**Comment by orthagh** [comment]
same indeed.
Could you create a pr (starting from this branch) and do the same in kanban

**Review by cconard96 — APPROVED** [review]

**Comment by cconard96** [comment]
Would it only need done for ITILObjects or global?

I'll start it tonight after my other job.

**Comment by orthagh** [comment]
Globally. The issue is some initials can be bad in some context, like SS for example, but in France PD is also bad (it means faggot).
So the initial feature should be deactivatable everywhere.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
