### PR TITLE
add dark mode

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

image

### CODE REVIEW

**Comment by orthagh** [comment]
wait before merging, some fixes to push (warning in central, priorities)

**Comment by cedric-anne** [comment]
Just a personnal remark: maybe the global font color should be a less lighter. Indeed, contrast between texts and background seems too weak for my eyes.

**Comment by orthagh** [comment]
last fixes done

image

**Comment by orthagh** [comment]
i don't know for lighter foreground, will ask to requester in the afternoon

**Comment by orthagh** [comment]
TODO:

* [ ] Racks
* [ ] volumes progress bars
* [ ] search progress bar (due date)

**Comment by cedric-anne** [comment]
Some elements may be improved.

Autocomplete:
image

Calendar in history filtering:
image

Trashbin view color is weird:
image

Assistance tab in profile rights:
image

Previous/next buttons on planning date range selection are not really visible unless on mouseover:
image

Note tab:
image

Priority column in Tickets tab of a change:
image

**Comment by orthagh** [comment]
no, i miss next/prev buttons in planning. Will do

**Pull request merged**
