### PR TITLE
Fix entry_i variable in timeline twig template

### PR DESCRIPTION
**Pull request by Aeto-J**
My issue was I can't modify attribute of a timeline object in hook because it didn't have any incidence in this twig template and I need to update property of this object before hook for having all correct datas

Add set attribute function (after research it is impossible to set or update an object attribute in twig template)

I have moved div declaration because if I modified something in my hook I want to update all variables

Update "entry_object" fields attribute for use it in an hook (in timeline twig template if "entry_i" (array fields of and timeline object) is modified before the hook we didn't have correct object) for example on this template I want to update data of timeline object field attribute and I didn't have "can_edit" in my array because "entry_object" in an new object created in twig template

After the hook, make an update of "entry_i" variable with data modified in the hook (for example in this twig template if I modified "can_edit" field in the array it does nothing because "entry_object" is not used in the template)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

Can you explain, from a user/functionnal point of view, what is your need? For instance, what is your plugin doing and which property do you want to change here?

**Comment by cedric-anne** [comment]
If you wan to modify an item of the timeline, you can do it by using the `show_in_timeline` hook.

**Comment by tomolimo** [comment]
> Hi,
> 
> Can you explain, from a user/functionnal point of view, what is your need? For instance, what is your plugin doing and which property do you want to change here?

Hello @cedric-anne,
We want to set the can_edit property to false, and we also want to prevent the promote.
Thank you,
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
@tomolimo 

Please try with #14510 with the `show_in_timeline` hook.

**Comment by Aeto-J** [comment]
Hello @cedric-anne, @tomolimo,
I did tests for show_in_timeline and all work
Thank you,
Regards,
Aeto-J

**Comment by cedric-anne** [comment]
> Hello @cedric-anne, @tomolimo, I did tests for show_in_timeline and all work Thank you, Regards, Aeto-J

OK, so I close this PR. The other one is less subject to side effects.

**Pull request closed without merging**
