### PR TITLE
Rewrite planning with fullcalendar.io

### PR DESCRIPTION
**Pull request by orthagh**
This works is almost finished and fully functional.
Before merge, i would like to have some external tests

@tsmr, @korial29 ?

### CODE REVIEW

**Comment by orthagh** [comment]
maybe @tomolimo ?

**Comment by orthagh** [comment]
a preview : 

image

**Comment by tomolimo** [comment]
I'm going to try :)

**Comment by tomolimo** [comment]
I've made some tests:

1. This is really nice.
1. Dialog box to create new item is placed top left on my screen: is it by design?
1. I believe that auto creation of items is not a good idea (right click or else to create new item)
1. Refresh should not be global when adding an item nor when using filter.
1. Refresh of items can be automatic (using ajax calls to get new values).
1. Deleting items should be possible (right click) (business rules to be defined!).
1. Should be possible to select a free range of days to view.
1. Edition should be like creation (not to be obliged to go to old form, or open it in another browser tab)
1. Date format doesn't respect user's settings.

More to come:),
Tomolimo

**Comment by tomolimo** [comment]
1. Tooltips are too big:
image

**Comment by tomolimo** [comment]
my browser is IE10

**Comment by tomolimo** [comment]
1. '+' Icon is disabled ('+' could be used to add an item to by default at current date time)
1. 'magnifier' icon leads to nowhere
image

**Comment by tomolimo** [comment]
1. Events with status information status should not be taken into account for event overlaps. Only 'Todo' and 'done' as you may set an informational event for the whole day/week/month and get a lot of warnings.
image

**Comment by tomolimo** [comment]
1. 'Issue tasks': this is confusing as these are really 'Problem tasks' (I saw this also in problem task form where they are named 'issue tasks').
image

**Comment by orthagh** [comment]
I check previous later, but for this one, you should go on transifex.
In my memory, this translation have changed recently

**Comment by tomolimo** [comment]
1. A click when pointer is with double arrows (means extension) will lead to open the reminder form if mouse is released without any move...
image

**Comment by tomolimo** [comment]
ok for the translation we'll see that later

**Comment by tomolimo** [comment]
1. With a click on a ticket task, the URL used behind is a "redirect" which leads to a lot of redirection (from index.php to ticket.php via central.php): not very usable, especially when we want to go 'back'...

**Comment by tomolimo** [comment]
1. Sometimes the tooltip of an item is showed briefly) at top left of browser page.
1. A kind of blinking occurs when mouse is over a tooltip like shown below (even without moving the mouse):
image

**Comment by tomolimo** [comment]
1. When several users are selected, as soon as a ticket form is open (due to click ticket task), when you go back to the planning via menu, or via browser history, then you lose the selected users and it goes back to default profile. I believe this is due to redirection instead of using a direct link. This behavior doesn't occur when you click on a reminder instead of a ticket task.

**Comment by orthagh** [comment]
> This is really nice.

Thank you

> Dialog box to create new item is placed top left on my screen: is it by design?

No, correction incoming

> I believe that auto creation of items is not a good idea (right click or else to create new item)

On this point, i believe @tsmr and @korial29 would add their own events (from activity plugin)
And would like to use these feature to select a range and add an event.
I don't like right click in web context, it's not the common usage.

> Refresh should not be global when adding an item nor when using filter.

I agree with that, but i think the load time of events is insignificant versus a big piece of javascript code.

> Refresh of items can be automatic (using ajax calls to get new values).

Good idea, i note this for later tests.

> Deleting items should be possible (right click) (business rules to be defined!).

As explained, no right click, please :)
I don't understand rules part.

> Should be possible to select a free range of days to view.

Maybe i miss such feature, but i think fullcalendar.io doesn't provide any way to do this (easily).
Comme calendar implemantion i kown (google, bluemind, zimbra) doesn't provide either.

> Edition should be like creation (not to be obliged to go to old form, or open it in another browser tab)

Should be difficult to do, but i'll do some tests.

> Date format doesn't respect user's settings.

Fix incoming

> '+' Icon is disabled ('+' could be used to add an item to by default at current date time)
> 'magnifier' icon leads to nowhere 

I disabled all icons (push incoming).
Addition of events needs more refining but i want direct range selection.

> Events with status information status should not be taken into account for event overlaps. Only 'Todo' and 'done' as you may set an informational event for the whole day/week/month and get a lot of warnings. 

Good point, i'll check this.

> A click when pointer is with double arrows (means extension) will lead to open the reminder form if mouse is released without any move... 

You're picky :)
If we do, inline edition of events, the problem will disapear.
Otherwise, i don't know

> With a click on a ticket task, the URL used behind is a "redirect" which leads to a lot of redirection (from index.php to ticket.php via central.php): not very usable, especially when we want to go 'back'...

You're right. I see the point.
Planning can be exported and viewed on external application.
But with the redirect mode of 0.85, 'redirect' param should be useless

> Sometimes the tooltip of an item is showed briefly) at top left of browser page.
> A kind of blinking occurs when mouse is over a tooltip like shown below (even without moving the mouse):

I didn't see that. Could you try to find a way to isolate it ?


> When several users are selected, as soon as a ticket form is open (due to click ticket task), when you go back to the planning via menu, or via browser history, then you lose the selected users and it goes back to default profile. I believe this is due to redirection instead of using a direct link. This behavior doesn't occur when you click on a reminder instead of a ticket task.

We'll see with the redirect removal

**Comment by tomolimo** [comment]
1. The very interesting feature is to have the possibility to move an item: this is ok; but not when trying to move an item from the all-day/week header to a specific day. In this case you get a 'phantom' item behind the mouse and when you click to get ride of it, guess? you go to the ticket or reminder form.

**Comment by tomolimo** [comment]
>> I believe that auto creation of items is not a good idea (right click or else to create new item)

> On this point, i believe @tsmr and @korial29 would add their own events (from activity plugin)
And would like to use these feature to select a range and add an event.
I don't like right click in web context, it's not the common usage.

Right-click was only a suggestion, but I strongly disagree with auto creation of item by a simple click.
I propose the following (to be adjusted of course):
A click in a cell (or a selection of cells) will only select it/them (already the case) and another click in the selection (or a click on a special button (the '+'?)) will create the item and open the dialog box.

>> Business rules

Forget it!

>> Sometimes the tooltip of an item is showed briefly) at top left of browser page.
A kind of blinking occurs when mouse is over a tooltip like shown below (even without moving the mouse):
> I didn't see that. Could you try to find a way to isolate it ?

Very easy: just place the mouse over a tooltip of an item (same behavior with IE10 and Chrome, but with FF: it's a bit different: blinks only one time).

**Comment by tomolimo** [comment]
See video in zip for blinking on Chrome

ezgif com-video-to-gif

**Comment by tomolimo** [comment]
With FireFox tooltips will blink only when mouse is moving over the tooltip
ffblink

**Comment by tsmr** [comment]
PHP-errors on Ical export - PHP 7
```
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; vcalendar has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; calendarComponent has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; vevent has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; vtodo has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; vjournal has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; vfreebusy has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; valarm has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Deprecated function(8192): Methods with the same name as their class will not be constructors in a future version of PHP; vtimezone has a deprecated constructor
  Backtrace :
  inc\planning.class.php:1737                        
  inc\planning.class.php:1737                        include_once()
  front\planning.php:121                             Planning::generateIcal()
2016-02-16 13:00:47 [2@P365]
  *** PHP Warning(2): trim() expects parameter 1 to be string, array given
  Backtrace :
  :                                                  
  lib\icalcreator\iCalcreator.class.php:8483         trim()
  lib\icalcreator\iCalcreator.class.php:2830         iCalUtilityFunctions::_setDate()
  lib\icalcreator\iCalcreator.class.php:5734         calendarComponent->setDtstart()
  lib\icalcreator\iCalcreator.class.php:7417         calendarComponent->setProperty()
  inc\planning.class.php:1754                        iCalUtilityFunctions::createTimezone()
  front\planning.php:121                             Planning::generateIcal()
```

**Comment by tsmr** [comment]
First of all : Good Job ! :+1: 
If i compare with activity plugin, 
I think it missing : 

- Add hook for add / delete plugins events : like add Notes on planning
- Add only event from plugin with special duration (example : activity with 2 hours minimum duration)
- Block events on Week End
- Filter display of events : example for aggregate several tickets (5 tickets tasks with a duration of 5 minutes) like a time repartition
- other @korial29 ?

**Comment by orthagh** [comment]
Here is a summary of last commits : 
- try to avoid blink of qtip
- edit event with ajax (so we have the former delete button also)
- no more php7 warnings on ical export (need to be tested, i upgraded the lib)
- no more redirect in url

**Comment by tsmr** [comment]
You have another problem : 
Create a Note into planning
Try to drag it into All Day zone : the calendar dont like it

**Comment by tomolimo** [comment]
yes, see this: https://github.com/glpi-project/glpi/pull/448#issuecomment-182891761

**Comment by tomolimo** [comment]
video sample of the drag/drop into 'all day event' 
2016-02-16 at 15-00-04

**Comment by orthagh** [comment]
It should be better

**Comment by orthagh** [comment]
@tsmr, @korial29 
I cannot figure how you disable (grey out) weekend days in activity plugin, any hints ?

**Comment by tomolimo** [comment]
Why do yo want to disable activities during week-ends?

**Comment by orthagh** [comment]
no i want to disable the possibility to add events on fullcalendar planning when we are out of entity day of work

**Comment by tomolimo** [comment]
@orthagh: Ok I agree with you about so called 'opening calendar': events must be set depending on the entity calendar.

**Comment by tsmr** [comment]
On add activity : 
```
if (myview != 'month' && myday != 'Sun' && myday != 'Sat') {
````

For display
on fullcalendar.js or into display script there is an option weekends: false

**Comment by tomolimo** [comment]
I'm testing the latest source, and I can see that many of the bugs have been fixed, bravo!
Just one more thing is: the tooltips appear a little bit too quick, could you increase the delay before appearance?
And only show the tooltip if the browser window is not selected

**Comment by tomolimo** [comment]
Another problem, not directly linked to new planning, but linked to the way ticket tasks are shown in the planning (same problem with old planning and in GLPI home page):
the Ticket tasks are missing information of the tasks: only the ticket info is present, so that nobody knows what should be done with the ticket tasks.

Here is a view of the new planning with such problem:
image

On the left this is a Reminder 'task': you can see the content of the todo task.
On the right this is a ticket task: you can see the content of the task, as it shows the content of the ticket.

Could it be possible to change the view so that it shows the content of the ticket task?

**Comment by orthagh** [comment]
very good point, i always had bad comprehension to this behavior.
I'll do an update on this.

For tootltip, yes i can increase duration before show.
I don't understand second part of your message.

**Comment by tomolimo** [comment]
> I don't understand second part of your message.

which part?

**Comment by orthagh** [comment]
> And only show the tooltip if the browser window is selected

**Comment by tomolimo** [comment]
Another thing:
When doing drag/drop of a reminder: could you prevent tooltips? as they disappear/disappear and so on at each new move.
Also when increasing or decreasing the size of an item, tooltips are appearing and disappearing...

> And only show the tooltip if the browser window is selected

if the browser window is in background (not active), then if the mouse passes over an item, then tooltips are shown. It can lead to a lot of tooltips shown when you don't need them.

**Comment by tomolimo** [comment]
> Another thing:
When doing drag/drop of a reminder: could you prevent tooltips? as they disappear/disappear and so on at each new move.
Also when increasing or decreasing the size of an item, tooltips are appearing and disappearing...

Another thing is that sometimes after a resize, the edit box appears

see following video that shows both problems:

2016-02-17 at 14-33-43

**Comment by orthagh** [comment]
I just made a general method to disable qtip.
I detect mousedown event and disable the possibility to trigger tip until mouseupevent.

Also i hide existing tip.

For window focus, i just tested some stuff but, rendreing of tip is done on page construction (or event changes). Without changes triggering (drag, resize), tip are not changed.

for information the method to detect focus is with a global variable : 
```javascript
var window_focus = true;

window.onblur = function() { window_focus = true; }
window.onfocus = function() { window_focus = false; }
```

**Comment by orthagh** [comment]
forget me, I just found a way to do this. See last commit

**Comment by tomolimo** [comment]
For the browser window: it's ok
For the problem of resize + edit: still here:
2016-02-17 at 16-25-35

**Comment by orthagh** [comment]
it should be better/.
i had a hard time to replicate the behavior :)

**Comment by orthagh** [comment]
And so, here is the real content for itil task

**Comment by tomolimo** [comment]
Don't worry, I understand!

**Comment by tomolimo** [comment]
Thank you for the content task: it's OK
But still not OK for the resize + edit...

**Comment by tomolimo** [comment]
In order to help you, here is another video:

2016-02-17 at 16-58-46

This is also existing with FF and with Chrome.

**Comment by orthagh** [comment]
See : https://github.com/fullcalendar/fullcalendar/issues/2934

**Comment by tomolimo** [comment]
Seems like a known problem :(

**Comment by orthagh** [comment]
Should be much better

**Comment by tomolimo** [comment]
That's perfect :)!
thank you,

Could you also increase the size of the selectable area for the resize of the 'all-day' events?
see below:
image

Arrow in this case should be like:
image

**Comment by orthagh** [comment]
There

**Comment by tomolimo** [comment]
Super! thank you

Could you limit the height of the 'all-day' events?
When the content text is long then the item can be very high, see:
image
and if there are several 'all-day' events then you may have a very reduced view for the rest:
image


Could it be possible to limit the height of the content to 0 or maximum 1 line? In Outlook calendar it is limited to the item title only (there is no view of the content), see:
image

**Comment by orthagh** [comment]
good point and there is the enhancement.

**Comment by tomolimo** [comment]
Thank you

Did you check also the mix of 'info' and 'todo' to prevent alert of planning overlaps?

**Comment by orthagh** [comment]
not yet, but soon.

@tsmr, @korial29 
I just enhanced the way to add events from planning selection.
You have now a new global variable $CFG_GLPI['planning_add_types']  (in define.php), where you could push your plugins itemtypes.

If this var contains only one value (by default Reminder), it show directly showForm of this itemtype,.
Otherwise, a dropdown will show the several values and getTypename of this var.
After selection of an itemtype, its showform method is called with 'begin' and 'end' dates params.

Let me know if it sufficient or not.

**Comment by orthagh** [comment]
So, here is some changes : 
- reduce already planned to todo/done reminders
- submit edit/delete event with ajax
- and fix positioning of some dialogs

I think we're close to merge

**Comment by tomolimo** [comment]
I'll test that tomorrow

**Comment by tsmr** [comment]
And for

- Add only event from plugin with special duration (example : activity with 2 hours minimum duration)
- Filter display of events : example for aggregate several tickets (5 tickets tasks with a duration of 5 minutes) like a time repartition

?

**Comment by tomolimo** [comment]
1. If you try to drag an item from lower part of planning

image
to 'all-day' events then during the drag, the event will show the complete item when over the header ('all-day') events:
image
It must be identical to the view shown when dropped in the 'all-day' area:
image

**Comment by tomolimo** [comment]
2. at end of drag/drop of an item the tooltip is shown then hidden and again shown, see small video:
2016-02-19 at 10-15-02

**Comment by tomolimo** [comment]
Instead of one click to create a new event, could it be possible to sue double-click?
In order to prevent unwanted event creation?

**Comment by tomolimo** [comment]
I did the test regarding the schedule overlaps: and it's ok for me, only 'todo' events are showing overlap alerts.
I made the test with all task types (Ticket, Change, Issue, Reminder, Project), and it seems OK, but Project task can be moved nor resized, and there is no alert when another todo task overlaps project task. Is it 'by design'?

**Comment by tomolimo** [comment]
Could it be possible to hide/show the left part of the planning (I mean "event types" and "Plannings") in order to free some space when using the dynamic planning with small screens?
You may add a small icon to show/hide the div 'planning_filter'.

**Comment by tomolimo** [comment]
Hello,
There is a problem about overlapping schedule:
if you drop an 'information' item over a 'todo' item then you get an alert about overlapping schedule. And not for the reverse action: if you drop a 'todo' item over an 'information' there is no alert (as requested by me).
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
There is a problem when changing the schedule of an item which is in the 'all-day' header part, after edit (for example change the start date), it will be shown in the lower part of the planning, see video:
2016-02-23 at 09-25-32

**Comment by tomolimo** [comment]
Another problem is that once the showPlan() function has been called then it can't be called any longer. See:

2016-02-23 at 09-37-19

The workaround is to refresh the page (F5)

**Comment by tomolimo** [comment]
If an item is scheduled outside of the working hours, then it doesn't appear!
Dynamic planning should show the complete hours from 00:00:00 to 23:59:59, and in order to limit the view should have a scroll bar on the right if needed to view items outside working hours.
like this:
image

And the working hours should be the one in the current entity (depending on the active calendar for the current entity). so that it should be possible to plan items for users in other entities and other working hours.

**Comment by orthagh** [comment]
Some fixes for this comments :

* https://github.com/glpi-project/glpi/pull/448#issuecomment-186124629
* https://github.com/glpi-project/glpi/pull/448#issuecomment-186133993
* https://github.com/glpi-project/glpi/pull/448#issuecomment-187599752
* https://github.com/glpi-project/glpi/pull/448#issuecomment-187602163

**Comment by tomolimo** [comment]
Hello,
OK for me, I made tests with the fixes.

But what about these?
https://github.com/glpi-project/glpi/pull/448#issuecomment-186125859
https://github.com/glpi-project/glpi/pull/448#issuecomment-186138232
https://github.com/glpi-project/glpi/pull/448#issuecomment-187599023
https://github.com/glpi-project/glpi/pull/448#issuecomment-187637657 (this one can be discussed)

**Comment by orthagh** [comment]
Another fixes incoming for toggle left filters and i must check overlap messages.

For clic behavior, I really like the actual implementation. 
I wanted the planning rework for this feature.
I don't understand the possibility of unwanted event creation. If a "missclik" appears, you can close the form.
I checked outlook  it's indeed a double click for desktop version, but in web version (live.com/office365), it provide single clic to add event like another calendar services.
I think double click is bad in web context (i agreed on another issue on edit timeline items, not done actually but i plan to review this).

For displayed hours in week/day mode, i set from general config.
You can globally disable or enable hours for planning configuration > General.
Its a behavior for former planning but i keep it for new one (I personally don't care, another people maybe).
I think we can't use entity calendar for displayed hours, it will be confusing.

**Comment by orthagh** [comment]
I think i can't change the behavior of overlap messages in the case you mention : drop todo event on information event

The current method check existing events on begin/end period provided by the drop.
I can't think to a solution who can check current dropped event state

**Comment by orthagh** [comment]
@tsmr 
> And for
> 
> Add only event from plugin with special duration (example : activity with 2 hours minimum duration)
> Filter display of events : example for aggregate several tickets (5 tickets tasks with a duration of 5 minutes) like a time repartition

All of theses features could be managed by itemtype::populatePlanning method, no ?

**Comment by tsmr** [comment]
Hi orthagh

- For Add only event from plugin with special duration (example : activity with 2 hours minimum duration) : OK i can use populateplanning

- For Filter display of events : example for aggregate several tickets (5 tickets tasks with a duration of 5 minutes) like a time repartition

I must add into my setup.php 

unset($CFG_GLPI['planning_types'][3]); (for TicketTask);
unset($_SESSION['glpi_plannings']['filters']['TicketTask']);

And use my own class - This is not very clean, no ?

**Comment by orthagh** [comment]
I don't think it bad for the CFG_GLPI, in fact, you redefine a new way to populate.

For session, it's not good, i agree.
I'll check soon

**Comment by yllen** [comment]
If a group is deleted permanently, it stay in planning with name N/A.
Question: how delete selected user or group on the left (to reduce the list)?

**Comment by orthagh** [comment]
With contextual dropdown actually.
Don't you have it ?

image

**Comment by yllen** [comment]
Sorry i haven't see it.

**Pull request merged**
