### PR TITLE
lower camel case for Auth::Login

### PR DESCRIPTION
**Pull request by btry**
coding standard

### CODE REVIEW

**Comment by trasher** [comment]
This should not reach 9.1 branch; but only master.

**Comment by btry** [comment]
I think this can reach 9.1 because in php function names is case insensitive. 

However, I think this PR has no functional impact then no matter the branch. OK for master.

**Comment by AnaelMobilia** [comment]
"in php function names is case insensitive."
Confirmed on http://php.net/manual/en/functions.user-defined.php
(I learned something today... :-))

**Comment by trasher** [comment]
@btry this is because this is case insensitive this should not reach a bugfix branch: this is not a bug :)

This is coding standards; and coding standard work has been done on master only ;)

**Comment by btry** [comment]
Ok, I'll note coding standard violation is not a bug. Maybe an bug in the developer's firmware ;) 

Thanks for the merge

**Pull request merged**
