### PR TITLE
Fix(Core): fix TWIG template error

### PR DESCRIPTION
**Pull request by stonebuzz**
Since https://github.com/glpi-project/glpi/pull/11968

An error occurs when trying to display an asset (assigned to the root entity and recursively) from a sub-entity

image

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

**Comment by stonebuzz** [comment]
Mentionned PR has introduced several problems

 The function indicates an ```int``` for the ```$right``` argument

but there is a switch on the ```recursive``` value ```string```

```php
    public function (from ```CommonDBTM``` can($ID, int $right, array &$input = null): bool
    {
        if (Session::isInventory()) {
            return true;
        }

       // Clean ID :
        $ID = Toolbox::cleanInteger($ID);

       // Create process
        if ($this->isNewID($ID)) {
            if (!isset($this->fields['id'])) {
                // Only once
                $this->getEmpty();
            }

            if (is_array($input)) {
                $input = $this->addNeededInfoToInput($input);
               // Copy input field to allow getEntityID() to work
               // from entites_id field or from parent item ref
                foreach ($input as $key => $val) {
                    if (isset($this->fields[$key])) {
                        $this->fields[$key] = $val;
                    }
                }
               // Store to be available for others functions
                $this->input = $input;
            }

            if (
                $this->isPrivate()
                && ($this->fields['users_id'] == Session::getLoginUserID())
            ) {
                return true;
            }
            return (static::canCreate() && $this->canCreateItem());
        }
       // else : Get item if not already loaded
        if (!isset($this->fields['id']) || ($this->fields['id'] != $ID)) {
           // Item not found : no right
            if (!$this->getFromDB($ID)) {
                return false;
            }
        }

       /* Hook to restrict user right on current item @since 9.2 */
        $this->right = $right;
        Plugin::doHook(Hooks::ITEM_CAN, $this);
        if ($this->right !== $right) {
            return false;
        }
        $this->right = null;

        switch ($right) {
            case READ:
               // Personnal item
                if (
                    $this->isPrivate()
                    && ($this->fields['users_id'] === Session::getLoginUserID())
                ) {
                    return true;
                }
                return (static::canView() && $this->canViewItem());

            case UPDATE:
               // Personnal item
                if (
                    $this->isPrivate()
                    && ($this->fields['users_id'] === Session::getLoginUserID())
                ) {
                    return true;
                }
                return (static::canUpdate() && $this->canUpdateItem());

            case DELETE:
               // Personnal item
                if (
                    $this->isPrivate()
                    && ($this->fields['users_id'] === Session::getLoginUserID())
                ) {
                    return true;
                }
                return (static::canDelete() && $this->canDeleteItem());

            case PURGE:
               // Personnal item
                if (
                    $this->isPrivate()
                    && ($this->fields['users_id'] === Session::getLoginUserID())
                ) {
                    return true;
                }
                return (static::canPurge() && $this->canPurgeItem());

            case CREATE:
               // Personnal item
                if (
                    $this->isPrivate()
                    && ($this->fields['users_id'] === Session::getLoginUserID())
                ) {
                    return true;
                }
                return (static::canCreate() && $this->canCreateItem());

            case 'recursive':
                if (
                    $this->isEntityAssign()
                    && $this->maybeRecursive()
                ) {
                    if (
                        static::canCreate()
                        && Session::haveAccessToEntity($this->getEntityID())
                    ) {
                       // Can make recursive if recursive access to entity
                        return Session::haveRecursiveAccessToEntity($this->getEntityID());
                    }
                }
                break;
        }
        return false;
    }
```

in addition, it is now possible to update an asset (assigned to the root entity) from a sub-entity which was not the case before

GLPI 10  :  

image


GLPI 11 : 
image

**Comment by cconard96** [comment]
As much as I've probably should have noticed the ridiculous use of a string as a right value (which isn't standard anywhere else afaik in GLPI in over a decade), this elseif and switch case statement were already present before my PR. The CommonDBTM method wasn't touched at all and the elseif with the 'recursive' parameter was moved from another template.

**Comment by cconard96** [comment]
If the behavior change is intentional, it needs put in the changelog.
Are there any other cases where 'recursive' is passed around as a right value?

**Comment by stonebuzz** [comment]
Sorry @cconard96 , you're right, the bit of code was already there.

in theory it's the only call, I've updated it to use a constant

**Comment by cconard96** [comment]
:/ I'm not sure it should be treated as a normal right at all. I think it would be the only 'virtual' right we have.
Moving to a separate method `canRecurs` to match `canUnrecurs` may be better (if I understand its purpose).

**Review by cconard96 — APPROVED** [review]

**Pull request merged**
