### PR TITLE
fix typo GLPi => GLPI

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by tomolimo** [comment]
Hello Remi
I believed it was GLPi and not GLPI? 
Regards 
Tomolimo

**Comment by remicollet** [comment]
It have never be GLPi, GLPI since the beginning, see http://glpi-project.org/
Don't know why (recently) some start using GLPi (which breaks the acronym).

**Comment by tomolimo** [comment]
Seems like there is a misunderstanding somewhere... 
https://github.com/glpi-project/glpi
For me there's no problem for one or the other, but I think that it has to be everywhere the same.

**Comment by AnaelMobilia** [comment]
Maybe we need to update the logo ("Glpi") too ?
image

**Comment by trasher** [comment]
Where did you find this one?

**Comment by AnaelMobilia** [comment]
@trasher On the top left of each page on the default template ? ;-)
It is on pics/fd_logo.png

**Comment by trasher** [comment]
Ohhh... Thank you, seems like I'm a bit tired :D

**Pull request merged**
