### PR TITLE
feature: add ajax to filter parent dynamically

### PR DESCRIPTION
**Pull request by delcroip**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

# need

This solve a issue pre-filter dynamically a dropdown, apparently I am not the only one that needs this 
https://forum.glpi-project.org/viewtopic.php?id=32662

I needed this because of an user request, they have a list of 6000+ items with similar names, being able to prefilter the drop down make it much more easier for them.

# working example

In that example, split a dropdown in 2 search boxes, one for the level 1 and one that get filtered on level 1

I needed to create rand and parent_field_id  here so I could pass it to the "real" drop down

```
      $rand =  mt_rand();
      $parent_name = 'plugin_openmedis_medicaldevicecategories_parent_id';
      $parent_field_id = Html::cleanId("dropdown_".$parent_name.$rand);
      PluginOpenmedisMedicalDeviceCategory::dropdown(['value' => $this->category ,
      'name' => $parent_name,
      'displaywith' => ['code','label'],
      'condition' => [ 'level' => 1],
      'rand' => $rand]);
      echo '<br>';
      PluginOpenmedisMedicalDeviceCategory::dropdown(['value' => $this->fields["plugin_openmedis_medicaldevicecategories_id"],
      'permit_select_parent' => true,
      'displaywith' => ['code','label'],
      'parentfieldid'   =>  $parent_field_id ]);
      echo "</td>";
```

# limitations

this doesn't solve all issue, because it works only with the parent

ideally it should be possible to use another form fields to feed a custom condition

next step: I  should add a similar approach but instead of working only for the parent, it should use call callback saved in SESSION with, as parameter, the "filter value" catched by the javascript. this callback would return a QueryExpression that would be added to the $where

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

It seems to be a really specific usage, not sure it is something that would be reused (ping @orthagh @trasher ).

In GLPI, we often filter dropdown using value selected in another dropdown, using the `Ajax::updateItemOnSelectEvent()` method, and I am pretty sure you could use it in your case.
You can get a simple example in `Notification::showForm()`.

Regards

**Comment by orthagh** [comment]
as discussed together with @cedric-anne, i agree with the changes, in many cases the code will be much more lisible than using `Ajax::updateItemOnSelectEvent()`

I just need to remember it

**Comment by cedric-anne** [comment]
In this case, this PR should target master, and tests made on `Dropdown::getDropdownValue()` should be updated to test this new feature.

**Comment by cedric-anne** [comment]
Hi @delcroip 

Sorry for the validation delay. I get most of your changes in #10343 and adapt them a little:
 - I renamed `parentfieldid` param to `parent_id_field` and `parentid` param to `parent_id`.
 - I replaced default `''` `parent_id_field` value by `null`,
 - I updated tests to check more cases.

**Pull request closed without merging**
