### PR TITLE
Apply PHPCS rule Squiz.ControlStructures.ControlSignature (White space after IF, ELSE, FOREACH, SWITCH keyword)

### PR DESCRIPTION
**Pull request by AnaelMobilia**
```
  <!-- White space after IF, ELSE, FOREACH, SWITCH keyword -->
  <rule ref="Squiz.ControlStructures.ControlSignature" />
```
+ Fix current code for this rule

Part of #1209

### CODE REVIEW

**Comment by AnaelMobilia** [comment]
Please note that the error on the CI checks aren't linked to this PR, but by the definition of the actual date on the tool (inc/define.php) ;-)
```
1) HtmlTest::testGetCopyrightMessage

Invalid copyright date!

Failed asserting that '<a href="http://glpi-project.org/" title="Powered By Teclib" class="copyright">GLPI 9.2 Copyright (C) 2015-2016 Teclib' - Copyright (C) 2003-2015 INDEPNET Development Team</a>' contains "2017".
```

**Comment by orthagh** [comment]
oh sorry for this one.
I merged #1485 first. I think i shouldn't

**Comment by orthagh** [comment]
In fact, all this PSR pr will conflict after one merge.
We'll go one by one if you are ok with that

**Comment by AnaelMobilia** [comment]
@orthagh no problems, all PR should anyway have problems as I edited the tools/phpcs-rules.xml on each...

I will resolved conflicts the one after the others, no problems for that ;-)

**Comment by orthagh** [comment]
@AnaelMobilia 
Need your help for this last one to resolve the conflict

**Comment by trasher** [comment]
I've fixed ;)

**Pull request merged**
