### PR TITLE
[API] /getMyEntities output proposal

### PR DESCRIPTION
**Pull request by humboldtux**
Following recent API responses changes, to be consistent, i would like to propose to change output of /getMyEntities to:

```json
{
	"myentities": [{
		"id": 1,
		"name": "Root entity > Sub1"
	}]
}
```

- "myentities" as top entry
- don't keep keys for entities

### CODE REVIEW

**Comment by trasher** [comment]
Sounds like it would be better to have consistence between API calls and returns, yes. @orthagh what do you think?

@humboldtux, if @orthagh  is OK with that, could you please check in the whole API there are no other changes for consistency? So we can spend time on all this once only ;)

**Comment by orthagh** [comment]
For specific endpoint like this one or the two previous (getMyProfiles, etc), i agree we can change.
For search and getItems, i would prefer to stick with the current version.

**Comment by orthagh** [comment]
Also, don't forget dedicated tests when you do this kind of changes

**Comment by humboldtux** [comment]
@trasher i will have a look at other endpoints.
@orthagh sorry for the tests, i will have a look asap.

**Comment by trasher** [comment]
Hello,

What's is the status of this PR? The 9.1 version will reach a stable state in a near future; all API changes after that will be handled with many precautions... It would be far better to include this before the release.

I can help on the tests if you need; but less on checking endpoints since I do not use the API right now myself.

**Comment by humboldtux** [comment]
@trasher I would like some help for the tests, please, i couldn't manage to run the tests suit.

**Comment by trasher** [comment]
@humboldtux ok; I'll work on the tests ;)

**Comment by trasher** [comment]
I take a quick look on all of these, seems like we get two more calls to adapt: `getActiveProfile` and `getFullSession`.
All other endpoints should stay as it.

**Comment by trasher** [comment]
All changes have been made. We can merge if this is OK for everyone.

**Pull request merged**
