### PR TITLE
Fix 1171

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by orthagh** [comment]
We still have the checkboxes in document tab, no ?

**Comment by trasher** [comment]
@orthagh massive actions checkboxes are displayed if the profile can update document; so, yes, they're still displayed if the user has the rights acls.

What I did is to add this check on the timeline view to display or not the delete icon, and add the check also in the business part to make sure anyone without required acls can delete it.

**Comment by orthagh** [comment]
okay

**Comment by trasher** [comment]
Thanks!

**Pull request merged**
