### PR TITLE
To fix issue #321

### PR DESCRIPTION
**Pull request by tomolimo**
This fixes the problem of attached emails into emails when no filename is given in the MIME part of the mutli part boby

### CODE REVIEW

**Comment by tomolimo** [comment]
Sorry for the Merge remote-tracking branch: I still don't master git-hub :(

**Comment by orthagh** [comment]
This PR seems interesting but add redundancy in mailcollector.class.php

Is it possible to do some factorisation on the imap_fetchbody  part ? Wit a dedicated function.

**Comment by tomolimo** [comment]
To be noted the upload will be ok if document type EML is authorized in the document type list, like following:
image

**Comment by tomolimo** [comment]
up!

**Comment by orthagh** [comment]
Almost for me.

Could you prefers this kind of notation : 
```php
$var = "string'
if (...) {
   $var = "anotherstring";
}
```

Instead of nested "else"

**Comment by tomolimo** [comment]
I don't see where there is a nested else...

**Comment by orthagh** [comment]
https://github.com/glpi-project/glpi/pull/324/files#diff-1d6b9cb0616c211290878ee8ba7177fcR1409

**Comment by tomolimo** [comment]
thank you

**Pull request merged**
