### PR TITLE
Fix pre and post form hooks in simplifed interface; fixes #1691

### LINKED ISSUE #1691: Strange behavior for $options in pre/post_item_form hooks in helpdesk form
Hello,
We can see this in Ticket::showFormHelpdesk():

```
if (count($delegating) || $CFG_GLPI['use_check_pref']) {
         echo "<div class='center'><table class='tab_cadre_fixe'>";

         Plugin::doHook("pre_item_form", ['item' => $this, 'options' => &$opt]);
      }
```

First question: why is the hook inside the test of delegating or check_pref? Should it be outside of the test?

second question:

`      Plugin::doHook("post_item_form", ['item' => $this, 'options' => &$options]);`

why the $opt (from the 'pre_item_form') is not passed to the 'post_item_form', but another array which has nothing to do with the first one?

regards,
Tomolimo

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by trasher** [comment]
There are no options in the method; there is nothing to send to the hook. I do not see what you want me to do here.

Those calls are just workarounds, because generics methods are not used (this is not going to be changed in the bugfixes branch).

**Comment by trasher** [comment]
Or maybe do you want to create another array that would be used only in the hooks?

**Comment by tomolimo** [comment]
I want to be able to pass values between pre hook and post hook, so to achieve that I need a real array in the pre, and this real variable to be passed to the post.

**Comment by trasher** [comment]
OK, I did this for the two originally modified; and I've make change on some others to be consistent :)

Thanks for the pointer.

**Comment by tomolimo** [comment]
Beware that, it can be useful to pass to the pre hook some data about the context : type of object that is to be edited, and if editing or creating, also when editing to pass the object itself is a good idea. Check what I did for the pre_show_item and pre_sho_tab. 
Regards 
Tomolimo

**Comment by trasher** [comment]
You are asking for changes that are out of the scope of this PR (and probably out of the scope of the bugfixes branch as well).
Would you please open another descriptive ticket for enhancements you'd like to get for this hook?

As for the options array, being able to pass data from pre hook to post hook does not work actually in the general case because of the way they're called. The pre hook is called from `showFormheader`and the post hook from `showFormButton` ; with an options array not being passed as reference from any of the calls...
If that must be changed, it's to be done in master as well I guess.

**Comment by tomolimo** [comment]
Ok, then just pass context (ticket object), and for the data passing between pre and post, I'll create a new issue,
thank you,

**Comment by trasher** [comment]
Isn't `$this` passed as item enough?

I've dropped the changes on array; since this would provide a different behavior from main cases.

**Comment by tomolimo** [comment]
Yes, correct, I don't know where are my eyes :)

**Pull request merged**
