### PR TITLE
Remove plural of firmware

### PR DESCRIPTION
**Pull request by ajsb85**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Refs: https://github.com/glpi-project/glpi/pull/1869

### CODE REVIEW

**Comment by trasher** [comment]
Thank you very much for the PR, but I've already fixed that.

And in facts, the change you propose is not correct... If that word do not ave a pluralized form in english, it may have on some other languages... And so we need to keep the pluralized call.

FYI, I've finally fixed it using `_n('Firmware', 'Firmware')` ;)

**Comment by ajsb85** [comment]
What languages you can see the suffix -wares?

**Comment by trasher** [comment]
Heu... Firwmare would be translated in french by "Micrologiciel", and for plural, it would become ""Micrologiciel**s**""

**Comment by ajsb85** [comment]
You are right.

**Pull request closed without merging**
