### PR TITLE
PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

### CODE REVIEW

**Comment by cedric-anne** [comment]
There are many libs that have to be patched to prevent the `Implicitly marking parameter $variable as nullable is deprecated` deprecation notice to be triggered. We have to discuss about the way to handle this. For instance, for some of them, this has already been fixed in an higher version, but we usually only do bugfixes updates on vendor libs in our bugfixes versions. It is still possible to manually apply patches, and we will anyway have to do it for some libs that we cannot update due to their incompatibility to both PHP 7.4 and PHP 8.4.

The declarations to patch can be found using the following regex: `(\s|,|\()(?<!\?)[A-Za-z0-9_\\]+\s*&?\$\w+\s*=\s*null(\s|,|\))`.

**Comment by trasher** [comment]
PHP 8.4 is planned for November; I guess there is no need to add first rc support in next minor GLPI release.

I'm not sure we have to support it in 10.0/bf branch since it requires many modifications in existing code (GLPI + 3rd party libraries).

**Comment by cedric-anne** [comment]
> PHP 8.4 is planned for November; I guess there is no need to add first rc support in next minor GLPI release.

The goal was to get tests results to see if this compatibility requires many changes or not. If it is too complicated, indeed, maybe we should only add this support in the main branch.

> 
> I'm not sure we have to support it in 10.0/bf branch since it requires many modifications in existing code (GLPI + 3rd party libraries).

Modifications in GLPI are quiet simple, and are backward-compatible with the previous code, see https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

The main problem is that we often use outdated versions of 3rd party libraries. Their PHP 8.4 supports will often be available only in upper major/intermediate versions and we cannot update all this libraries without risking some unexpected side effect (including in plugins).


Anyway, it seems that there are failures related to session variables. I do not know if it is an issue that will be fixed on the PHP side or if there is something to change in our code. I think we can wait for a rc version to see if tests are passing (the current version is an alpha).

**Comment by trasher** [comment]
While taking a look is not a big deal, PHP alpha releases are often problematic; we generally wait for RC1 to really work on compatibility (8.4-rc in PR title and YML files is confusing).

As of the issue for old libraries.. Until PHP 8.4 is be really widely adopted, I guess the next major GLPI release will be released as well :)

**Comment by AdrienClairembault** [comment]
FYI, tests fails because php 8.4 increased the bcrypt cost.

This trigger this piece of code:
image

Which set `glpiID` when we don't expect it, fucking up the tests that rely on session.

**Comment by cedric-anne** [comment]
> I'm not sure we have to support it in 10.0/bf branch since it requires many modifications in existing code (GLPI + 3rd party libraries).

@orthagh doesn't agree to add so many patches either, so I will close this PR and open a new one in the main branch later.

The only remaining issues are on 3rd party libs and are only deprecation issues, so, anyway, if someone really want to execute GLPI 10.0 on PHP 8.4, the only requirement would be to patch the `GLPI_MAX_PHP` value and to lower the log level to ignore deprecations.

**Pull request closed without merging**
