### PR TITLE
Add migration to use usigned int for primary/foreign keys; see #10262

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Here is the first step of migration to unsigned integers for primary/foreign keys. Switching installation file to unsigned int is too impacting and would trigger too many conflicts to be done on 9.5 branch, but the migration command should be, IMHO, be available in 9.5 branch, as it will be usefull for people using behaviours plugin.

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Comment by JosephLive93** [comment]
Where/how do you install/run the script(s) for GLPI?

Sorry for the beginner level question but this is new to me. I've tried doing research and had no luck. It's relatively time sensitive since we are unable to create tickets as an organization.

Thanks for any help!

**Comment by orthagh** [comment]
@JosephLive93

We just changed the PR to better detect columns with all mysql engines (like MariaDB), would you test again with the last changes ?
Regards

**Comment by JosephLive93** [comment]
> @JosephLive93
> 
> We just changed the PR to better detect columns with all mysql engines (like MariaDB), would you test again with the last changes ? Regards

@orthagh 

Ticketing now works! However, I ran into some errors due to negative values, but isn't as big of a deal for the time being. See below:

image

I really appreciate the support!

**Comment by cedric-anne** [comment]
> However, I ran into some errors due to negative values, but isn't as big of a deal for the time being. See below:
> 
> image

Negative values in these columns may be explicitely set by some plugins, so we cannot enforce the migration on them as we would these negative values.

For the `glpi_events.items_id` column, you can run the ``` UPDATE `glpi_events` SET `items_id` = '0' WHERE `items_id` = '-1' AND `type` = 'system'; ``` query. It should replace all negative values in this field. Then you can run the migration again to migrate it.

**Comment by cedric-anne** [comment]
@JosephLive93 

I identified the source of negative values in `glpi_networkportaliases.networkports_id_alias` (see commit 8bfb97525ece4bf85ca83800dc2c458a6ee16b1e). So you can also fix theses values by running ``` UPDATE `glpi_networkportaliases` SET `networkports_id_alias` = '0' WHERE `networkports_id_alias` = '-1'; ```.

**Review by trasher — APPROVED** [review]

**Comment by arthurrschaefer** [comment]
I've had problems with moreticket

Migration of column "glpi_events.items_id" cannot be done as it contains negative values.
Migration of column "glpi_plugin_manageentities_configs.documentcategories_id" cannot be done as it contains negative values.
Migration of column "glpi_plugin_moreticket_urgencytickets.tickets_id" cannot be done as it is referenced in CONSTRAINT "glpi_plugin_moreticket_urgencytickets_ibfk_1" of table "glpi_plugin_moreticket_urgencytickets.tickets_id".
Migration of column "glpi_tickets.id" cannot be done as it is referenced in CONSTRAINT "glpi_plugin_moreticket_urgencytickets_ibfk_1" of table "glpi_plugin_moreticket_urgencytickets.tickets_id".
 1285/1285 [============================] 100%
Errors occured during migration.

image

**Comment by cedric-anne** [comment]
Hi @arthurrschaefer ,

Handling database constraints has not be done in this migration as it is quiet complex and critical. You have to drop this constraint, run the migration again, and recreate the constraint.

I guess we would accept a code update that correctly handles such a case, but, as far as I know, usage of foreign key constraints on DB is really rare in plugins (I found not usage of them in plugins available in the marketplace for 9.5 version of GLPI).

Regards

**Comment by franciscoassissj** [comment]
Esteemed,

Performing some tests here on GLPI 10, after downloading and installing the Entities Management plugin, the message below appeared:

Erro GLPI 10

Even executing the command informed via the GLPI console, the error persists.

Erro GLPI 10 2

**Comment by tsmr** [comment]
Already corrected - https://github.com/InfotelGLPI/manageentities/commit/07eb6990f2437e628a97d316b395eed2e94dc9c0
Please open issue on plugin page project when you have issue

**Pull request merged**
