### PR TITLE
Move Search Query Builder UI to Twig

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

### CODE REVIEW

**Comment by orthagh** [comment]
There's still an vertical alignment issue with group removal button:
image

**Comment by orthagh** [comment]
a date criterion displays a dirty spacing before its value field:
image

**Comment by orthagh** [comment]
Another issues:

- [ ] "normal" rules cannot be deleted
- [ ] "globall" rules don't have the delete button
- [ ] probably not new, broken queries hide the general buttons (to reset view for example). 
- [ ] What's seem new is when submitting the form, **a reload of the page seems to happens**. So any errors will broke the page.

**Comment by cconard96** [comment]
> a date criterion displays a dirty spacing before its value field

Seems to exist already in 10.0.2 even.

> What's seem new is when submitting the form, a reload of the page seems to happens. So any errors will broke the page.

Apparently that was broken when I refactored the search code. There was a PHP error during the AJAX refresh so it fell back to doing a page reload instead to try and avoid the bug or at least show the error when in debug mode.

**Comment by orthagh** [comment]
Commenting your last commit, is the 50% width on `<td>` is required somewhere. I'm pretty in favor to completly remove it.

**Comment by cconard96** [comment]
`showGenericDateTimeSearch` is used by massive actions in metademands plugin and the rules engine.

For rule criteria at least, it doesn't seem needed.

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — COMMENTED** [review]
When reloading the page, if I have an empty criteria group, it triggers some errors.

To reproduce: `/front/computer.php?criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=0&criteria%5B1%5D%5Blink%5D=AND%20NOT&criteria%5B1%5D%5Bfield%5D=5&criteria%5B1%5D%5Bsearchtype%5D=notcontains&criteria%5B1%5D%5Bvalue%5D=9&criteria%5B2%5D%5Blink%5D=AND&criteria%5B2%5D%5Bitemtype%5D=0&criteria%5B2%5D%5Bmeta%5D=true&criteria%5B3%5D%5Blink%5D=AND&criteria%5B3%5D%5Bcriteria%5D%5B0%5D%5Blink%5D=AND&criteria%5B3%5D%5Bcriteria%5D%5B0%5D%5Bfield%5D=1&criteria%5B3%5D%5Bcriteria%5D%5B0%5D%5Bsearchtype%5D=contains&criteria%5B3%5D%5Bcriteria%5D%5B0%5D%5Bvalue%5D=u&itemtype=Computer&start=0&_glpi_csrf_token=aa0e877aaa8102458c8ed12a62b03f76eb6c6906aaac828a9dea1b66bd426d24&sort%5B%5D=1&order%5B%5D=ASC`

**Comment by cconard96** [comment]
The only error I saw was from the tags plugin because of an empty metacriteria. The itemtype for the empty metacriteria was set to "0" and the plugin tried using it as a class. Although, I'm thinking that was an issue before. I've added some logic to prevent that issue. For empty groups, they get converted to an items seen criteria if empty but that behavior is not new with this PR.

**Pull request merged**
