### PR TITLE
Allow content to be inserted after inputs labels

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Allow arbitrary HTML content to be inserted after inputs labels in our forms (only for the "vertical field" layout).

For example:

```twig
{% set content %}
    <div class='ms-auto'>test</div>
{% endset %}

{{ fields.textField(
    input_name,
    value,
    label,
    {
        insert_content_after_label: content
    },
) }}
```

image

For extra context, this is needed for a new helpdesk forms related feature that I'm working on this week.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Comment by cconard96** [comment]
How does this look when the screen width is larger and the fields have the labels horizontally aligned? I guess ms-auto won't work as expected at least.

**Comment by AdrienClairembault** [comment]
> How does this look when the screen width is larger and the fields have the labels horizontally aligned? I guess ms-auto won't work as expected at least.

This is a "vertical field" in this case so the layout doesn't change with screen width.
I had enabled the option for "horizontal field" too but it doesn't work really well on them so I'll disable it for now.

**Comment by cconard96** [comment]
I don't know the exact intention with the Forms feature, but if it will allow a field description in addition to a field name:
- When the field is vertical, the description could be displayed under the label with muted text.
- When the field is horizontal, maybe the description could be moved to the helper text but I'm not really sure it will work well at all especially if there is already a helper defined. Also, we don't allow HTML content in the helper anymore.

**Comment by AdrienClairembault** [comment]
This is not for a description.

**Comment by AdrienClairembault** [comment]
Had to fix some unrelated E2E test as its selectors were too brittle.

Adding the proper selectors required some changes to the `actors` field as the `for` attribute of the label didn't match the id of the `select`:

image

Should be all good now for reviews.

**Review by cconard96 — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Pull request merged**
