### PR TITLE
Fix Priority Right for ticket rules Engine

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2059

### CODE REVIEW

**Comment by trasher** [comment]
@tsmr as I cannot easily test the fix; could you please take a look? Thanks.
As for now, it's planned for 9.1.4; will be postponed until tested.

**Comment by tsmr** [comment]
Thanks for your work @trasher 

I'll check it as soon as possible

**Comment by tsmr** [comment]
ok for me

**Comment by trasher** [comment]
Great, thanks you both for review!

**Pull request merged**
