### PR TITLE
Changed date_mod of document to be viewed in timeline

### LINKED ISSUE #1942: When adding an already existing document to ticket -> problem in timeline
Hello,
When uploading to a ticket (in a followup for example) an already existing document (which has not been edited since), then there is a problem in the timeline, as the date used to order the document in the timeline is the date_mod of the Document and not the date_mod of the Document_Item.
This leads to an issue like:
image

In this exemple the document has been added with the followup '2017-03-13 11:45' and is viewed with the date_mod of the original document (i.e. the '2017-02-01 16:45') which is even earlier than the ticket creation date.
It should have been set to the date_mod of the document_item, like following:
image

Fix is coming,

Regards,
Tomolimo

### PR DESCRIPTION
**Pull request by tomolimo**
To fix #1942

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1942

### CODE REVIEW

**Comment by trasher** [comment]
I wonder if it would not be better to change on the UI side to use `document_item` date rather than change document date.

**Comment by tomolimo** [comment]
Hello @trasher ,
Sorry for being late to answer you, I missed your question.

> I wonder if it would not be better to change on the UI side to use document_item date rather than change document date.

I do not change the date of the document, I just select the right date for the UI.

Regards,
Tomolimo

**Comment by trasher** [comment]
Hello,

Replacing `$timeline[$document_obj->fields['date_mod']` with `$timeline[$document_item['date_mod']` sound much better.

**Comment by trasher** [comment]
BTW, note that we'll freeze 9.1.3 today (no more changes on the code) ;)

**Pull request merged**
