### PR TITLE
Add missing index on glpi_logs id_search_option fields; fixes #1921

### LINKED ISSUE #1921: Missing index in database glpi_logs
The field `id_search_option` from the `÷glpi_logs` table is not indexed.

I'ts used in the core (see https://github.com/glpi-project/glpi/blob/master/inc/ticket.class.php#L6070); but also in some plugins (FI, Purgelogs).

As the logs table may be huge, querying on a non indexed field may take too long.

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1921

Opened against master since there are schema updates.

### CODE REVIEW

**Comment by trasher** [comment]
I admit the limit is completely... Random :) For sure 36M is too huge for the update process ;)

What would be a "correct" limit?

**Comment by tomolimo** [comment]
keep it like that, and we'll see

**Comment by trasher** [comment]
Hum... I do not really agree; we'll have to set a "safe" limit bofore this is released; it will be too late after ;)

Anyways, thanks for the review :)

**Comment by tomolimo** [comment]
FIY: I've added this index on our test DB version 9.1.2 (only 27M of recs), and it took only 1'17".
But could this time also depend on the fact that our tables are InnoDB?

**Comment by trasher** [comment]
I think the table type may affects the time, yes. Of course, many other factors may also be considered. Thanks for the values, it will probably help :)

**Comment by trasher** [comment]
We make some tests on our side, it appears that 2 000 000 would be a pretty acceptable limit; since it should not take more than ~10 seconds (1/3 of the defautl PHP maximum execution time).

**Pull request merged**
