### PR TITLE
Permit to send a class to apply on the main div

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by trasher** [comment]
Before:
userprefs-before
After:
userprefs-after

**Comment by orthagh** [comment]
LGTM.
Btw, i think the createTabs method parameters could be merged in one array (with default values).
Almost all parameters have a default value

**Comment by trasher** [comment]
Would not it break plugins?

**Comment by orthagh** [comment]
indeed, some plugins use it (fusion, monitoring, racks)

**Pull request merged**
