### PR TITLE
Check for the right field

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by yllen** [comment]
**You can't change an already published file**. 
You must create a new one for next migration.

In your PR, you check is due_date is present but it was rename to time_to_resolve in update_91_92, line 773.
Done also in update_92_921, line 238.

So for me this field is not present.
And if it's always present, you must rename it to time_to_resolve

**Comment by trasher** [comment]
This field should be present as of 9.1; but in some cases, there is a (fixed) bug, and field has not been renamed.
So we can have both cases, and this makes a fatal error. There is no way to get that fixed without changing the file.

**Comment by yllen** [comment]
You must make a new file for new version.
- if field due_date present => rename it
- if field time_to_own not present => add it

**Comment by trasher** [comment]
Upgrade will still fail on the original file.

**Pull request merged**
