### PR TITLE
Asset rules: add last inventory update criteria

### PR DESCRIPTION
**Pull request by AdrienClairembault**
image

This new criteria required quite a bit of code as there was no support for dates

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !23959

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
On hold, waiting for #11716 to be merged as it fixes some unit tests

**Comment by AdrienClairembault** [comment]
Should be good for reviews :)

**Comment by AdrienClairembault** [comment]
Force pushed to fix conflicts, would appreciate some reviews before more conflicts appears ;)

**Comment by AdrienClairembault** [comment]
Up

**Review by trasher — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
