### PR TITLE
fix(assets): input label

### PR DESCRIPTION
**Pull request by Rom1-B**
The label "Technician in charge of the hardware" is a generic text, but it's not suitable for software. Same thing for the group.

Perhaps replace with "Technician in charge of the asset" or just "Technician in charge"?

Before:

image

After:

image

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30281

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
I think that "Technician in charge" would be enough.

**Comment by trasher** [comment]
> I think that "Technician in charge" would be enough.

I wonder if removing "of ..." should not be done globally; this is not the first fix of that kind (see #15886); and I'm not sure this is really usefull.

**Comment by cedric-anne** [comment]
> > I think that "Technician in charge" would be enough.
> 
> I wonder if removing "of ..." should not be done globally; this is not the first fix of that kind (see #15886); and I'm not sure this is really usefull.

I agree.

The only case where it is really usefull is in ITIL objects, to be able to distinguish `Technician in charge of the ticket` and `Technician in charge of the task` in the notification settings. But, even here, it is badly named when the ITIL object is not a ticket. `__('Technician in charge of the ticket')` could probably be changed to `__('Technician in charge')`.

**Comment by trasher** [comment]
@Rom1-B could you please globally change the sentence in this PR?

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
