### PR TITLE
Fix#12455

### PR DESCRIPTION
**Pull request by tomolimo**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12455

### CODE REVIEW

**Review by cconard96 — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
It seems OK from the functionnal point of view, and, as it does not break test suite, I guess it is OK.

**Review by trasher — DISMISSED** [review]

**Review by orthagh — COMMENTED** [review]
Please don't merge before my approval.
Don't have time today, but at first glance, i'm not pleased with the current solution.
I need to check in detail tomorrow

**Comment by cedric-anne** [comment]
@tomolimo 

Did you find an alternative solution ?

**Comment by tomolimo** [comment]
Hello @cedric-anne 
Yes: it's here: #12780 
Thank you
Regards,
Tomolimo

**Pull request closed without merging**
