### PR TITLE
Rework linear amortise calculation

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2923 

Since the original code was a bit obscure, I've write a new method for this specific case. Problem is I started from scratch; and results are not the same (especially on the first year).

Well, I'm not accountant; can't say what is the correct way to go. Tests are provided; check them for the values.

### CODE REVIEW

**Comment by orthagh** [comment]
reviewed by @flegastelois, no ?

**Comment by trasher** [comment]
Yes, @flegastelois has tested (I made some adaptations). Was waiting for a feedback from the original author; but since we have no news; I think we can merge.

**Comment by romainlombart** [comment]
Hello,
It still does not work properly

**Comment by trasher** [comment]
@romainlombart please provide explanations.

**Comment by romainlombart** [comment]
Hello,

http://forum.glpi-project.org/viewtopic.php?id=159219 
<http://forum.glpi-project.org/viewtopic.php?id=159219http://forum.glpi-project.org/viewtopic.php?id=159219>

I just installed the new version that must fix the problems (9.2.1), but 
it does not work.
The calculations of VNC are completely foolish, the monthly TCO is 
displayed in a computer on 2 ... it is almost worse than before.

A computer bought this early November has already lost 224.68 € worth, 
while its depreciation is 3 years in linear.
I can put any date of purchase in this file, it always brings me the 
same value VNC and nothing at all in TCO.


Best regards

Romain LOMBART

*Administrateur SI*

Tel +33 (0)4 73 26 98 47

LD +33 (0)4 73 28 60 63

Glisshop.com <http://www.glisshop.com/>


Le 02/01/2018 à 08:03, Johan Cwiklinski a écrit :

**Comment by trasher** [comment]
> A  computer bought this early November has already lost 224.68 € worth,

I dot not see what is wrong here. A prorata is calculated from the use date for the current year. See https://www.compta-facile.com/construire-tableau-plan-amortissement-lineaire/.

> I can put any date of purchase in this file, it always brings me the same value 

You have to change the use date, not the purchase date.

**Comment by romainlombart** [comment]
Is the date of use just below the date of purchase? (Date of 
commissioning ?, in french "Date de mise en service" ?)

I tried to change a date on one of my computers, and I had the following 
error :
Please enter the date of purchase or the date of commissioning in the 
preferences.

And now Look at a financial report as an attachment, all VNC values are 
at zero... I really do not understand what's going on and why it's not 
working

Romain LOMBART

*Administrateur SI*

Tel +33 (0)4 73 26 98 47

LD +33 (0)4 73 28 60 63

Glisshop.com <http://www.glisshop.com/>


Le 02/01/2018 à 09:46, Johan Cwiklinski a écrit :

**Comment by trasher** [comment]
> Date de mise en service

Yes. If no "date de mise en service" is set; the "date d'achat" should be used.

> Please enter the date of purchase or the date of commissioning in the preferences.

Are you sure the entered date respects the format? Using the date picker should provide the good one.
This error message is talking about "preferecnes", this is a mistake. It related to the date you've entered on the computer form.

A quick test on my instance (with a fiscal end date set to 31/12) gives the following:
screenshot-2018-1-2 glpi - ordinateurs - 8

Which seems ok.

**Comment by romainlombart** [comment]
Please see that in debug mode :
<a href="https://www.hostingpics.net/viewer.php?id=947607glpidebug01.png">Heberger image</a>
<a href="https://www.hostingpics.net/viewer.php?id=999917glpidebug02.png">Heberger image</a>

**Pull request merged**
