### PR TITLE
Feature/minify

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by remicollet** [comment]
Cannot the Robo file be in tools directory instead to top dir ?

**Comment by trasher** [comment]
It could, yes; using the `--load-from` argument. But this one is not documented in the inline help (I only can find it on their website) :/

**Comment by trasher** [comment]
OK, I've moved the RoboFile, adapted the command in the release script, and some other changes @orthagh requested :)

**Comment by trasher** [comment]
I found a bug that I've fixed (url prefix was not added when passing false as 3rd arg). I've also added some unit tests.

**Pull request merged**
