### PR TITLE
Fix ITILFollowup delete

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Should be using the field value instead of the field name.

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

Thanks for the fix.

It could be nice to add a functionnal test on this case.

Regards

**Comment by trasher** [comment]
I totally agree with @orthagh; thank you very much @cconard96. Your contributions are really appreciated! :+1: :+1:

**Comment by trasher** [comment]
I've just added a commit to "refine tests". In the past, I had difficult to understand issues because an entry has not been added/updated/deleted as expected; but without causing an error in the code.

That's why we used to test each add/update/getFromDB/delete

**Comment by cedric-anne** [comment]
Thanks for the quality of your contributions :1st_place_medal: .

**Pull request merged**
