### PR TITLE
Fix registration_number locale for entity

### PR DESCRIPTION
**Pull request by tsmr**
Fix registration_number locale for entity 

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Comment by cconard96** [comment]
I see 8 cases where the lowercase "number" is used and only one case with the uppercase "Number".

**Comment by tsmr** [comment]
Yes : 

#: src/Entity.php:1509
msgid "Administrative Number"
msgstr "Numéro administratif"

#: templates/generic_show_form.html.twig src/AuthLDAP.php:896
#: src/Auth.php:1681 src/Contact.php:410 src/User.php:2609 src/User.php:3099
#: src/User.php:3665 src/Entity.php:826 src/Supplier.php:345
msgid "Administrative number"
msgstr "Matricule"

Not the same signification

**Comment by trasher** [comment]
If a same strnig has several meanings, it should be using gettext contexts.

**Review by trasher — CHANGES_REQUESTED** [review]
see comment

**Comment by trasher** [comment]
ping?

**Comment by tsmr** [comment]
> ping?

I use two context like these ?

For Entity & supplier
_x('infocom', 'Administrative Number')

For users
_x('user', 'Administrative Number')

**Comment by trasher** [comment]
something like that yes, I'm a bit unsure about context names as I'm not a translator :)

**Review by trasher — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Pull request merged**
