### PR TITLE
Apply PHPCS rule PSR2.ControlStructures.ControlStructureSpacing (No white spaces after opening bracket and before closing bracket in IF)

### PR DESCRIPTION
**Pull request by AnaelMobilia**
```
  <!-- No white spaces after opening bracket and before closing bracket in IF -->
  <rule ref="PSR2.ControlStructures.ControlStructureSpacing" />
```
+ Fix current code for this rule

Part of #1209

### CODE REVIEW

**Comment by AnaelMobilia** [comment]
Please note that the error on the CI checks aren't linked to this PR, but by the definition of the actual date on the tool (inc/define.php) ;-)
```
1) HtmlTest::testGetCopyrightMessage

Invalid copyright date!

Failed asserting that '<a href="http://glpi-project.org/" title="Powered By Teclib" class="copyright">GLPI 9.2 Copyright (C) 2015-2016 Teclib' - Copyright (C) 2003-2015 INDEPNET Development Team</a>' contains "2017".
```

**Comment by orthagh** [comment]
hello @AnaelMobilia 

We merged #1487 (fix travis errors with copyright).
Could you rebase this pr and others one wit the same travis error to relaunch a correct build ?

Thank you

**Comment by AnaelMobilia** [comment]
@orthagh 
Hi, I have rebase all PR, and CI is now OK an all of them !
Thank you :)

**Comment by orthagh** [comment]
merged, thank you very much

**Pull request merged**
