### PR TITLE
Fix tables of changes and problems

### PR DESCRIPTION
**Pull request by Lainow**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

Fix tables of changes and problems for an item so that they are similar to the table of tickets for an item and compatible with the print preview functionality.

**Before**
image

**After**
image

### CODE REVIEW

**Review by AdrienClairembault — APPROVED** [review]

**Comment by orthagh** [comment]
It works yes.
But a suggestion, we should take the time to move on a twig datatable.
We should not have any more `tab_cadre_fixe` or `tab_cadre_fixehov` at this point

**Comment by trasher** [comment]
> we should take the time to move on a twig datatable.

That's what I said on our internal channel. Maybe we can merge this one, to start on "cleaner" state for twig migration.

**Comment by orthagh** [comment]
> Maybe we can merge this one, to start on "cleaner" state for twig migration.

Ok for that, let's merge, but @Lainow could you take in charge the migration to twig ?

**Comment by Lainow** [comment]
> > Maybe we can merge this one, to start on "cleaner" state for twig migration.
> 
> Ok for that, let's merge, but @Lainow could you take in charge the migration to twig ?

Yes no problem

**Pull request merged**
