### PR TITLE
Added user location to locations_id

### LINKED ISSUE #1793: Add default location for helpdesk ticket creation
Hello,

When creating ticket via helpdesk (simplified interface), the location field must be set by default to the locations_id of the requester.

regards,
Tomolimo

### PR DESCRIPTION
**Pull request by tomolimo**
Fixes #1793

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1793

### CODE REVIEW

**Comment by yllen** [comment]
Not agree with this change

**Comment by yllen** [comment]
If the user want this value as default value he can define it in a business rule.

For lot of people, you define this field only if the location to act is temporally different, so the network can also be different (not the same society, in another town...) so intervention must even be more complex as a standard one.
So technician take all tickets without location for a requester group and do other with location onother time.
With this change, simple action will not be done or the society must review all its way to do

**Comment by remicollet** [comment]
As I said in the ticket, I think this is unneeded.
Rules are there if user doesn't provide location.

Having defaul ticket location = user location is NOT a correct default value (only for some case)

**Comment by trasher** [comment]
OK, then the PR is refused.

**Pull request closed without merging**
