### PR TITLE
Add used JS libraries + links to dev

### PR DESCRIPTION
**Pull request by AnaelMobilia**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none

Add used JS libraries + links to dev
Will help to maintain up to date / get doc

### CODE REVIEW

**Comment by AnaelMobilia** [comment]
Tests are breaked due to a composer.org availibity issue... nothing to care with the PR :)

**Comment by orthagh** [comment]
I'm not sure about this one.
The "best" way should be to use a dependency manager (npm/yarn/bower not sure about the correct one today).
But our last tests seems to add a lot of noise files in the archive

**Comment by trasher** [comment]
This is indeed not the "best" way; dependency manager seems not to be the best way neither...

For me, this is OK; I did exactly the same for the Telemetry app, this would permit to know very quickly which versions are used and if upgrade are needed.

**Comment by orthagh** [comment]
so ok for me

**Pull request merged**
