### PR TITLE
do not send encoded html to ldap search; see #10135

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10135

@cedric-anne opinion on this one would be required before merging i suppose
Original error was on `ldap_search` (but the `@` before https://github.com/glpi-project/glpi/blob/10.0.0-beta/src/AuthLDAP.php#L3329 hides completly the error for me, also in logs):

```
[2021-12-21 12:21:20] glpiphplog.WARNING:   *** PHP Warning (2): ldap_search(): Search: Bad search filter in /var/www/html/glpi/10.0-git/src/AuthLDAP.php at line 3331
  Backtrace :
  src/AuthLDAP.php:3331                              ldap_search()
  src/AuthLDAP.php:2732                              AuthLDAP::searchUserDn()
  src/AuthLDAP.php:352                               AuthLDAP::ldapImportUserByServerId()
  src/MassiveAction.php:1168                         AuthLDAP::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1146                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()
```

And the bad content was the `&` encode to `&#38;`, both in db and also in form data (you can change it live in import form)

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Comment by flegastelois** [comment]
Should be also fixed:
https://github.com/glpi-project/glpi/blob/89c9c67945b4f510e855b54e6a7ce659f8276a08/src/AuthLDAP.php#L1969

**Review by trasher — APPROVED** [review]

**Comment by orthagh** [comment]
Yes i know, and i'm on it since lunch.
It's a encoding/decoding nightmare as usual and i can't find a way to fix the issue properly.

**Comment by orthagh** [comment]
To note, i initially tried to fix the bad filter (content like `(& (&#38;...`) in `Sanitizer::unsanitize` method but this choice may trigger regressions on other parts of GLPI.
I choose so to fix all occurence where the filter is extracted from DB or send from a form.

**Review by trasher — APPROVED** [review]

**Comment by cedric-anne** [comment]
> @cedric-anne opinion on this one would be required before merging i suppose Original error was on `ldap_search` (but the `@` before https://github.com/glpi-project/glpi/blob/10.0.0-beta/src/AuthLDAP.php#L3329 hides completly the error for me, also in logs)

In this kind of cases, I think `@` should be removed. Indeed, if PHP is configured properly (i.e. `display_errors=Off` in production), these errors will be shown on UI only in debug mode. Using `@` should be kept only for really specific cases.

May be part of a more global PR.

> And the bad content was the `&` encode to `&#38;`, both in db and also in form data (you can change it live in import form)

The best solution would be and to use raw form value and to store raw value in DB, as we do for passwords, (have to ensure that value is escaped when it is displayed), but it would require a migration for existing values.

**Comment by orthagh** [comment]
> The best solution would be and to use raw form value and to store raw value in DB, as we do for passwords, (have to ensure that value is escaped when it is displayed), but it would require a migration for existing values.

I'm not sure it's the best solution regarding the current beta period.
If you agree with the current change, we can merge i think

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
