### PR TITLE
Fix In-Reply-To token for thread of notifications

### PR DESCRIPTION
**Pull request by OlivierLM**
Attended thread view of notifications doesn't work :
  - http://cr.yp.to/immhf/thread.html : In-Reply-To is a tokenisable field
  - http://cr.yp.to/immhf/token.html : An atom shall be around < and >
With this modification, thread view is finally OK…

### CODE REVIEW

**Comment by orthagh** [comment]
Great !
Last thing, could you open an issue to describe the problem and link the commit to it.
I'll merge after that

**Comment by OlivierLM** [comment]
I wrote an answer to the problem described by another user in the web forums a few years ago…

----- Mail original -----
> Great !
> Last thing, could you open an issue to describe the problem and link the
> commit to it.
> I'll merge after that
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/glpi-project/glpi/pull/244#issuecomment-155093918

-- 
Olivier Le Monnier — ☎ 023156.6209 
Administrateur systèmes libre(s) 
Direction du Système d'Information 
Université de Caen Normandie

**Comment by orthagh** [comment]
Yes, and it's a good patch.
But i need an (issue)[https://github.com/glpi-project/glpi/issues] to keep changelog comprehensive.
I don't need a big paragraph, just an understable issue to avoid duplicate reports.

**Comment by OlivierLM** [comment]
DIY

----- Mail original -----
> Yes, and it's a good patch.
> But i need an (issue)[https://github.com/glpi-project/glpi/issues] to keep
> changelog comprehensive.
> I don't need a big paragraph, just an understable issue to avoid duplicate
> reports.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/glpi-project/glpi/pull/244#issuecomment-155100540

-- 
Olivier Le Monnier — ☎ 023156.6209 
Administrateur systèmes libre(s) 
Direction du Système d'Information 
Université de Caen Normandie

**Comment by orthagh** [comment]
Can see the point of your answer....
But fine, do as you want

**Comment by remicollet** [comment]
Merged.

**Pull request closed without merging**
