### PR TITLE
Improve timeline item form layouts for non-xxl screens

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10931

The timeline item forms (such as tasks) can feel very cramped unless the browser window is very large. I some cases, the fields are too small to interact with. This is also an issue if, like me, you have the browser's console open often and it is docked on the left or right.

The following changes were made to alleviate these issues:
- Less padding around timeline item forms on non-xxl screens
- Adjusted timeline layout so the left side would have more space on non-xxl screens
- Adjusted col breakpoints in timeline item forms to match xxl and not md screens and added a second break point to slightly reduce the size of the `content` field before falling back on having the extra fields show under the content.

I'm still looking at the behavior of the right-side panel. The expand/collapse isn't working right and I notice some odd resize issues before my changes.

### CODE REVIEW

**Comment by orthagh** [comment]
Can you add a screenshot ?

**Comment by cconard96** [comment]
Using the same screen size comparing `master` to the changes in this PR.
Before:
Screenshot from 2022-03-10 09-52-34


Current:
Screenshot from 2022-03-10 09-53-27

It still isn't great, but this is the smallest the fields get in this PR so is a worst-case scenario. There may be other tweaks that can be done to improve it more.

**Comment by cconard96** [comment]
> it's better but not great indeed. under (and equals) xl screens maybe we can wrap the right column. And maybe hide it under a toggle for cleaner display.

Since there are already controls for collapsing and expanding the panel, maybe some JS can collapse it automatically when the timeline loads if the screen is too small.
For the timeline forms themselves, the right column does wrap for screens smaller than `xl`. Since the breakpoints are based on the screen size and not parent element, these breakpoints start to mean less when you have a ton of nested elements and have a lot of elements horizontally as we do here. It would almost have to wrap and show the fields vertically under the content for anything less than `xxl`.

**Comment by orthagh** [comment]
> the right column does wrap for screens smaller than xl

Indeed, tested live, it's ok with these breakpoints (xxl spacing, xl wrap)


Here is a suggestion for gaining 30-40 px more.
image


One last thing not related to this pr (i have the issue on current master), we currently have an horizontal scrollbar on the timeline.
Don't know why (yet)

**Comment by orthagh** [comment]
i tried and in fact, the last issue is more than the margin-start.
when the `#new-itilobject-form` take all the width, we need at least -3 spacing
but when it doesn't, it require the ms-auto to right aligned.

I suggest so: `ms-auto ps-3`

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
