### PR TITLE
Fix attachments renaming

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #9667 #9600

### CODE REVIEW

**Comment by BorisNovg** [comment]
Fix 89104ec (https://github.com/glpi-project/glpi/pull/9672) solves the problem.

I tested using the message [Message16335125161734170604.zip](https://github.com/glpi-project/glpi/files/7293469/Message16335125161734170604.zip).

In addition, I created a message with three different attachments, but having the same name without an extension.
[Message-test_3_different_attachments_with_the_same_filename_without_extension.zip](https://github.com/glpi-project/glpi/files/7303449/Message-test_3_different_attachments_with_the_same_filename_without_extension.zip)

test_3_different_attachments_with_the_same_filename_without_extensions-1

test_3_different_attachments_with_the_same_filename_without_extensions-2

All three files have been saved, their names are:
1234567890
1234567890_1
1234567890_2

Ok!

Also, I checked a letter in which two screenshots are attached inside the letter, different but with the same file name.
The file name is =?US-ASCII?B?0LjQt9C+0LHRgNCw0LbQtdC90LjQtS5wbmc=?=, which means изображение.png (screenshot.png in Russian).

test_3_different_attachments_with_the_same_filename_without_extensions-3

test_3_different_attachments_with_the_same_filename_without_extensions-4

As shown in the screenshot, 2 images have been successfully inserted into the message text.
Ok!

All five documents received by mail:
test_3_different_attachments_with_the_same_filename_without_extensions-5

In addition, I sent copies of the last 538 messages from the my production system to the mail receiver. No errors were found.

Maybe you can suggest additional testing methods?

**Comment by trasher** [comment]
No problem for me to switch back to `_2`; that does not matter from the code point of view.

**Comment by BorisNovg** [comment]
Sorry to barge in. Perhaps this line should be deleted.
https://github.com/glpi-project/glpi/blob/0e6fda77eb1156df0b242826469c2df1f569c20b/tests/emails-tests/28-multiple-attachments-no-extension.eml#L9
It was probably accidentally added when cleaning the headers (@trasher Cleanup headers 811a436). In my original example, there is no such string.

**Comment by BorisNovg** [comment]
I noticed that during the control testing these tests were failed
```"Test on PHP 8.0 using mariadb:10.6"``` - ```"IMAP test"```
 and
```"Test on PHP 8.0 using mysql:8.0"``` - ```"IMAP tests"```
 
with log messages:
```*** Uncaught Exception Laminas\Mail\Exception\InvalidArgumentException: The input is not a valid email address. Use the basic format local-part@hostname in /var/glpi/vendor/laminas/laminas-mail/src/Address.php at line 78```

```*** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name date or date not found in /var/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307```

As a solution, you are trying to change the test email ```glpi/tests/emails-tests/28-multiple-attachments-no-extension.eml``` by focusing on these messages in the log (you have changed the email and data fields), assuming that it is the text in the test email that creates **these errors**.

However, these are most likely erroneous actions, since exactly the **same error messages** are present in absolutely all successful tests, for example, a month ago:
https://github.com/glpi-project/glpi/pull/9529/checks?check_run_id=3566315938#step:14:22
https://github.com/glpi-project/glpi/pull/9529/checks?check_run_id=3566315938#step:14:23

The presence of these messages in the log caused a **warning**, but not an error when completing the IMAP test:
https://github.com/glpi-project/glpi/pull/9529/checks?check_run_id=3566315938#step:14:19
```Success (1 test, 10/10 methods, 0 void method, 0 skipped method, 276 assertions)!```

IMHO the test completion error is related to adding a file ```glpi/tests/emails-tests/28-multiple-attachments-no-extension.eml```, however, the reason for the error is not related to the log messages about the email and date fields, and this reason is still unknown to us.

Perhaps the reason for the error was indicated in the following lines (they are incomprehensible to me):
```
==> -Expected
==> +Actual
==> @@ -1 +1 @@
==> -int(0)
==> +int(2) in /var/glpi/vendor/atoum/atoum/classes/asserter.php at line 131"
Error: Process completed with exit code 1.
```

**Comment by trasher** [comment]
> with log messages: `*** Uncaught Exception Laminas\Mail\Exception\InvalidArgumentException: The input is not a valid email address. Use the basic format local-part@hostname in /var/glpi/vendor/laminas/laminas-mail/src/Address.php at line 78`
> 
> `*** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name date or date not found in /var/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307`

Indeed, those ones are "expected", good catch.

> Perhaps the reason for the error was indicated in the following lines (they are incomprehensible to me):
> 
> ```
> ==> -Expected
> ==> +Actual
> ==> @@ -1 +1 @@
> ==> -int(0)
> ==> +int(2) in /var/glpi/vendor/atoum/atoum/classes/asserter.php at line 131"
> Error: Process completed with exit code 1.
> ```

Yes, I saw that one and spent time on it; but I do not understand what the problem is :/

**Comment by BorisNovg** [comment]
Maybe this script output has useful information?
```
Run .github/actions/init_initialize-imap-fixtures.sh
Initialize email fixtures

GLPI dataset version 4.7 already loaded

.......U..                                                   [10/10]
```
If I understood this script output correctly, the failure occurred precisely in the eighth test (out of 10).

**Comment by trasher** [comment]
Great, many thanks @cedric-anne for tests debug!

**Pull request merged**
