### PR TITLE
.htaccess files adaptation and normalisation

### LINKED ISSUE #196: Attached file with ie 11
Hello,
There is a bug with ie11, it's impossible to add a file in a ticket.

### PR DESCRIPTION
**Pull request by barbuslex**
This pull request fix #196 #329 issues and make .htaccess files compatible with Apache 2.2 and Apache 2.4.

### CODE REVIEW

**Comment by remicollet** [comment]
Notice: those changes are not needed in most case, Apache 2.4 is perfectly able to understand "deny from all" (thanks to http://httpd.apache.org/docs/2.4/mod/mod_access_compat.html) 

Notice: the compat test is still mandatory to grant access.

**Comment by barbuslex** [comment]
Yes with mod_access_compat but the syntax "deny from all" will be deleted in the future of apache.

**Comment by orthagh** [comment]
good point @remicollet, i missed the Satisfy.

@barbuslex, i'll revert this pr, please provide another one who is compatible with all Apache.
We can't add this prerequisite.

**Comment by barbuslex** [comment]
@orthagh the pr #393 fix the issue ;)

**Comment by orthagh** [comment]
all reverted currently, i need more tests to revalidate this one.

**Pull request merged**
