### PR TITLE
Hide plugins with no installable version

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !21108

When `GLPI_MARKETPLACE_PRERELEASES` is set to false (default), plugins with only unstable versions are shown but no action is proposed.
I propose to hide these plugins from the list.

### CODE REVIEW

**Comment by trasher** [comment]
Should this be unit tested?

**Comment by cedric-anne** [comment]
> Should this be unit tested?

Not sure how to test that. A solution could be to force "cached" value and verify results.

**Comment by trasher** [comment]
Yes, that would be a solution. Another one would be to mock the class and override `getPaginatedCollection` maybe.

**Review by trasher — APPROVED** [review]

**Comment by cedric-anne** [comment]
> Yes, that would be a solution. Another one would be to mock the class and override `getPaginatedCollection` maybe.

In fact, this behaviour cannot be tested without refactoring this part. Indeed, result will depend on `GLPI_MARKETPLACE_PRERELEASES`, but we cannot redefine a constant.

This is really an edge case, so I am not sure we should spend too many time on it.

**Comment by trasher** [comment]
:+1: for me then

**Comment by trasher** [comment]
ping @orthagh

**Pull request merged**
