### PR TITLE
Added support for all fields in links (See #3091)

### PR DESCRIPTION
**Pull request by edgardmessias**
TAG: [FIELD:field name in DB]
Example: [FIELD:name], [FIELD:content], ...

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3091

### CODE REVIEW

**Comment by trasher** [comment]
Checks are failing because of small CS issues

**Comment by edgardmessias** [comment]
Fixed.

**Comment by orthagh** [comment]
I'm not very confident with the proposed solution.
This can permits to expose fields (like hashed password in users for example) 
  
alternative proposal:

```diff
diff --git a/inc/link.class.php b/inc/link.class.php
index 2d75701f90..b5bafa4adc 100644
--- a/inc/link.class.php
+++ b/inc/link.class.php
@@ -280,7 +280,7 @@ class Link extends CommonDBTM {
       }
 
       if (strstr($link, "[NAME]")) {
-         $link = str_replace("[NAME]", $item->getName(), $link);
+         $link = str_replace("[NAME]", $item->getField('name'), $link);
       }
       if (strstr($link, "[SERIAL]")
           && $item->isField('serial')) {
```
It fix the original issue (#3091) and it's more simple

**Comment by orthagh** [comment]
ping @edgardmessias ?

**Comment by edgardmessias** [comment]
I'm sorry for the delay in replying.

Maybe, we can filter fields using `unsetUndisclosedFields`, like the API

**Pull request merged**
