### PR TITLE
Fix update called via install process

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

### CODE REVIEW

**Comment by tigerblue77** [comment]
Hello,

you closed my issue and I understand it has been fixed here but how do I apply it ? I used the latest tar.gz archive release to install 9.5.0 some days ago, used the tar.gz archive release to install v9.5.1 but the problem wasn't fixed when I processed to upgrade...

I'm a bit confused. Thanks by advance

**Comment by cedric-anne** [comment]
This patch has not been released yet. You should apply it to GLPI 9.5.1 source and then process to the upgrade.

**Comment by NT3R117** [comment]
Sorry, I'm a bit confused too,

If I understand well, we have to wait a new commit ? Or there is a way to fix this when upgrading GLPI from 950 to 951 ?

Can you please give mor information ?

Thanks for your support

**Comment by trasher** [comment]
You can try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)); or wait for 9.5.2 to be released.

**Pull request merged**
