### PR TITLE
Fixe #4108 Plugin Redirect

### PR DESCRIPTION
**Pull request by keha35**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4108

### CODE REVIEW

**Comment by orthagh** [comment]
Hello @keha35 

ok for the issue for the redirect missing on helpdesk interface.

Some points:
- Since 0.90, this redirect feature is replaced by direct url calls, if login required, redirect will be automatically set after, we don't need anymore to "forge" redirect params.
- We can add your enhancement, but one change required: as the code you added is the same as the central interface, we need to factorise it in a function.
- Much better, with this function we could add an unit test to avoid regressions.

**Comment by trasher** [comment]
I do not understand the factorization. It sems that some cases are now lost, I do not think this is expected.

**Comment by trasher** [comment]
ping?

**Comment by trasher** [comment]
No ping response; I'm closing this one.

**Pull request closed without merging**
