### PR TITLE
see #2198

### PR DESCRIPTION
**Pull request by yllen**
Add new hook

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2198

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by yllen** [comment]
Example of hook (only see computers of my groups)

 function hook can($item) {
    if (($item-getType() == 'Computer')
        && ($item->right == READ)
        && ($item->fields['groups_id'] > 0)
        && !in_array($item->fields['groups_id'], $_SESSION["glpigroups"])) {
       $item->right = 0; // unknown, so denied.
    }
}

**Comment by remicollet** [comment]
Only make sense if both #2200 and #2201 are merged together.

**Comment by trasher** [comment]
Indeed; one PR has been enough (I'm going to merge them).

BTW, I guess it would be better to target 9.2 to add new hooks.

**Comment by trasher** [comment]
Example for the search engine hook (#2201):
```
function hook_add_default_where($in) {
   list($itemtype, $condition) = $in;
   if ($itemtype == 'Computer') {
      $table = getTableForItemType($itemtype);
      $condition .= " (".$table.".groups_id NOT IN (".implode(',',$_SESSION["glpigroups"])."))";
   }
   return [$itemtype, $condition];
}
```

**Comment by trasher** [comment]
Will be merged for 9.1.5 (9.1.4 will only be a regression/bugfixes release).

By the way, could you please drop a line on the developper docs for this new hook? (see existing at http://glpi-developer-documentation.readthedocs.io/en/master/plugins/hooks.html). Thank you.

**Comment by yllen** [comment]
Done: https://github.com/glpi-project/docdev/pull/50

**Comment by trasher** [comment]
Great, thank you :) Just waiting now for .4 to be released before merging.

**Comment by trasher** [comment]
Looking at the doc PR, I've seen something wrong with hooks (duplicate).

**Pull request merged**
