### PR TITLE
Fix(inventory): Update status of computer items

### PR DESCRIPTION
**Pull request by Rom1-B**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !33699
- Here is a brief description of what this PR does

When configuring the inventory update process to ensure that a computer's items adopt the same status as the computer, an issue arises. If the computer already has the default status set in the "inventory" menu and one of its items has a different status, the item's status was not updated accordingly.
Before, it was only updated if the computer changed status.

### CODE REVIEW

**Comment by stonebuzz** [comment]
I wonder if we shouldn't apply this fix to all fields that need to be propagated. 

image


```When connecting or updating``` => ```When it's connected or when connecting or updating```

**Comment by trasher** [comment]
> I wonder if we shouldn't apply this fix to all fields that need to be propagated.

I guess issues is the same on other fields, yes. @Rom1-B could you please check?

**Review by stonebuzz — APPROVED** [review]
functionally ok for me, it keeps the status up to date for linked items

related documentation -> https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/general/assets.html#automatically-update-of-the-elements-related-to-the-computers

should also be updated

**Comment by orthagh** [comment]
Ok for the functional side.
Could we take the opportunity to move all the *_autoupdate processing into a dedicated method (better design for a test)

**Comment by cedric-anne** [comment]
> Ok for the functional side. Could we take the opportunity to move all the *_autoupdate processing into a dedicated method (better design for a test)

There are already many conflicts when a merge is done in the main branch. As a test has been added to validate the feature, I propose to not refactor it right now.

**Comment by orthagh** [comment]
I asked precisions to the customer, the current fix lets all updates trigger the propagation of these fields (for ex, a change of user_id_tech propagates the status), and I'm not sure this is desired.

So please wait for customer's answer before making anything more on this PR.

**Comment by cedric-anne** [comment]
> So please wait for customer's answer before making anything more on this PR.

I changed the status to draft to be sure that it will not be merged until you get the customer's feedback.

**Comment by Rom1-B** [comment]
The client has two scenarios:

1. In the case of remote work, the PC goes out of sync, meaning both the computer and the monitor become unsynchronized. However, when the PC returns to the office, the computer switches back to "production" status, but the monitor does not.
2. You manually change the monitor's status because it has been returned to stock and remove the lock on the status. After the next synchronization, the status is not updated.

I don't see how else we could handle this in this PR. I believe that if we configure the settings to synchronize the item's status based on the computer, the status should always be updated whenever the computer changes any value, even if it's not directly the status, right?

**Comment by trasher** [comment]
> the current fix lets all updates trigger the propagation of these fields (for ex, a change of user_id_tech propagates the status), and I'm not sure this is desired.

Reviewing this PR again along with original issue, and I agree this does not seems expected. Customer complains about issues when the status "changed"; therefore removing the check seems unnecessary.

Problem is we cannot reproduce the original issue; and it can just be a problem with existing data (we already have several problems with data from the old plugin - or data may have been changed by hand/by API/whatever).

**Comment by Rom1-B** [comment]
After an IRL discussion with @stonebuzz, I understand that the "When connecting or updating" only applies to the updated field and not the entire computer. In this case, we could make the label clearer by changing it to "When connecting or updating **the relevant field**".
What do you think?

**Comment by Rom1-B** [comment]
Replaced by https://github.com/glpi-project/glpi/pull/17990

**Pull request closed without merging**
