### PR TITLE
replace planning listYear by a 10years list

### PR DESCRIPTION
**Pull request by orthagh**
see #1281
see https://github.com/glpi-project/glpi/issues/758#issuecomment-253521264

### CODE REVIEW

**Comment by orthagh** [comment]
@tomolimo, when you'll have time, i need your review here

**Comment by tomolimo** [comment]
next Monday morning?

**Comment by orthagh** [comment]
perfect. It's not urgent, i target 9.1.2 for this.

**Comment by tomolimo** [comment]
Hello,

1. As I've a big DB, it takes too long to view the 'Your planning' on GLPi home page. During this time, browser is blocked.
1. I can see that 'done' tasks are not filtered-out. and what about past reminders?

Second point can be the cause of point 1

regards,
Tomolimo

**Comment by orthagh** [comment]
Right for 2, in this branches, list view now displays done events, i fixed that, could you pull and test again ?

**Comment by tomolimo** [comment]
For 'done' tasks it's ok,
but same problem with information notices:

image

and still a big problem of blocking IE10 when computing the planning:
image
during 15" IE10 is blocked doing javascript execution (probably computing the items to be shown): could it be a better idea to filter on server instead of inside browser?

**Comment by orthagh** [comment]
removed past events with status = INFO to gain load time.

Could you test again ?
If the delay is still very long (>5s), could you test to edit planning.class.php, l558 and l720, we have the 5years who could be reduced.

**Comment by tomolimo** [comment]
past information have disappeared from the list :)!
but still 15" to show in IE10 late tasks from 2014 up to today, so only 2 years in the past!!!
Tested also with chrome, it takes about 1", and in FF: about 2", there is a problem with javascript in IE10

**Comment by orthagh** [comment]
strange behavior on your IE, i tested this morning on my ie11 without noticing delay.
But my events list contains only 4 lines

**Comment by tomolimo** [comment]
In my tests, there are only 21 tasks 'to do'

**Comment by trasher** [comment]
What is the state of this one? Is it ready for review?

**Comment by orthagh** [comment]
i think yes.

@tomolimo mentionned performance issues on windows env but i didn't replicate.

**Comment by tomolimo** [comment]
for me it's also ok, perf will need to be tested further, but currently it's ok, I think we can merge

**Comment by trasher** [comment]
LGTM, but there are conflicts I'm not sure I'm able to resolve :) Please rebase ad squash ;)

**Comment by orthagh** [comment]
merge done

**Comment by orthagh** [comment]
or not, it seems i did some sh**

**Comment by trasher** [comment]
@tomolimo could you try this one again and tell us if this is still OK for you please?

**Comment by tomolimo** [comment]
I'm going to test this afternoon, thank you

**Comment by tomolimo** [comment]
Seems perfect to me :)
I didn't test performances, but for few tasks (~6) seems ok. Will see later for more :)
thank you,

**Pull request merged**
