### PR TITLE
Added cache suffix for TinyMCE

### LINKED ISSUE #3663: HTML code elements in the Notes field in GLPI 9.2.1 and after update for 9.2.2
Issue Started after updating GLPI 9.1.6 for 9.2.1 in November of 2017 and now in updating to 9.2.2

Some HTML elements appear in the Notes field, the problem comes from version 9.2.1 and maintained in version 9.2.2.

image

### PR DESCRIPTION
**Pull request by edgardmessias**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3663

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by trasher** [comment]
Should this one be closed? I don't know if the change impacts anything; I don't think so.

**Comment by edgardmessias** [comment]
This is util on version upgrade.

**Comment by edgardmessias** [comment]
Prevent cache of plugins of tiny mce on GLPI upgrade

**Comment by trasher** [comment]
OK, I'll merge this one as well ;)

**Pull request merged**
