### PR TITLE
reopen right now also based on [closed->assign]

### PR DESCRIPTION
**Pull request by orthagh**
in addition of [closed->new]

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2751

### CODE REVIEW

**Comment by tomolimo** [comment]
Now I've the 'reopen' button near the 'Closed' ticket status, but when I click on it, it switches to the 'Processing ticket' tab, but nothing more happens...
and no special error in the PHP error log

**Comment by orthagh** [comment]
add a new fonction Ticket::canReopen to factorise all checks

**Comment by tomolimo** [comment]
Still nothing happens in the timelime, no followup appears, as it should be?

**Comment by orthagh** [comment]
do you have the button by the way ?

**Comment by tomolimo** [comment]
yes:
image

but when I click on it, I get:
image

**Comment by orthagh** [comment]
ok, i'm currently searching about the _autoopen of followup form

**Comment by tomolimo** [comment]
I remember that this re-open mechanism was working at beginning of August

**Comment by tomolimo** [comment]
This time, I got the followup and was able to add a new fup with save as 'processing', but at the end I got a "You don't have the permission to perform this action", after a reload of the home page, I can see my ticket as "open":

image

**Comment by orthagh** [comment]
ok, one stop closer

**Pull request merged**
