### PR TITLE
Enable/Disable group notification on Ticket, Change and Problem

### PR DESCRIPTION
**Pull request by Aeto-J**
Add the possibility to enable or disable group notification for a specific group like users in ticket, change or problem

image
image

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Comment by Aeto-J** [comment]
Hello, does anyone have a solution for the tests which do not pass, it is due to the fact that i have to create new columns in 3 tables, perhaps i'm not doing the migration procedure correctly or something else

**Comment by ftoledo** [comment]
i like this feature.
Could it be added via rules if it can be decided that for a particular group to enable or disable notification?

**Comment by cedric-anne** [comment]
> Hello, does anyone have a solution for the tests which do not pass, it is due to the fact that i have to create new columns in 3 tables, perhaps i'm not doing the migration procedure correctly or something else

With #15997, the output would be more detailed.

**Comment by Aeto-J** [comment]
Hi,
I have a question. Do you have a timeline for when the changes from PR #15997 will be merged into the main branch? My PR is also targeting the main branch, and the tests are still failing.
Thank you

**Comment by cedric-anne** [comment]
> Hi, I have a question. Do you have a timeline for when the changes from PR #15997 will be merged into the main branch? My PR is also targeting the main branch, and the tests are still failing. Thank you

It has already been merged. You have to rebase your branch now.

**Comment by Aeto-J** [comment]
Hi,
I close the pullrequest because I made an error from the start in my branch and it repushed the commits that I didn't have in the branch, so I'm going to do a clean pull request again, sorry for the inconvenience

**Pull request closed without merging**
