### PR TITLE
fix(promote to ticket): empty fields for self-services

### PR DESCRIPTION
**Pull request by Rom1-B**
For self-services, "promote to ticket" is available (right = ticket creation), but the ticket form did not retrieve the data.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24167

### CODE REVIEW

**Comment by cedric-anne** [comment]
> For self-services, "promote to ticket" is available

Not sure that a such advance feature should be available on "simplified interface".

**Comment by cedric-anne** [comment]
> For self-services, "promote to ticket" is available

Not sure that a such advance feature should be available on "simplified interface".

**Comment by orthagh** [comment]
> Not sure that a such advance feature should be available on "simplified interface".

I had the same though yesterday, and talked about it with @Rom1-B
But the fact is the feature is already available in 9.5. So i don't know

**Comment by Rom1-B** [comment]
> > Not sure that a such advance feature should be available on "simplified interface".
> 
> I had the same though yesterday, and talked about it with @Rom1-B But the fact is the feature is already available in 9.5. So i don't know

The partner who reported the bug also thinks it's a good idea to remove the self-service action, especially since it didn't work in 9.5 either.

So, I will redo my PR

**Comment by orthagh** [comment]
> especially since it didn't work in 9.5 either.

Ah, this data was missing 2 days ago -> so agree to filter the feature on self-service interface

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Review by cconard96 — APPROVED** [review]

**Pull request merged**
