### PR TITLE
Add tags and display for plugins on GLPI External links

### PR DESCRIPTION
**Pull request by tsmr**
Add tags and display for plugins on GLPI External links : 

into plugins : 
Need add into setup.php : 
```
'link_types' => true into Plugin::registerClass
```
```
Link::registerTag(PluginExampleExample::$tags);
```
into plugin class : 
```
static $tags = '[EXAMPLE_NAME]';

and 

static function generateLinkContents($link, CommonDBTM $item) {

      if (strstr($link,"[EXAMPLE_NAME]")) {
         $link = str_replace("[EXAMPLE_NAME]", $item->getName(),$link);
         return array($link);
      }

      
      return parent::generateLinkContents($link, $item);
   }
```

### CODE REVIEW

**Comment by orthagh** [comment]
TY for this.

Could you add a linked PR in the example plugin : https://github.com/pluginsGLPI/example
For illustrate the implementation.

**Comment by orthagh** [comment]
Or commit directly, you now have the rights to example repository

**Comment by tsmr** [comment]
I have already do it :+1: 

https://github.com/pluginsGLPI/example/commit/285a86be4e4c9754ff337f9bf194390df653793a

**Comment by orthagh** [comment]
1da2ebb cherry-picked to avoid insertion of 314d7a9 in the same pr

**Pull request closed without merging**
