### PR TITLE
User synchro: remove double escaping for manager field

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Internal ref: 19550.

When synchronizing an user, the value used to search for his manager was escaped twice.
If the manager DN contained any escaped chars like `\` it would then never be found.

First escaping in `User::getFromLDAP()`  
```php
$val = Toolbox::addslashes_deep($val);
```
Second escaping in `User::getIdByField()`
```php
$iterator = $DB->request([
         'SELECT' => 'id',
         'FROM'   => self::getTable(),
         'WHERE'  => [$field => addslashes($value)]
]);
```

I've removed the second escaping for this specific case and kept it as a default parameter for the function since it is used in others places that may need the escaping.

----

Concrete example:

Manager DN to search for: `cn=Clairembault\2C Adrien,cn=abcd,dc=nodomain`
-> `\2C` is an encoded coma here, the displayed CN in the LDAP is `Clairembault, Adrien`

With double escaping, we end up doing this request which will never find anything:
```sql
SELECT `id`
FROM `glpi_users`
WHERE `user_dn` = 'cn=Clairembault\\\\2C Adrien,cn=abcd,dc=nodomain'
```

---

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by trasher** [comment]
I guess a better solution would be to fix encoding coming from ldap, what is that kind of encoding?

By the way, it would be usefull to add tests cases with you case, `'`, etc.

**Comment by AdrienClairembault** [comment]
I've updated the description to be more precise, there should be no SQL injections since values are still escaped (but only once).

**Comment by trasher** [comment]
> > Wait... No. If there are some values that should be escaped in the name, this will open a SQL injection possibility (and query will fail anyways)
> 
> I've updated the description to be more precise, there should be no SQL injections since values are still escaped (but only once).

Oh, OK, yes, it's exploicitely called on the value passed, did not see this. Just look if a test case with your issue can be added then and it's ok for me ;)

**Comment by AdrienClairembault** [comment]
> I guess a better solution would be to fix encoding coming from ldap, what is that kind of encoding?

For the encoding, it seems consistent with ldap_escape so it should be standard: 
```sh
php > echo ldap_escape(',');
\2c
```

**Comment by AdrienClairembault** [comment]
> > > Wait... No. If there are some values that should be escaped in the name, this will open a SQL injection possibility (and query will fail anyways)
> > 
> > 
> > I've updated the description to be more precise, there should be no SQL injections since values are still escaped (but only once).
> 
> Oh, OK, yes, it's exploicitely called on the value passed, did not see this. Just look if a test case with your issue can be added then and it's ok for me ;)

Ok, working on the test then.

**Comment by trasher** [comment]
> > I guess a better solution would be to fix encoding coming from ldap, what is that kind of encoding?
> 
> For the encoding, it seems consistent with ldap_escape so it must be standard:
> 
> ```shell
> php > echo ldap_escape(',');
> \2c
> ```

Good to know, thank you :)

**Pull request merged**
