### PR TITLE
decode entity_restrict in users dropdown

### LINKED ISSUE #1086: Search engine for ticket actors
http://forum.glpi-project.org/viewtopic.php?id=155498

### PR DESCRIPTION
**Pull request by orthagh**
fix #1086

### CODE REVIEW

**Comment by trasher** [comment]
Should not these PR be merged back to 9.1/bugfixes?

**Comment by orthagh** [comment]
Yes, i labelled it 'need_cherrypick' to warn about this.
I not sure what was the decision about cherry picks : 
- pr on master and cp bugfixes 
- pr on bugfixes and cp on master

**Comment by ddurieux** [comment]
Prefer pr on master and cp bugfixes

**Comment by trasher** [comment]
Well... I've begin to write a doc that should statue on those cases... :p

A fix should be done on the bugfix branch, and be merged back to the bugfix.

Working on master and cherry-pick on bugfixes may introduce master code in bugfix branch, that _must_ be avoided.

**Comment by orthagh** [comment]
Ok, i'll do it next time

**Comment by trasher** [comment]
Why wait? :p You'll just have to rebase on the correct branch and change destination in the PR. Anyways, you'll have to rebase since GH says that your branch is out of date.

**Comment by orthagh** [comment]
Done

**Comment by trasher** [comment]
Great, thanks! Feel free to merge and cherry pick if you wish; I won't be able to do until this evening

**Pull request merged**
