### PR TITLE
Use dropdown limit option for actor fields

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12520

Limit the results for the user search query to the `dropdown_max` config option instead of being unlimited to improve performance in cases where a lot of users could be matched.

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Review by orthagh — CHANGES_REQUESTED** [review]
It's my bad to forgot about pagination of select2 in actors fields.
But, I'm not sure about the choice you made to force the limit on the first page only.

Regarding https://select2.org/data-sources/ajax#pagination
You can pass a `page` param to the ajax query and it should answer with a `"pagination": {"more": true}` if there is still data to load. So on scrolling the dropdown, an ajax query is send to load each page, but you can still scroll the entire list.

Also as new actor fields are a aggregated one for User/Group/Supplier, you don't want to splice the data on each but rather on the final array `$results` in `getDropdownActors`. 

I don't know if we can have good performance this way. Is the bottleneck on javascript or php side ? If the later, we can also try to cache data.

**Comment by cconard96** [comment]
I added some profiling to `getDropdownActors`. With a users table with 16,000 records and the limit set to -1 again:
Call to `User::getSqlSearchResult` took around 700ms.
Call to `Dropdown::getDropdownActors` took a total of 1120ms.
The full time taken from 'ajax/actors.php' was only a few ms more.
The total request time according to Chrome's dev tools was over 8 seconds with around 2.8 MB transferred from the server.
This was when there were a lot of potential matches (most of my users are clones with the same name).

If there are very few matches, performance is a little better on the server side. However, the total request time was still over 5 seconds even though only 1 kb was transferred from the server.

**Comment by cconard96** [comment]
Adding the debounce from the other PR, reduces the total transfer time to 2.7 seconds. This seems to be because without it, the server gets AJAX requests after each key typed even though they would eventually be cancelled.
Re-adding the limit from this PR along with the debounce, reduces the total request time to 400ms and reduces the amount of data sent to the client.

**Comment by orthagh** [comment]
My guess (i didn't took the time) is php side is not the issue here (nor sql nor transfer), but rather the select2 lib receiving 20k+ options to render.
And that part could very slow. Chrome has some tools to checks function time in performance tab to check this assumption.
Debounce is also strongly required but i think we need to do more, and pagination can be a solution

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Comment by orthagh** [comment]
@cconard96 it's sufficient for the linked issue and simple enough to go to 10.0.3 directly.
But maybe, we can do a little better after merge (in another pr) if you want.
If the number of users is superior to the curernt page, maybe we can skip the query on groups and suppliers

**Comment by cedric-anne** [comment]
> @cconard96 it's sufficient for the linked issue and simple enough to go to 10.0.3 directly. But maybe, we can do a little better after merge (in another pr) if you want. If the number of users is superior to the current page, maybe we can skip the query on groups and suppliers

We can probably pass start/limit to `User::getSqlSearchResult()` also, and maybe also some computed limits to `Dropdown::getDropdownValue()` for groups and suppliers, but it may be a little tricky.

**Pull request merged**
