### PR TITLE
Add gettext.js for client side translations

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Add gettext.js for client side translations (only for core translations).
1. ~~Translations files are build during webpack build.~~ Translations are loaded from `$TRANSLATOR` object, including overrides.
2. Translation are now extracted also from `js/*.js` files.

Usage:
```js
__('My text to translate');
  //alias of: i18n.__('My text to translate');
  //alias of: i18n.gettext('My text to translate');

_n('User', 'Users', users.length);
  //alias of: i18n._n('User', 'Users', users.length);
  //alias of: i18n.ngettext('User', 'Users', users.length);

_x('button', 'Click me!');
  //alias of: i18n._p('button', 'Click me!');
  //alias of: i18n.pgettext('button', 'Click me!');

_nx('button', 'A button', 'Many buttons', 2);
```

### CODE REVIEW

**Comment by orthagh** [comment]
Note, this is needed for #6459 
Maybe we could replace some parts in kanban also with this pr

ping @cconard96

**Comment by cconard96** [comment]
> Maybe we could replace some parts in kanban also with this pr

Yep. I'll take a look at this when I get home tonight.

**Comment by orthagh** [comment]
1st impressions:

- having same names for php and js could be easier to remember : `__(...)` and `_n(...)`
- we may have the need for `_x(...)` adn `_nx(...)` (contextual function)
- plugins are not handled for moment, maybe we don't need to have the support, i don't know

**Comment by orthagh** [comment]
ping @AdrienClairembault

**Comment by cedric-anne** [comment]
> * having same names for php and js could be easier to remember : `__(...)` and `_n(...)`

Done.

> * we may have the need for `_x(...)` adn `_nx(...)` (contextual function)

Done.

> * plugins are not handled for moment, maybe we don't need to have the support, i don't know

Done. If `public/locales/{$locale}.json` file esxists in the plugin dir, it will be loaded.
A documentation about that should be done if this is OK for everyone.

**Comment by cedric-anne** [comment]
3 commits.

1. translation functions;
2. replacement of custom translation system in Kanban feature;
2. replacement of custom translation system in Impact feature.

**Pull request merged**
