### PR TITLE
Feature/phpunit 4

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no :(
| Fixed tickets | #number

### CODE REVIEW

**Comment by trasher** [comment]
As usual, some tests are failing only when ran within the whole suite; but works per class...

I do not reproduce Search fails locally; but I have another issue (sql syntax error in a query).

**Comment by AdrienClairembault** [comment]
There is also one million warning about "Session ini settings cannot be changed after headers have already been sent".
We had the same issue on main and it was fixed by removing the output of the `loadDataset` function (https://github.com/glpi-project/glpi/pull/17532/files#diff-6d7384b59e2c2f0b69510fbff7fb05a82bf4c8b479d80c2b2c4ed0d2bd2fadfc).

**Comment by trasher** [comment]
Looks like the `SessionTest` cause issues after it has been ran; but currently have no idea why... Session is reset from the `DbTestCase::setUp()` method so everything should be OK.

**Comment by trasher** [comment]
> There is also one million warning about "Session ini settings cannot be changed after headers have already been sent". We had the same issue on main and it was fixed by removing the output of the `loadDataset` function (https://github.com/glpi-project/glpi/pull/17532/files#diff-6d7384b59e2c2f0b69510fbff7fb05a82bf4c8b479d80c2b2c4ed0d2bd2fadfc).

I've already tried (just did right now to be 100% sure): that does not fix.

On my local instance, removing the `SessionTest` file fix all those issues; so it does not seems related with what `loadDataset()` does in any way.

 I already have that "headers have already been sent" issue several times since I began phpunit migration; removing output from `loadDataset()` has in facts never been a fix (most of the time an output is anyway done elsewhere in phpunit framework).

**Comment by trasher** [comment]
> You should maybe keep a backup of the `SessionTest` file and rollbak it on the current PR if that permits to validate and merge all other migrations quickly.

Yes, that was my intention if I cannot find what's wrong :/

**Comment by trasher** [comment]
There is one issue left: Crontask test fails if database has just been installed; but works on a second run. If I remove the bootstrap data for Plugin, it always fails oO

**Review by orthagh — APPROVED** [review]

**Review by AdrienClairembault — APPROVED** [review]

**Pull request merged**
