### PR TITLE
api: add ip adresses to with_networkports option

### PR DESCRIPTION
**Pull request by orthagh**
Here is an example: 

```
http://.../apirest.php/Computer/71?with_networkports=true
{
	"id": 71,
	"entities_id": 0,
	"name": "adelaunay-ThinkPad-Edge-E320",
	"serial": "LR9NKZ7",
	"otherserial": "test2qsdq",
	"contact": "adelaunay",
	"contact_num": "qds",
	"users_id_tech": 0,
	"groups_id_tech": 0,
	"comment": "test222222qsdqsd",
	"date_mod": "2016-06-30 15:03:59",
	"operatingsystems_id": 32,
	"operatingsystemversions_id": 48,
	"operatingsystemservicepacks_id": 0,
	"os_license_number": null,
	"os_licenseid": null,
	"os_kernel_version": null,
	"autoupdatesystems_id": 0,
	"locations_id": 3,
	"domains_id": 18,
	"networks_id": 0,
	"computermodels_id": 11,
	"computertypes_id": 3,
	"is_template": 0,
	"template_name": null,
	"manufacturers_id": 260,
	"is_deleted": 0,
	"is_dynamic": 1,
	"users_id": 0,
	"groups_id": 0,
	"states_id": 1,
	"ticket_tco": 0,
	"uuid": "725BA801-507B-11CB-95E6-C66052AAC597",
	"date_creation": null,
	"is_recursive": 0,
	"operatingsystemarchitectures_id": null,
	"_networkports": {
		"NetworkPortEthernet": [
			{
				"entities_id": 0,
				"is_recursive": 0,
				"logical_number": 1,
				"name": "Intel(R) Ethernet Connection I217-LM",
				"mac": "40:a8:f0:60:e3:33",
				"comment": null,
				"is_dynamic": 1,
				"id": 156,
				"networkports_id": 404,
				"items_devicenetworkcards_id": 0,
				"netpoints_id": 0,
				"type": "",
				"speed": 0,
				"date_mod": "2016-09-19 15:28:31",
				"date_creation": "2016-09-19 15:28:31",
				"ip": "10.2.41.127",
				"links": [
					{
						"rel": "Entity",
						"href": "http://localhost/glpi/0.91-git/apirest.php/Entity/0"
					},
					{
						"rel": "NetworkPort",
						"href": "http://localhost/glpi/0.91-git/apirest.php/NetworkPort/404"
					}
				]
			}
		],
...
```

### CODE REVIEW

**Comment by orthagh** [comment]
not ready to merge, we have a problem with aggregation of ip adresses

**Comment by orthagh** [comment]
yes, will do tomorrow

**Comment by axlroden** [comment]
Output looks correct now :)

might be useful to have on /networkPort/:id as well

`{
  "id": 3,
  "entities_id": 1,
  "name": "thor_ac_hotel_porto_maravilha",
  "serial": "ZM161S010625",
  "otherserial": "To Be Filled By O.E.M.",
  "contact": "root",
  "contact_num": null,
  "users_id_tech": 0,
  "groups_id_tech": 0,
  "comment": null,
  "date_mod": "2016-09-16 13:05:09",
  "operatingsystems_id": -1,
  "operatingsystemversions_id": -1,
  "operatingsystemservicepacks_id": -1,
  "os_license_number": null,
  "os_licenseid": null,
  "autoupdatesystems_id": 0,
  "locations_id": 1,
  "domains_id": 0,
  "networks_id": 0,
  "computermodels_id": 2,
  "computertypes_id": 2,
  "is_template": 0,
  "template_name": null,
  "manufacturers_id": 1,
  "is_deleted": 0,
  "is_dynamic": 1,
  "users_id": 0,
  "groups_id": 0,
  "states_id": 0,
  "ticket_tco": 0,
  "uuid": "00000000-0000-0000-0000-0CC47AC1A76A",
  "os_kernel_version": null,
  "operatingsystemarchitectures_id": 0,
  "date_creation": "2016-09-16 13:05:09",
  "is_recursive": 0,
  "_networkports": {
    "NetworkPortEthernet": [
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 1,
        "name": "bmc",
        "mac": "0c:c4:7a:c1:a0:b3",
        "comment": null,
        "is_dynamic": 1,
        "id": 24,
        "networkports_id": 819,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "200.186.51.134",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/819"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "lo",
        "mac": "00:00:00:00:00:00",
        "comment": null,
        "is_dynamic": 1,
        "id": 25,
        "networkports_id": 820,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "127.0.0.1,::1",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/820"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 1,
        "name": "eth1",
        "mac": "0c:c4:7a:c1:a7:6b",
        "comment": null,
        "is_dynamic": 1,
        "id": 26,
        "networkports_id": 821,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 1000,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::ec4:7aff:fec1:a76b",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/821"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 1,
        "name": "eth0",
        "mac": "0c:c4:7a:c1:a7:6a",
        "comment": null,
        "is_dynamic": 1,
        "id": 27,
        "networkports_id": 822,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 1000,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::ec4:7aff:fec1:a76a,200.186.51.133",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/822"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "thor0",
        "mac": "f6:44:f0:49:80:d5",
        "comment": null,
        "is_dynamic": 1,
        "id": 28,
        "networkports_id": 823,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::f444:f0ff:fe49:80d5,1.1.1.1",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/823"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "eth1.1000@eth1",
        "mac": "0c:c4:7a:c1:a7:6b",
        "comment": null,
        "is_dynamic": 1,
        "id": 29,
        "networkports_id": 827,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::ec4:7aff:fec1:a76b",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/827"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "br0",
        "mac": "0c:c4:7a:c1:a7:6b",
        "comment": null,
        "is_dynamic": 1,
        "id": 30,
        "networkports_id": 828,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::ec4:7aff:fec1:a76b,172.20.0.1",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/828"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "eth1.105",
        "mac": "0c:c4:7a:c1:a7:6b",
        "comment": null,
        "is_dynamic": 1,
        "id": 31,
        "networkports_id": 829,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 1000,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "10.181.219.66",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/829"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "eth1.105@eth1",
        "mac": "0c:c4:7a:c1:a7:6b",
        "comment": null,
        "is_dynamic": 1,
        "id": 32,
        "networkports_id": 830,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::ec4:7aff:fec1:a76b",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/830"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "eth1.1016@eth1",
        "mac": "0c:c4:7a:c1:a7:6b",
        "comment": null,
        "is_dynamic": 1,
        "id": 33,
        "networkports_id": 831,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::ec4:7aff:fec1:a76b",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/831"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "eth1.1001@eth1",
        "mac": "0c:c4:7a:c1:a7:6b",
        "comment": null,
        "is_dynamic": 1,
        "id": 34,
        "networkports_id": 832,
        "items_devicenetworkcards_id": 0,
        "netpoints_id": 0,
        "type": "",
        "speed": 10,
        "date_mod": "2016-09-16 13:05:09",
        "date_creation": "2016-09-16 13:05:09",
        "ip": "fe80::ec4:7aff:fec1:a76b",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          },
          {
            "rel": "NetworkPort",
            "href": "http://172.16.3.10/glpi/api/NetworkPort/832"
          }
        ]
      }
    ],
    "NetworkPortLocal": [
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "tun1",
        "mac": "",
        "comment": null,
        "is_dynamic": 1,
        "id": null,
        "networkports_id": null,
        "date_mod": null,
        "date_creation": null,
        "ip": "fe80::8d35:d009:e2fe:93bd,10.17.0.97",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "tun2",
        "mac": "",
        "comment": null,
        "is_dynamic": 1,
        "id": null,
        "networkports_id": null,
        "date_mod": null,
        "date_creation": null,
        "ip": "fe80::4fe0:ee7d:7a50:a3bb,10.13.0.146",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          }
        ]
      },
      {
        "entities_id": 1,
        "is_recursive": 0,
        "logical_number": 0,
        "name": "tun0",
        "mac": "",
        "comment": null,
        "is_dynamic": 1,
        "id": null,
        "networkports_id": null,
        "date_mod": null,
        "date_creation": null,
        "ip": "fe80::7f10:b93a:ae62:2aac,10.11.1.154",
        "links": [
          {
            "rel": "Entity",
            "href": "http://172.16.3.10/glpi/api/Entity/1"
          }
        ]
      }
    ]
  },
  "links": [
    {
      "rel": "Entity",
      "href": "http://172.16.3.10/glpi/api/Entity/1"
    },
    {
      "rel": "OperatingSystem",
      "href": "http://172.16.3.10/glpi/api/OperatingSystem/-1"
    },
    {
      "rel": "OperatingSystemVersion",
      "href": "http://172.16.3.10/glpi/api/OperatingSystemVersion/-1"
    },
    {
      "rel": "OperatingSystemServicePack",
      "href": "http://172.16.3.10/glpi/api/OperatingSystemServicePack/-1"
    },
    {
      "rel": "Location",
      "href": "http://172.16.3.10/glpi/api/Location/1"
    },
    {
      "rel": "ComputerModel",
      "href": "http://172.16.3.10/glpi/api/ComputerModel/2"
    },
    {
      "rel": "ComputerType",
      "href": "http://172.16.3.10/glpi/api/ComputerType/2"
    },
    {
      "rel": "Manufacturer",
      "href": "http://172.16.3.10/glpi/api/Manufacturer/1"
    },
    {
      "rel": "ReservationItem",
      "href": "http://172.16.3.10/glpi/api/Computer/3/ReservationItem/"
    },
    {
      "rel": "Document_Item",
      "href": "http://172.16.3.10/glpi/api/Computer/3/Document_Item/"
    },
    {
      "rel": "Contract_Item",
      "href": "http://172.16.3.10/glpi/api/Computer/3/Contract_Item/"
    },
    {
      "rel": "Infocom",
      "href": "http://172.16.3.10/glpi/api/Computer/3/Infocom/"
    },
    {
      "rel": "Item_Ticket",
      "href": "http://172.16.3.10/glpi/api/Computer/3/Item_Ticket/"
    },
    {
      "rel": "Item_Project",
      "href": "http://172.16.3.10/glpi/api/Computer/3/Item_Project/"
    },
    {
      "rel": "NetworkPort",
      "href": "http://172.16.3.10/glpi/api/Computer/3/NetworkPort/"
    },
    {
      "rel": "DeviceMotherboard",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceMotherboard/"
    },
    {
      "rel": "DeviceProcessor",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceProcessor/"
    },
    {
      "rel": "DeviceMemory",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceMemory/"
    },
    {
      "rel": "DeviceHardDrive",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceHardDrive/"
    },
    {
      "rel": "DeviceNetworkCard",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceNetworkCard/"
    },
    {
      "rel": "DeviceDrive",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceDrive/"
    },
    {
      "rel": "DeviceControl",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceControl/"
    },
    {
      "rel": "DeviceGraphicCard",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceGraphicCard/"
    },
    {
      "rel": "DeviceSoundCard",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceSoundCard/"
    },
    {
      "rel": "DevicePci",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DevicePci/"
    },
    {
      "rel": "DeviceCase",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DeviceCase/"
    },
    {
      "rel": "DevicePowerSupply",
      "href": "http://172.16.3.10/glpi/api/Computer/3/DevicePowerSupply/"
    }
  ]
}`

**Comment by orthagh** [comment]
@trasher, here is the tests for networkports

I had to change some code in networkport.[class/form].php, the part for adding ipaddress was in the .form file. I think it's not a good way, i change this parts into prepare/post add/update functions to be consistent (and to permit to add ipaddresses with ports also with api)

I also added a new function to clean input api, in some cases, i retrieved the data with stdobject type.

**Comment by trasher** [comment]
Looks good to me; I'd like another review, even if @axlroden validates it solves the issue for its usage; I'm not very familiar with all those changes - and I can't actually say if something is missing in the tests suite or not :)

Oh, another point... Could you please add minimal phpdoc at least on new methods you've added? ;)

**Comment by orthagh** [comment]
Done for docblock

**Comment by behinddesign** [comment]
Very useful change, however by combining the IPs into a single coma delimited string you've lost the ability to provide other useful information relating to the IP side of things. From the database you've a field for IPv6 flag, network addresses, netmasks and gateways.

Consider the endpoint as a whole, you're adding the 'include' for network ports, but not responding with half of the critical network information most likely required in association with the ports.

**Comment by orthagh** [comment]
You're right @behinddesign.
We still can enhance this part.

In fact, i could provide full NetworkName for each Networkport including:
- name
- ipadresse**s**
- ipnetworks
- domain (fqdn)

**Comment by orthagh** [comment]
Here is the reworked key '_networkports':

```json
"_networkports": {
   "NetworkPortEthernet": [
      {
         "networkports_id": 36045,
         "entities_id": 1,
         "is_recursive": 0,
         "logical_number": 0,
         "name": "Miniport d'ordonnancement de paquets",
         "mac": "ac:c3:20:52:41:53",
         "comment": null,
         "is_dynamic": 1,
         "id": 158,
         "items_devicenetworkcards_id": 0,
         "netpoints_id": 0,
         "type": "",
         "speed": 0,
         "date_mod": "2016-09-20 15:51:30",
         "date_creation": "2016-09-20 15:51:30",
         "NetworkName": {
            "id": 321143,
            "name": "",
            "fqdns_id": 0,
            "ipnet": null,
            "FQDN": {
               "id": 0,
               "name": null,
               "fqdn": null
            },
            "IPAddress": [
               {
                  "id": 192512,
                  "name": "10.0.1.6",
                  "IPNetwork": [
                     {
                        "id": 19,
                        "completename": "10.0.1.0/255.255.255.0 - 10.0.1.1",
                        "name": "10.0.1.0/255.255.255.0 - 10.0.1.1",
                        "address": "10.0.1.0",
                        "netmask": "255.255.255.0",
                        "gateway": "10.0.1.1",
                        "ipnetworks_id": 0,
                        "comment": null
                     }
                  ]
               },
               {
                  "id": 192513,
                  "name": "10.0.1.7",
                  "IPNetwork": [
                     {
                        "id": 19,
                        "completename": "10.0.1.0/255.255.255.0 - 10.0.1.1",
                        "name": "10.0.1.0/255.255.255.0 - 10.0.1.1",
                        "address": "10.0.1.0",
                        "netmask": "255.255.255.0",
                        "gateway": "10.0.1.1",
                        "ipnetworks_id": 0,
                        "comment": null
                     }
                  ]
               }
            ]
         },
         "links": [
            {
               "rel": "NetworkPort",
               "href": "http://localhost/glpi/0.91-git/apirest.php/NetworkPort/36045"
            },
            {
               "rel": "Entity",
               "href": "http://localhost/glpi/0.91-git/apirest.php/Entity/1"
            }
         ]
      }
   ]
}
```

I need to enhance test to match theses changes and i'll commit

**Comment by behinddesign** [comment]
This is definitely a step in the right directly, perfect. Thanks for your time.

**Comment by orthagh** [comment]
done

**Pull request merged**
