### PR TITLE
Create link to standard phpstan config file if not present

### PR DESCRIPTION
**Pull request by trasher**
## Checklist before requesting a review

Create link to standard phpstan config file if not present

### CODE REVIEW

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
I don't know, not sure if we want to include this kind of code related to a dev environment feature into the console bin that will be used in production :/

For example, it could break the console if the `.dist` file does not exist in production.

If the need is to run your own config, I would prefer an `.example` file that developers can manually copy if they need to use it (as it was proposed in 3a29386781033b07d785aecd7473699bbbc76f93).

Also note that you do not need a full copy of the file content as phpstan support an `includes` directive.

**Comment by AdrienClairembault** [comment]
I've just seen your comment in our internal chat saying this is phpstorm related.

In this case maybe we could add the default phpstan.neon file to the repository with only the `includes` directive, then .gitignore it to not take any update into account ?

**Comment by trasher** [comment]
> I don't know, not sure if we want to include this kind of code related to a dev environment feature into the console bin that will be used in production :/

It's inside "depdencies install" command, which should not be used in production.

> In this case maybe we could add the default phpstan.neon file to the repository with only the `includes` directive, then .gitignore it to not take any update into account ?

I did not know about the includes directive. If that works, it's ok for me (I just want to stop having to create myself a copy/symlink several times each day)

**Comment by cconard96** [comment]
I don't see any error in PHPStorm from this. What version are you using?

**Comment by trasher** [comment]
> add the default phpstan.neon file to the repository with only the `includes` directive, then .gitignore it to not take any update into account ?

Done that way. Was already part of gitignore file.

**Review by orthagh — APPROVED** [review]

**Comment by trasher** [comment]
> I don't see any error in PHPStorm from this. What version are you using?

2024.2.3

Just removing .neon file:
image

Settings only allows to define executable path; more options allows to ignore or mute until restart.

**Comment by cconard96** [comment]
> > I don't see any error in PHPStorm from this. What version are you using?
> 
> 2024.2.3
> 
> Just removing .neon file: image
> 
> Settings only allows to define executable path; more options allows to ignore or mute until restart.

It seems at some point I manually changed the config file path in the settings. I don't really have any reason to switch to a 10.0 branch anymore. There is also the option to mute the error until the next restart.

Is there any reason the file is still named differently on 10.0/bugfixes. Seems better just to make the name match in both.

**Comment by trasher** [comment]
> Is there any reason the file is still named differently on 10.0/bugfixes? 

No; PR to add the .dist was just done on main only (maybe because we all work more on main branch than 10.0 one). With current proposal and includes directive, all will be fine - and no need to change config.

**Review by AdrienClairembault — APPROVED** [review]

**Pull request merged**
