### PR TITLE
feat(inventory): ability to import multiple inventory files

### PR DESCRIPTION
**Pull request by flegastelois**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A

### CODE REVIEW

**Comment by flegastelois** [comment]
This PR is currently in draft because:
- "displayImportFile" (which manages the multiple files and display a new result page) is a temporary copy of "importFile" (which display "addMessageAfterRedirect" and which returns "Request")
- I modified the "importContentFile" method to remove the "addMessageAfterRedirect" displays and instead have a "return" of Requests
- there is however an automated test (legitimate) which checks after the import if "File has been successfully imported!" is in session

What is the best solution ?

**Comment by cedric-anne** [comment]
> This PR is currently in draft because:
> 
> * "displayImportFile" (which manages the multiple files and display a new result page) is a temporary copy of "importFile" (which display "addMessageAfterRedirect" and which returns "Request")
> * I modified the "importContentFile" method to remove the "addMessageAfterRedirect" displays and instead have a "return" of Requests
> * there is however an automated test (legitimate) which checks after the import if "File has been successfully imported!" is in session
> 
> What is the best solution ?

Best solution is probably to split logic.

1. One method to import a list of files, that takes an array of file path as parameter (e.g. `['/path/to/computer1.xml', '/path/to/computer2.xml']`) and that returns the result of operations (e.g. `['/path/to/computer1.xml' => ['success' => true, 'message' => 'File has been successfully imported!', 'asset' => (Computer object)], '/path/to/computer2.xml' => ['success' => false, 'message' => 'It fails, blablabla', 'asset' => null]]`.
2. One method that transforms the request into a path of inventory files, then executes the import, then call the view renderer with results.

With such splitted logic, you would just avec to test the method from point 1.

**Review by stonebuzz — APPROVED** [review]
Seems good to me :+1: 

we could possibly add a progress bar (in the case of a large archive)
(maybe in another PR)

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
As asked on our private channel, I guess this one could target 10.0/bf.

**Pull request closed without merging**
