### PR TITLE
Drop methods that should have been deprecated and aht should no be us…

### PR DESCRIPTION
**Pull request by trasher**
…ed at all now

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no (not in the core)
| Deprecations? | yes (kind of)
| Tests pass?   | yes

This may break plugins; but they should have been updated. Without methods, users will raise an real error (instead of an empty page without logs).

### CODE REVIEW

**Comment by trasher** [comment]
I'm not going to merge that one right now; because some plugins still use some of those methods... As far a I can see (greppin' from my plugins dir):
* formcreator,
* fusioninventory-for-glpi (verified :/),
* simcard,
* geninventorynumber.

I've njot yet checked if they really use the dropped methods for the core or if they redefine their own.

**Comment by orthagh** [comment]
+ accounts
+ racks
+ monitoring
+ order (some commented)

**Comment by trasher** [comment]
I've reported the issue on every identified plugin.

**Comment by yllen** [comment]
If you deletd functions, don't forget to add them in wiki of the plugin, like https://forge.glpi-project.org/projects/plugins/wiki/Fr_Plugin083to084

**Comment by yllen** [comment]
You can't indicate a function deprecated if this function is already used in the core.
You must change all calls before (ex. function next())

**Comment by wawax** [comment]
Hi @yllen ,

We're currently finishing a brand new, complete, developer documentation at http://glpi-developer-documentation.readthedocs.io/en/master/ .
Adding a _deprecated functions_ page is, IMHO, the best place to do it.

Regards

**Comment by trasher** [comment]
I'll change `next()` calls to reflect the state; good catch.

As for methods depreciation; they're actually all referenced in the CHANGELOG.md file; we'll add them in a more complete documentation later, I'm missing time ;)

**Comment by remicollet** [comment]
> You must change all calls before (ex. function next())

See pr #1939

**Pull request merged**
