### PR TITLE
Date exceptions for recurrent events

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

image

Aditionnaly, i fixed some issues with timezones (some events didn't change in the planning regarding the user timezone)

### CODE REVIEW

**Comment by orthagh** [comment]
**Important**: Caldav server support is not done, @cedric-anne could you check if it's possible ?

**Comment by cedric-anne** [comment]
I saw this in error log.
```
[2019-11-18 14:42:47] glpiphplog.WARNING: Html::convDate() in /var/www/glpi/inc/html.class.php line 156
Invalid date 2019-11-13, 2019-11-16, 2019-11-24!  {"user":"2@4028a755e155"} 
```

**Comment by cedric-anne** [comment]
> **Important**: Caldav server support is not done, @cedric-anne could you check if it's possible ?

I quickly added support for this.

**Comment by orthagh** [comment]
:+1:

**Comment by cedric-anne** [comment]
2 bugs remaining.

1. The multipleDatePicker component does support the `altFormat` property (see https://github.com/dubrox/Multiple-Dates-Picker-for-jQuery-UI/blob/master/jquery-ui.multidatespicker.js#L449 ). Result values will be saved in DB using the display format, instead of `Y-m-d` format.

2. The RRule PHP lib uses datetime comparison for exclusions (see https://github.com/rlanvin/php-rrule/blob/master/src/RSet.php#L664). Result is that `Rset::getOccurrencesBetween()` will return events inside exclusion date (e.g. if EXDATE is `2019-12-01` and RRULE is `every day at 1pm`, the component will consider that `2019-12-01 13:00:00` is valid, as it is different from `2019-12-01 00:00:00`).
We use this feature when checking for user availability. It means that a message indicating that user has already a planned event may be displayed even if there is no occurence of any event conflicting with the new event we just created.

**Pull request merged**
