### PR TITLE
add template for pull requests

### PR DESCRIPTION
**Pull request by orthagh**
found here: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by trasher** [comment]
Since ticket reference should be don in commits messages; is it really relevant ot ask for it creating the PR?
Also, tests status are retrieved from travis; no need I guess to ask for that here (everybody knows almost nobody run tests before submitting a pr :p)

**Comment by tomolimo** [comment]
As far as I understand the Travis tests, they are not functional tests, but only syntax tests aren't they?
And most of the time, I'm doing extensive functional tests before doing a PR...
Regards,
Tomolimo

**Comment by trasher** [comment]
Travis checks coding standards, and alos run some functionnal tests with PHPUnit.

Indeed, I had in mind 'automated tests', not user tests.

**Comment by orthagh** [comment]
> Since ticket reference should be don in commits messages; is it really relevant ot ask for it creating the PR?
For me, yes, i'm in pain to retrieve ticket linked to a pr.
A ref into the pr is easy.

**Pull request merged**
