### PR TITLE
Make Domain_Item purgeable with the delete right

### PR DESCRIPTION
**Pull request by RomainLvr**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !35411
- Here is a brief description of what this PR does

To remove a relationship between two items (e.g., Domain -> Computer), the system currently requires purge rights on the source item (Domain in this case). This behavior is problematic because granting purge rights not only allows the removal of relationships but also permits the deletion of items themselves. This creates a security concern when the intent is solely to manage relationships without affecting the items involved.

## Screenshots (if appropriate):

image

image

### CODE REVIEW

**Comment by trasher** [comment]
Please fix tests

**Comment by RomainLvr** [comment]
> Please fix tests

@trasher The PR targets 10.0/bugfixes but the failed test is a main branch test. The error comes from `phpunit/functional/MassiveActionTest.php:743` but in 10.0/bugfixes this line doesn't exist.

**Comment by cedric-anne** [comment]
> > Please fix tests
> 
> @trasher The PR targets 10.0/bugfixes but the failed test is a main branch test. The error comes from `phpunit/functional/MassiveActionTest.php:743` but in 10.0/bugfixes this line doesn't exist.

I triggered a new test suite execution. I guess the previous execution has been started when the target branch was the `main` branch.

**Comment by RomainLvr** [comment]
> > > Please fix tests
> > 
> > 
> > @trasher The PR targets 10.0/bugfixes but the failed test is a main branch test. The error comes from `phpunit/functional/MassiveActionTest.php:743` but in 10.0/bugfixes this line doesn't exist.
> 
> I triggered a new test suite execution. I guess the previous execution has been started when the target branch was the `main` branch.

Thanks :+1:

**Review by stonebuzz — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by Rom1-B — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
