### PR TITLE
Improved cron re-scheduling computation

### PR DESCRIPTION
**Pull request by tomolimo**
Improved cron re-scheduling computation, by setting the real time for lastrun field, and by truncating it to last minute.

### CODE REVIEW

**Comment by remicollet** [comment]
I think, frequency accuracy have been fixed in https://github.com/glpi-project/glpi/commit/b5e943e1a71c55af78847802a39ec7c2777582ec

Keepting the start timestamp instead of the end timestamp seems not really a good idea for long running task, configured to run every minute...

**Comment by tomolimo** [comment]
Consider the following issue: #264

**Comment by remicollet** [comment]
Merged

**Comment by remicollet** [comment]
Make sense, thanks.

**Comment by tomolimo** [comment]
Thank you to you also,
regards,
Tomolimo

**Pull request closed without merging**
