### PR TITLE
More Rules UI Work

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Before:
Selection_327

After:
Selection_328

Before:
Selection_330

After:
Selection_331

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]
Seems technically OK. I made a quick test but I am not sure to have cover the whole changes.

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
Some small suggestions for the UI:


image
-> Shouldn't the icon and the title be on the same row ?

image
-> "AND"  is not aligned with its content (was aligned properly on the "before" screenshot). Also it is very far from the content (but that was already the case before).

image
-> Not related to the changes, but we could directly rename the "----" value by "All" (I think there is an existing option to specific the empty value label ?)

image
-> Not related to the changes, but Is "Post" the correct label to use here ? Doesn't seem right to me.

**Comment by cconard96** [comment]
> Not related to the changes, but Is "Post" the correct label to use here ? Doesn't seem right to me.

I'm not sure this label makes sense anywhere for users unless it makes sense to a UK English speaker. It can probably be globally replaced by "Execute".

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Could you please rebase to solve conflict?

**Pull request merged**
