### PR TITLE
Cartridge and Consumable Twig UI

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Twig UI and cleanup of Cartridge and Consumable code.

### CODE REVIEW

**Review by orthagh — COMMENTED** [review]
(note, it's worse on current main)

integration of search engine in consumables list in consumable item has broken UI
image

Not sure where the fixed height is set

**Comment by cconard96** [comment]
> (note, it's worse on current main)
> 
> integration of search engine in consumables list in consumable item has broken UI
> 
> Not sure where the fixed height is set

I didn't notice that issue because I didn't interact with the search results when I fixed the UI issue where they were appearing side-by-side. After all this work converting sublists to use the datatable template, this one case where it uses the full search results display with the controls feels very out of place. The "Queries log" tab for webhooks also uses the search result display but without controls so it fits in a little better.

The intent for consumables to have the search engine display was to allow exporting the results and control which columns are shown, but none of the other lists have this same functionality.

**Comment by orthagh** [comment]
> The intent for consumables to have the search engine display was to allow exporting the results and control which columns are shown, but none of the other lists have this same functionality.

We may add flags to keep only the export part.
I'm not sure it's that important to have full search controls here

**Comment by cconard96** [comment]
> Not sure where the fixed height is set

Actually, it seems less about a fixed height and more that there is only one result so the table is short and the search dropdown has an absolute position so the z-index doesn't apply/work.

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — COMMENTED** [review]
Seems technically OK.

**Pull request merged**
