### PR TITLE
Fix redirections when object url contains params

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/pluginsGLPI/genericobject/issues/179

### CODE REVIEW

**Comment by cedric-anne** [comment]
Method can be override by any object. For exemple, in the `genericobject` plugin, generated objects returns URL having a parameter. See https://github.com/pluginsGLPI/genericobject/blob/master/objects/generic.class.tpl.

**Comment by trasher** [comment]
Oh.. plugins :/ ok...

**Comment by trasher** [comment]
Looking at the plugin example, I do not really understand the need... `Toolbox::getItemTypeFormURL( get_parent_class() , $full)` should be enough, isn't it?

**Comment by cedric-anne** [comment]
Another solution could be, for this plugin, to redirect to a generated front file located into `files/_plugins` (which actually exists but is not used). It means that the plugin should write an `.htaccess` file in its own directory `files/_plugins/genericobject/front` to override the `Require all denied` rule applied to `files` directory.

**Comment by cedric-anne** [comment]
`Toolbox::manageRedirect()` statically uses the `Html::redirect()` which ends with an `exit()`. I cannot add an automatic test without changing a lot of things :(.

**Pull request merged**
