### PR TITLE
fix(inventory): prevent double 'Dropdown::import()' 

### PR DESCRIPTION
**Pull request by stonebuzz**
Alternative to https://github.com/glpi-project/glpi/pull/13634

Prevent double ```Dropdown::importExternal()```

Which generates ```Manufacturer``` and ```SoftwareCategory``` with numbers

The first from ```src/Inventry/Asset/Software.php``` (which returns an ID as value)

https://github.com/glpi-project/glpi/blob/56f60f6e62bc9094551a0c469cd104ceeb05011c/src/Inventory/Asset/Software.php#L155-L163

The second from  ```src/Inventry/Asset/Software.php``` (which import ID previously generated)
https://github.com/glpi-project/glpi/blob/56f60f6e62bc9094551a0c469cd104ceeb05011c/src/Inventory/Asset/InventoryAsset.php#L253

Or 
https://github.com/glpi-project/glpi/blob/56f60f6e62bc9094551a0c469cd104ceeb05011c/src/Inventory/Asset/InventoryAsset.php#L257

N.B:
Sometime a number is added as a ```Manufacturer```
In my case I have memories with a number in the ```MANUFACTURER``` XML node 
this case is therefore legitimate

```xml
    <MEMORIES>
      <CAPACITY>8192</CAPACITY>
      <CAPTION>ChannelA-DIMM0</CAPTION>
      <DESCRIPTION>DIMM</DESCRIPTION>
      <MANUFACTURER>1315</MANUFACTURER>
      <MODEL>BLT8G3D1608DT1TX0.</MODEL>
      <NUMSLOTS>1</NUMSLOTS>
      <SERIALNUMBER>A0154896</SERIALNUMBER>
      <SPEED>1600</SPEED>
      <TYPE>DDR3</TYPE>
    </MEMORIES>
```

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12933 #13459

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]
I am OK with this workaround, but for me, the most reliable solution would be to:

1. Store raw values in different keys (e.g. `$val->manufacturer` that would contain the raw value, and `$val->manufacturers_id` that would contains the ID, or null if import has not be done yet).
2. In `handleLinks`, parse all keys that validates `isForeignKeyField($key)`and, if value is null, call `Dropdown::importExternal()` based on raw key value.

With this kind of logic, it would not be possible anymore to mix raw values and IDs in the same property key.

I guess it has many impact on code, so I do not know if it is possible to do such a change in 10.0/bugfixes branch.

**Comment by cedric-anne** [comment]
Maybe it also fixes https://github.com/glpi-project/glpi/issues/12202.

**Comment by stonebuzz** [comment]
Work with

rule dictionnaries 

ex : assign another manufacturer
image

ex : assign another software category (
image

**Review by cedric-anne — DISMISSED** [review]

**Review by trasher — DISMISSED** [review]

**Comment by trasher** [comment]
I'm completely lost in PRs, issues and comments... Please add tests (or tell me how to be sure to reproduce all cases and I'll add tests myself).

**Comment by trasher** [comment]
As said on #13642; relying on `is_int()` sounds a very bad solution. 

Handling properly relations is kind of an headache because it's been modified since the original implementation, and not the better way (mostly my bad, but it's too late/complicated to change that now).

In inventory files logic, `*_id` must be the raw original value, and not any corresponding ID. Corresponding IDs are stored in `known_links` property array. This has been changed because it was almost impossible to properly deal with a mix of those values to get older bugs fixed.

I'm working on an alternative PR using "correct" logic.

**Comment by trasher** [comment]
> I'm working on an alternative PR using "correct" logic.

#13669

**Comment by stonebuzz** [comment]
I close in favor of https://github.com/glpi-project/glpi/pull/13669

**Pull request closed without merging**
