### PR TITLE
Allow to bypass some CommonITIL rights checks

### PR DESCRIPTION
**Pull request by AdrienClairembault**
I'm facing an issue with a plugin that is trying to add a group to a ticket through the `_groups_id_assign` special input.
It will not work from a self-service profile because of some rights checks done in the model.

Regarding the specific subject of rights checks being done in random parts of the model, it seems to me that it's a bad design as it can create unexpected behavior in some "low-level" code depending of which user is logged-in.
Users actions should definitely be limited by checks done in controllers, but once we reach the model layer we should be able to interact with the data without limitations (in my opinion).

To bypass this I've added a flag to manually disable some checks as needed.
The plugin can thus call `$ticket->disableRightChecks()` before calling `$ticket->update()` and the group will be added correctly.
It feels like a band-aid but I don't see any others solutions that would be less hacky (switching session, adding rights at runtime and removing them after, ...).

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24944

### CODE REVIEW

**Comment by trasher** [comment]
As I said on internal communication channel; I'm not fan of this solution. To me, allowing any plugin to easily bypass all rights checks applied on core is probably not a good idea.

**Comment by cedric-anne** [comment]
You could probably bypass this restriction by setting the value in `post_prepareadd` hook, that will act after `prepareInputForAdd`, but before `post_addItem` that is responsible of adding actors.

**Comment by AdrienClairembault** [comment]
It isn't possible as `post_prepareadd` won't trigger ticket rules.

**Comment by tomolimo** [comment]
Hello @AdrienClairembault 
You may trigger the rules from the `post_prepareadd` hook in the plugin.
I do that already in one of my plugins, after doing some modifications on a ticket, I call the ticket rules, to be sure that it will be business compliant.
Regards,
Tomolimo

**Pull request closed without merging**
