### PR TITLE
Fix asset form header alignment on small screens

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #16938

### CODE REVIEW

**Comment by trasher** [comment]
Just tested on my instance, with debug mode enabled and cache removed; this does not seems to be fixed (using Firefox, no idea if that matters).

Also, I have a display issue in manufacturers (probably due to another change).

image

**Comment by trasher** [comment]
>  (using Firefox, no idea if that matters).

Same with chromium.

**Comment by cedric-anne** [comment]
> Just tested on my instance, with debug mode enabled and cache removed; this does not seems to be fixed (using Firefox, no idea if that matters).
> 
> Also, I have a display issue in manufacturers (probably due to another change).
> 
> image

This is the only case corresponding to a `label` returned in `CommonDropdown::getAdditionalFields()` returns a HTML string. IMHO, `label` should never contains HTML. We should refactor this part, for instance by moving this small form in the `registeredIDChooser` case of `CommonDevice::displaySpecificTypeField()`. @cconard96 Could you fix it in another PR ?

**Comment by cconard96** [comment]
> > Just tested on my instance, with debug mode enabled and cache removed; this does not seems to be fixed (using Firefox, no idea if that matters).
> > Also, I have a display issue in manufacturers (probably due to another change).
> > image
> 
> This is the only case corresponding to a `label` returned in `CommonDropdown::getAdditionalFields()` returns a HTML string. IMHO, `label` should never contains HTML. We should refactor this part, for instance by moving this small form in the `registeredIDChooser` case of `CommonDevice::displaySpecificTypeField()`. @cconard96 Could you fix it in another PR ?

This was already fixed for devices in #17027. Its just a matter of looking for missed cases and replicating the fix.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
