### PR TITLE
fix right of update ticket

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2193

@AircraftRu, could you test the following change and indicate if it solve your issue with update right on ticket ?

### CODE REVIEW

**Comment by yllen** [comment]
You don't have right to update ticket but you can add a revert a ticket cost, you can add or revert an item linked (read rights only for item too), you can change ticket category, urgency).
For me this commit solve one problem intyroduce with https://github.com/glpi-project/glpi/commit/7d067bac7cba2fb3e9775923da0a75dfa1e0be5f#diff-007edb12589cf3c8df3121cd7b19028a
but there are still problems i listed

**Comment by orthagh** [comment]
@yllen the issue you mention seems to be already present in previous glpi versions.

Anyway, we can enhance this pr to fix theses additionnal.

**Comment by yllen** [comment]
@orthagh No the issue indicated is present since 9.1.3 with https://github.com/glpi-project/glpi/issues/876

**Comment by orthagh** [comment]
I disagree, juste tested with a 0.85.5 and a profile without update on ticket: I still can add items/costs/etc.

But like i said, i'll see if we fix this behavior

**Comment by yllen** [comment]
Tested in 0.85.5 and 0.90.5 => i can't change urgency or ticket category
In 9.1.3 i can

**Comment by orthagh** [comment]
- priority is on a specific right and you change yourself this behavior (see 8c9a4ab6)
- actually, i can't change category with the code of this pr, see this capture: 

image

**Comment by yllen** [comment]
I don't speak about priority but urgency
image

**Comment by orthagh** [comment]
Ok my error.
But as you can see in my screenshot, the current pull request fixes this issue.
Please test with it with this command:

```
git checkout -b orthagh-ticket_update_right 9.1/bugfixes
git pull https://github.com/orthagh/glpi.git ticket_update_right
```

In fact, with the current correction (and proposed commits), we stay only with the old issues on tabs.
Theses tabs rely on Ticket::canUpdateItem which finally call Ticket::canUpdate.
This last function check with an OR operator the following tickets rights:
- UPDATE
- ASSIGN
- STEAL
- OWN

My guess is this was done to permits assignment of actor but don't match really good with the need of the cost/items tabs.

The only solution i think, is to add a specific right for attribution and clean the Ticket::canUpdate of this Session::haveRightsOr.

What do you think ?

**Comment by yllen** [comment]
Another problem i see in your commit.
I can't update ticket, just create and read.
In a ticket already created, i can change description of the ticket even if i am not the author or the requester.

**Comment by orthagh** [comment]
@trasher just commit in the last minutes about that (in this pr).
See: https://github.com/glpi-project/glpi/pull/2196/commits/1e07d17545583f9e2eab609ec362471b15207d57

**Comment by yllen** [comment]
Problem still exists: i am the author of the ticket and i can't update description.

**Comment by trasher** [comment]
The issue I've fixed on description was only on the display; a textarea was displayed but the save button was not present during my tests ;)

**Comment by orthagh** [comment]
Ticket update - Use Cases without UPDATE right:

- Requester(s) (self-service or not) without UPDATE right can still update ticket general content (title/itilcat) if no task/fup added and if ticket is still in progress (not closed/solved)
- Adding sub items (Item_Ticket, Ticket_Cost) matches the previous statement
- Deleting sub items is (imo) based on the same behavior of adding items.
- Priority is on a dedicated right, if the first statement is not matched, if you CANPRIORITY, you should be able to change and save priority (without alter the rest of the ticket)
- Same for Assignement (technician's rights) is also on dedicated parts (OWN, STEAL, ASSIGN) and should not be prevented by first statement

I think the current branch state and commits reflect this list of need.

@yllen if you have some time, i'll appreciate your tests and review on this branch.
In my opinion, i think i achieved all the mandatory for previous issues.

**Comment by trasher** [comment]
Note: I've added unit tests (for update case right now); that needs to be rewrite for the master branch.

**Pull request merged**
