### PR TITLE
Fix #1032 implement a signal handler for cron task in CLI mode

### LINKED ISSUE #132: Problem of translation
http://forum.glpi-project.org/viewtopic.php?id=122160

I don't have right to translate en_GB
La traduction n'est pas correct dans le .po (termes ITIL à utiliser)

### LINKED ISSUE #1032: Properly exit of system cron when task is killed.
To avoid having task stalled in "running" state.

### PR DESCRIPTION
**Pull request by remicollet**
To test, add in  CronTask::cronLogs()

```
      Toolbox::logInFile('cron', "process ".posix_getpid()."\n");
      sleep(10);
```
And from command line

```
$ php front/cron.php --force logs&
[1] 2319
$ kill 2319
```

Should  trace:

```
2016-09-22 13:42:32 [@xx]
Externe #1 : Démarrage logs
2016-09-22 13:42:32 [@xx]
process 2319
2016-09-22 13:42:39 [@xx]
Action aborted
```

### CODE REVIEW

**Comment by trasher** [comment]
Guess you would reference ticket 1032 and not 132?

**Comment by remicollet** [comment]
@trasher indeed

**Comment by remicollet** [comment]
> Not related to this PR, but I'm wondering about lines 297 and 298; what is the prupose of the first one?
As documented in the comment ;)

The first is only there to trigger string retrieval for translation, while untranslated string is store in DB, will be translated before output, see https://github.com/glpi-project/glpi/blob/5c76246b7a0215f7c830ceeddcbbf9bb1cea0cca/inc/crontask.class.php#L1190

**Comment by trasher** [comment]
OK, thanks!

**Pull request merged**
