### PR TITLE
fix(treebrowse): sorting operation

### PR DESCRIPTION
**Pull request by Rom1-B**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !300072

In tree view mode, column sorting did not work.

On documents, for example:
image

### CODE REVIEW

**Review by stonebuzz — APPROVED** [review]

**Review by cedric-anne — CHANGES_REQUESTED** [review]
It works, but when the column names are clicked, it first send the ajax request and then reload the entire page. Only the search results should be reloaded, not the whole page.
Maybe @cconard96 could help to identify the issue.

**Review by cedric-anne — DISMISSED** [review]
With the latest commit, all items are shown when a sorting operation is made, instead of only displaying the items from the selected category.

**Comment by cconard96** [comment]
> It works, but when the column names are clicked, it first send the ajax request and then reload the entire page. Only the search results should be reloaded, not the whole page. Maybe @cconard96 could help to identify the issue.

I missed this review. I will check later today, but if the page reloads it is probably because the fluid search JS isn't loaded at all or there is a JS error when it tried refreshing the results (would be logged in the console).

**Comment by cconard96** [comment]
You need to output the updated content in `TreeBrowse::showBrowseView` directly during an update rather than outputting an inline script that makes another AJAX call. The content returned from the `ajax/search.php` call is missing a `search-card` element so it is determined to be an invalid response and the page reload fallback is being used.

Also, there may need to be some handling added for the `cat_id` parameter since it isn't currently sent to `ajax/search.php`.

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
Two issues on my side:
* If I change the category in the tree and click on search it reload the whole page
* If I search for a string then change category then the filter is not taken into account in the new category.

E2E tests in `main` are probably needed to make sure it stays working (and saves us time by avoiding to manually retest all the scenarios).

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
The search still seems to reload every two searches (but results are OK).
Not sure if we need to fix it or if it is acceptable.

If you select "without categories" and search something that doesn't return any result you get stuck on a loading indicator:

image

**Review by AdrienClairembault — APPROVED** [review]
There is still the reload issue but it might be hard to fix it properly without more changes that we may not want to risk doing on the bugfixes branch (as we have no E2E tests), so OK for me.

It can be fixed later in main (with tests added), I've added it to https://github.com/orgs/glpi-project/projects/16/views/1.

**Comment by cconard96** [comment]
I keep getting CSRF errors in the browse view from just the initial load so I cannot test the search or reload.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
