### PR TITLE
Add the menu item 'Ticket waiting for your approval' in ticket followup panel

### PR DESCRIPTION
**Pull request by Drimmwald**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

Issuse #3016

### CODE REVIEW

**Comment by edgardmessias** [comment]
See `TicketValidation::getNumberToValidate(Session::getLoginUserID());`

**Comment by Drimmwald** [comment]
I do not have much experience in development, tell me please what you mean.

**Comment by edgardmessias** [comment]
Replace

```php
           $query_waitapproval = "SELECT COUNT(DISTINCT `glpi_ticketvalidations`.`id`) AS COUNT
             FROM `glpi_ticketvalidations`
             WHERE `glpi_ticketvalidations`.`users_id_validate` = '".Session::getLoginUserID()."'";

           $result_waitapproval = $DB->fetch_assoc($DB->query($query_waitapproval));
           $number_waitapproval = $result_waitapproval['COUNT'];
```

with

```php
$number_waitapproval = TicketValidation::getNumberToValidate(Session::getLoginUserID());
```

**Comment by edgardmessias** [comment]
Remove this code:

```php
           $query_waitapproval = "SELECT COUNT(DISTINCT `glpi_ticketvalidations`.`id`) AS COUNT
             FROM `glpi_ticketvalidations`
             WHERE `glpi_ticketvalidations`.`users_id_validate` = '".Session::getLoginUserID()."'";

           $result_waitapproval = $DB->fetch_assoc($DB->query($query_waitapproval));
```

**Comment by orthagh** [comment]
Hello @Drimmwald 

Last thing before merging your proposal (it's very good).
You need to fix the two small coding standard reported by travis: https://travis-ci.org/glpi-project/glpi/jobs/295730705#L3031

After that, he will be good.

**Comment by orthagh** [comment]
Fixed the cs issues myself, this pr good to merge so

**Pull request merged**
