### PR TITLE
Fix category predefined field in ITIL templates

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15363

### CODE REVIEW

**Comment by trasher** [comment]
All the logic of applying predefined fields is UI side; I've not been able to add a test on that. 
It's working on my instance.

**Review by cedric-anne — COMMENTED** [review]
I do not really understand the method itself, it is a pain to understand (`$type` may be an integer `INCIDENT_TYPE/DEMAND_TYPE`, `null`, or `true`), but the previous affectation seems OK to me.
As far as I understand, we just want to check if the template loaded previously assigns a new type/category, and, in this case, try to see if there is a better template to use. You change just seems to disable this behaviour (unless the template itself defines a type), and I do not know if it is correct.
Maybe an alternative solution could be:
```diff
diff --git a/src/CommonITILObject.php b/src/CommonITILObject.php
index 579b388b75..8885e1dc27 100644
--- a/src/CommonITILObject.php
+++ b/src/CommonITILObject.php
@@ -7656,8 +7656,8 @@ abstract class CommonITILObject extends CommonDBTM
                 $newtype = $tt->predefined['type'];
             }
             if (
-                $newtype
-                && $newitilcategories_id
+                $newtype != $type
+                && $newitilcategories_id != $itilcategories_id
             ) {
                 $categ = new ITILCategory();
                 if ($categ->getFromDB($newitilcategories_id)) {
```

**Comment by trasher** [comment]
Alternative solution may indeed be correct; but I do not really understand the whole code :/

**Comment by trasher** [comment]
@orthagh an opinion?

**Comment by trasher** [comment]
> @orthagh an opinion?

ping?

**Pull request closed without merging**
