### PR TITLE
Fixed line break display for content of ticket

### PR DESCRIPTION
**Pull request by edgardmessias**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3712

### CODE REVIEW

**Comment by edgardmessias** [comment]
@trasher @orthagh, maybe I change to:

```php
      if (!preg_match("/<br\s?\/?>/", $content) && !preg_match("/<p>/", $content)) {
         echo nl2br($content);
      } else
         echo $content;
     }
```
Suggestions?

**Comment by trasher** [comment]
I do not see the benefit of the proposal, and I'm pretty sure it is a simple `nl2br()` that is used elsewhere in GLPI.

**Comment by nqb** [comment]
@trasher : maybe this commit https://github.com/glpi-project/glpi/commit/591217f13552a7409a957e8f9d5396ed40b41f3f#diff-bb7c2f434e967018d0af7b0789728933

Issue was not present in 9.2.1.

**Comment by nqb** [comment]
@edgardmessias : please create an issue.

**Comment by edgardmessias** [comment]
Issue created: #3712

**Comment by edgardmessias** [comment]
@trasher, I can change?
```php
echo Toolbox::getHtmlToDisplay($content);
```

**Comment by trasher** [comment]
@edgardmessias good catch ;)

**Pull request merged**
