### PR TITLE
Item form hook

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by trasher** [comment]
Maybe a `pre_` hook should be added, and this one renamed to `post_`; I guess that should make sense

**Comment by trasher** [comment]
Maybe would it be a good idea to send the options as well, to get things like colspan

**Comment by trasher** [comment]
For precision:
- `post_item_hook` will be useful for plugins like [Fields](https://github.com/pluginsGLPI/fields) which actually adds content at the end of the form using some javascript code,
- `pre_item_hook` will be useful for plugins like [Tag](https://github.com/pluginsGLPI/tag) which actually adds content at the beginning of the form using also javascript code.

**Comment by tomolimo** [comment]
Yes, I've also some plugins doing that

**Comment by trasher** [comment]
I've realized Ticket and Entity object do not call `showFormButtons` and therefore do not call the hook...

I've just added the call in those two objects; this looks like the "less intrusive" solution to me. The *best* option would certainly be to add the expected call, but I'm not sure it will not create some problems.

As this PR is intended to reach the 9.1 branch; I've tried to avoid changing too much existing code.

**Comment by tsmr** [comment]
You have forget the pre_item_form hook for Ticket class which not use showFormHeader

**Comment by trasher** [comment]
Missed call have been added; thanks!

**Comment by tomolimo** [comment]
Hello Trasher,

What would be really cool is to distinguish Ticket an ticket solution in the options for the hooks.
Currently when viewing a Ticket or viewing a Ticket solution the $this type is the Ticket, and the options are the same..., there is nothing to distinguish the forms
The problem is the same when viewing a Computer and its Operating System: there is nothing to distinguish the forms.
Could it be possible to pass an option like 'form_name' => 'ticket_main' for Ticket and for Ticket Solution 'form_name' => 'ticket_solution'?

Thank you,
regards,
Tomolimo

**Comment by trasher** [comment]
While adapting the fields plugin to use this new hook; I got the same problem... Getting the tab num/name in options would be a quite huge change, since we do not get this information at all when calling the hook; I've prefered to use:
```
$subtype = $_SESSION['glpi_tabs'][strtolower($item::getType())]
```

**Comment by trasher** [comment]
Note this is why I had to do changes in 2b6c626ea0179417957566f84a979e80474aad90 ;)

**Comment by tomolimo** [comment]
Hello,
Currently testing these, and it seems like post_item_form is missing for TicketTask form...
regards,
Tomolimo

**Comment by trasher** [comment]
@tomolimo good catch, thank you :)

**Comment by tomolimo** [comment]
Also it seems strange to 
1. not call the pre_item_form right after the output of the <form> HTML tag... but currently called after a lot of  stuff
1. not call the post_item_form right before the output of the </form> HTML tag... but currently called before the output of the form buttons

**Comment by trasher** [comment]
The pre hook is called after the form "header"; I don't think we want it to be diplsayed at the very beginning.

> not call the post_item_form right before the output of the HTML tag

Which tag are you talking about?

**Comment by tomolimo** [comment]
sorry, github has eaten my tags, I was speaking about the `<form>` and `</form>` tags.

**Comment by tomolimo** [comment]
>  I don't think we want it to be diplsayed at the very beginning.

if a plugin wants to replace or to add some stuff inside the form, it would be better to call the hook at the very beginning (so just after the `<form>` tag)

**Comment by tomolimo** [comment]
and the nested post_item_form should also be called just before the `</form>` tag?

**Comment by trasher** [comment]
The post hook is designed to add contents before the buttons; those ones will stay at the bottom of the form (just before the `</form>` tag.

As for the pre hook, it should indeed be added at the very begining of the form; but this is not what the plugin tag does for example; it add its content after the `tr/@class='headerRow'`; that's why it's been called there; but it can be changed I guess.

**Comment by tomolimo** [comment]
ok, let's them like you did, and let's do some tests

**Comment by trasher** [comment]
OK, it is quite easy to change anyways ;)

**Comment by trasher** [comment]
There is something wrong. On some cases, hooks are called inside a table (so it is expected to output a `<tr>` tag) and on some other cases, they're called outside any table (so it is expected to output a full `<table>` or else) :(

**Comment by tomolimo** [comment]
On which cases?

**Comment by trasher** [comment]
Inside a table:
https://github.com/glpi-project/glpi/pull/1444/files#diff-7f569484c496f62a6ccf54647fed2b1bR2097

Outside:
https://github.com/glpi-project/glpi/pull/1444/files#diff-9fa7de3963d21e4e0fc3c5599247ad2cR1134

**Comment by trasher** [comment]
Yep, I'll change; it must have the same behavior everywhere. For the moment, I do not know where is the best place, I'll have to check for possible technical limitations before proceed :)

**Comment by trasher** [comment]
OK, so now:
- pre hook is called inside the `<table>` element, just after the `headerRow` if present, and at the begining if not,
- post hook is called inside the `<table>` element, just before the `showDates()` call if present, and at the very end if not.

**Comment by trasher** [comment]
If this sounds good to you; I'll merge this afternoon :) ping @tomolimo @tsmr

**Comment by tomolimo** [comment]
Ok for me

**Comment by tomolimo** [comment]
Seems like there is no hook for the helpdesk.public.php?

**Comment by trasher** [comment]
Indeed; I did not see this one (another which does not use main form header/footer :( )

**Comment by trasher** [comment]
@tomolimo see #1538.

Please note that I'll only do a global PR to add missing hooks; once it's been merged, that will end the feature for the 9.1.2 release.

**Pull request merged**
