### PR TITLE
Add user anonymous can fill dropdown with data

### PR DESCRIPTION
**Pull request by rosunad**
When we're with the anonymous user and we're in the helpdesk.php we're not able to fill a dropdown with data (i.e: categories) because of we're not logged. Adding a new parameter.
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by trasher** [comment]
Hello,

Thank you for the PR but... You should have a ticket or a suggestion opened before to get this discussed...

We cannot know what it is for, and you add a possibility that is not used... As is; this will not be included.

Also, you still have issues to fix for the checks.

**Comment by rosunad** [comment]
Ok, i will open a suggestion.

By the way, this is my first contribution to a project and i don't know how identify the problem with the travis ci checks

**Comment by trasher** [comment]
Just follow the red cross :D

There are issues on coding standards, see:
https://travis-ci.org/glpi-project/glpi/jobs/240684661#L602

**Comment by orthagh** [comment]
@rosunad 
PR are welcome, but as @trasher explains here is some points to address:
- Explain the usage of your change (in a ticket/suggestion). At the moment, your change doesn't have any usage in glpi and may open a security weakness. Maybe it's for a plugin ?
- Fix travis errors. In your pr, it fails on our coding standards rules : https://travis-ci.org/glpi-project/glpi/jobs/240684661#L602-L623 (bad indentation, missing space)

**Comment by rosunad** [comment]
Well, I thought the last commit will fix the indentation and spaces issue.

Anyway, thank you for your time and explantion ;)

**Pull request closed without merging**
