### PR TITLE
Add namespace/use coding rules

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

https://github.com/slevomat/coding-standard is a set of coding standards rules that can be added to PHPCS base rules.

In this PR, I added rules related to `namespace`/`use` directives and applied fix using phpcbf. Some other rules are also interesting, but may be harder to fix and it would be preferable to split the job into multiple PRs.

First commit (b745ce2) contains a patch for `glpi-project/coding-standard` and can be removed if new rules are added there.

### CODE REVIEW

**Comment by cedric-anne** [comment]
Applies rules from https://github.com/glpi-project/coding-standard/pull/8.

**Comment by trasher** [comment]
coding standards has been updated. also, if you ask for review, this is no longer a draft, is it?

**Comment by cedric-anne** [comment]
> coding standards has been updated. also, if you ask for review, this is no longer a draft, is it?

I was waiting for the new version of `glpi-project/coding-standard` to be able to update composer files.

**Comment by cedric-anne** [comment]
I have to rebase this PR.

**Pull request merged**
