### PR TITLE
Handle AJAX search failure better

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

The biggest case I notice is with the short lifespans the CSRF tokens have by default and having auto-refresh of the ticket list enabled. If you leave the ticket list open for more than 2 hours, the refresh will fail and show "The action you have requested is not allowed." instead of the search results.

If the refresh fails, it seems better to fall back on a page reload after updating the search URL as the initial results are sent with the page request and not done async.

### CODE REVIEW

**Comment by cconard96** [comment]
Not ready for merge. I need to fix JS tests.

**Comment by cconard96** [comment]
I had to increase the ECMA version for JS tests so that the linter wouldn't complain about async arrow functions.

Is there anything stopping us from increasing the target ECMA version globally? ECMAScript 2020 (ES11) has nearly full support across all currently supported browsers except some missing features in mobile browsers which is the case for any ECMA level.

**Comment by orthagh** [comment]
> ECMAScript 2020 (ES11) has nearly full support across all currently supported browsers except some missing features in mobile browsers which is the case for any ECMA level.

https://caniuse.com/?feats=mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nullish_coalescing,mdn-javascript_builtins_globalthis,es6-module-dynamic-import,bigint,mdn-javascript_builtins_promise_allsettled,mdn-javascript_builtins_string_matchall,mdn-javascript_statements_export_namespace,mdn-javascript_statements_import_meta

Seems indeed ok.
Imo, we shouldn't be annoyed by this upgrade.
@cedric-anne any opinion ?

**Comment by cedric-anne** [comment]
Even ES12 is fully supported now (excluding mobile browsers), so OK for this change.

**Comment by trasher** [comment]
Maybe this one should be rebased

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
