### PR TITLE
Log full profile information to user record on profile add or suppression

### PR DESCRIPTION
**Pull request by kabassanov**
When a profile is attached to a user account, it is defined by both entity and the profile itseilf. Actually, only this second part is logged to the user history and this information is meaningless without the entity environment it is attached to.

The proposd approach is probably not the best one and any other way to do this is welcome.

### CODE REVIEW

**Review by kabassanov — COMMENTED** [review]
Spaces...

**Comment by cconard96** [comment]
It looks like the issue is just that the `post_addItem` function in `CommonDBRelation` uses the 1st item of the relation, which in this case is the Profile, when adding the log event so the friendly name of the Profile is used rather than the Profile_User (which already accounts for the entity and recursivity). You mentioned on Discord that is used to show this information in the log, but I cannot find the version where this may have changed.

I'm wondering if there could be something simple missing somewhere to restore the functionality if it was there before, or at least avoid having a specific exception here and duplicating logic already done in the Profile_User's `computeFriendlyName`. Maybe there needs to be a flag to indicate that the logs should be for the relation item itself and use `getHistoryNameForItem` instead of the `getHistoryNameForItem1` or `getHistoryNameForItem2` functions.

**Comment by kabassanov** [comment]
> It looks like the issue is just that the `post_addItem` function in `CommonDBRelation` uses the 1st item of the relation, which in this case is the Profile,

This is a Profile_User object with the first item is a User Object and the second one: a Profile Object... Or we don't talk about the same thing.

> when adding the log event so the friendly name of the Profile is used rather than the Profile_User (which already accounts for the entity and recursivity). You mentioned on Discord that is used to show this information in the log, but I cannot find the version where this may have changed.

As loyal user of GLPI since 2008, I used several versions... The trace I talked about was from 2014, so probably a very old implementation of GLPI...

> 
> I'm wondering if there could be something simple missing somewhere to restore the functionality if it was there before, or at least avoid having a specific exception here and duplicating logic already done in the Profile_User's `computeFriendlyName`.

No idea...

**Review by cedric-anne — CHANGES_REQUESTED** [review]
The cleaner solution, from the technical point of view, would probably to define `$logs_for_item_1` and `$logs_for_item_2` to false, and to handle specific behaviour is `Profile_User::post_addItem()` and `Profile_User::post_deleteFromDB()`.

`CommonDBRelation` should not contains code dedicated to a specific child class.

**Comment by trasher** [comment]
@kabassanov are you going to work on this or should we close?

**Comment by kabassanov** [comment]
> @kabassanov are you going to work on this or should we close?

Need to fix it before closing... And move it forward in my todo list...

**Comment by kabassanov** [comment]
I wonder, where we should keep histories for these modifications? In the user history, in the profile history, in the entity history?

**Review by kabassanov — COMMENTED** [review]
Rollback code from wrong place

**Review by kabassanov — COMMENTED** [review]
Force testing...

**Review by kabassanov — COMMENTED** [review]
Wrong alignment

**Comment by kabassanov** [comment]
@trasher , I changed the way this patch completes user-profile-entity logs. It is OK for me.
I had to force IDs displays while retreiving User, Profile or Entity informations, because without this some tests fail. The reason is that post_addItem method is called during login procedure (for user synchronisation) and getNameID function is looking for not existing (at this time) $_SESSION["glpiis_ids_visible"] if not forcing display...

**Review by orthagh — CHANGES_REQUESTED** [review]
I may be wrong, other can confirm or not, but i think replicating the genericity  is not necessary.
You can directly use all **new defined properties** (and remove them) in the overridden methods.

The genericity could have been useful if they have been declared in `CommonDBRelation` but i don't think it's desirable as `Profile_User` is an exception with its 3 relations fields

**Comment by orthagh** [comment]
Apart this, seems good 👍🏽

**Comment by cedric-anne** [comment]
@kabassanov 

I rebased branch, simplified code and added tests. Could I force-push to your branch, or should I create a new pull request ?

**Comment by kabassanov** [comment]
> @kabassanov
> 
> I rebased branch, simplified code and added tests. Could I force-push to your branch, or should I create a new pull request ?

Yes, you can.

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
