### PR TITLE
fileupload: prevent error on drop file + add some dockblock

### PR DESCRIPTION
**Pull request by orthagh**
fix "console Uncaught TypeError: Cannot read property 'replace' of undefined" in browser dev tools when dropping img in File(s) zone

### CODE REVIEW

**Comment by trasher** [comment]
Is this one OK finally? I was waiting for @tsmr approval to merge.

**Comment by orthagh** [comment]
with this last commit, it should be ok.

**Comment by orthagh** [comment]
please close #1662 after merge of this pr

**Comment by satyan01** [comment]
after modification

image

**Pull request merged**
