### PR TITLE
Fix 2124

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2124

### CODE REVIEW

**Comment by trasher** [comment]
Thanks for your feedback. Indeed, this does not work for groups; whle it should. I'll investigate.

As for documents, this is not a "tooltip", so I've not changed anything yet (but it should also be opened in a another window).

**Comment by trasher** [comment]
Both have been fixed.

But, I wonder if this is the way to go. Indeed, when you set _target, user cannot choose to open link in current window or a new one. If you do not specify, user can do what he wants.
What about remonving all _blank to stay consistent (the only ones to keep are to open documents I guess).

**Comment by tomolimo** [comment]
> But, I wonder if this is the way to go. Indeed, when you set _target, user cannot choose to open link in current window or a new one. If you do not specify, user can do what he wants.
What about remonving all _blank to stay consistent (the only ones to keep are to open documents I guess).

Yes, it could be a problem for some people who are used to click on the "open in a new tab feature". then Could it be an option per user, to set this behavior?

**Comment by trasher** [comment]
It should be an option (while not in the bugfixes branch); but users preferences already are huge :(

**Comment by trasher** [comment]
I've reworked the PR; and removed default _blank to get a natural behavior

**Comment by trasher** [comment]
I've also removed some other _blank calls. The logic is:
- if the link point to an external website, open with _blank,
- if the link is designed to get a document, open with _blank (stored documents, exports and so on),
- everything else: open in the same window.

**Pull request merged**
