### PR TITLE
Feature/solutions

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2089

- [x] Fix rights
- [x] Fix massive actions
- [x] Change rejected image
- [x] Fix data migration

### CODE REVIEW

**Comment by tomolimo** [comment]
Hello @trasher, 

1. Question: why not use a similar DB schema than for tasks? I mean glpi_tickettasks, glpi_problemtasks, ..., this schema is also used for followups (glpi_ticketfollowups). My opinion on this schema: this way of grouping all solutions into one unique table leads to low performances, and more complex queries than splitting into three tables, also it leads to bigger tables: more fields :), and more records in one table.
1. I saw that during migration, date_creation and date_mod are set to current datetime instead of real datetime of the solution. and that users_id, users_id_editor and is_rejected is always set to 0:
image
1. If you don't want to re-build solution history, then why not use glpi_tickets which contains the latest info instead of logs
1. of course it would be good to rebuild solution history :smiley:, this is complex but feasible.

regards,
Tomolimo

**Comment by trasher** [comment]
Hi @tomolimo ,

1. mainly because this is more complex to manage several objects/tables than only one...
2. I know there are some issues on the migration; this is on the todolist ;) Anyways, thanks for the details; that will help
3. as far as I remember, I rely on informations that are used from the ticket class
4. I do not want to plan too much queries on the logs tables... Existing ones are (in my mind) required to get all solutions informations; adding more should be a big deal :(

**Comment by tomolimo** [comment]
> 3. as far as I remember, I rely on informations that are used from the ticket class

currently info are coming from logs, and not from ticket table :)

**Comment by tomolimo** [comment]
> 1. mainly because this is more complex to manage several objects/tables than only one...

But to harmonize DB schema: what will be done in future?

**Comment by trasher** [comment]
> currently info are coming from logs, and not from ticket table :)
Yes, informations are retrieved from logs table from ticket class.

> But to harmonize DB schema: what will be done in future?
This is a good question.... I had in mind using tables with itemtype + items_id was the way to go. BTW, I'm pretty sure there are several other existing inconsistances :(

**Comment by tomolimo** [comment]
In order to retrieve the solution history, you may test this sql query:
```
select tkt.id as tickets_id, 
			IFNULL(glsolve.date_mod, tkt.solvedate) as date_begin, 
			IF( IFNULL(glansw.date_mod, tkt.closedate) is null, 1, IF( glansw.new_value = 6 or (glansw.new_value is null and tkt.closedate is not null), 3, 2)) as approval,
			IFNULL(glansw.date_mod, tkt.closedate) as date_answer, 
			SUBSTRING_INDEX(SUBSTRING_INDEX(glsolve.user_name, '(', -1), ')', 1) as users_id,  
			fup.content as approval_comment, 
			fup.users_id as users_id_approver,
			0 as solutiontemplates_id,
			IF(glsolvetype.new_value is not null, SUBSTRING_INDEX(SUBSTRING_INDEX(glsolvetype.new_value, '(', -1), ')', 1), tkt.solutiontypes_id) as solutiontypes_id,
			IFNULL(glsolve.new_value, tkt.solution) as solution
from glpi_tickets as tkt
left join glpi_logs as glsolve on glsolve.itemtype='Ticket' and glsolve.items_id=tkt.id and glsolve.id_search_option=24 
left join glpi_logs as glsolvetype on glsolvetype.itemtype='Ticket' and glsolvetype.items_id=tkt.id and glsolvetype.id_search_option=23 and glsolvetype.id = (select max(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=tkt.id and gl.id_search_option=23 and gl.id < glsolve.id group by gl.items_id)
left join glpi_logs as glansw on glansw.itemtype='Ticket' and glansw.items_id=tkt.id and glansw.id_search_option=12 and glansw.old_value = 5 and glansw.id = (select min(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=tkt.id and gl.id_search_option=12 and gl.old_value = 5 and gl.id > glsolve.id group by gl.items_id )
left join glpi_logs as glfup on glfup.itemtype='Ticket' and glfup.items_id=tkt.id and glfup.itemtype_link='TicketFollowup' and glfup.id = (select min(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=tkt.id and gl.itemtype_link='TicketFollowup' and gl.id > glansw.id group by gl.items_id)
left join glpi_ticketfollowups as fup on fup.id=glfup.new_value
where tkt.solution is not null and tkt.solution <> ''
```

It will return the complete solution history.

to fill the table, you must use a REPLACE INTO, like following:

```
REPLACE INTO `glpi_ticketsolutions` (tickets_id, date_begin, approval, date_answer, users_id, approval_comment, users_id_approver, solutiontypes_id, solution)
(select tkt.id as tickets_id, 
			IFNULL(glsolve.date_mod, tkt.solvedate) as date_begin, 
			IF( IFNULL(glansw.date_mod, tkt.closedate) is null, 1, IF( glansw.new_value = 6 or (glansw.new_value is null and tkt.closedate is not null), 3, 2)) as approval,
			IFNULL(glansw.date_mod, tkt.closedate) as date_answer, 
			SUBSTRING_INDEX(SUBSTRING_INDEX(glsolve.user_name, '(', -1), ')', 1) as users_id,  
			fup.content as approval_comment, 
			fup.users_id as users_id_approver,
			IF(glsolvetype.new_value is not null, SUBSTRING_INDEX(SUBSTRING_INDEX(glsolvetype.new_value, '(', -1), ')', 1), tkt.solutiontypes_id) as solutiontypes_id,
			IFNULL(glsolve.new_value, tkt.solution) as solution
from glpi_tickets as tkt
left join glpi_logs as glsolve on glsolve.itemtype='Ticket' and glsolve.items_id=tkt.id and glsolve.id_search_option=24 
left join glpi_logs as glsolvetype on glsolvetype.id = (select max(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=tkt.id and gl.id_search_option=23 and gl.id < glsolve.id group by gl.items_id)
left join glpi_logs as glansw on glansw.id = (select min(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=tkt.id and gl.id_search_option=12 and gl.old_value = 5 and gl.id > glsolve.id group by gl.items_id )
left join glpi_logs as glfup on glfup.id = (select min(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=tkt.id and gl.itemtype_link='TicketFollowup' and gl.id > glansw.id group by gl.items_id)
left join glpi_ticketfollowups as fup on fup.id=glfup.new_value
where tkt.solution is not null and tkt.solution <> '')
```

as you may encounter several solutions at the same datetime (several consecutive solution saves with different texts) you must use REPLACE INTO. the request will keep the latest when datetime are identical.

This request lasts about 3.8 seconds on my server test DB: tickets: 253154, followups: 538488, logs: 28M (5.8GB), and it adds 228997 solution records.

As soon as you'll have define new fields in the glpi_itilsolutions table, I'll provide you with a new request. 

regards,
Tomolimo

**Comment by trasher** [comment]
Great, thank you :)

**Comment by tomolimo** [comment]
New version for Ticket solution history migration:

```
SELECT 'Ticket' AS itemtype,
		                  obj.`id` AS items_id,
			               IFNULL(glsolve.`date_mod`, obj.`solvedate`) AS date_creation,
			               SUBSTRING_INDEX(SUBSTRING_INDEX(glsolve.`user_name`, '(', -1), ')', 1) AS users_id,
			               IF(glsolvetype.`new_value` IS NOT NULL, SUBSTRING_INDEX(SUBSTRING_INDEX(glsolvetype.`new_value`, '(', -1), ')', 1), obj.`solutiontypes_id`) AS solutiontypes_id,
			               IFNULL(glcontent.`new_value`, obj.`solution`) AS content,
			               IF( IFNULL(glansw.`date_mod`, obj.`closedate`) IS NULL, 1, IF( glansw.`new_value` = 6 OR (glansw.`new_value` IS NULL AND obj.`closedate` IS NOT NULL), 3, 2)) AS approval,
			               IFNULL(glansw.`date_mod`, obj.`closedate`) AS date_mod,
			               fup.`id` AS 'ticketfollowups_id', fup.`users_id` AS users_id_editor
                     FROM glpi_tickets AS obj
                     LEFT JOIN `glpi_logs` AS glsolve ON glsolve.`itemtype` = 'Ticket' AND glsolve.`items_id` = obj.`id` AND glsolve.`id_search_option` = 12 AND glsolve.`new_value` = 5
                     LEFT JOIN `glpi_logs` AS glsolvetype ON glsolvetype.`itemtype` = 'Ticket' AND glsolvetype.`items_id` = obj.`id` AND glsolvetype.`id_search_option` = 23 AND glsolvetype.`date_mod` = glsolve.`date_mod`
                     LEFT JOIN `glpi_logs` AS glcontent ON  glcontent.`id` = (SELECT MAX(gl.`id`) FROM `glpi_logs` AS gl WHERE gl.`itemtype`='Ticket' AND gl.`items_id` = obj.`id` AND gl.`id_search_option` = 24 AND gl.`id` < glsolve.`id` GROUP BY gl.`items_id`)
                     LEFT JOIN `glpi_logs` AS glansw ON glansw.`id` = (SELECT MIN(gl.`id`) FROM `glpi_logs` AS gl WHERE gl.`itemtype`='Ticket' AND gl.`items_id` = obj.`id` AND gl.`id_search_option` = 12 AND gl.`old_value` = 5 AND gl.`id` > glsolve.`id` GROUP BY gl.`items_id`)
                     LEFT JOIN `glpi_logs` AS glfup ON glfup.`itemtype` = 'Ticket' AND glfup.`items_id` = obj.`id` AND glfup.`itemtype_link`='TicketFollowup' AND glfup.`date_mod` = glansw.`date_mod`
                                 LEFT JOIN `glpi_ticketfollowups` AS fup ON fup.`id`=glfup.`new_value`
                     WHERE obj.`solution` IS NOT NULL AND obj.`solution` <> ''
```

regards,
Tomolimo

**Comment by tomolimo** [comment]
Basic request which uses most of solution info from tickets table and does not retrieve solution history:

```
REPLACE INTO `glpi_itilsolutions` (`itemtype`, `items_id`, `date_creation`, `users_id`, `solutiontypes_id`, `content`, `approval`, `date_mod`, `ticketfollowups_id`, `users_id_editor`)
                     (SELECT 'Ticket' AS itemtype,
		                 obj.`id` AS items_id,
			               obj.`solvedate` AS date_creation,
			               SUBSTRING_INDEX(SUBSTRING_INDEX(glsolve.`user_name`, '(', -1), ')', 1) AS users_id,
			               obj.`solutiontypes_id` AS solutiontypes_id,
			               obj.`solution` AS content,
			               IF( obj.`closedate` IS NULL, 1, 3) AS approval,
			               obj.`closedate` AS date_mod,
			               fup.`id` AS 'ticketfollowups_id', 
										 SUBSTRING_INDEX(SUBSTRING_INDEX(glfup.`user_name`, '(', -1), ')', 1) AS users_id_editor
                     FROM glpi_tickets AS obj
                     LEFT JOIN `glpi_logs` AS glsolve ON glsolve.`itemtype` = 'Ticket' AND glsolve.`items_id` = obj.`id` AND glsolve.`id_search_option` = 12 AND glsolve.date_mod = obj.`solvedate`
                     LEFT JOIN `glpi_logs` AS glfup ON glfup.`itemtype` = 'Ticket' AND glfup.`items_id` = obj.`id` AND glfup.`itemtype_link`='TicketFollowup' AND glfup.`date_mod` = obj.`closedate`
                     LEFT JOIN `glpi_ticketfollowups` AS fup ON fup.`id`=glfup.`new_value`
                     WHERE obj.`solvedate` IS NOT NULL 
                  )
```

regards
Tomolimo

**Comment by tomolimo** [comment]
Hello,

Here is the latest version of the basic request :

```
REPLACE INTO `glpi_itilsolutions` (`itemtype`, `items_id`, `date_creation`, `users_id`, `solutiontypes_id`, `content`, `approval`, `date_mod`, `ticketfollowups_id`, `users_id_editor`)
                     (SELECT DISTINCT 'Ticket' AS itemtype,
		                 obj.`id` AS items_id,
			               obj.`solvedate` AS date_creation,
			               SUBSTRING_INDEX(SUBSTRING_INDEX(glsolve.`user_name`, '(', -1), ')', 1) AS users_id,
			               obj.`solutiontypes_id` AS solutiontypes_id,
			               obj.`solution` AS content,
			               IF(obj.`closedate` IS NULL, 1, 3) AS approval,
			               obj.`closedate` AS date_mod,
			               fup.`id` AS 'ticketfollowups_id', 
										 SUBSTRING_INDEX(SUBSTRING_INDEX(glfup.`user_name`, '(', -1), ')', 1) AS users_id_editor
                     FROM glpi_tickets AS obj
                     LEFT JOIN `glpi_logs` AS glsolve ON glsolve.`itemtype` = 'Ticket' AND glsolve.`items_id` = obj.`id` AND (glsolve.`id_search_option` = 12 OR glsolve.`id_search_option` =  24) AND glsolve.`date_mod` = obj.`solvedate`
                     LEFT JOIN `glpi_logs` AS glfup ON glfup.`itemtype` = 'Ticket' AND glfup.`items_id` = obj.`id` AND glfup.`itemtype_link`='TicketFollowup' AND glfup.`date_mod` = obj.`closedate`
                     LEFT JOIN `glpi_ticketfollowups` AS fup ON fup.`id`=glfup.`new_value`
                     WHERE obj.`solvedate` IS NOT NULL 
                     )
```

regards
Tomolimo

**Comment by tomolimo** [comment]
Hello,

Complete SQL request with solution history and names when id can't be extracted from names (logs not normalized):

```
SELECT 'Ticket' AS itemtype,
		                obj.`id` AS items_id,
			               IFNULL(glsolve.`date_mod`, obj.`solvedate`) AS date_creation,			               
			               IF(glsolve.user_name REGEXP '\\(([0-9]+)\\)$', SUBSTRING_INDEX(SUBSTRING_INDEX(glsolve.`user_name`, '(', -1), ')', 1), NULL) AS users_id,
			               IF(glsolve.user_name REGEXP '\\(([0-9]+)\\)$', NULL, glsolve.`user_name`) AS user_name,
			               IF(glsolvetype.`new_value` REGEXP '\\(([0-9]+)\\)$', SUBSTRING_INDEX(SUBSTRING_INDEX(glsolvetype.`new_value`, '(', -1), ')', 1), NULL) AS solutiontypes_id,
			               IF(glsolvetype.`new_value` REGEXP '\\(([0-9]+)\\)$', NULL, glsolvetype.`new_value`) AS solutiontype_name,
			               IFNULL(glcontent.`new_value`, obj.`solution`) AS content,
			               IF( IFNULL(glansw.`date_mod`, obj.`closedate`) IS NULL, 1, IF( glansw.`new_value` = 6 OR (glansw.`new_value` IS NULL AND obj.`closedate` IS NOT NULL), 3, 2)) AS approval,
			               IFNULL(glansw.`date_mod`, obj.`closedate`) AS date_mod,
			               fup.`id` AS 'ticketfollowups_id', 
										 IF(glansw.`user_name` REGEXP '\\(([0-9]+)\\)$', SUBSTRING_INDEX(SUBSTRING_INDEX(glansw.`user_name`, '(', -1), ')', 1), NULL) AS users_id_editor,
										 IF(glansw.`user_name` REGEXP '\\(([0-9]+)\\)$', NULL, glansw.`user_name`) AS user_name_editor
                     FROM glpi_tickets AS obj
                     LEFT JOIN `glpi_logs` AS glsolve ON glsolve.`itemtype` = 'Ticket' AND glsolve.`items_id` = obj.`id` AND glsolve.`id_search_option` = 12 AND glsolve.`new_value` = 5
                     LEFT JOIN `glpi_logs` AS glsolvetype ON glsolvetype.id = (select max(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=obj.id and gl.id_search_option=23 and gl.id < glsolve.id group by gl.items_id)
                     LEFT JOIN `glpi_logs` AS glcontent ON  glcontent.`id` = (SELECT MAX(gl.`id`) FROM `glpi_logs` AS gl WHERE gl.`itemtype`='Ticket' AND gl.`items_id` = obj.`id` AND gl.`id_search_option` = 24 AND gl.`id` < glsolve.`id` GROUP BY gl.`items_id`)
                     LEFT JOIN `glpi_logs` AS glansw ON glansw.`id` = (SELECT MIN(gl.`id`) FROM `glpi_logs` AS gl WHERE gl.`itemtype`='Ticket' AND gl.`items_id` = obj.`id` AND gl.`id_search_option` = 12 AND gl.`old_value` = 5 AND gl.`id` > glsolve.`id` GROUP BY gl.`items_id`)
                     LEFT JOIN `glpi_logs` AS glfup ON glfup.id = (select min(gl.id) from glpi_logs as gl where gl.itemtype='Ticket' and gl.items_id=obj.id and gl.itemtype_link='TicketFollowup' and gl.id > glansw.id group by gl.items_id)
                     LEFT JOIN `glpi_ticketfollowups` AS fup ON fup.`id`=glfup.`new_value`
                     WHERE obj.`solution` IS NOT NULL 
```

Three new columns need to be created: 
```
`solutiontype_name` VARCHAR(255) NULL,
`user_name` VARCHAR(255) NULL,
`user_name_editor` VARCHAR(255) NULL,
```

regards,
Tomolimo

**Comment by trasher** [comment]
Issue spotted: when reopening a ticket; the solution is not set as rejected as it should.

**Pull request merged**
