### PR TITLE
manage translation override

### PR DESCRIPTION
**Pull request by remicollet**
POV, For discussion

### CODE REVIEW

**Comment by trasher** [comment]
Sounds really correct, thanks.
This should target 9.5.

**Comment by remicollet** [comment]
BTW, not complete, missing the same override for pllugins

**Comment by trasher** [comment]
Yes, there are several things to be changed, we wera talking about that this morning :)

**Comment by cedric-anne** [comment]
Solution is simple but powerfull so +1.

Some remarks:

1. It may be usefull to handle custom locales directory using a new constant (`GLPI_CUSTOM_LOCALES_DIR`, `GLPI_VAR_DIR . "/_locales"` by default). It could simplify the backup/update process for people already using custom path for their directories.
2. Using mo files would avoid requirement of a new dependency, and free tools exists on many plaforms to edit po files and export them into mo, so it may be even simplier than using ini files.
3. To be able to override plugins locales as well, maybe we could define a directory structure in the custom locale dir (e.g. `GLPI_CUSTOM_LOCALES_DIR . '/glpi/*.mo'` for core and `GLPI_CUSTOM_LOCALES_DIR . '/plugins/fields/*.mo''` for field plugin).

**Comment by trasher** [comment]
Done in https://github.com/glpi-project/glpi/pull/5907

**Pull request closed without merging**
