### PR TITLE
fix: disable submit via enter key

### PR DESCRIPTION
**Pull request by Rom1-B**
For example: On a ticket, if you add a text input via the Fields plugin. When you modify this field and press enter, the ticket is deleted, because the 1st submit button on the form is delete.

_I don't think this case is specific to the plugin._

This PR disables submit via enter key from an input field (itilobject only).

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

### CODE REVIEW

**Review by orthagh — COMMENTED** [review]
I'm not sure I would have taken this road.
Alternative solution:

- reverse in html and use flex to reverse also the display
- make an hidden submit button in first position (acting like the save one)

**Comment by cedric-anne** [comment]
> * reverse in html and use flex to reverse also the display

This is what we do in other forms, and it is the best solution IMHO.

**Comment by Rom1-B** [comment]
Bootstrap doesn't handle reverse with btn-group, so border-radius is wrong.

image

I made 2 commits for the 2 proposed roads

**Comment by orthagh** [comment]
One comment because I didn't check when suggestion the solution, is the second works on Enter key ?

**Comment by Rom1-B** [comment]
> One comment because I didn't check when suggestion the solution, is the second works on Enter key ?

Yes, but the tests fail. So there's still work to be done on the 2 solutions. Which one should I keep working on?

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request closed without merging**
