### PR TITLE
Fix parsing of `x-www-form-urlencoded` input in API

### PR DESCRIPTION
**Pull request by InoueKenta**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

I found a bug that when calling GLPI Request using application/x-www-form-urlencoded content, glpi throw critical error
This error orrcurs on PHP >= 8
```
*** Uncaught Exception Error: Attempt to assign property "id" on array in \glpi\src\Api\APIRest.php at line 324
  Backtrace :
  apirest.php:57                                     Glpi\Api\APIRest->call()
```

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
Seems OK, but a test should be added in `web` test suite to validate this.

**Comment by InoueKenta** [comment]
> Seems OK, but a test should be added in `web` test suite to validate this.

Having some trouble running tests but I'm working on it.

**Comment by cedric-anne** [comment]
> Having some trouble running tests but I'm working on it.

I pushed a commit to add a test, to be able to merge this PR quickly.

Without the fix, added tes was failing:
```
> There are 2 failures:
=> tests\units\Glpi\Api\APIRest::testUpdateItemFormEncodedBody():
In file /var/glpi/tests/web/APIRest.php on line 75, string() failed: string is not empty
-Expected
+Actual
@@ -1 +1,5 @@
-string(0) ""
+string(251) "[2023-03-31 18:06:47] glpiphplog.WARNING:   *** PHP Warning (2): Attempt to assign property 'id' of non-object in /var/glpi/src/Api/APIRest.php at line 324
+  Backtrace :
+  apirest.php:57                                     Glpi\Api\APIRest->call()
+  
+"
=> tests\units\Glpi\Api\APIRest::testUpdateItemFormEncodedBody():
In file /var/glpi/tests/web/APIRest.php on line 1427, array() failed: array(2) is not equal to array(1)
-Expected
+Actual
@@ -1 +1 @@
-array(1) {
+array(2) {
@@ -3,5 +3,4 @@
-  array(2) {
-    [12]=>
-    bool(true)
-    ["message"]=>
-    string(0) ""
+  array(0) {
+  }
+  [1]=>
+  array(0) {
```

**Review by cedric-anne — APPROVED** [review]

**Comment by InoueKenta** [comment]
> > Having some trouble running tests but I'm working on it.
> 
> I pushed a commit to add a test, to be able to merge this PR quickly.
> 
> Without the fix, added tes was failing:
> 
> ```
> > There are 2 failures:
> => tests\units\Glpi\Api\APIRest::testUpdateItemFormEncodedBody():
> In file /var/glpi/tests/web/APIRest.php on line 75, string() failed: string is not empty
> -Expected
> +Actual
> @@ -1 +1,5 @@
> -string(0) ""
> +string(251) "[2023-03-31 18:06:47] glpiphplog.WARNING:   *** PHP Warning (2): Attempt to assign property 'id' of non-object in /var/glpi/src/Api/APIRest.php at line 324
> +  Backtrace :
> +  apirest.php:57                                     Glpi\Api\APIRest->call()
> +  
> +"
> => tests\units\Glpi\Api\APIRest::testUpdateItemFormEncodedBody():
> In file /var/glpi/tests/web/APIRest.php on line 1427, array() failed: array(2) is not equal to array(1)
> -Expected
> +Actual
> @@ -1 +1 @@
> -array(1) {
> +array(2) {
> @@ -3,5 +3,4 @@
> -  array(2) {
> -    [12]=>
> -    bool(true)
> -    ["message"]=>
> -    string(0) ""
> +  array(0) {
> +  }
> +  [1]=>
> +  array(0) {
> ```

Many thanks.
I run the test. It looks good.
I added another test for DELETE case.
There is one test failed but it is not related.
image

BTW, I still can't run a specific test case with below command so I ended up run whole suite 😅
```bash
php vendor/bin/atoum --debug --no-code-coverage --force-terminal -bf tests/bootstrap.php -m tests\web\APIRest::testUpdateItemFormEncodedBody
```

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
