### PR TITLE
Fix Vue webpack chunk loading in subfolders

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #17533

Use a custom `__webpack_chunk_load__` function to resolve chunk paths using `CFG_GLPI.root_doc` in order to support GLPI installations in subfolders.

### CODE REVIEW

**Comment by Rom1-B** [comment]
Using FuzzySearch-Modal-vue.js as an example

It works on the central page: `http://localhost/GLPI/main/front/central.php`, because it finds `http://localhost/GLPI/main/public/build/vue/vue-sfc/FuzzySearch-Modal-vue.js`

But not here: `http://localhost/GLPI/main/front/asset/assetdefinition.form.php?id=1`, because it searches for `http://localhost/GLPI/main/front/public/build/vue/vue-sfc/FuzzySearch-Modal-vue.js`

**Comment by cconard96** [comment]
Did you rebuild the vue sources and clear your cache?

**Review by cedric-anne — APPROVED** [review]
Thanks.

I just pushed a commit to fix the presence of a double slash in URLs
```diff
- /public/build/vue//vue-sfc/Debug-WidgetButton-vue.js
+ /public/build/vue/vue-sfc/Debug-WidgetButton-vue.js
```

**Comment by cedric-anne** [comment]
> Using FuzzySearch-Modal-vue.js as an example
> 
> It works on the central page: `http://localhost/GLPI/main/front/central.php`, because it finds `http://localhost/GLPI/main/public/build/vue/vue-sfc/FuzzySearch-Modal-vue.js`
> 
> But not here: `http://localhost/GLPI/main/front/asset/assetdefinition.form.php?id=1`, because it searches for `http://localhost/GLPI/main/front/public/build/vue/vue-sfc/FuzzySearch-Modal-vue.js`

I did not had this problem with the proposed solution. I tried with multiple aliases `/glpi` and `/glpi/test`.

**Comment by cedric-anne** [comment]
@cconard96 It seems that the tests are failing due to this change. Could you check?

**Comment by cconard96** [comment]
Looks like the keys from `component_context` aren't actually the chunk IDs. Need to see if there is another way I can translate the chunk ID to the chunk/file name.

**Comment by cconard96** [comment]
My second method doesn't seem to work either, but maybe it is a step in the right direction.
Currently, it seems to fail to load the ProfilerTable.vue component which is loaded through Profiler.vue. It looks like when this component is chunked, it is chunked twice and is placed as `public/build/vue/19.js` as well as `public/build/vue/vue-sfc/Debug-Widget-ProfilerTable.js`. When it is loaded in the Profiler widget, it tries loading the numeric chunk and it doesn't use the webpack stuff from `app.js`.

**Comment by Rom1-B** [comment]
Oh yes, sorry, I didn't rebuild. I just did (+ clear cache) from the last commit, but it still doesn't work.
It's looking for `http://localhost/public/build/vue/GLPI/main/vue-sfc/FuzzySearch-Modal-vue.js` from `http://localhost/GLPI/main/front/asset/assetdefinition.form.php?id=1`

**Comment by cconard96** [comment]
The behavior of these module variables and paths don't make any sense to me at all.

If I manually prepend "/glpi/main/" to the `__webpack_public_path__`, it loads from `/main/public/build/...`. It gets rid of the first part. If I use `glpi/main/` (no slash at front), it loads from `/front/glpi/main/public/build/...`. If the public path is set to `auto` in the config, it becomes a http url to the `js` folder. 
Changing `__webpack_base_uri__` to match `CFG_GLPI.url_base` doesn't seem to matter, although by default it is the current URL.

**Comment by cconard96** [comment]
@Rom1-B can you test with the latest commit? I set up a subdirectory like you have and tested adding the root_doc to the front of the webpack public path. It seemed to work OK with the subdirectory and the subdomain setups I had.

**Review by Rom1-B — APPROVED** [review]
Yes great, it works for me

**Comment by trasher** [comment]
Tests are failing

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
