### PR TITLE
Extend solution type with ITIL Object filter

### PR DESCRIPTION
**Pull request by VladoTTX**
We have a request to filter solution types per type of ITIL object they are used for.
I am not sure about rawSearchOptions id, i used same as was defined in ITILCategory.
Please review whether it is acceptable for future branch.. 

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | NA

### CODE REVIEW

**Comment by VladoTTX** [comment]
But maybe for future would it be better in ITILCategory and here in SolutionType not to use individual columns but maybe multiselect with Item types (either JSON or some connecting table?), so plugins which for example extend CommonITILObject could add their own type and also for future when some new type is introduced..
What do you think?

**Review by cedric-anne — APPROVED** [review]

**Comment by cedric-anne** [comment]
> But maybe for future would it be better in ITILCategory and here in SolutionType not to use individual columns but maybe multiselect with Item types (either JSON or some connecting table?), so plugins which for example extend CommonITILObject could add their own type and also for future when some new type is introduced.. What do you think?

Unless you require such a feature, there is no need to spend time on this. We already have a hard time proofreading all the PRs as they come in, so best to keep it simple.

**Review by orthagh — APPROVED** [review]

**Comment by VladoTTX** [comment]
> > But maybe for future would it be better in ITILCategory and here in SolutionType not to use individual columns but maybe multiselect with Item types (either JSON or some connecting table?), so plugins which for example extend CommonITILObject could add their own type and also for future when some new type is introduced.. What do you think?
> 
> Unless you require such a feature, there is no need to spend time on this. We already have a hard time proofreading all the PRs as they come in, so best to keep it simple.

Thanks for all your time reading the PRs.. 
Probably not worth the effort. Maybe easier would be to add hook similar to actors filter on Category and Solution.
What is best way to discuss ideas before start working on them, forums?

**Comment by cedric-anne** [comment]
> What is best way to discuss ideas before start working on them, forums?

@VladoTTX 

You can open an issue on Github, and we can discuss on it. Main contributor may receive notifications and so may participate.

**Pull request merged**
