### PR TITLE
Add some Japanese translations

### PR DESCRIPTION
**Pull request by akira345**
Hi.
I'm GLPI user in Japanese.
I have found that some translations are missing.
so, i search the transifex. But i can't found.
I'm not good at English. However, as a GLPI user I wanted to contribute even a little.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | none
| Fixed tickets | #number

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by trasher** [comment]
Hi,

Thanks for your contribution, but translations are handled only on transifex. When logged in into transifex, go to https://www.transifex.com/glpi/GLPI/translate/#ja_JP/glpipot92 and you should see untranslated strings.

It is also possible that some strings have been translated since the last release. Anyways, japanese translation is not complete yet ;)

**Comment by akira345** [comment]
Thanks.
But. transifex URI is 404 NOT FOUND :<

**Comment by trasher** [comment]
Then login to your transifex account, go to the glpi project; then resources; then glpi92, click on your language and finally click on translate.

**Comment by akira345** [comment]
Thanks!
I can fount the glpi-project in transifex.
(There were several GLPI projects in transifex and I was going to be missing.)

**Pull request closed without merging**
