### PR TITLE
Fix old survey clean

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Found while looking into #9931 but may not be related.
The code looks like it is removing any survey that has the same ID as the current ticket rather than deleting old surveys for this ticket.

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Comment by cconard96** [comment]
> Even if it is confusing, code is actually OK, due to `getIndexName()` result and `getFromDB()` behaviour.
> 
> ```
>     public static function getIndexName()
>     {
>         return 'tickets_id';
>     }
> ```
> 
> Maybe the initial issue is related to something that does not correctly handle this somewhere (e.g. a code that is using `getFromDB()` using the statisfaction survey id, instead of the ticket id).

I'm not sure why the index field is set that way but that seems like it would only add to confusion. It could explain why troubleshooting the initial issue was so difficult. Only 3 itemtypes in GLPI override the default `getIndexName` so it is easy to think that `getFromDB` is always matching the parameter with the `id` field.

**Comment by cconard96** [comment]
For example in `addToDB`:
```php
    public function addToDB()
    {
        global $DB;


        $nb_fields = count($this->fields);
        if ($nb_fields > 0) {
            $params = [];
            foreach ($this->fields as $key => $value) {
                //FIXME: why is that handled here?
                if (($this->getType() == 'ProfileRight') && ($value == '')) {
                    $value = 0;
                }
                $params[$key] = $value;
            }


            $result = $DB->insert($this->getTable(), $params);
            if ($result) {
                if (
                    !isset($this->fields['id'])
                    || is_null($this->fields['id'])
                    || ($this->fields['id'] == 0)
                ) {
                    $this->fields['id'] = $DB->insertId();
                }


                $this->getFromDB($this->fields['id']);


                return $this->fields['id'];
            }
        }
        return false;
    }
```

It always reloads the item after adding using the ID field.
This may be the issue with the surveys going out for a ticket with the survey's ID instead of the ticket's own ID.

**Comment by cedric-anne** [comment]
> Only 3 itemtypes in GLPI override the default `getIndexName` so it is easy to think that `getFromDB` is always matching the parameter with the `id` field.

I find only one plugin that is using this. Maybe we should deprecate usage of this method (e.g. by trigerring a deprecation warning when result of this method is not `id`). We already had some bugs related to this, and clearly the whole GLPI codebase is far from being compatible with this usage.

**Comment by cconard96** [comment]
For this PR, is the change OK or just revert it for now and keep the tests?

**Comment by cedric-anne** [comment]
> For this PR, is the change OK or just revert it for now and keep the tests?

Fix is OK for me.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
