### PR TITLE
Fix "Operating system name" search option

### PR DESCRIPTION
**Pull request by AdrienClairembault**
This search option may return multiple results and should thus use `GROUP CONCAT` to prevent duplicated results.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Comment by trasher** [comment]
Some other SO may suffer of the same issue (61, 64, 48, 63), reported by @cedric-anne on local chat

**Comment by AdrienClairembault** [comment]
The others SO do not recreate the issue on my side.
I guess that while they could technically causes issues (since this is a 1-N relation) they don't end up with more than a 1-1 relationship in real world cases.

@stonebuzz was also telling me that even for the original case it should no longer happens with GLPI's native inventory.

Since `GROUP CONCAT` is probably not great performances wise, maybe its not worth it to add it the others options ?

**Comment by trasher** [comment]
If original issue should not happen; maybe could we try to fix what's wrongly stored in DB instead of trying to fix the search? I guess it's the better option for performances.

Several OS on a same asset never has been supported in facts, it should not have been done that way in the code (my bad at the origin).

This is an issue that keeps rearing its ugly head; I wonder if we should not change the relation to a real 1-1 to definitely fix that (not before 10.1 anyway).

**Comment by orthagh** [comment]
Please extends the `forcegroupby` key to all searchoptions like said by Cedric.
We'll make a decision about relation nature of OS later.
In the case we move to 1-1, the forcegroupby will probably not interfer from a UI pov

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
