### PR TITLE
Update de_DE.po

### PR DESCRIPTION
**Pull request by wagneral**
Corrected and optimized German language expressions

### CODE REVIEW

**Comment by trasher** [comment]
Hello, thanks for your contribution.

GLPI translations are managed on transifex; opening pull request to update languages may throw conflicts that will be very hard to fix :)

**Comment by wagneral** [comment]
Hello,
I'm sorry, didn't know about that. So what does that mean? Should I join the Transifex Project?

**Comment by trasher** [comment]
Joining the project on transifex would be the best solution in the future, yes. As for the current request, we'll check if your changes can be merged without breaking anything... I'll keep you in touch.

**Comment by orthagh** [comment]
Hello @wagneral 

Thank you for your contribution.
But as @trasher says, we manage glpi translations on [transifex service](https://www.transifex.com/glpi/GLPI/).

You should join the german team and send your translation on the service.
I checked if i can import your file, but it seems there is some changed keys (ex here https://github.com/glpi-project/glpi/pull/1339/files#diff-f06d8da9597864a8c209cd41561c8ce4L6891)
and i can't achieve the import.

So i'm sorry, but my only solution is to ask you to do again your contribution on the transifex site.

**Comment by wagneral** [comment]
Hello @orthagh 

no problem, this is completely comprehensible. As soon as I have reverted the linebreaks in the keys, I'll send my translation on transifex. I already created an account and will try my best over there ;)

Thanks for the explanation.

**Comment by orthagh** [comment]
BTW, It's a pity i couldn't import your translations.

**Pull request closed without merging**
