### PR TITLE
Workaround for config record ID requirement

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12267

Replace #12270

### CODE REVIEW

**Comment by dsci-naw** [comment]
Hi, tested and worked fine for general config page! thanks

But in notification page didn't work /front/notificationmailingsetting.form.php

I think the new method is needed here too (found in search):
- https://github.com/glpi-project/glpi/blob/10.0/bugfixes/front/notificationajaxsetting.form.php#L51
- https://github.com/glpi-project/glpi/blob/10.0/bugfixes/front/notificationmailingsetting.form.php#L51

And also the new method here to save the notification settings:
- https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/NotificationSettingConfig.php#L52
- https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/NotificationSettingConfig.php#L69

**Review by cedric-anne — COMMENTED** [review]
I do not like this kind of workarounds, but I dig a bit and handling it differently, like it was proposed in previours PR, would require lots of changes.
So, for me, this kind of change is OK.
Same kind of change should be added on notification settings.

**Review by cedric-anne — APPROVED** [review]

**Comment by cconard96** [comment]
Based on @dsci-naw comment, ID 1 is hard coded other places for configs and saving doesn't work for them so this fix doesn't seem to be complete yet.

**Comment by cconard96** [comment]
@dsci-naw Can you test again?

Some of the usages of ID 1 you mentioned seem to just be to handle the older databases which may not have the new configs table layout yet (useful during the update process).

**Comment by dsci-naw** [comment]
All seems to work except general config "Save" that is not saving (notifications are ok anda saving now)

**Comment by cconard96** [comment]
Are there any new errors in the GLPI logs (access-errors, php-errors, or sql-errors)?

**Comment by dsci-naw** [comment]
unfortunately no, nothing

**Comment by dsci-naw** [comment]
just one note, i think this can be used to reproduce the issue (not sure since don't know glpi database structure), change the id 1 to other id

> UPDATE glpi_configs SET id=1000 WHERE name = 'version';
> UPDATE glpi_logs SET items_id=1000 WHERE itemtype = 'Config';

and for rollback
> UPDATE glpi_configs SET id=1 WHERE name = 'version';
> UPDATE glpi_logs SET items_id=1 WHERE itemtype = 'Config';

**Comment by dsci-naw** [comment]
with the latest change, now config options save. All seems to work fine.

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
