### PR TITLE
Add into rawSearchOptions Number of users for Group 

### PR DESCRIPTION
**Pull request by Elric59**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

Add into rawSearchOptions function of Group.php, numbers of users who are assign to a group

### CODE REVIEW

**Comment by cconard96** [comment]
This may be OK for 10.0.X versions, but I think this will be difficult to adapt for 11.0 which adds recursive group memberships (#13578) unless we specify it is only direct members of the group.

**Comment by trasher** [comment]
We won't accept new features on 10.0 branch, it's bugfixes only. You must target min branch for new features.

**Comment by Elric59** [comment]
Hi ! ,

Sorry I forgot to answer yesterday, 

@cconard96 
Actually I just need this feature for 10.0.X versions, 
for 11.X.X I'm gonna check how new features work on Group and see how I can modify it

@trasher 
"min branch" is main branch right ?

**Comment by trasher** [comment]
> @trasher "min branch" is main branch right ?

Yes, I've fixed my comment.

**Comment by Elric59** [comment]
Ok,
So like Curtis said, that's not gonna work on v11, so better close this PR and wait next major version and see I guess

**Pull request closed without merging**
