### PR TITLE
Fix missing Connected To column

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #13532

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

**Comment by cconard96** [comment]
Does anyone know why this search option is added only if `TU_USER` is not defined? It seems odd to me, and maybe a comment should be added to explain it.

**Comment by trasher** [comment]
> Does anyone know why this search option is added only if `TU_USER` is not defined? It seems odd to me, and maybe a comment should be added to explain it.

No idea. You can try to remove this condition, if that does not cause tests failure...

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Comment by trasher** [comment]
Looks like condition is still needed :D But honestly, I have no idea why.

**Comment by cconard96** [comment]
> Looks like condition is still needed :D But honestly, I have no idea why.

Looks like it is a virtual field but not declared as one. I'll re-add the condition and look into it more later.

**Comment by cedric-anne** [comment]
Name has to be prefixed by `_virtual`
```diff
diff --git a/src/NetworkPort.php b/src/NetworkPort.php
index d272132c77..0923925c78 100644
--- a/src/NetworkPort.php
+++ b/src/NetworkPort.php
@@ -1698,17 +1698,14 @@ class NetworkPort extends CommonDBChild
             'joinparams' => ['beforejoin' => $netportjoin]
         ];
 
-        if (!defined('TU_USER')) {
-            $tab[] = [
-                'id'    => '39',
-                'table' => $this->getTable(),
-                'field' => 'noone',
-                'name' => __('Connected to'),
-                'nosearch' => true,
-                'nodisplay' => true,
-                'massiveaction' => false
-            ];
-        }
+        $tab[] = [
+            'id'    => '39',
+            'table' => $this->getTable(),
+            'field' => '_virtual_connected_to', // virtual field
+            'name' => __('Connected to'),
+            'nosearch' => true,
+            'massiveaction' => false
+        ];
 
         $tab[] = [
             'id'    => '40',
```

**Comment by trasher** [comment]
I've openend another PR for the condition #13550

**Pull request merged**
