### PR TITLE
Use bigint for disks size

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #16844

### CODE REVIEW

**Review by orthagh — COMMENTED** [review]
We may also change Toolbox::getSize (and related functions), no?

**Review by cedric-anne — APPROVED** [review]

**Comment by trasher** [comment]
> We may also change Toolbox::getSize (and related functions), no?

You mean, like this?
```diff
diff --git a/src/Toolbox.php b/src/Toolbox.php
index 9dcd1e5ac5..6f7f74b914 100644
--- a/src/Toolbox.php
+++ b/src/Toolbox.php
@@ -974,7 +974,7 @@ class Toolbox
     {
 
        //TRANS: list of unit (o for octet)
-        $bytes = [__('o'), __('Kio'), __('Mio'), __('Gio'), __('Tio')];
+        $bytes = [__('o'), __('Kio'), __('Mio'), __('Gio'), __('Tio'), __('Pio'), __('Eio'), __('Zio'), __('Yio')];
         foreach ($bytes as $val) {
             if ($size > 1024) {
                 $size = $size / 1024;
```

**Comment by cedric-anne** [comment]
> ```diff
> Yio
> ```

Sounds correct.

Still, I guess the 2038 bug will have destroy the whole internet before anyone would be able to have a 1Yio volume capacity.

**Comment by orthagh** [comment]
yes

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
