### PR TITLE
remove copyright in null footer

### LINKED ISSUE #2307: [9.2] malformed login error page
Hi

If I enter wrong credentials to login in GLPI I get the following page:
image

i cannot click on "log in again", because the footer is invisible ans palced over the link. This may lead the user to http://glpi-project.org

See the screenshot with highlighted text
image

### PR DESCRIPTION
**Pull request by btry**
fix #2307

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2307 

remove the copyright in the null footer

### CODE REVIEW

**Comment by trasher** [comment]
I'd propose to fix the CSS rather than remove the © message; something like this:

```diff
diff --git a/css/styles.css b/css/styles.css
index d7b1006..d361d4d 100644
--- a/css/styles.css
+++ b/css/styles.css
@@ -2445,13 +2445,15 @@ a.icon_nav_move:hover img {
    position: absolute;
    right: 10px;
    bottom: 0px;
-   height: 40px;
    font-size : 10px;
    font-family: Verdana,Arial,Helvetica,sans-serif;
    font-weight: bold;
 }
 
-#footer-login a {
+#footer-login.home {
+   bottom: 15px;
+}
+#footer-login.home a {
    color: #FFF;
 }
 
diff --git a/index.php b/index.php
index 8fc1509..972469f 100644
--- a/index.php
+++ b/index.php
@@ -200,7 +200,7 @@ if (!file_exists(GLPI_CONFIG_DIR . "/config_db.php")) {
       Event::getCountLogin();
       echo "</div>";
    }
-   echo "<div id='footer-login'>" . Html::getCopyrightMessage() . "</div>";
+   echo "<div id='footer-login' class='home'>" . Html::getCopyrightMessage() . "</div>";
 
 }
 // call cron
```

**Comment by btry** [comment]
Updating the CSS was my initial idea, but @orthagh thought the footer is useless on these pages and we agreed to remove it. 

So we need to talk again with him. My vote would be for a CSS fix.

**Comment by trasher** [comment]
For the login error page, the footer is not really important; but it should be present on the update page I guess.

**Comment by btry** [comment]
This means creating an extra footer method.

**Comment by trasher** [comment]
No, the fix I propose display the footer on all pages; but not with a white texte (and without height to prevent the issue you initially get)

**Comment by btry** [comment]
:D

**Comment by trasher** [comment]
For reference, I've pushed my proposal in a branch: https://github.com/glpi-project/glpi/compare/master...trasher:fix-footer

**Comment by orthagh** [comment]
provided css patch seems ok for me.
one point: we still don't have any footer on update, no ?

**Comment by trasher** [comment]
With CSS patch applies, we have the footer:
capture d ecran de 2017-08-21 12-16-09

**Comment by trasher** [comment]
Replace by https://github.com/glpi-project/glpi/pull/2626

**Pull request closed without merging**
