### PR TITLE
get cache options from configuration

### PR DESCRIPTION
**Pull request by remicollet**
See #2712

Tested adapters, see https://zendframework.github.io/zend-cache/storage/adapter/:
- none (cache disabled)
- APCu
- Dba
- Filesystem
- Memcache
- Memcached (igbinary as default serializer)
- Redis

To test other cache adapters: add in glpi_configs, context = core, name = cache_db or cache_trans and for value, see tested examples:

```
(empty = no cache)
{"adapter":"apcu"}
{"adapter":"redis","options":{"server":{"host":"127.0.0.1"}},"plugins":["serializer"]}
{"adapter":"filesystem"}
{"adapter":"filesystem","options":{"cache_dir":"_cache_trans"},"plugins":["serializer"]}
{"adapter":"dba"}
{"adapter":"dba","options":{"pathname":"trans.db","handler":"flatfile"},"plugins":["serializer"]}
{"adapter":"memcache","options":{"servers":["127.0.0.1"]}}
{"adapter":"memcached","options":{"servers":["127.0.0.1"]}}
```

### CODE REVIEW

**Comment by remicollet** [comment]
@tomolimo your test welcome, especially when **WinCache** is available (and **APCu** is not)

**Comment by remicollet** [comment]
Some bench results

```
+ Entities: 299598
+ Cache: disabled
+ Clear sons cache
+ Run with empty cache
> time: 2.7468
+ Run with populated cache
> time: 2.6772
+ Done

+ Entities: 299598
+ Cache: Zend\Cache\Storage\Adapter\Apcu
+ Clear sons cache
+ Run with empty cache
> time: 2.8290
+ Run with populated cache
> time: 0.0335
+ Done

+ Entities: 299598
+ Cache: Zend\Cache\Storage\Adapter\Memcache
+ Clear sons cache
+ Run with empty cache
> time: 3.0366
+ Run with populated cache
> time: 0.1195
+ Done

+ Entities: 299598
+ Cache: Zend\Cache\Storage\Adapter\Redis
+ Clear sons cache
+ Run with empty cache
> time: 2.9524
+ Run with populated cache
> time: 0.1247
+ Done
```

**Comment by tomolimo** [comment]
Hello,
At start of GLPI, I got these errors:
```
Uncaught Zend\Cache\Exception\RuntimeException: wincache_ucache_add('glpi_cache_db_9.3-dev:glpi_entities_ancestors_cache_0', <array>, 0) failed in C:\Projects\glpi-master\vendor\zendframework\zend-cache\src\Storage\Adapter\WinCache.php:300

Stack trace:

#0 C:\Projects\glpi-master\vendor\zendframework\zend-cache\src\Storage\Adapter\AbstractAdapter.php(790): Zend\Cache\Storage\Adapter\WinCache->internalAddItem('glpi_entities_a...', Array)

#1 C:\Projects\glpi-master\inc\dbutils.class.php(874): Zend\Cache\Storage\Adapter\AbstractAdapter->addItem('glpi_entities_a...', Array)

#2 C:\Projects\glpi-master\inc\dbutils.class.php(558): DbUtils->getAncestorsOf('glpi_entities', Array)

#3 C:\Projects\glpi-master\inc\db.function.php(739): DbUtils->getEntitiesRestrictRequest('OR', 'glpi_profiles_r...', '`glpi_profiles_...', 0, true, false)

#4 C:\Projects\glpi-master\inc\reminder.class.php(255): getEntitiesRestrictRequest('OR', 'glpi_profiles_r...', '', '', true)

#5 C:\Projects\glpi-master\inc\reminder.class.php(1074): Reminder
```

and


```
Uncaught Zend\Cache\Exception\RuntimeException: wincache_ucache_add('glpi_cache_db_9.3-dev:glpi_entities_ancestors_cache_0', <array>, 0) failed in C:\Projects\glpi-master\vendor\zendframework\zend-cache\src\Storage\Adapter\WinCache.php:300

Stack trace:

#0 C:\Projects\glpi-master\vendor\zendframework\zend-cache\src\Storage\Adapter\AbstractAdapter.php(790): Zend\Cache\Storage\Adapter\WinCache->internalAddItem('glpi_entities_a...', Array)

#1 C:\Projects\glpi-master\inc\dbutils.class.php(874): Zend\Cache\Storage\Adapter\AbstractAdapter->addItem('glpi_entities_a...', Array)

#2 C:\Projects\glpi-master\inc\dbutils.class.php(558): DbUtils->getAncestorsOf('glpi_entities', Array)

#3 C:\Projects\glpi-master\inc\db.function.php(739): DbUtils->getEntitiesRestrictRequest('OR', 'glpi_profiles_r...', '`glpi_profiles_...', 0, true, false)

#4 C:\Projects\glpi-master\inc\reminder.class.php(255): getEntitiesRestrictRequest('OR', 'glpi_profiles_r...', '', '', true)

#5 C:\Projects\glpi-master\inc\reminder.class.php(843): Reminder:
```

**Comment by tomolimo** [comment]
Hello again,
The root cause is the returned code of wincache-ucache-add() (see http://php.net/manual/en/function.wincache-ucache-add.php) where it is explained that if key is already present then it will fail (i.e.: returns false). From PHP doc : 

> If a variable with same key is already present the function will fail and return FALSE.

 regards,
Tomolimo

**Comment by tomolimo** [comment]
To fix the issue with Wincache, I propose to change this line 
https://github.com/glpi-project/glpi/blob/9d24eaeb8a5a75203c6e69cc9d938fcf25a8a0d0/inc/dbutils.class.php#L762
into `$GLPI_CACHE->setItem($ckey, $sons);`

and this line https://github.com/glpi-project/glpi/blob/9d24eaeb8a5a75203c6e69cc9d938fcf25a8a0d0/inc/dbutils.class.php#L874 into `$GLPI_CACHE->setItem($ckey, $sons);`

regards,
Tomolimo

**Comment by trasher** [comment]
https://github.com/glpi-project/doc/issues/17 for doc

**Pull request merged**
