### PR TITLE
Assign licenses to users

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24476

Allow assigning software licenses to users.

UserEcho:
https://glpi.userecho.com/communities/1/topics/928-assign-license-to-a-user

### CODE REVIEW

**Comment by cedric-anne** [comment]
IMHO, mixing assets and `User` in `$CFG_GLPI['software_types']` may result in unexpected side effects. Also, I guess people would want to assign licence to both user and its computer, and in this case, having distinct tabs (one for assets that have the software installed, and one for users that are using the license) would probably be more easier to understand.

**Comment by cconard96** [comment]
This will be handled differently so I'll close this PR.

**Comment by AdrienClairembault** [comment]
@cconard96 was this merged in another PR or cancelled ?

**Comment by cconard96** [comment]
AFAIK, cancelled in favor of a more comprehensive rework of license management later (not done).
I certainly didn't do anything more with this since this PR was closed.

**Pull request closed without merging**
