### PR TITLE
API: Add text search for limit getItems endpoint

### PR DESCRIPTION
**Pull request by orthagh**

### CODE REVIEW

**Comment by orthagh** [comment]
For information, i target 9.1.1 as you could see.
The need is to replicate the feature of autocomplete of dropdowns in an external application.

It's an enchancement or rather a hole filling but not a BC, imo.

**Comment by trasher** [comment]
I do notice you've requested a merge into the 9.1; but you only add a new parameter wih a default value, this is ok for me; nothing will be broken :)

**Comment by trasher** [comment]
@orthagh could you rebase your branch to solve the conflict please? If you could squash your commit at the same time; I'll merge this one.

**Comment by orthagh** [comment]
rebased

**Comment by newls** [comment]
There's something that appear strange to me today,
it looks like the ID searchoption of (per example) Ticket provides only "contains" as available searchtype, which seems weird to me as I think a search by id is more likely to be done with the "equals" searchtype.
Whatever if "contains" is provided or not for id lookup, it isn't the most important part.
But wouldn't it be normal that the "equals" searchtype was provided aswell ?

This is the ID searchoption I get when doing

`GET /listSearchOptions/Ticket`

screenshot_2016-11-11_16-01-40

**Pull request merged**
