### PR TITLE
add authtype when create user by SSO

### PR DESCRIPTION
**Pull request by eltharin**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by orthagh** [comment]
Hello @eltharin 

Thank you for your contribution.
As checking your pr, i disagree with the added line.

In case of sso with a user existing in ldap, we need to have a authtype = LDAP not EXTERNAL.
I'm not sure if actual case fill the value of authtype or keep it empty.

We recently change on the master a behavior which automaticaly changed the authtype of an existing user from LDAP to external.
Now, the authtype field keeps LDAP type.

**Comment by eltharin** [comment]
hello @orthagh 
Avant d'avoir mis EXTERNAL j'avais mis LDAP, mais lors de l'envoi de mails, ca forcait en noauto=1 dans l'URL. en mettant external, il met en réalité Externe + LDAP et du coup le SSO fonctionne encore.

Du coup si maintenant ça marche, nikel!

**Comment by trasher** [comment]
Could you please use english in tckets and PR so everyone can understand? Thank you :)

**Comment by orthagh** [comment]
For NoAuto=1, the pr #1760 merged in master should fix the issue.

Could you push the change for LDAP and we will merge this pull request ?

**Comment by trasher** [comment]
BTW, if tis is a bugfix; it should maybe reach the 9.1/bugfixes branch, and not master.

**Comment by orthagh** [comment]
i close this, as initial issue is already fixed

**Pull request closed without merging**
