### PR TITLE
rights for tickettask - fixed #7200

### LINKED ISSUE #7200: Right for ticket task
I can create a task but i can't change it after creation.

### PR DESCRIPTION
**Pull request by yllen**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #7200

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

Unless I missed something, it means that it will give you ability to update task created by another person. In this case, I disagree with this change.

Regards

**Comment by trasher** [comment]
No feedback from a while, closing; this does not seems to be the right fix.

**Comment by yllen** [comment]
Yes i thing you missing something because if you are not the author of the task you don't have the icon to edit it.
My PR, added just the button to save change like displayed in copy under past

Capture d’écran de 2020-07-20 19-54-58

**Comment by cedric-anne** [comment]
> Yes i thing you missing something because if you are not the author of the task you don't have the icon to edit it.

Form is not the only entry point of update methods. If you change the update check, you may give unwanted update rights in plugins, API, ...

**Comment by yllen** [comment]
OK. So i purpose to change the control to display the update button (it's a specific function for tickettask).
change
if ($params['canedit'] && $this->can($ID, UPDATE)) {
by
if ($params['canedit'] && self::canUpdateItem()) {
ShowFormButton is only used for form, no?

**Comment by cedric-anne** [comment]
Using `$this->canUpdateItem()` seems more logical to me. I do not even know why it is not already used.
By the way, I guess the same problem appears for followup object, as the `showFormButton` does almost the same as in ticket tasks.

**Comment by yllen** [comment]
Done

**Pull request closed without merging**
