### PR TITLE
Fix installation

### LINKED ISSUE #3997: GLPI 9.3 installing from tarball issue
Hi @trasher ,
while installing ( fresh ) or upgrading 9.3 from tarball the installation stops at this step testing DB engine. cant proceed after that , please refer the screen shots.
image

### PR DESCRIPTION
**Pull request by AnaelMobilia**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none

  - Fix install which silently break
  - Fix bad CSS & JS URL

Replace PR #3940 
Fix #3997

### CODE REVIEW

**Comment by trasher** [comment]
> I think that it is responsability of the displayCheckDbEngine function to check if it is possible to do the check. Maybe it should display a warning like Unable to check DB engine since database connection is not established..

If you display a warning during the install process, we'll have reports and help requests about it; so I guess it is better to not display anything on the install at this time.

**Comment by trasher** [comment]
> The step3 function of the install process should also include this check.

Agree with that. Fact is the check while installing must be done elsewhere, not dropped.

**Comment by trasher** [comment]
I've added the check for installation

**Comment by trasher** [comment]
@cedric-anne, @AnaelMobilia  are you ok with my change?

**Comment by AnaelMobilia** [comment]
@trasher Seem good :-)
I made a minor commit to fix doc (int / integer)

Regards

**Comment by trasher** [comment]
Great, thanks for the feedbacks. This one is OK for me.

**Pull request merged**
