### PR TITLE
Update reservation.class.php

### PR DESCRIPTION
**Pull request by tidji31**
Not allow to create reservations in the past

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Comment by trasher** [comment]
Hello,

This sounds correct from a code point of view; but I really don't know if we should add that restriction :/

**Comment by tidji31** [comment]
Hello,
It is possible to block dates prior to a defined date, so that the user cannot click on those days?

**Comment by cedric-anne** [comment]
Hi,

You can add the ability to tweak this in a new entry in the general configuration, but we want administrator to be able to disable it.

Regards

**Comment by cedric-anne** [comment]
I close this PR as it seems stale. Feel free to reopen it if you want to complete it.

**Pull request closed without merging**
