### PR TITLE
Fix Dashboard Rights -Undefined index

### PR DESCRIPTION
**Pull request by tsmr**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12005

### CODE REVIEW

**Comment by trasher** [comment]
I think the front file should handle not logged requests

**Comment by tsmr** [comment]
Yes i need to add Session::checkLoginUser(); too

**Comment by orthagh** [comment]
Warning : make sure to not break embed/public feature when adding a session check on the front file

**Comment by cedric-anne** [comment]
@tsmr I put this PR to draft, as it does not seems to be finished (according to comments).

**Comment by trasher** [comment]
Ping @tsmr?

**Comment by cedric-anne** [comment]
Hi,

I close this PR as it seems abandonned. Feel free to reopen and complete it.

**Pull request closed without merging**
