### PR TITLE
Fixed unused variable $values

### PR DESCRIPTION
**Pull request by tomolimo**
Replaced by $params

### CODE REVIEW

**Comment by tomolimo** [comment]
No it isn't see #1200 and PR #1689

**Comment by trasher** [comment]
OK then. I've seen that this line has been added in https://github.com/glpi-project/glpi/commit/182cc772ed584da21ad51805fa57200e39309ee7; and have never been used.

I guess the correct fix would be to drop the line. @orthagh?

**Comment by orthagh** [comment]
lgtm

**Comment by tomolimo** [comment]
> Also, remove the $values['right'] = 'all' into the showFormHelpdesk function

can't do that, as it is set to 'id' above in the function, then we must keep it.

> Fix the $values/$params and set the default value to 'all'.

Ok

**Pull request closed without merging**
