### PR TITLE
Switch to phpunit (part 2)

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
Seems OK, except that the test suite exits with a 255 code :/

**Comment by cconard96** [comment]
Hitting a PHP memory limit that isn't triggering a clear error message? The last PHPUnit PR was only using 50MB, but this one is 150MB. Atoum tests are overriding the default memory limit, so maybe these need to as well.

**Comment by cedric-anne** [comment]
> Hitting a PHP memory limit that isn't triggering a clear error message? The last PHPUnit PR was only using 50MB, but this one is 150MB. Atoum tests are overriding the default memory limit, so maybe these need to as well.

I increased the limit as it fixes an issue on my local machine, but it does not fix the problem. I also have the 255 result code on my machine.
image

**Comment by cedric-anne** [comment]
> Seems OK, except that the test suite exits with a 255 code :/

It was due to the GLPI exception handler. I disabled it in the test suite context.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
