### PR TITLE
fix(inventory): fix search / link between stacked switch and relateports

### PR DESCRIPTION
**Pull request by stonebuzz**
Since -> https://github.com/glpi-project/glpi/pull/13359

It is now possible to find the chassis linked to the port as follows (especially if ```ifname``` is related to index ```0``` -> ```Gi0/1```) 

```port->ifnumber``` -> ```component->index``` -> ```component->chassis```

It's works if the ```ifnumber``` 

```xml
<PORT>
  <IFDESCR>GigabitEthernet 0/1</IFDESCR>
  <IFNAME>GigabitEthernet 0/1</IFNAME>
  <IFNUMBER>177783810</IFNUMBER>
  <IFTYPE>6</IFTYPE>
</PORT>
```
is identical to the ```index```

```xml
<COMPONENT>
  <CONTAINEDININDEX>1</CONTAINEDININDEX>
  <INDEX>177783810</INDEX>
  <TYPE>port</TYPE>
</COMPONENT>
```

but it's not working if the ```ifnumber``` is not identical to the ```index```

```xml
<PORT>
  <IFDESCR>Unit: 1 Slot: 0 Port: 1 Gigabit - Level</IFDESCR>
  <IFNAME>Gi1/0/1</IFNAME>
  <IFNUMBER>1</IFNUMBER>
  <IFTYPE>6</IFTYPE>
</PORT>
```

```xml
<COMPONENT>
  <CONTAINEDININDEX>3</CONTAINEDININDEX>
  <DESCRIPTION>Unit: 1 Slot: 0 Port: 1 Gigabit - Level</DESCRIPTION>
  <FRU>2</FRU>
  <INDEX>4</INDEX>
  <NAME>Gi1/0/1</NAME>
  <TYPE>port</TYPE>
</COMPONENT>
```

So I went back to the original problem.
the mapping of the ports referring to the chassis starting ```0``` (```Gi0/1```, ```GigabitEthernet 0/1```)

first we need to change ```regex``` to match ```Gi0/1``` or ```GigabitEthernet 0/1``` and other format
see : https://regex101.com/r/rOWai2/1

When related port icontain a ```0``` just increment index to match ```stack_id```
because GLPI start index at ```1```

```php
    /**
     * Get detected switches (osrted by their index)
     *
     * @return array
     */
    public function getStackedSwitches(): array
    {
        $components = $this->extra_data['network_components'] ?? [];
        if (!count($components)) {
            return [];
        }

        $switches = [];
        $stack_number = 1;
        foreach ($components as $component) {
            switch ($component->type) {
                case 'chassis':
                    if (property_exists($component, 'serial')) {
                        $component->stack_number = $stack_number;
                        $switches[$component->index] = $component;
                    }
                    $stack_number++;
                    break;
            }
        }

        ksort($switches);
        return $switches;
    }
```

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
I do not even know how it is supposed to work.

**Comment by po1vo** [comment]
The regexp approach is fundamentally broken: there's just no way to differentiate between a stacked switch and a switch with multiple line cards. The fact that `port->ifindex` equals to `component->index` has been true for Cisco and Juniper so far as i can tell.

**Comment by GuidoWilden** [comment]
Tried this with our stacked switches and unfortunately still only one switch (the last/sixth in the stack) shows in the inventory.

**Comment by GuidoWilden** [comment]
I can not share these files publicly here I'm afraid. I have however shared them previously privately with g-bougard.

**Comment by GuidoWilden** [comment]
I believe the issue was created starting with our problem.

**Comment by stonebuzz** [comment]
@GuidoWilden 

> Tried this with our stacked switches and unfortunately still only one switch (the last/sixth in the stack) shows in the inventory.

the fix is in the agent (currently unreleased).

But following this fix, we have detected a problem with the management of network ports -> hence this PR

**Comment by g-bougard** [comment]
Hi @GuidoWilden 
can you confirm you're using a nightly build of GLPI agent ?

**Comment by GuidoWilden** [comment]
I just generated a new xml which imported correctly.
Apologies the xml I imported this morning must have been generated with an earlier build of the agent. This all seems to be working. Thank you for your help.

**Review by g-bougard — APPROVED** [review]

**Comment by r0bertk** [comment]
Hello, Stack switch
I have switches in the Huawei S5731-S48T4X stack. Glpi does not show network ports. It only shows port management.
Does not work on glpi version 10.0.7 and on dev version 10.0.8 from 02/06/2023. My version of Glpi-Agent nightly is: GLPI-Agent-1.5-gitf1a94d56-x64.
Please help

**Pull request merged**
