### PR TITLE
Fix relative path for themes stored outside of GLPI_ROOT + cache on last update

### PR DESCRIPTION
**Pull request by AdrienClairembault**
`str_replace(GLPI_ROOT, '', $path);` won't work if `GLPI_THEMES` is outside `GLPI_ROOT`.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28015

### CODE REVIEW

**Comment by trasher** [comment]
Why not just replace `GLPI_ROOT` with `GLPI_THEMES`?

**Comment by AdrienClairembault** [comment]
> Why not just replace `GLPI_ROOT` with `GLPI_THEMES`?

The path will be exposed on the client side with an http request to `css.php`, thus we need to avoid disclosing any absolute path that would expose the server directory tree.

**Comment by trasher** [comment]
I do not understand. This is a str_replace, no absolute path will be exposed; GLPI_ROOT was not.

**Comment by AdrienClairembault** [comment]
Note: changes to `front/css.php` could probably be done to remove the need for a relative URL by adding an extra `&theme=true` param which will set the base dir to `GLPI_THEMES`

Not sure why it wasn't done that way originally, maybe some constraint I'm not aware of ?

**Comment by AdrienClairembault** [comment]
> I do not understand. This is a str_replace, no absolute path will be exposed; GLPI_ROOT was not.

`GLPI_ROOT` was not exposed because it was replaced by an empty string, leaving only the relative path to the theme directory (`/files/_themes/my_theme.css`).
However, this only work if `GLPI_THEMES` is a subfolder of `GLPI_ROOT` (= `GLPI_THEMES` contains `GLPI_ROOT`).

If you replace `GLPI_THEMES` completely you end up with `/my_theme.css`, which `front/css.php` wont load because it doesn't know you are requesting a theme (it could be a css file from a plugin; you need an exact path to the file).

Thus my alternate proposal of adding an additional query parameter to `front/css.php` to indicate we want to load a theme.
Then we can only send the theme name and `front/css.php` will know to look for it in `GLPI_THEMES` + the core theme folder, without the need for a full qualified path.

**Comment by AdrienClairembault** [comment]
After trying for a while the alternate solution seems possible but difficult to integrate properly without rewriting a lot of code, I think this one this better for now.

**Comment by AdrienClairembault** [comment]
Second commit handle some cache issue when custom themes are modified.

Our usual URL key based on GLPI version is not enough here since the theme files may be modified in between versions by the system administrator or some plugins.

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
