### PR TITLE
add tests to getById

### PR DESCRIPTION
**Pull request by btry**
tests for CommonDBTM::getById() (branch master  only)

### CODE REVIEW

**Comment by trasher** [comment]
Duplicates #9268?

**Comment by btry** [comment]
No, it is not a duplicate : the implementation of the method is very different between branches 9.5/bf and master. Then I created a PR for each branch

**Comment by cedric-anne** [comment]
> No, it is not a duplicate : the implementation of the method is very different between branches 9.5/bf and master. Then I created a PR for each branch

OK, so please rebase on master and adapt the test that was merged from 9.5/bugfixes branch.

**Comment by btry** [comment]
done, @cedric-anne

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
