### PR TITLE
To add pre_show, post_show for items and tabs

### PR DESCRIPTION
**Pull request by tomolimo**
Issue #685 
Added pre_show_tab, post_show_tab
Added pre_show_item, post_show_item

Commit for example plugin will follow

### CODE REVIEW

**Comment by tomolimo** [comment]
done in Example plugin: https://github.com/pluginsGLPI/example/pull/6

**Comment by orthagh** [comment]
Hello @tomolimo 

Your PR in example plugin fail to merge, could you check ?
Could you also complete this page : https://github.com/pluginsGLPI/example/wiki/0.90.1-to-0.91

**Comment by tomolimo** [comment]
> Your PR in example plugin fail to merge, could you check ?

Where? Could you point me to an error message or else?

**Comment by orthagh** [comment]
https://github.com/pluginsGLPI/example/pull/6

image

**Comment by tomolimo** [comment]
Yes I saw this but...:)
I'll check that and push the corrected files

**Comment by tomolimo** [comment]
I've merged and pushed the modifications into Example.
See: https://github.com/pluginsGLPI/example/commit/1db4385559a244768e077a879a8ccfcd81e9bce7

**Comment by orthagh** [comment]
Ok great.

Think about the wiki also, thank you

**Comment by tomolimo** [comment]
on going :)

**Comment by tomolimo** [comment]
Done

**Pull request merged**
