### PR TITLE
Prevent redirection to aim an other site than this GLPI

### PR DESCRIPTION
**Pull request by Etiennef**
Fix proposition for issue I created : #506 
Error message cannot be translated, but it is just a principle proposition.

### CODE REVIEW

**Comment by orthagh** [comment]
Thank you for your PR

**Comment by Etiennef** [comment]
Uhh, I failed somewhere. The line 1832 
if ($link = preg_match('/https?:\/\/.+/',$decoded_where)) {
should have changed into 
if ($link = preg_match('/(https?:\/\/[^\/]+)\/.+/',$decoded_where, $matches)) {

Otherwise the matches[1] just after makes no sense.

It's on my local repository, but it seems I failed to push it. I don't know how I did it, I'm not sure I'd be able to do it if I wanted. Just found it out because it makes me a conflict when I try to update my files.

**Comment by orthagh** [comment]
Correction pushed.

Anyway, for this 
> It's on my local repository, but it seems I failed to push it. I don't know how I did it, I'm not sure I'd be able to do it if I wanted. Just found it out because it makes me a conflict when I try to update my files.

You can't push to a **merged** branch.
You need to redo a new branch and a new "pull request".

**Comment by yllen** [comment]
@Etiennef 
What is $matches?

**Comment by Etiennef** [comment]
It is the result of the regexp (the matched patterns). It's designed to check the domain of the redirection and allow it only if it redirects somewhere in this GLPI instance. Otherwise it would open GLPI to an open redirection vulnerability
I failed my pull request, the line where it was defined was missing, but @orthagh corrected it here : 8fbf6ef

**Pull request merged**
