### PR TITLE
Add test for search engine

### PR DESCRIPTION
**Pull request by ddurieux**
I have added tests 
* test search all fields (in getSearchOptions) to be sure not have SQL errors
* test search with all META in itemtypes use meta to be sure not have SQL errors

So I have fixed more than 10 bugs in the search engine

### CODE REVIEW

**Comment by trasher** [comment]
That sounds great, even if I'm not familiar enough with the search stuff to review this one :)

One question: is the change you made on the empty schema required? I can't find it used anywhere, and it would be a blocker to integrate this PR in 9.1 release since db is freezed.

**Comment by ddurieux** [comment]
This field _is_task_ in empty.sql has missed in old commit, so you can find it in the update file: https://github.com/glpi-project/glpi/blob/master/install/update_0905_91.php#L816

**Comment by trasher** [comment]
OK, well catched :)

**Comment by orthagh** [comment]
Ok, for me, i tested with problematic queries i met in the past without issues.
I merge.

Could you detail the "10 bugs" you mention ? I'm curious about them.

**Comment by ddurieux** [comment]
* the is_tasks of glpi_groups forgotten in fresh install
* the software join disabled in cli / cron mode
* the _time_to_own_ and _time_to_own + progress_ in problems but it's only for tickets (the fields not exists in problems)
* same for _Time to own exceedeed_
* the field _rights_ in table glpi_profilerights not right writen in getSearchOptions (_right_ instead _rights_) 
* add _complexjoin_ in meta, without that may have too many sql errors 
* clean some _global $CFG_GLPI;_ in search.class.php not used
* and so all SQL errors it fixed, I have about 8 sql errors in various searches (not test all manually)

**Pull request merged**
