### PR TITLE
'serach_config' doesn't look like a right name for a module

### PR DESCRIPTION
**Pull request by tomolimo**
'serach_config' doesn't look like a right name for a module

### CODE REVIEW

**Comment by tomolimo** [comment]
More than that: I have real doubts about utility of 
`Session::haveRightsOr('search_config', array(DisplayPreference::PERSONAL,
                                             DisplayPreference::GENERAL));`

which leads to nothing when rights is not OK, nor when OK

**Comment by tomolimo** [comment]
up!

**Comment by orthagh** [comment]
We can't remove the right to display page (useless in this case), but we can add a right error in this case.
I close this pr.
I did a more general fix for this (and corrected the typo on search_config)

**Comment by tomolimo** [comment]
Thank you,

**Comment by yllen** [comment]
a know-base item can be read without being log in.
You can import ldap group with a cron

**Pull request closed without merging**
