### PR TITLE
Impact badges

### PR DESCRIPTION
**Pull request by AdrienClairembault**
### Graph view

image

Show a badge with the number of ongoing incidents for this asset.
The badge color match the highest priority among the incidents with some tweaks to ensure a decent level of contrast (default colors for the lowest priorities are too close to white to be directly used).
The badge can be clicked to access the ongoing incident list.

### List view

image

Show the number of ongoing incidents, problems and changes (if any).
Color match the highest priority level.
The cells can be clicked to access the ongoing incidents/problems/change list for the given asset.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
Waiting for merge of #6664 to rebase and set to "Ready for review".

**Comment by cedric-anne** [comment]
I am not in favor of opening a new tab with ongoing ticket list when clicking on the badge for multiple reasons.
1. Nothing explains what is the target of this link, we should at least have a tooltip that indicates that clicking on this will open ongoing ticket list,
2. Why using a new tab instead of just changing current page ?

**Comment by orthagh** [comment]
I agree with @cedric-anne.

a[target=_blank] should be avoided nowadays, user can open in a new tab himself, we should not force this kind of behavior.

But maybe the lib don't permits that ?

**Comment by cedric-anne** [comment]
Links in canvas are not natively supported, but maybe it can be done using https://github.com/cytoscape/cytoscape.js-popper to display a tooltip containing a link to target page when mouse hovering the badge.

**Comment by AdrienClairembault** [comment]
Click on badges now change the current page, middle click or ctrl + click open in a new tab.

**Pull request merged**
