### PR TITLE
fix(kb): missing article in search

### PR DESCRIPTION
**Pull request by Rom1-B**
The search result only showed articles without a category.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Comment by Piputrrrr** [comment]
thank you work perfectly for me :)

**Comment by troublestarter** [comment]
Can someone tell me how to install the nightlies ?

**Comment by cedric-anne** [comment]
> Can someone tell me how to install the nightlies ?

You can get the archive from this URL: https://nightly.glpi-project.org/glpi/10.0.tar.gz
Then you can install it like any other GLPI version.

**Comment by troublestarter** [comment]
Thanks you.

**Comment by M9-Doppler** [comment]
The KnowbaseItem.php fix work perfecty for me.
Thank you very much !

**Comment by stylnchris** [comment]
would you have to install the whole nightly release to fix this or can the KnowBaseItem.php file be replaced in the /src/ folder to get this working again? 

I tried replacing the file and it yielded the same result.

**Comment by trasher** [comment]
Patching a single file is often not enough. New release including this fix will be available soon anyway.

**Pull request merged**
