### PR TITLE
fix display MA - see #2574

### PR DESCRIPTION
**Pull request by yllen**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2574

### CODE REVIEW

**Comment by trasher** [comment]
A CSS fix would probably be preferable

**Comment by yllen** [comment]
I don't understand. It's not a CSS problem but space missing before submit button

**Comment by yllen** [comment]
So you must delete all <br> in source code?
I let you correct this issue.

**Comment by trasher** [comment]
No; I've never said we have to change all bad practices in the whole code.
Just trying not to add new ones just because it's the way it's been done before.

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/pull/2666

**Pull request closed without merging**
