### PR TITLE
Add ability to mention users in ITIL objects

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Add ability to mention users in ITIL objects.

image

Remaining work to do:
- [x] create a "you have been mentionned" notification;
- [x] send notification when users are mentionned;
- [x] replace mention by a link to user on rendering;
- [x] tweak styles;
- [x] implement feature on followups, solutions and changes and problems;
- [x] ~~add a configuration to disable this feature ?;~~
- [x] add tests.

### CODE REVIEW

**Comment by cedric-anne** [comment]
Only style tweaking and unit tests are missing, so code should be reviewable/testable now.

**Comment by orthagh** [comment]
i just checked the feature from an ux pov.
The image like behavior seems not fully ok.

If the mention is the first tag in the textarea, it's impossible to go before it.
In fact, it's impossible to go just before it but it's very visible with start of document.

Apart this, i think the background is very dark currently (and contrast very small).
Maybe it's to be compatible with darker palette. For this case, maybe we can add a css class which can be overrided by the theme.

one thing i just though, if notification is disabled in glpi (when using helpdesk, it's probably not the case) maybe we can also disable the feature ? or we want to keep the style

**Comment by cedric-anne** [comment]
> i just checked the feature from an ux pov.
> The image like behavior seems not fully ok.
> 
> If the mention is the first tag in the textarea, it's impossible to go before it.
> In fact, it's impossible to go just before it but it's very visible with start of document.
> Ctrl+A is impossible also

I completely removed this "image like behaviour" and finally find another solution to handle inputs that alter existing mentions. Code is simplier and UX is better as there is no more need to prevent "selection" of the user mention.

> 
> Apart this, i think the background is very dark currently (and contrast very small).
> Maybe it's to be compatible with darker palette. For this case, maybe we can add a css class which can be overrided by the theme.

I updated a bit styles, but it can still be tweaked. I have no really idea about the styles we should apply. The current styles makes testing easier, as we directly see if a node contains attributes that will trigger a notification, but, for instance, on Mattermost, there is no style applied.

> 
> one thing i just though, if notification is disabled in glpi (when using helpdesk, it's probably not the case) maybe we can also disable the feature ? or we want to keep the style

I added this check. Indeed, there is no need to enable this feature if notifications are disabled.

**Review by orthagh — COMMENTED** [review]
current implementation is almost ok for merge.
noneditable content is perfect in behavior.

todo:
- private objects should not mention users without the adequate right
- tests

**Comment by cedric-anne** [comment]
> todo:
> 
> * private objects should not mention users without the adequate right
> * tests

Done.

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
