### PR TITLE
Error research ticket resquesttypes

### PR DESCRIPTION
**Pull request by amma35**
see #1452

### CODE REVIEW

**Comment by balike** [comment]
I am out of the office until 2017.01.02.

I'm on holiday, won't be able to check my mails regularly. 
On ICT Operational issues please contact helpdeskHU, in other topics please consult Gabor PAL. 


Note: This is an automated response to your message  "[glpi-project/glpi] Error research ticket resquesttypes (#1461)" sent on 12/23/2016 2:00:22 PM. 

This is the only notification you will receive while this person is away.Member of KBC Group

KBC Securities Disclaimer

http://data.kbcsecurities.be/Disclaimer/Disclaimer.html

**Comment by trasher** [comment]
Hello @amma35; I've rebased your branch to drop extra commits and edit the commit message.

For future PR, please try to add a "fix #issuenum" in your commit messages so ticket can be automatically closed (when commit really should close if, of course ;)

Thank you!

**Comment by balike** [comment]
I am out of the office until 2017.01.02.

I'm on holiday, won't be able to check my mails regularly. 
On ICT Operational issues please contact helpdeskHU, in other topics please consult Gabor PAL. 


Note: This is an automated response to your message  "Re: [glpi-project/glpi] Error research ticket resquesttypes (#1461)" sent on 12/30/2016 8:25:14 AM. 

This is the only notification you will receive while this person is away.Member of KBC Group

KBC Securities Disclaimer

http://data.kbcsecurities.be/Disclaimer/Disclaimer.html

**Comment by balike** [comment]
I am out of the office until 2017.01.02.

I'm on holiday, won't be able to check my mails regularly. 
On ICT Operational issues please contact helpdeskHU, in other topics please consult Gabor PAL. 


Note: This is an automated response to your message  "Re: [glpi-project/glpi] Error research ticket resquesttypes (#1461)" sent on 12/30/2016 8:25:06 AM. 

This is the only notification you will receive while this person is away.Member of KBC Group

KBC Securities Disclaimer

http://data.kbcsecurities.be/Disclaimer/Disclaimer.html

**Comment by balike** [comment]
I am out of the office until 2017.01.02.

I'm on holiday, won't be able to check my mails regularly. 
On ICT Operational issues please contact helpdeskHU, in other topics please consult Gabor PAL. 


Note: This is an automated response to your message  "Re: [glpi-project/glpi] Error research ticket resquesttypes (#1461)" sent on 12/30/2016 8:25:34 AM. 

This is the only notification you will receive while this person is away.Member of KBC Group

KBC Securities Disclaimer

http://data.kbcsecurities.be/Disclaimer/Disclaimer.html

**Comment by amma35** [comment]
Ok, Thank you!

**Comment by balike** [comment]
I am out of the office until 2017.01.02.

I'm on holiday, won't be able to check my mails regularly. 
On ICT Operational issues please contact helpdeskHU, in other topics please consult Gabor PAL. 


Note: This is an automated response to your message  "Re: [glpi-project/glpi] Error research ticket resquesttypes (#1461)" sent on 12/30/2016 8:35:28 AM. 

This is the only notification you will receive while this person is away.Member of KBC Group

KBC Securities Disclaimer

http://data.kbcsecurities.be/Disclaimer/Disclaimer.html

**Pull request merged**
