### PR TITLE
Fix TinyMCE word-wrap

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Internal ref 19501.

Set word-wrap for tinymce content.

Before:
image

After:
image

I've added the new css after the minified content like this is done in `skin.min.css`.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by orthagh** [comment]
I disagree to set the change in the min file. We should have our fixes in our files (like styles.scss)

**Comment by cedric-anne** [comment]
You should not alter this `skin` file, as it was a copy of an external lib file an may be replaced in the future.
You should put this style somewhere here: https://github.com/glpi-project/glpi/blob/9.4/bugfixes/css/styles.scss#L469

**Comment by AdrienClairembault** [comment]
We can't use `styles.scss` as this is an iframe.
I'll inject a new file in the iframe head instead.

PS: we should remove the whole css/tiny_mce dir in 9.5 and use the one supplied by npm.

**Comment by cedric-anne** [comment]
> Note for myself: do not merge this one in 9.5; need another PR.
It looks also valid on 9.5 branch. @AdrienClairembault can you confirm ?

**Comment by AdrienClairembault** [comment]
> It looks also valid on 9.5 branch. @AdrienClairembault can you confirm ?

It is valid for 9.5 too (switch to npm does not affect this).

**Comment by cedric-anne** [comment]
I cherry-picked on 9.5 branch and fix works.

**Pull request merged**
