### PR TITLE
Fix#12455

### PR DESCRIPTION
**Pull request by tomolimo**
Hello,
1. Fixed issue with the IS NOT for requesters, watchers and technicians for Ticket, Change and Problem
2. Improved "contains" searches for User by adding to the group_concat the firstname and realname of users (Search::addSelect).
3. Added Change table for the Search::addSelect when glpi_users.name field is searched.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12455

### CODE REVIEW

**Comment by cedric-anne** [comment]
@tomolimo

Sorry for the late reply, we are quiet busy.

As far as I understand, there a 3 changes on your PR that could be reviewed separately. Could you split your proposal into multiple PRs, so it could probably be easier to review ?

Thanks

**Comment by tomolimo** [comment]
Added PR #13073

**Comment by tomolimo** [comment]
Added PR #13081

**Comment by tomolimo** [comment]
Added #13083

**Comment by cedric-anne** [comment]
Replaced by #13073 #13081 #13083.

**Pull request closed without merging**
