### PR TITLE
Fix #4771 - Move order of rules process

### LINKED ISSUE #4771: Ticket rules with categories
* Steps to reproduce (which actions have you made) :
Create two groups :
- The first group at the root entity with child entity option to "yes",
- The other group at a child entity 

Create One category at the root entity with : 
- The "Group in charge of the hardware" option selected with the first created group
- Child entities option to "Yes"

Create one rule with : 
- Criteria : Technician group |     is     | Group of the root entity
- Action : Technician group  | Assign | Group of the child entity

--> Create a ticket (on the child entity) in selecting the newly created category .

* Expected result :
Affect the group of the child entity to the ticket

* Actual result :
Affect the group defined in the category to the ticket

It seems that the business rule process before the category rules.
I have tested with glpi 9.2.2 and 9.3.1, same result.

### PR DESCRIPTION
**Pull request by keha35**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4771

### CODE REVIEW

**Comment by trasher** [comment]
I do not know this part enough to say if proposal is correct or not btu:
1- you have CS to fix,
2- are you sure you want this fix on master only?

**Comment by keha35** [comment]
For me it need to be backported to all branches.
Business rules need to be processed at the end of all core process.

**Comment by trasher** [comment]
> For me it need to be backported to all branches.

So, please target 9.3/bugfixes branch, as explained at https://glpi-developer-documentation.readthedocs.io/en/master/sourcecode.html#in-short

**Comment by keha35** [comment]
Im' closing this pr and redo one in the 9.3/bugfixes branche

**Pull request closed without merging**
