### PR TITLE
fix(Widget): prevent undefined array key from 'multipleNumber'

### PR DESCRIPTION
**Pull request by stonebuzz**
Prevent PHP warning

```
Warning: Undefined array key 26 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 27 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 28 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 29 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
Warning: Undefined array key 30 in /mnt/diskhome/home///htdocs/src/Dashboard/Widget.php on line 419
```
Because ```multipleNumber``` can display can display as many lines as the user wants

image

but technically ```multipleNumber``` is limited to the number of characters in the alphabet (26)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Review by trasher — APPROVED** [review]
Seems correct. Any idea why it was limited to letters only?

**Comment by trasher** [comment]
(btw, test have to be adapted aswell)

**Comment by stonebuzz** [comment]
I propose to wait for @orthagh , having worked a lot on it, he might have the answer

**Comment by orthagh** [comment]
> Seems correct. Any idea why it was limited to letters only?

Linked to series management in chartist CSS, ex: 
image

Returning from vacations is hard, but i think this is fixed in main with the removal of chartist library

But searching a little, i'm pretty sure the issue didn't exist at all in multiple numbers widget.
The css from chartist adresses series with classes suffixed with [a-z] to display different colors, but as far as i checked this widget type doesn't to support multiple colors palette (or it's currently broken but i'm pretty sure it's ok), it's a flat color, or a gradient palette. The case with series color palette is not available for this widget.

So agree for the change

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
