### PR TITLE
Add rule action to skip remaining rules

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Add new global rule action for `Stop rules processing` which will tell the engine to skip all other rules in the collection.
Currently, some rule collections are set to stop after the first match but the default and the case for most is to run all matching rules. With this new option along with the existing ability to change the rule priority/order, this will give the user more control over which rules run and when they run.

This does not stop other collections from running for the same event.

### CODE REVIEW

**Review by orthagh — COMMENTED** [review]
Globally ok with this proposal, it could be usefull.
Two things:

- the wording for "Stop rules processing" may be interpreted by canceling rules changes, we may add a small precision with `(and apply changes)` or something like that (suggestions welcome)
- i don't understand the changes relative to `parent::getActions`, can you explain ?

**Comment by cconard96** [comment]
>     * the wording for "Stop rules processing" may be interpreted by canceling rules changes, we may add a small precision with `(and apply changes)` or something like that (suggestions welcome)

Would "Skip remaining rules" work better?

>     * i don't understand the changes relative to `parent::getActions`, can you explain ?
Instead of adding this new action to every rule collection that allows multiple rules to run, it is declared in the parent class and inherited.

**Comment by orthagh** [comment]
> Would "Skip remaining rules" work better?

yes completly

> it is declared in the parent class and inherited.

Indeed, i miss that in my first reading (it's the first change ...)

**Review by orthagh — APPROVED** [review]
Ok for me (after rewording)

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
