### PR TITLE
Fixes #3896

### LINKED ISSUE #3896: [9.3 beta] new service level wrong url
9.3 beta fresh install  (or upgraded from 9.2.2)
* Steps to reproduce (which actions have you made) :
setup>service level> add (+)

* Expected result :
go to glpi/front/slm.php

* Actual result :
go to glpi/**glpi**/front/slm.php

* URL of the page :
/glpifront/slm.php

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
9.3 beta ( tarball) fresh install ( but same behaviour with 9.3 upgraded from 9.2.2)

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3896

Fixes the issue with the double root in URL when trying to add a new SLM item.

### CODE REVIEW

**Comment by trasher** [comment]
I wonder if the fix is correct... There are numerous calls of `getFormURL()`, and only a few `getFromURL(false)` in the current codebase. If that was the issue, I guess it should have been reported long time ago.
But I do not have any idea of what is wrong yet :/

**Comment by cconard96** [comment]
I'm not sure. The fixes work for me, and originally I thought it was just 1 or 2 classes that had issues, but it seems to be more than that. I'm not that familiar with the source code, but I can check to see why it's working for some forms and not others later today.

The only relevant changes I saw was a commit to change some hard coded URLs to use method calls.

**Comment by trasher** [comment]
As you've stated, issue seems global, we'll need to investigate a bit on that.

**Comment by trasher** [comment]
Since I was not sure of all possible issues; I took the faultly commit, and I reviewed all the changes, changing one by one all errors introduced.
See https://github.com/glpi-project/glpi/pull/3906 (mainly the same as yours) ; thank you :)

**Pull request closed without merging**
