### PR TITLE
fullcalendar upgrade to 3.10.0

### PR DESCRIPTION
**Pull request by M-Falken**
Fullcalendar jquery plugin upgrade to the last version 3.10.0.
This is the last version with jQuery and Moment JS as a dependency.
Bugfix 3.10.0 in changelog.
See for alpha 4.0: https://fullcalendar.io/docs/v4/release-notes

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

We already have  jQuery and Moment JS in `/lib` directory, so they should not be added in `/lib/jqueryplugins/fullcalendar/lib`.

Can you remove them ? I do not see any loading instruction, so I guess these files are not even used.

Regards

**Comment by M-Falken** [comment]
Done (moment.js not so dependent for calendar in fact)
Regards

**Comment by trasher** [comment]
Hi, thanks for the PR. but this seems tool late to integrate such a change for the 9.4.0 (rc2 has been released; only bugs will get fixed).
Will wait for 9.4.0 to be released anyways.

**Comment by AnaelMobilia** [comment]
Hello,

Due to 988c642df9d38d047bf2d86a34ca70513d9825b5, the 3.10.0 version of fullcalendar is still included : 
```
        "fullcalendar": "^3.10.0",
```

Regards,
Anael

**Comment by cedric-anne** [comment]
Hi @AnaelMobilia,

This PR targets 9.4/bugfixes, and the commit you are talking about is in master branch, so this PR is still relevant.

Regards

**Comment by cedric-anne** [comment]
Hi,

Could you please squash all your commits and rebase on current state of 9.4/bugfixes ?

Regards

**Comment by trasher** [comment]
Manually merge, thanks.

**Pull request closed without merging**
