### PR TITLE
Get items from parent returns too many items

### PR DESCRIPTION
**Pull request by btry**
If a child itemtype is associated to a parent item with a foreign key (in the parent) then show only this one.

Should we do the same for parent itemtype having *itemtype* and *items_id* columns ?

### CODE REVIEW

**Comment by btry** [comment]
The issue happens when requesting something like this 

```/Computer/3/Location```

Notice this request does not provide an ID for location.

**Comment by btry** [comment]
Where clause fixed.

Now the result is consistent.

Maybe should I improve this to handle parent items having itemtype / items_id column.

**Comment by orthagh** [comment]
Ok for the last commit.
Merge waiting for your last case

**Comment by btry** [comment]
Use case for last change : 

Book at least 2 computers and try requests like 
/Reservationitem/1/Computer

**Comment by trasher** [comment]
OK, forget about the milestone, it has been set on the ticket... But this has to be rebased anyways.

**Comment by btry** [comment]
I cleaned up the PR. 

You may reopen and finish the review.

**Pull request closed without merging**
