### PR TITLE
Bug fix for Computer -> Connections ignore is_deleted flag

### PR DESCRIPTION
**Pull request by lufik**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4705 

Bug fix for Issue #4705 to 9.3/bugfix branch.

### CODE REVIEW

**Comment by trasher** [comment]
I do not agree with the proposal. Deleted items are here displayed with a different BG color, which is intended.
That was maybe not the case in older releases, this was very inconsistent (sometimes, deleted were displayed, sometimes not...).

**Comment by lufik** [comment]
Ok, I'm going to change the pull request so Monitor -> Connections will use the same logic as Computer -> Connections.

**Comment by lufik** [comment]
I wait for the decision how to fix the problem (in issue #4705).

**Comment by trasher** [comment]
i'm closing this one since this is not OK for the moment; you can reopen once this will be ok. Thank you

**Pull request closed without merging**
