### PR TITLE
Use Laminas instead of Zend; closes #6742

### LINKED ISSUE #6742: From Zend to Laminas
Because ZF is dead

See https://framework.zend.com/blog/2019-04-17-announcing-laminas.html

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes/no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #6742

### CODE REVIEW

**Comment by remicollet** [comment]
Hmmm.... I think namespace is also different (even if a polyfill exists)
Don't understand how test suite passes...

**Comment by remicollet** [comment]
Ok, haven't notice that `laminas/laminas-zendframework-bridge` is pulled by `laminas/laminas-stdlib`

Need to think a bit more about this....

* If we rely on old namespace, I think we should explicitly requires this bridge
* Else we have to switch to new namespace

Don't know yet...

**Comment by cedric-anne** [comment]
Hi,

Have you done this using a simple search and replace or have you try using https://github.com/laminas/laminas-migration ?

**Comment by trasher** [comment]
Hello,

Since the old namespace is deprecated, we should no longer use it in the core. Maybe should we require the bridge for plugins? Dunno if some do use Zend directly.

@cedric-anne I've just sed the sources.

**Comment by cedric-anne** [comment]
I ran laminas-migration tool and it just detects a mention of Zend in a unit test (see last commit).
I also run ComposerRequireChecker and, as we do not use Zend namespace anymore, adding `laminas/laminas-zendframework-bridge` in our dependencies is not required anymore.

**Comment by remicollet** [comment]
LGTM

**Comment by trasher** [comment]
> I also run ComposerRequireChecker and, as we do not use Zend namespace anymore, adding `laminas/laminas-zendframework-bridge` in our dependencies is not required anymore.

Brigdge package is required from laminas stdlib package.

**Pull request merged**
