### PR TITLE
Feature/send document from api

### PR DESCRIPTION
**Pull request by btry**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | not tested yet
| Fixed tickets | none

Provides a way to download a document from the API

### CODE REVIEW

**Comment by btry** [comment]
I think the tests on canView() ans canViewItem() can be removed, as the API already checks this earlier.

Neds an unit test

**Comment by orthagh** [comment]
without all stuff mentionned above, already lgtm.

So waiting for enhancement on documentation and tests before merge

**Comment by btry** [comment]
Currently I don't see an good way to unit test this. There are calls to exit on the way.

Doc added, and removed redundant calls to canView() and canViewItem()

**Comment by btry** [comment]
This pr and #2525 should use the same HTTP header **Accept** 

Please have a look on it to ensure we use the same header everywhere.

**Pull request merged**
