### PR TITLE
[wip] Enhance ticket/change validation with group validation

### PR DESCRIPTION
**Pull request by ddurieux**
validation

### CODE REVIEW

**Comment by ddurieux** [comment]
Add an icon to see what line I need click to add my validation:

validation

**Comment by ddurieux** [comment]
I'm modifying the database to be more simple + modify ticket rules

**Comment by cedric-anne** [comment]
Hi,

Are you still working on this ?

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.

**Pull request closed without merging**
