### PR TITLE
No time on date option for notification templates tag

### PR DESCRIPTION
**Pull request by M-Falken**
Sometimes it's necessary to just have the day without the time in the notification.
It's my own tag, but perhaps something like ##task.begin.notime## would be better ?

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by trasher** [comment]
I am not against the change. 
Maybe could you use `##task.begin.date##`; and you also have to fix unit tests

**Comment by trasher** [comment]
You also miss tags descriptions in `gettags`

**Comment by M-Falken** [comment]
Seen, but will do that asap
thx

**Comment by cedric-anne** [comment]
Hi,

This PR looks stale. I close it. Feel free to reopen on master branch if you plan to finish it.

Regards

**Pull request closed without merging**
