### PR TITLE
"Russian" is write part latin / part cyrillic => switch to cyrillic only

### LINKED ISSUE #1363: Not found language
Not found Russian language

setup glpi - google chrome 2016-11-29 13 01 20

### PR DESCRIPTION
**Pull request by AnaelMobilia**
Fix #1363

### CODE REVIEW

**Comment by AnaelMobilia** [comment]
For memories : The "P" chr was in latin (ord = 80) and not in Cyrillic (ord = 208)

**Comment by AnaelMobilia** [comment]
Nice idea, I will check that !

**Comment by trasher** [comment]
Maybe merged a bit quickly; may have reach 9.1/bf

**Comment by orthagh** [comment]
merged, thank you.
I cherry-picked on 9.1/bugfixes.

For future pr, think about sending fixes on 9.1/bugfixes branch, i'll manage to merge them into master.

**Comment by AnaelMobilia** [comment]
Thanks, I will target the correct branche next time ! :)

**Pull request merged**
