### PR TITLE
Add  ssl connect option to mysql/mariadb databases

### PR DESCRIPTION
**Pull request by cyrilus**
Permit to add config of ssl connection in config_db.php

like this for example

    public $dbssl=True;

    public $dbsslkey = '/etc/maria/ssl/key.pem';

    public $dbsslcert = '/etc/maria/ssl/cert.pem';

    public $dbsslca = '/etc/maria/ssl/cert.pem';

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Comment by trasher** [comment]
Such a change should prbably reach master.

**Comment by trasher** [comment]
Or maybe 9.5, but definitively not 9.4.

**Comment by cyrilus** [comment]
> Or maybe 9.5, but definitively not 9.4.

should i do another request for master or 9,5 and close this one

**Comment by trasher** [comment]
Yes,, or you can rebase onto 9.5 on your side, I'll change the target branch of the PR.

**Comment by cyrilus** [comment]
> Yes,, or you can rebase onto 9.5 on your side, I'll change the target branch of the PR.

Ok thanks

**Comment by trasher** [comment]
https://github.com/glpi-project/glpi/pull/5892

**Pull request closed without merging**
