### PR TITLE
Fix English (typo and grammar)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by wawax** [comment]
Hello,

Thanks for your pull request but translation are managed using Transifex (http://transifex.com/).
I suggest that you register on this platform and ask for being added to the glpi organisation.

**Comment by stweil** [comment]
??? Is that really a translation issue? The changes are in normal code, not in the localization part.

**Comment by stweil** [comment]
I just had a look at Transifex and got the impression that it is unrelated to my modifications.

**Comment by wawax** [comment]
Sorry, my bad. It's not related to gettext.

**Pull request merged**
