### PR TITLE
Fixing issue #94

### PR DESCRIPTION
**Pull request by pvasener**
This makes the project tasks appear on the planning.

### CODE REVIEW

**Comment by orthagh** [comment]
Ty @pvasener .

I'm currently working on planning (jquery fullcalendar w/ ajax behaviours).
I planned to add project task si i'll check your pr and integrate in it.

Thank you very muck for your contribution

**Comment by orthagh** [comment]
see https://github.com/orthagh/glpi/tree/0.91/dynamic_planning

**Comment by pvasener** [comment]
Great news. I had to develop that because we needed this feature urgently but I'm thrilled to use the fullcalendar you're working one when it's ready.

**Comment by orthagh** [comment]
a capture of current work (a lot of thing need to be fixed) : 
image

**Comment by pvasener** [comment]
The screenshot is very promising, especially if we can select a set of technicians. It would be great to help finding availabilities. Do you think all this will be ready for 0.91? Is it a matter of weeks, months?

**Comment by orthagh** [comment]
I target the 0.91 version.
Set of technician (or group) is the next step.

I think it will ready to test before the end of the month

**Comment by pvasener** [comment]
Nice, unfortunately, I don't have much time to help coding but if I can help at the testing/debugging stage, let me know.

**Comment by yllen** [comment]
when clic on Show button of a planning

[Fri Feb 05 16:43:38 2016] [error] [client ::1] PHP Fatal error:  Class 'value' not found in /home/yllen/gitsvn/inc/planning.class.php on line 780, referer: http://localhost/glpisvn/front/planning.php?limititemtype=value&_date=05-02-2016&date=2016-02-05&type=month&submit=Show&_glpi_csrf_token=99aa322ce18da71f93b1535164a91d77

**Comment by yllen** [comment]
I search in all the code and it's not possible.
You can't show project task in the planning because you can have duration without begin or end.
And showing only if begin and end are define is not top.

**Comment by orthagh** [comment]
I disagree with that.
if you see the planning as the occupation of a technician, seeing "projecttasks" (with only both planned dates filled) seems mandatory.
It permits to avoid to plan another tasks (from other objects) in the same timeslot.

For the fact of seeing or not planned task without duration, i don't know.
Maybe we can virtually set a duration of 15 min (for example).

**Pull request merged**
