### PR TITLE
FIx entity inheritance; closes #11641

### LINKED ISSUE #11641: Inventory with tag not association recursive
### Bug reporting acknowledgment

Not applicable

### Professional support

Yes, I know

### Describe the bug

My inventory is working fine, but the TAG defined in glpi-agent1.2 is not assigned recursively.
Computer assigns ok
Printers do not assign.

Is resulting with my printers.
image

### To reproduce

1 - I created a new entity with TAG=example
2 - I installed the agent on a computer with a printer connected
3 - I waited for the sync
4 - I checked the result.

### Expected behavior

The printer was associated with TAG=example

### Operating system

Linux

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #11641

### CODE REVIEW

**Review by g-bougard — APPROVED** [review]
Thx, I can confirm this fixes the issue.

**Review by orthagh — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Comment by g-bougard** [comment]
> Hi, I have the same problem, I see that the issue has been solved by modifying some config files like (MainAsset.php, Inventory.php, RuleImportEntity.php). But I can't find the path of these 2 files "tests/functionnal/Glpi/Inventory/Inventory.php" and "tests/functionnal/RuleImportEntity.php".

"tests/*" files are only available in sources. They are NOT integrated in release, so you don't need to update them.

**Comment by jdahim** [comment]
> > Hi, I have the same problem, I see that the issue has been solved by modifying some config files like (MainAsset.php, Inventory.php, RuleImportEntity.php). But I can't find the path of these 2 files "tests/functionnal/Glpi/Inventory/Inventory.php" and "tests/functionnal/RuleImportEntity.php".
> 
> "tests/*" files are only available in sources. They are NOT integrated in release, so you don't need to update them.

Thanks for your reply.
So, I just need to modify the file "src/Inventory/Asset/MainAsset.php"  ??

**Comment by cedric-anne** [comment]
> > > Hi, I have the same problem, I see that the issue has been solved by modifying some config files like (MainAsset.php, Inventory.php, RuleImportEntity.php). But I can't find the path of these 2 files "tests/functionnal/Glpi/Inventory/Inventory.php" and "tests/functionnal/RuleImportEntity.php".
> > 
> > 
> > "tests/*" files are only available in sources. They are NOT integrated in release, so you don't need to update them.
> 
> Thanks for your reply. So, I just need to modify the file "src/Inventory/Asset/MainAsset.php" ??

You should just update to GLPI 10.0.3.

**Pull request merged**
