### PR TITLE
Make sure VMs are removed if node is empty

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15220

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
IMHO, this should be handled on inventory agent side, using a generic behaviour for all data, when we are not in the "partial inventory" case.

This is the only way to distinguish the 2 following cases on GLPI side.

1. The agent does not care about the corresponding data (e.g. there is a configuration of the agent that disabled the VM inventory on this computer) or is not able to process to VM inventory (e.g. something went wrong when VM data has been fetched, but it is not the agent fault, for instance a timeout occured). In this case, the `virtualmachines` node should not be present in the inventory file and GLPI should do nothing related to VM of the computer.

2. The agent searched for VMs on the computer, but does not find any. In this case, an empty  `virtualmachines` node should be present in the inventory file and GLPI should remove all dynamic VM from the computer.

**Comment by trasher** [comment]
We're not trying to know if there ware an agent issue here, but we address the case when there is no longer any VM in a full inventory - a case that may happen).

Having agent side issues is a totally different issue no one has complained about until now, and may have as result to report 1 VM instead of 2 for example, so outside scope of current issue.

**Comment by cedric-anne** [comment]
IMHO, if inventory agent does not define a `virtualmachines` node, then we should not do anything with computer VMs. This is exactly what we do currently, and it sems logical to me.

**Review by stonebuzz — APPROVED** [review]
functionally it's ok for me

**Comment by stonebuzz** [comment]
We still need to know how to handle the case where there are no more VMs on the ESX.

- Improve the agent to send an empty node anyway
- Improve the converter to insert an empty array if necessary (absence of node)
- Improve the native inventory (like this PR)

**Comment by orthagh** [comment]
> IMHO, if inventory agent does not define a virtualmachines node, then we should not do anything with computer VMs. This is exactly what we do currently, and it seems logical to me.

This is only true for partial inventory.
In case of full inventory (I think this is the current case), we should remove them if the node disappears.

**Review by orthagh — APPROVED** [review]

**Pull request merged**
