### PR TITLE
0.90/ie8 compat

### PR DESCRIPTION
**Pull request by etiquet**
Hi, I am new.  Apologies if not proceeding the proper way.

I the changes are about fixing IE8 compatibility issues with glpi
Fixes consists to use html syntax that IE recognize in html.class.php ( header parts)
and CSS styles in the ie8compatibility.css for stuff like menu background, etc... 
includes also a new palette logo.

### CODE REVIEW

**Comment by trasher** [comment]
Oh, the commit on "Update notificationtemplate.class.php" should not be present in this review; we'll heve to drop it before merge (that is not a big problem; just for a reminder).

**Comment by etiquet** [comment]
Hi, lot of activity for a weekend ;)
Many thanks for the review, my comments inline.

> Le 17 sept. 2016 à 16:01, Johan Cwiklinski <notifications@github.com> a écrit :
> 
> @trasher commented on this pull request.
> 
> OK, a few global comments:
> 
> OK to replace with on elements that are not self closed according to standards
> Maybe shoule be avoid all the "MODIFS" comments, even if, it won't make sense out of this specific review
	the « motif » was there just to track the changes and help to come back to original changes ( never knows...)
> OK also to translate code comments that are in french.
> Maybe is this just a visual issue, but it seems that the last part of the changes brings more than origin; a bit strange for a simple browser compatibility.
> 
	This change is extracted from the generic part of fork to a client's need for personalized look&feel.
	Therefore yes, maybe looks like a little different from the standard template. This is also the reason why style change where put on a particular style css.
	Only the html I could not fix where changed in html.class. And also homogenized the two portions of the page header that were not identical in standard & simplified template.
	Tooks quite sometimes to find the root cause in html… bloody IE teams.
	I decided to bring back this little things to the community since I know some people are concerned with IE8 issues on some government agencies.
> On line 1469, you've added an empty echo, was that intended? If it is, you'll have to add a comment to explain this, or it will probably be deleted quickly :)
> 
> 
	Please remove, this might have been from a previous cut & paste from code.

**Comment by trasher** [comment]
For the changes to be done, you can do it as a new commit on your branch, that will be added to the PR on push. We'll squash all at the end, don't worry.

As for the part that looked strange to me; I must admit this is a part I absolutely do not know for the moment, I'll take some informations about all that ;)

Thank you!

**Comment by etiquet** [comment]
Well, I tried to commit the updated changes into the branch. 
But I admit I am still a bit lost about the various way of doing things between command line,
the web and desktop interfaces will spend some times to better understand.
Hope this is fine in the process.

**Comment by trasher** [comment]
No problem, this can not be easy. Whatever you use; just keep in mind commits are local, and then you need to push them. You GUI should display you informations about what is pushed or not I guess; I can't help with that, I only use command line myself ;)

Thanks.

**Comment by orthagh** [comment]
I tested your branch, i think also a specific "palette" for your ie8 compatibility is not a very good idea. 
It forces the user to use this "theme" for the browser.
We can provide theses fix with another ways:
- specific css file sended for this browser only
- css attributes in the main css file. we need vendor attributes like -ms-filter, no ?

**Comment by etiquet** [comment]
Hi, I have not the skill to tackle the points you mention there, the css stuff are quite workarounds and lot of testing.
My though is : since these fixes are for a relative old browser. why spending too much energy having a generic css and why not just providing the styles (that works also for modern browser) for people that requires them and let the main branch use modern css tags. 
As I mention above I don't no how to do conditional stuff in css for particular browser/version. 
You may need step in to help here, we can do this together. that could be fun

**Comment by trasher** [comment]
Hello,

To include specific stylesheets ofr old IE versions, this is far better to use html conditional includes than css hacks (see http://www.quirksmode.org/css/condcom.html).

Hope that helps.

**Comment by etiquet** [comment]
Hello Trasher, do you mean, for example we could invoke one particular CSS only if one iE version ?
If works this could lead in orthargh direction, just "patch" the minimum CSS stuff for that browser.
I'll give a try as soon I'll find some times.

**Comment by trasher** [comment]
Yep exactly :)

With conditionnal comments, you can load specific html code (really... what you want, may be a stylesheet, a javascript file or even some html tags). I use that quite often to display warnings messages to the users if they're working with an old browser.

You can work with equals to, greater than, greater or equals than, and so on.

Those comments are only loaded by IE; all other browsers will ignore it. I do not remember if it has been removed in IE9 or 10; for for IE8, no problem.

**Comment by orthagh** [comment]
Hello @etiquet 
This pr begin to be pretty old.

Do you plan to continue it or it can be closed ?

**Comment by etiquet** [comment]
Hi, will do IT on 9.1. 
However did not work on one of the rewiwer idéa. (Conditionnal css ) Not trivial.

**Comment by trasher** [comment]
What does "not trivial" mean?

**Comment by etiquet** [comment]
Hello this is a polite way to say, not easy to do ;) 

Concretely the suggestion of the reviewer was to do conditional CSS depending on browser type instead of a having a dedicated CSS for an older browser (IE8) that was my original proposal.

I personally don't know how to do condition in a CSS. Should you by any chance have a pointer or suggestion how to do it ?  this could help me. 

For the moment having a dedicated CSS style for IE8 (without patching the core of glpi) is the only simple option I can propose in short term.

Please let me know your view.

**Comment by trasher** [comment]
Here is an article about conditional comments:
http://www.quirksmode.org/css/condcom.html

GLPI already have a stylesheet loaded using this; see:
https://github.com/glpi-project/glpi/blob/master/inc/html.class.php#L1151

The existing stylesheet can be replaced by yours; I do not think we plan to keep IE6 support :D
So, you "just" have to replace line `<!--[if lte IE 6]>` in the `html.class.php ` with `<!--[if lte IE 8]>` and adapt contents in file `css/styles_ie.css`.

**Comment by etiquet** [comment]
Hi thank I'll try.

**Comment by trasher** [comment]
Most of the requested changes have already been done in master branch. Here is what I propose:
https://github.com/glpi-project/glpi/compare/master...trasher:ie8
Changes on notification template are out of the current PR scope and have been ignored.

I cannot test since I do not have IE; so please test if that is OK so I'll open a PR and get that for 9.2 GLPI release.

**Comment by etiquet** [comment]
Hello

I was focused on other stuff regarding these changes proposal for some while.
I had a quick look, this seems fine => now need to test. I’ll do some in the 2 coming weeks.

Last things did you integrate the HTML update proposition  on html.class.php ?


The tips to test against old IE browser is to use :  http://modern.ie <http://modern.ie/> that point to IE + Windows VMs (free to use for 3 months)
(https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ <https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/>)

You have basically IEs for your test on your desktop without disturbing you own desktop... ( I use it with parallels on my Mac)

If you have a GLPI instance on line. you can use https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/ <https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/> (never used)

Thanks for the job / helps.

For your info : Currently we’re working on some enhancements on the SCCM plug-in and formcreators.

**Comment by trasher** [comment]
> Last things did you integrate the HTML update proposition on html.class.php ?

Work has already been done in master branch (for GLPI 9.2).

> The tips to test against old IE browser is [...]

I'm sorry, but I won't have time to test that. Being compatible with such old browsers is not a priority; we have many, many other stuff to test/fix/whatever ;)

**Comment by orthagh** [comment]
Hello.

Maybe we could close this pr in favor of a new one based on 
https://github.com/glpi-project/glpi/compare/master...trasher:ie8

no ?

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/pull/1982

**Pull request closed without merging**
