### PR TITLE
Event Management

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | -

Goals:
Provide a method of storing, interpreting and displaying events/logs. Plugins will handle the process of gathering the events/logs. GLPi can act as a standalone monitoring solution (with plugins) or provide a central place to view data from multiple external monitoring systems.

Done/Planned Here:
- Hosts: Any item with monitoring enabled
- Services: A metric or log that is monitored on a host. Can be actively or passively checked
- Loggers/Sensors: A logger is any plugin that can gather events. A sensor is a method of gathering events (ping, snmp, wmi, etc).
- Provide unified interface for configuring sensors through Service templates.
- Host status is dependent on a service selected as the "availability service"
- Migrated old Events to the new system. They will show up under a special host that represents the GLPI install.
- Basic flapping detection modeled after Nagios to provide a consistent experience across plugins.
- GLPI controls when actively monitored services are checked.
- Scheduled downtimes to suppress notifications during a specified period
- Acknowledgements to suppress notifications until the service/host recovers
- Static dashboard for viewing host/service status by entity or location
- Event Management through stateful events (affect service status) and Information Management through stateless events (Independent of service status).
- Ability to create tickets, changes, or problems from an event
- Event filtering rule engine
- Basic business rule engine for events

Not Done Here (Can be done in other PRs):
- Trend analysis
- Reporting
- Correlation engine
- Host reachability (Has a placeholder status for this)
- Host/Service groups
 
Example plugin for testing:
https://github.com/cconard96/siemsensors

UserEcho: https://glpi.userecho.com/communities/1/topics/42-event-management

Some screenshots (My events are performance-based, but could be security):
From items' Event Management tab after being configured:
Screenshot from 2019-06-18 21-50-42

Dashboard (Currently replaces search. Not a final design):
Screenshot from 2019-07-07 10-45-26

### CODE REVIEW

**Comment by orthagh** [comment]
Thank you @cconard96 .
Could you post some screenshots to have a gloabl idea ?

**Comment by cconard96** [comment]
Done. UI side is still very much WIP and doesnt work with the new UI yet.

**Comment by cconard96** [comment]
Work on this feature is on hold pending the finished UI feature on master branch.

**Comment by cconard96** [comment]
I just realized that I never commented on this, but this feature is very much still in development (and will be picking up speed) as a plugin to make it easier to develop alongside the current GLPI releases.
See https://github.com/cconard96/siem for the current status.

Since some of this feature was built on version 10 code which was postponed, I moved development to a plugin to try and separate the plugin logic from the core to allow myself to evolve the feature alongside the GLPI releases. When the core is in a feasible state for this feature, the plugin code will be converted and integrated into this PR.

**Comment by cedric-anne** [comment]
> I just realized that I never commented on this, but this feature is very much still in development (and will be picking up speed) as a plugin to make it easier to develop alongside the current GLPI releases.
> See https://github.com/cconard96/siem for the current status.
> 
> Since some of this feature was built on version 10 code which was postponed, I moved development to a plugin to try and separate the feature logic from the core to allow myself to evolve the feature alongside the GLPI releases. When the core is in a feasible state for this feature, the plugin code will be converted and integrated into this PR.

Hi @cconard96 ,

I'm closing this PR because it looks like it's going to be a draft for a long time yet.

Regards

**Pull request closed without merging**
