### PR TITLE
fix duplicate Computer search options

### PR DESCRIPTION
**Pull request by cconard96**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15689

### CODE REVIEW

**Comment by trasher** [comment]
Changing a search option ID may affect saved searches (at least); it's never that simple.

Also, I do not see the link beetween number of linked assets and contracts date. If SO are duplicated, there is a miss in our tests suite; fixing such a bug certainly require either an extra test, either a change in existing ones.

**Comment by cedric-anne** [comment]
> If SO are duplicated, there is a miss in our tests suite

I agree, our test suite should fail, so we would be able to detect this kind of issues.

**Comment by 0xNath** [comment]
> Changing a search option ID may affect saved searches (at least); it's never that simple.
> 
> Also, I do not see the link beetween number of linked assets and contracts date. If SO are duplicated, there is a miss in our tests suite; fixing such a bug certainly require either an extra test, either a change in existing ones.


Those IDs are arbitrarily chosen ?
https://github.com/glpi-project/glpi/issues/15689#issuecomment-1743691380

**Comment by cconard96** [comment]
> Those IDs are arbitrarily chosen ?

Pretty much. They have to be unique, but otherwise mean absolutely nothing.

**Comment by cconard96** [comment]
> I agree, our test suite should fail, so we would be able to detect this kind of issues.

Tests wouldn't fail when the exception is thrown only when `CommonDBTM::searchOptions` is called and there are duplicates at that time; not when `Search::getOptions` or other places blindly merges the result with other non-raw (the keys have been set to the ID) search option arrays.

**Comment by cconard96** [comment]
> Changing a search option ID may affect saved searches (at least); it's never that simple.

Since #9066 `Migration::changeSearchOption` handles changing search options in display preferences and saved searches.

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Pull request merged**
