### PR TITLE
9.1/child of for software licence

### PR DESCRIPTION
**Pull request by stonebuzz**
Add 'Child Of' notion for SoftwareLicence based on 'CommonTreeDropdown'

### CODE REVIEW

**Comment by orthagh** [comment]
Looks good to me.
Here is the next steps to include this feature.
- have an issue tagged on 9.2
- link this pr to the issue.
- wait for #1198 merged
- changes update_script to the new one
- add unit tests (you can call me for that)

**Comment by stonebuzz** [comment]
I created an issue to explain the feature, and i link it to PR

#1302

**Comment by trasher** [comment]
Hi @wawax ;

I've rebased current PR to fix tests that were failing because of an issue in the master branch. There are still 2 tests failing; I guess the count has just changed; but I prefer to let you take an eye on this.

**Comment by trasher** [comment]
Also, I did a quick test with tests data from the UI:
licenses

The count in the tab is incorrect; for the main table, I do not know what is expected really :)

**Pull request merged**
