### PR TITLE
Add form hooks on helpdesk.public.php

### PR DESCRIPTION
**Pull request by trasher**
Follows #1444

### CODE REVIEW

**Comment by trasher** [comment]
I do not know if the pre hook should be called also in the "else" part.

**Comment by orthagh** [comment]
the 'pre' souldn't be moved upper (out of the if delegating condition) ?

**Comment by trasher** [comment]
It must be in a table, so, no. That was my question with the "else" part.

**Comment by orthagh** [comment]
otherwise, move the div > table.cadre_cadre_fixe outsided of the if else condition
Both case have this html blocks

**Comment by trasher** [comment]
Should not have been merged; I was waiting for other missed hooks calls to add (that's why the PR was tagged wip). Well not really a problem, thanks anyways ;)

**Pull request merged**
