### PR TITLE
update fullcalendar to 3.0; add listview feature for planning and cen…

### PR DESCRIPTION
**Pull request by orthagh**
…tral; see #758

### CODE REVIEW

**Comment by orthagh** [comment]
See theses links:
- https://fullcalendar.io/blog/2016/09/feature-packed-releases/
- https://github.com/fullcalendar/fullcalendar/issues/560
- https://fullcalendar.io/docs/list_view/intro/

**Comment by orthagh** [comment]
My central page: 
image

**Comment by tomolimo** [comment]
That's very good! Better than what I thought! 

But do you have the possibility to color the late tasks? in red for example?

**Comment by tomolimo** [comment]
WIP?

**Comment by orthagh** [comment]
Work in progress

**Comment by tomolimo** [comment]
thank you

**Comment by orthagh** [comment]
Here is:
image

changes
- position of qtip
- addition of event type chip
- css for past events and an autoscroll after them
- removal of day names

**Comment by tomolimo** [comment]
very nice!
thank you

**Comment by orthagh** [comment]
if you could, i'll appreciate a review on IE

**Comment by tomolimo** [comment]
On next Monday?

**Comment by orthagh** [comment]
sure

**Comment by tomolimo** [comment]
Hello,
I'm currently testing this new feature and I can see some problems:

1. colors for past due 'todo' task are not very clear: could it be possible to use the same colors than the 'Due date progression' colors? 
1. the past due tasks, when set to 'done' don't disappear from the list...so the list is growing and growing.
image

I propose these rules for colors (use of 'Due date progression' colors) and visibility of tasks:

1. if datebegin == today and datebegin >= now and status == todo then show them in green (-> OK state color)
1. if datebegin < now and dateend >= now  and status == todo then show them in yellow (-> Warning state color)
1. if dateend < now and status == todo then show them in red (->Critical state color)
1. if dateend  == today and status == done then show them in grey (-> this color is not existing in the 'Due date progression scheme)
1. if dateend < today and status == done then don't show them (-> in this case: no color :smiley:)

Like this the panel will show the tasks to be done, the tasks done today, and the past-due tasks.

thank you,
regards,
Tomolimo

**Comment by orthagh** [comment]
Ok, Thank you for your review and suggestions, some questions so:

- Is it works on IE ?
- Is previous version of planning displays done task also ?

For point 2, i managed to scroll to the current last past task, to avoid user scrolling, is it work ?

For colorize depending on dates, i'll do some tests quickly.

**Comment by tomolimo** [comment]
> Is it works on IE ?

Yes, tested on IE10

> Is previous version of planning displays done task also ?

yes, but only when tasks are for current day

**Comment by orthagh** [comment]
Here is:
image

I do a more simpler version of your proposal:
- In list view, done events are never displayed (they still exist in other views)
- added colors: 
    - state=todo, end_date exceeded but it's alway a today event: add orange color
    - state=todo end_date exceeded, and not today: add red color
    - other past event stay gray as previous.

I didn't change future events, regardless of their states, i think the current default link color is fine.
I didn't find any solutions for today done events.


I also did a little modification to force event refetch when changing view, when you set done an event, it disappeared from other views (waiting for a full refresh).

**Comment by orthagh** [comment]
Oh, also i changed the default scrolling, now here is the behavior, scroll to:
- first late event
- if no one, first today event
- ..., first future event
- ..., last past event
- then don't scroll

**Comment by tomolimo** [comment]
Looks very good :smiley:

**Comment by orthagh** [comment]
if it's ok for you, you can now squash & merge

**Comment by orthagh** [comment]
thank you

**Pull request merged**
