### PR TITLE
feature: delete Computers and/or NetworkDevices from a rack via MassiveAction

### PR DESCRIPTION
**Pull request by po1vo**
Deleting (multiple) servers from racks was taking too many actions (mouse clicks).

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Review by cedric-anne — CHANGES_REQUESTED** [review]
It could be even better to add this action dynamically on all itetmtypes that are listed in `$CFG_GLPI['rackable_types']`.
In `CommonDBTM::getSpecificMassiveActions()`:
```php
if (in_array(static::getType(), $CFG_GLPI['rackable_types'])) {
 ...
}
```

**Review by cedric-anne — DISMISSED** [review]

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by cedric-anne — APPROVED** [review]

**Comment by cedric-anne** [comment]
It could probably be cherry-picked in 10.0/bugfixes branch. @orthagh @trasher , do you agree?

**Comment by orthagh** [comment]
Agree also.
As discussed together, after merge, we must clean declarations of actions. We know the current proposal has been copied from Appliance actions in CommonDBTM relative methods, but we should move both to` MassiveAction::getAllMassiveActions` (like Infocom)

**Comment by cedric-anne** [comment]
Manually picked in 10.0/bugfixes branch, see d7e90f56099e64192461d7327c9f6b26375d3aaa.

Thanks for the contribution.

**Pull request closed without merging**
