### PR TITLE
Prevent issues with big images handling in right text

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12961

During rich text images handling on server side, when base64 source of an image is huge and `pcre.backtrack_limit` PHP directive has a small value, images are not correctly replaced in rich text and produces following kind of data:
image

To prevent this, I propose to remove, in the hidden textarea related to rich text editor, the src attribute of every images that were handled by upload process.

Validated by uploading a 650kb image after applying following patch:
```diff
diff --git a/src/Toolbox.php b/src/Toolbox.php
index bf1c7b4d76..15fe761560 100644
--- a/src/Toolbox.php
+++ b/src/Toolbox.php
@@ -2668,6 +2668,7 @@ class Toolbox
             if ($was_escaped) {
                 $content_text = Sanitizer::dbUnescape($content_text);
             }
+            ini_set('pcre.backtrack_limit', 1000);
 
             foreach ($doc_data as $id => $image) {
                 if (isset($image['tag'])) {
```

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Comment by AdrienClairembault** [comment]
These changes breaks images when failing to submit a ticket form (e.g. missing mandatory fields):

image

**Comment by trasher** [comment]
@AdrienClairembault it's maybe better to open a new issue

**Comment by SylvieCoz** [comment]
Hello,

I have the issue being unable to upload "big" image from the web interface

For instance, with a 753 ko PNG image :

image

I use GLPI 10.0.7 and the proposed fix (`ini_set('pcre.backtrack_limit', 1000);`) is not part of version 10.0.7.

I tried applying it (by modifying Toolbox.php) : The image is correctly shown but, as mentionned by @AdrienClairembault, this fix generates other errors with mandatory fields (resetting already set values,...) I reverted back.

The initial issue still exists...

**Comment by cedric-anne** [comment]
> I use GLPI 10.0.7 and the proposed fix (`ini_set('pcre.backtrack_limit', 1000);`) is not part of version 10.0.7.

This is not a fix but a wayy to easilly reproduce the bug.

Bug is still present and tracked in #13606.

**Pull request merged**
