### PR TITLE
Fix SLA/OLA values in ticket rules export; fixes #4865

### LINKED ISSUE #4865: RuleTicket XML export doesn't contains value for SLA/OLA actions
Tested only on current 9.3/bugfixes.

Here is an example of a ticket rule with the assignment of an SLA in actions:
image

And the XML export corresponding to this rule:
```xml
<?xml version="1.0"?>
<rules>
	<rule>
		<entities_id>Root entity</entities_id>
		<sub_type>RuleTicket</sub_type>
		<ranking>3</ranking>
		<name>TEST</name>
		<description></description>
		<match>AND</match>
		<is_active>0</is_active>
		<comment></comment>
		<is_recursive>0</is_recursive>
		<uuid>2bb71c9e-2e32f874-5be1c5487f4a47.74032511</uuid>
		<condition>1</condition>
		<date_creation>2018-11-06 17:46:00</date_creation>
		<rulecriteria>
			<criteria>_groups_id_of_requester</criteria>
			<condition>0</condition>
			<pattern>GROUPE1</pattern>
		</rulecriteria>
		<rulecriteria>
			<criteria>itilcategories_id</criteria>
			<condition>11</condition>
			<pattern>CAT1</pattern>
		</rulecriteria>
		<ruleaction>
			<action_type>assign</action_type>
			<field>slas_ttr_id</field>
			<value></value>
		</ruleaction>
	</rule>
</rules>
```

We don't have the **<value></value>** in the SLA assignment action.

I tested with other fields (type, _users_id_assign, _groups_id_assign, status, etc), it works.

Seems to be a problem only with "SLA/OLA" fields, confirmed with another test:
```xml
		<ruleaction>
			<action_type>assign</action_type>
			<field>slas_ttr_id</field>
			<value></value>
		</ruleaction>
		<ruleaction>
			<action_type>assign</action_type>
			<field>slas_tto_id</field>
			<value></value>
		</ruleaction>
		<ruleaction>
			<action_type>assign</action_type>
			<field>olas_ttr_id</field>
			<value></value>
		</ruleaction>
		<ruleaction>
			<action_type>assign</action_type>
			<field>olas_tto_id</field>
			<value></value>
		</ruleaction>
```

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4865

### CODE REVIEW

**Comment by cedric-anne** [comment]
If this solution is OK for you, I will add unit tests.

**Comment by flegastelois** [comment]
@stonebuzz Can you test the fix please ?

**Comment by cedric-anne** [comment]
Last commit is an alternative fix.

The best fix would be to fix naming of these columns. If the `ttr`/`tto` part of field name is moved after `_id`, `getTableNameForForeignKeyField()` would return the good table name (see https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/dbutils.class.php#L89 ).

`getTableNameForForeignKeyField('olas_tto_id');` -> `glpi_olas_tto`
`getTableNameForForeignKeyField('olas_id_tto');` -> `glpi_olas`

**Comment by trasher** [comment]
@stonebuzz could you please confirm your issue is still fixed with final patch? Thanks :)

**Comment by trasher** [comment]
No feedback, I consider this is ok.

**Pull request merged**
