### PR TITLE
Restrict nightly GitHub actions to GitHub repository glpi-project/glpi

### PR DESCRIPTION
**Pull request by stweil**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

### CODE REVIEW

**Comment by stweil** [comment]
See this [example](https://github.com/stweil/glpi/actions) for unnecessary (and failing) actions which get fixed by this pull request.

**Comment by trasher** [comment]
(note: this one should reach 9.5/bugfixes branch)

**Review by cedric-anne — COMMENTED** [review]
OK, but should be cherry-picked in 9.5/bugfixes branch.

**Comment by trasher** [comment]
Manually applied on 9.5/bugfixes

**Pull request closed without merging**
