### PR TITLE
Add retries to flaky entity selector tests

### PR DESCRIPTION
**Pull request by AdrienClairembault**

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
Yes, the full tree feature is broken.

**Comment by trasher** [comment]
As far as I see in CI results, it began to fail after the latest 10.0/bf branch merge

**Comment by cedric-anne** [comment]
I guess it is due to this change:

image

**Comment by AdrienClairembault** [comment]
This mean this issue may also affect the 10.0 branch, I'll try to find out.

**Pull request closed without merging**
