### PR TITLE
To prevent TinyMCE to output \r\n (CR LF) at submit

### LINKED ISSUE #1944: TinyMCE adds CR LF to its return content that will be transformed to "rn" in solution
Hello,

When adding simple text like 

> Test 
of 
multilines

 in a ticket solution,

Then will get 

> Test
rn
of
rn
multilines

And when doing some spying on the HTTP traffic, one can see that tinyMCE is sending:
`<p>Test</p>\r\n<p>of</p>\r\n<p>multilines</p>`

And GLPI will transform this into 
`<p>Test</p>rn<p>of</p>rn<p>multilines</p>` 
due to `Toolbox::stripslashes_deep()` that uses stripslashes() which will delete any `\`, and left only the "rn" string.

Use of stripcslashes() will solve this issue,

thank you,
regards,
Tomolimo

### PR DESCRIPTION
**Pull request by tomolimo**
Fixes #1944

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1944

### CODE REVIEW

**Comment by tomolimo** [comment]
Hello,
I cannot reproduce the #2031 issue
regards,
Tomolimo

**Comment by trasher** [comment]
Hum... Maybe this has been fixed elsewhere yet... @sebfun, please try with current 9.1/bugfixes branch and tell us if you can reproduce the issue.

**Comment by tomolimo** [comment]
@trasher I believe your comment to @sebfun is not in the right place...

**Comment by trasher** [comment]
The issue also seems to be present when rich text is disabled :/

**Comment by trasher** [comment]
Fixed; see #2195

**Pull request closed without merging**
