### PR TITLE
Missing column in the table glpi_devicespcis

### PR DESCRIPTION
**Pull request by DataSharing**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3786

### CODE REVIEW

**Comment by DataSharing** [comment]
I do not want to make any mistakes, do I have to change update files: update_921_922.php, update_92_921.php and update_92_93.php or just 92_922?

**Comment by trasher** [comment]
92_93 since you've opened your PR on the master branch.

**Comment by trasher** [comment]
This is almost OK, but you've changed too much things in the update file. Anyways; this should target 9.2/bugfixes branch since this is a bug.
I'll take care of that.

**Comment by trasher** [comment]
See #3813

**Pull request closed without merging**
