### PR TITLE
Requester no need received your own email

### PR DESCRIPTION
**Pull request by edgardmessias**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3709

### CODE REVIEW

**Comment by edgardmessias** [comment]
@orthagh, currently, there is an option to notify the follow-up author.

glpi

**Comment by edgardmessias** [comment]
You should only send the notification only if you have configured it, not always

**Comment by orthagh** [comment]
I close as requester agreed on existing feature covers it's need.
If you want, you may send a more global option (and permits to configure parts of it) in a new pr (need specs on this i think).

**Comment by edgardmessias** [comment]
I will wait the #3662

**Pull request closed without merging**
