### PR TITLE
disable inclusion of documentation reference for some error messages

### PR DESCRIPTION
**Pull request by btry**
see #1049

### CODE REVIEW

**Comment by trasher** [comment]
What about relying on GLPi's debug mode to display or not those messages?

That way, we should continue to see them while debuging, but they will not be displayd on production instances. Thoughts? 

Anyways, could you please reference ticket in commit message ;)

**Comment by btry** [comment]
About using debug mode : let's check this idea with @orthagh who wrote most of the API. To me, it looks a good idea. 

For future single commit fixes I may add the reference ticket. For now, let's do a squash commit to add this reference.

**Comment by trasher** [comment]
OK for the ticket link; I just have to remember that when merging :)

And let's wait for @orthagh point of view ;)

**Comment by orthagh** [comment]
Ok for the change
for the debug mode, i don't know. 
In api usage, maybe theses "link to doc" messages are not very usefull

**Comment by trasher** [comment]
@btry OK, it's up to you right now :)

**Comment by btry** [comment]
If @orthagh don't know about debug mode, then I consider this should be discussed separately (in an other issue). For now we may merge the PR as is to fix the identified problem.

**Pull request merged**
