### PR TITLE
re-enable dynamic dates in footer for copyright; fix #936

### LINKED ISSUE #936: change copyright date to 2016
- files headers
- html footers

### PR DESCRIPTION
**Pull request by orthagh**

### CODE REVIEW

**Comment by trasher** [comment]
Merged

**Comment by remicollet** [comment]
I'm not a big fan of dynamic date in Copyright message.

* For dead project (yes this sometime happens), it seems the project still alive.
* when you use an old GLPI version (on some distro), I think it is better to display the "real" release date, not the current year.

**Comment by trasher** [comment]
Indeed, I did not think about that; sorry.
I'll revert the change and open another PR to fix missed dates in footer.

**Comment by remicollet** [comment]
And probably need to be factorized, e.g. 

     echo Html::getCopyrightMessage()

**Pull request closed without merging**
