### PR TITLE
Sending notification of type new will contain wrong informations in i…

### PR DESCRIPTION
**Pull request by kabassanov**
…t if status has already changed.

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

### CODE REVIEW

**Comment by orthagh** [comment]
related #12111

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — COMMENTED** [review]
IMHO, we should keep sending both notifications. Indeed, people may have configure their notifications to receive detailled information in the `new` notification and just a `Ticket has been solved/closed.` sentence in `solved`/`closed` notifications. Thus, they may have different recipients configured, and some of them may receive only the `new` notification.

What is the issue you are trying to fix?

**Comment by kabassanov** [comment]
> IMHO, we should keep sending both notifications. Indeed, people may have configure their notifications to receive detailled information in the `new` notification and just a `Ticket has been solved/closed.` sentence in `solved`/`closed` notifications. Thus, they may have different recipients configured, and some of them may receive only the `new` notification.
> 
> What is the issue you are trying to fix?

I agree with this. The issue is that without this modification some fields of the "new" ticket notification are already modified... For instance, the status is "closed" and if a solution has been used (set by rule), it is also in this notification.

**Comment by cedric-anne** [comment]
We cannot remove the sending of the `new` notification here as some people will probably want to receive both.

In GLPI 10.1, you will be able to filter notifications (see #14403).
In GLPI 10.0, you can adapt the `new` notification to use a template that does not include status and solutions.

**Pull request closed without merging**
