### PR TITLE
Prevent empty followups generated by mail collector; fixes #10792

### LINKED ISSUE #10792: [9.5.5] Sometimes replies to notifications are not integrated into tickets
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5

### Bug description

Hello,
Sometimes the replies to GLPI notifications are not integrated into GLPI, but they appear in the notimportedemail.php page.
image

And they are kept in the INBOX folder of the mailbox.
Thank you
Regards,
Tomolimo

### Relevant log output

```shell
There is no log for that in the error logs.
```

### Page URL

_No response_

### Steps To reproduce

1. Create a ticket like the one I've provided here in eml format:
[headertag test - initial email.eml.txt](https://github.com/glpi-project/glpi/files/8142048/headertag.test.-.initial.email.eml.txt)
1. Then use the reply to notification email here in eml format (change the ticket ID in the eml file before using it:
[headertag test fup email.eml.txt](https://github.com/glpi-project/glpi/files/8142054/headertag.test.fup.email.eml.txt)
1. go to the email receiver, and press "Get email tickets now"
2. You should get an error: 
image
1. and the notification reply will stay in the INBOX
1. Expected result would be to get the reply email integrated in the ticket as a followup

### Your GLPI setup information

_No response_

### Anything else?

This is also an issue for GLPI 10.0 release.

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10792 

With this proposal, when initial notification stripping logic leads to an empty followup, then the "non stripped" mail content will be used.

I opened this PR on master branch as it is changing the mail collector behaviour.

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Comment by tomolimo** [comment]
Hello @cedric-anne 
We must also delete the tags themselves, otherwise when receiving a notificaiton from these followups containing tags, they will have more than one tag per kind (header or footer), and then the risk will be to delete more text than the one really needed.
Thank you,
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
Thanks @tomolimo for pointing this. I fixed it.

**Review by orthagh — APPROVED** [review]
I guess this is ok.
Maybe we should not merge this for 10.0

**Comment by tomolimo** [comment]
Hello @cedric-anne 
I think that we should not delete anything from the content as soon as the patern header-tag / footer-tag is not present
If we keep the code as it is currently commited, then if any text is present before header tag or after footer tags then it will not be empty, and then the content will not be reverted...
Thank you,
Regrds,
Tomolimo

**Comment by cedric-anne** [comment]
> I think that we should not delete anything from the content as soon as the pattern header-tag / footer-tag is not present
> If we keep the code as it is currently commited, then if any text is present before header tag or after footer tags then it will not be empty, and then the content will not be reverted...

Unless I am wrong, this behaviour is here since the 0.85 version.

When stripped response is empty, we can assume that user did not respect the header/footer lines indications, but when one of these lines is missing, and stripped content is not empty, should we assume that removal of some part of initial notification is not intentionnal ? @orthagh @trasher

**Comment by trasher** [comment]
Well... I'm not sure to understand the whole conversation :D

I read the tests, the whole logic there seems correct, so it's ok for me. @tomolimo maybe could you check tests case, and see if you think one is missing?

**Comment by trasher** [comment]
Oh, and alos, I agree with @orthagh: this will wait hte version after 10.0 ;)

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Pull request merged**
