### PR TITLE
Fix number of changes id

### PR DESCRIPTION
**Pull request by Lainow**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

- It fixes !35088
- Here is a brief description of what this PR does

The new SO Number of Change overwrites an existing SO with id 98

### CODE REVIEW

**Comment by trasher** [comment]
Seems "100" is not a good choice either

**Comment by trasher** [comment]
Since the new search option has been released, I wonder if we should take care of the ID change from an update script. ping @cedric-anne?

**Comment by cconard96** [comment]
You can use the search options widget in the debug toolbar on `main` to identify which search option numbers are in use already.

**Comment by trasher** [comment]
> You can use the search options widget in the debug toolbar on `main` to identify which search option numbers are in use already.

Since the issue cames from a plugin, this will only work if this plugin is installed and active :/

**Comment by cedric-anne** [comment]
> Since the new search option has been released, I wonder if we should take care of the ID change from an update script. ping @cedric-anne?

IMHO, this ID will be more often related to the plugin SO than the new GLPI SO, so I think we should not add any migration for it.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
